### PR TITLE
Ensure props are loaded from matching endpoint during client-side navigation

### LINKED ISSUE #4038: Clashing endpoint-powered pages break route sorting
### Describe the bug

When multiple endpoint-powered pages have a clashing route path, both client- and server-side routers break, not following sorting rules.

Given:

```
/[id].js
/[id].svelte
/[slug].js
/[slug].svelte
```

A client-side navigation to any matching route renders `[id].svelte` with undefined props, without hitting the endpoint.

A full-page navigation _does_ hit the endpoints and falls through them, but you get back their JSON payload instead of the rendered page.

### Reproduction

[Minimal reproduction available here.](https://github.com/mrkishi/mrkishi-repro-sveltekit-clashing/commit/ca1c21dd2ad2a35b6d0a62db4044d5bda9fe3d9c)

### Logs

_No response_

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 1.44 GB / 7.88 GB
  Binaries:
    Node: 17.5.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 8.4.0 - ~\scoop\apps\nodejs\current\bin\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.279
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
Fixes #4038.

Credit to @aolose for the first version of this (https://github.com/sveltejs/kit/pull/4139). I tried to work on that branch but things had diverged too much, and I was concerned that the implementation came with fair bit of intrinsic complexity. This implementation is slightly less sophisticated — if an endpoint falls through during client-side navigation, Kit won't find which endpoint _actually_ matches and allow the client to short-circuit the next attempt — but it's less code and easier to follow. Fallthroughs are something of an edge case so I'm okay with them not being fully optimised.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/types/internal.d.ts [hunk 1]
```diff
@@ -179,6 +177,8 @@ export interface ShadowEndpointOutput<Output extends JSONObject = JSONObject> {
 	body?: Output;
 }
 
+type ShadowKey = string;
```
Comment (benmccann) [inline packages/kit/types/internal.d.ts:180]: could we add a comment describing the format of this key and why we need it?
