### PR TITLE
fix: allow commands in more places

### LINKED ISSUE #14325: Remote Functions: `Cannot call a command during server-side rendering` when calling a command from an API endpoint
### Describe the bug

When calling a [command](https://svelte.dev/docs/kit/remote-functions#command) from an API endpoint, the server throws a 500 error with the message `Cannot call a command during server-side rendering`, even when ssr is set to false!

Calling a [query](https://svelte.dev/docs/kit/remote-functions#query) works fine!

### Reproduction

[https://github.com/MAttila42/cannot-call-command-repro](https://github.com/MAttila42/cannot-call-command-repro)

Endpoints made in the repro:
`GET http://localhost:5173/api/data` (works as intended)
`POST http://localhost:5173/api/data` (throws the error mentioned)
`POST http://localhost:5173/api/data/alternative` (first alternative - having the logic in a separate server function)
`POST http://localhost:5173/api/data/alternative2` (second alternative - only using query functions)

The POST requests need a body like this:
```json
{
    "title": "test"
}
```

### Logs

```Shell
[500] POST /api/data
Error: Cannot call a command (`addData(...)`) during server-side rendering
    at wrapper (node_modules\@sveltejs\kit\src\runtime\app\server\remote\command.js:68:10)
    at POST (src\routes\api\data\+server.ts:12:9)
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 2.76 GB / 15.63 GB
  Binaries (bun used):
    Node: 24.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.2.20 - ~\AppData\Roaming\npm\bun.CMD
  Browsers (none used):
    Edge: Chromium (139.0.3405.111)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @sveltejs/adapter-auto: ^6.1.0 => 6.1.0 
    @sveltejs/kit: ^2.36.3 => 2.36.3 
    @sveltejs/vite-plugin-svelte: ^6.1.3 => 6.1.3 
    svelte: ^5.38.5 => 5.38.5 
    vite: ^7.1.3 => 7.1.3
```

### Severity

blocking an upgrade

### Additional Information

The reason why I'm doing this is because my project's not only present on the web, but also has an app counterpart. Following [Rich Harris' advice](https://github.com/sveltejs/kit/discussions/13897#discussioncomment-13531998) I exposed a public endpoint that calls my remote functions.

### PR DESCRIPTION
**Pull request by dummdidumm**
In POST/PUT/PATCH/DELETE handlers and in form actions

Closes #14325

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/app/server/remote/command.js [hunk 1]
```diff
@@ -64,15 +64,10 @@ export function command(validate_or_fn, maybe_fn) {
...
 
-		if (state.is_endpoint_request) {
-			if (!['POST', 'PUT', 'PATCH', 'DELETE'].includes(event.request.method)) {
-				throw new Error(
-					`Cannot call a command (\`${__.name}(${maybe_fn ? '...' : ''})\`) from a ${event.request.method} handler`
-				);
-			}
-		} else if (!event.isRemoteRequest) {
+		if (!state.allows_commands) {
+			const disallowed_method = !['POST', 'PUT', 'PATCH', 'DELETE'].includes(event.request.method);
```
Comment (teemingc) [inline packages/kit/src/runtime/app/server/remote/command.js]: I wonder if it's useful to put this in https://github.com/sveltejs/kit/blob/244838cf3db806c5f92a09b8b860511da09f27ed/packages/kit/src/constants.js as a list of mutative methods

File: packages/kit/src/runtime/server/respond.js [hunk 2]
```diff
@@ -419,6 +419,7 @@ export async function internal_respond(request, options, manifest, state) {
 						current: root_span
 					}
 				};
+				event_state.allows_commands = ['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method);
```
Comment (teemingc) [inline packages/kit/src/runtime/server/respond.js]: See https://github.com/sveltejs/kit/pull/15288/changes#r2852179884
