### PR TITLE
fix loading of conditional Vite configs

### LINKED ISSUE #5372: Conditional configuration in vite.config.js breaks prod build
### Describe the bug

If your `vite.config.js` uses conditional configuration, Svelte stops trying to compile components files to JS during SSR, and the resulting build fails because Rollup/Acorn is trying to parse Svelte files as JS.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-4wrfgp

### Logs

```shell
❯ npm run build
$ vite build
vite v2.9.13 building for production...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/immutable/manifest.json                                             2.67 KiB
.svelte-kit/output/client/_app/immutable/start-ab798b44.js                                         23.25 KiB / gzip: 8.72 KiB
.svelte-kit/output/client/_app/immutable/pages/__layout.svelte-f0707ee1.js                         4.77 KiB / gzip: 1.86 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-c8df2b3e.js                                  1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/pages/about.svelte-692f0ea0.js                            2.51 KiB / gzip: 1.15 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-471ba9cf.js                            5.47 KiB / gzip: 2.42 KiB
.svelte-kit/output/client/_app/immutable/pages/todos/index.svelte-dda24c9b.js                      6.86 KiB / gzip: 2.89 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-9fe72fd8.js                                  11.81 KiB / gzip: 5.02 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-92d65ea7.js                                  0.43 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-d1fb5791.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/__layout.svelte-da7c5ce3.css                 5.08 KiB / gzip: 1.56 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/about.svelte-bf4528fa.css                    0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/index.svelte-e12bfb09.css                    1.45 KiB / gzip: 0.52 KiB
.svelte-kit/output/client/_app/immutable/assets/pages/todos/index.svelte-a910a02d.css              3.70 KiB / gzip: 1.03 KiB
vite v2.9.13 building SSR bundle for production...
✓ 0 modules transformed.
transforming (1) .svelte-kit/build/index.js[rollup-plugin-dynamic-import-variables] Unexpected token (1:0)
file: /home/projects/sveltejs-kit-template-default-4wrfgp/src/routes/__layout.svelte:1:0
[vite-plugin-svelte-kit] Unexpected token (1:0)
file: /home/projects/sveltejs-kit-template-default-4wrfgp/src/routes/__layout.svelte:1:0
```

### System Info

```shell
  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.53 
    @sveltejs/kit: next => 1.0.0-next.359 
    svelte: ^3.46.0 => 3.48.0 
    vite: ^2.9.13 => 2.9.13
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Conduitry**
Hopefully fixes #5372. I briefly tested this, and it seemed to work, but it could do with more manual testing and also some automated tests. I'm done for the evening, so if someone gets to this before I do, feel free to take this branch over.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/vite/utils.js [hunk 1]
```diff
@@ -4,13 +4,15 @@ import { pathToFileURL } from 'url';
...
 	for (const file of ['vite.config.js', 'vite.config.mjs', 'vite.config.cjs']) {
 		if (fs.existsSync(file)) {
-			const config = await import(pathToFileURL(file).toString());
-			return config.default || config;
+			const m = await import(pathToFileURL(file).toString());
+			const config = m.default || m;
+			return typeof config === 'function' ? config(config_env) : config;
 		}
 	}
 	throw new Error('Could not find vite.config.js');
```
Comment (bluwy) [inline packages/kit/src/vite/utils.js:18]: Maybe we could use `resolveConfig` from `vite` to search for the vite config? It handles typescript too so that could make this part more aligned to Vite.

Though we could also do this separately.

Comment (Conduitry) [reply packages/kit/src/vite/utils.js:18]: Would I call it like this?

```js
export async function get_vite_config(config_env) {
	// @ts-ignore
	return await resolveConfig({}, config_env.command, config_env.mode);
}
```

That was my best guess. But `resolveConfig` returns a `ResolvedConfig` rather than a `UserConfig`. If I tell TypeScript not to worry about that, I get a runtime error `[vite-plugin-svelte-kit] Cannot read properties of null (reading 'constructor')` so apparently one of the things in `UserConfig` but not `ResolvedConfig` is needed here.

Comment (bluwy) [reply packages/kit/src/vite/utils.js:18]: Yeah I think that would work. A SvelteKit project now would always need a Vite config so the error should never happen.

Comment (Conduitry) [reply packages/kit/src/vite/utils.js]: Updated in ccee0571df341b9f9c6dda81cba54f119812f21b.

File: .changeset/poor-knives-yawn.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': patch
+---
+
+[fix] can't build production app when using conditional Vite config
```
Comment (Rich-Harris) [inline .changeset/poor-knives-yawn.md:5]:
```suggestion
[fix] support conditional Vite configs
```
