### PR TITLE
breaking: tighten up error handling

### LINKED ISSUE #11287: Tighten up error handling
### Describe the problem

#11278 sent me down a rabbit hole of error handling once more. It occured to me that us throwing `error`s is not correct, strictly speaking. Someone could've enhanced the `App.Error` object which means that more properties than just `message` are required, and as such calling `error` with just a string is wrong.

### Describe the proposed solution

Instead of using `error`, we distinguish between unforseen fatal errors and not-so-bad errors by expanding on what was introduced in #11131:
- We create a `NonFatalError` with `status` and `message` (and `NotFound` introduced in that PR would go away)
- `handleError` is called with those, too, but our fallback uses the `message` verbatim in that case (because we know it doesn't contain sensitive information)
- We expose that class through `@sveltejs/kit` so people can do `instanceof NonFatalError` in `handleError` and inspect the status/message (would also make #6774 more clear)/not send this to an error reporting service in that case
- If `NonFatalError` is discovered, the `status` is not `500` but instead the one defined in the instance

### Alternatives considered

Leave this as is and document this somewhere in the code base

### Importance

would make my life easier

### Additional Information

Putting this on the 2.0 milestone because if we change this it could be seen as a breaking change (things appearing in `handleError` differently)

### PR DESCRIPTION
**Pull request by dummdidumm**
Introduces `status` and `message` to `handleError` which default to `500` and `"Internal Error"`. Introduces a NonFatalError object that is used internally and is used to convert to more specific `status`/`message` objects. It's used everywhere where we can reasonably assign a non-500 status code.

closes #11287

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/exports/node/index.js [hunk 1]
```diff
@@ -62,14 +61,12 @@ function get_raw_body(req, body_size_limit) {
...
-								content_length ? "'content-length'" : 'BODY_SIZE_LIMIT'
-							} of ${length}`
-						)
-					);
+					controller.error({
+						status: 413,
+						message: `request body size exceeded ${
+							content_length ? "'content-length'" : 'BODY_SIZE_LIMIT'
+						} of ${length}`
+					});
```
Comment (dummdidumm) [inline packages/kit/src/exports/node/index.js:69]: somewhat of a drive-by-fix - the "`error` throws itself" change caused a breakage here. It's not really necessary to use the `error` function in this context, so I replaced both usages with POJO in this file

File: packages/kit/src/runtime/server/page/actions.js [hunk 2]
```diff
@@ -24,8 +24,7 @@ export async function handle_action_json_request(event, options, server) {
 	const actions = server?.actions;
 
 	if (!actions) {
-		// TODO should this be a different error altogether?
-		const no_actions_error = new HttpError(
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/actions.js:28]: Side note: This shows we weren't 100% adhereing to the "no `error` functions in our code" rule for a long time, the recent PRs only made it so it's done in a few more places.

**Comment by Rich-Harris** [comment]
Instead of introducing a `NonFatalError` (which is a bit of a weird name) and expecting users to do `instanceof` checks, why don't we just add `status` and `message` properties to `handleError`?

```js
export function handleError({ error, status, message }) {
  const id = crypto.randomUUID();

  report(id, error);

  return {
    id,
    message // e.g. 'Not Found' for things we threw ourselves, 'Internal Error' for unexpected stuff (as today)
  };
}
```

**Comment by dummdidumm** [comment]
We still need the class internally to distinguish it before passing it to `handleError` though, else how do we know if we can show the message? So if we need it we might aswell surface it.
Having `status` and `message` part of the API feels nicer though, I give you that.

**Comment by Rich-Harris** [comment]
> we might aswell surface it.

I disagree. We should only expose the things we _need_ to expose, and it's not clear to me that we need to expose this

File: packages/kit/src/exports/node/index.js [hunk 3]
```diff
@@ -28,10 +27,10 @@ function get_raw_body(req, body_size_limit) {
...
 			length = body_size_limit;
 		} else if (length > body_size_limit) {
-			error(
-				413,
-				`Received content-length of ${length}, but only accept up to ${body_size_limit} bytes.`
-			);
+			throw {
+				status: 413,
+				message: `Received content-length of ${length}, but only accept up to ${body_size_limit} bytes.`
+			};
```
Comment (Rich-Harris) [inline packages/kit/src/exports/node/index.js:33]: Why doesn't this use `SvelteKitError`?

```suggestion
			throw new SvelteKitError(413, 'Payload Too Large', `Received content-length of ${length}, but only accept up to ${body_size_limit} bytes.`);
```

File: packages/kit/src/runtime/control.js [hunk 4]
```diff
@@ -30,15 +30,20 @@ export class Redirect {
...
+/**
+ * An error that was thrown from within the SvelteKit runtime that is not fatal and doesn't result in a 500, such as a 404.
+ * `SvelteKitError` goes through `handleError`.
+ */
+export class SvelteKitError extends Error {
 	/**
-	 * @param {string} pathname
+	 * @param {number} status
+	 * @param {string} message
+	 * @param {string} [context]
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/control.js:41]: `details` probably fits better than `context`?

```suggestion
	 * @param {string} [details]
```

File: packages/kit/src/runtime/control.js [hunk 5]
```diff
@@ -30,15 +30,20 @@ export class Redirect {
...
 	 */
-	constructor(pathname) {
-		super();
-
-		this.status = 404;
-		this.message = `Not found: ${pathname}`;
+	constructor(status, message, context) {
+		super(message);
+		this.status = status;
+		this.context = context;
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/control.js:46]:
```suggestion
	constructor(status, message, details) {
		super(message);
		this.status = status;
		this.details = details;
```

File: packages/kit/src/runtime/server/page/actions.js [hunk 6]
```diff
@@ -142,7 +141,7 @@ export async function handle_action_request(event, server) {
 		});
 		return {
 			type: 'error',
-			error: new HttpError(405, 'POST method not allowed. No actions exist for this page')
+			error: new SvelteKitError(405, 'POST method not allowed. No actions exist for this page')
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/page/actions.js:144]: we should probably use the stand HTTP error codes consistently

```suggestion
			error: new SvelteKitError(405, 'Method Not Allowed', 'POST method not allowed. No actions exist for this page')
```

File: packages/kit/src/runtime/server/page/actions.js [hunk 7]
```diff
@@ -219,12 +218,14 @@ async function call_action(event, actions) {
 
 	const action = actions[name];
 	if (!action) {
-		throw new Error(`No action with name '${name}' found`);
+		throw new SvelteKitError(404, `No action with name '${name}' found`);
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/page/actions.js:221]:
```suggestion
		throw new SvelteKitError(404, 'Not Found', `No action with name '${name}' found`);
```

File: packages/kit/src/runtime/server/page/actions.js [hunk 8]
```diff
@@ -219,12 +218,14 @@ async function call_action(event, actions) {
...
 	}
 
 	if (!is_form_content_type(event.request)) {
-		throw new Error(
-			`Actions expect form-encoded data (received ${event.request.headers.get('content-type')})`
+		throw new SvelteKitError(
+			415,
+			'Actions expect form-encoded data',
+			`Received ${event.request.headers.get('content-type')}`
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/page/actions.js:228]:
```suggestion
			'Unsupported Media Type',
			`Form actions expect form-encoded data — received ${event.request.headers.get('content-type')}`
```

File: documentation/docs/30-advanced/25-errors.md [hunk 9]
```diff
@@ -77,7 +77,7 @@ By default, unexpected errors are printed to the console (or, in production, you
 { "message": "Internal Error" }
 ```
 
-Unexpected errors will go through the [`handleError`](hooks#shared-hooks-handleerror) hook, where you can add your own error handling — for example, sending errors to a reporting service, or returning a custom error object.
+Unexpected errors will go through the [`handleError`](hooks#shared-hooks-handleerror) hook, where you can add your own error handling — for example, sending errors to a reporting service, or returning a custom error object. `handleError` is passed the `error` along with the `event` and a `status` and `message`. `message` is just `"Internal Error"` for unforseen errors, in which case the `status` is 500. `status` may also contain other values such as 404 (page not found) or 415 for actions (wrong content-type), in which case a more specific but still safe `message` is provided.
```
Comment (benmccann) [inline documentation/docs/30-advanced/25-errors.md:80]: "Unexpected errors" is too vague

File: documentation/docs/30-advanced/25-errors.md [hunk 10]
```diff
@@ -95,14 +95,21 @@ import * as Sentry from '@sentry/sveltekit';
...
+		};
+	} else {
+		// example integration with https://sentry.io/
+		Sentry.captureException(error, { extra: { event } });
+
+		return {
+			message: 'Whoops!',
+			code: error?.code ?? 'UNKNOWN'
+		};
+	}
```
Comment (benmccann) [inline documentation/docs/30-advanced/25-errors.md:112]: I'd probably write this as:
```suggestion
	if (status >= 500) {
		// example integration with https://sentry.io/
		Sentry.captureException(error, { extra: { event } });

		return {
			message: 'Whoops!',
			code: error?.code ?? 'UNKNOWN'
		};
	}
	return {
		message, // safe to forward
		code: 'UNKNOWN'
	};
```

File: packages/kit/src/exports/node/index.js (hunk 3 above)
Comment (dummdidumm) [reply packages/kit/src/exports/node/index.js:33]: I don't think an error at this stage will be handled by `handelError`, so I kept this clear of it. But we could use it.

File: documentation/docs/30-advanced/25-errors.md (hunk 10 above)
Comment (Rich-Harris) [reply documentation/docs/30-advanced/25-errors.md:112]: the `>=` is unnecessary — SvelteKit will never throw a 5xx error itself, so the only way you could get a 5xx error other than 500 is by using `error(...)`, in which case `handleError` wouldn't be involved

File: packages/kit/test/apps/basics/test/test.js [hunk 11]
```diff
@@ -1186,6 +1186,42 @@ test.describe('Actions', () => {
...
+		const response = await page.request.fetch(`${baseURL}/actions/enhance?/${randomActionName}`, {
+			method: 'POST',
+			body: 'irrelevant',
+			headers: {
+				Origin: `${baseURL}`
+			}
+		});
+		const { type, error } = await response.json();
+		expect(type).toBe('error');
+		expect(error.message).toBe(`No action with name '${randomActionName}' found`);
```
Comment (dummdidumm) [inline packages/kit/test/apps/basics/test/test.js:1222]:
```suggestion
		expect(error.message).toBe(`Not Found`);
```

File: packages/kit/test/apps/basics/test/test.js [hunk 12]
```diff
@@ -1186,6 +1186,42 @@ test.describe('Actions', () => {
...
+		expect(type).toBe('error');
+		expect(error.message).toBe('Actions expect form-encoded data');
+		expect(response.status()).toBe(415);
+	});
+
+	test('submitting to a form action that does not exists, should return http status code 404', async ({
+		baseURL,
+		page
+	}) => {
+		const randomActionName = 'some-random-action';
```
Comment (dummdidumm) [inline packages/kit/test/apps/basics/test/test.js:1212]:
```suggestion
```

File: packages/kit/test/apps/basics/test/test.js [hunk 13]
```diff
@@ -1186,6 +1186,42 @@ test.describe('Actions', () => {
...
+		const response = await page.request.fetch(`${baseURL}/actions/enhance?/${randomActionName}`, {
```
Comment (dummdidumm) [inline packages/kit/test/apps/basics/test/test.js:1213]:
```suggestion
		const response = await page.request.fetch(`${baseURL}/actions/enhance?/doesnt-exist`, {
```

File: packages/kit/test/apps/basics/test/test.js [hunk 14]
```diff
@@ -1186,6 +1186,42 @@ test.describe('Actions', () => {
...
+			method: 'POST',
+			body: JSON.stringify({ foo: 'bar' }),
+			headers: {
+				'Content-Type': 'application/json',
+				Origin: `${baseURL}`
+			}
+		});
+		const { type, error } = await response.json();
+		expect(type).toBe('error');
+		expect(error.message).toBe('Actions expect form-encoded data');
```
Comment (dummdidumm) [inline packages/kit/test/apps/basics/test/test.js:1204]:
```suggestion
		expect(error.message).toBe('Unsupported Media Type');
```

File: documentation/docs/30-advanced/25-errors.md (hunk 9 above)
Comment (dummdidumm) [reply documentation/docs/30-advanced/25-errors.md:80]: What is a better term? (the phrase was there previously, too)

Comment (benmccann) [reply documentation/docs/30-advanced/25-errors.md:80]: I would say, "Errors thrown without using [`error`](...)"

File: documentation/docs/30-advanced/20-hooks.md [hunk 15]
```diff
@@ -139,10 +139,10 @@ The following can be added to `src/hooks.server.js` _and_ `src/hooks.client.js`:
 
 ### handleError
 
-If an unexpected error is thrown during loading or rendering, this function will be called with the `error` and the `event`. This allows for two things:
+If an unexpected error is thrown during loading or rendering, this function will be called with the `error`, the `event`, a `status` code and a `message`. This allows for two things:
```
Comment (benmccann) [inline documentation/docs/30-advanced/20-hooks.md:142]: it's a bit odd that "the" is used before some words and "a" before others
```suggestion
If an unexpected error is thrown during loading or rendering, this function will be called with the `error`, `event`, `status` code and `message`. This allows for two things:
```

File: documentation/docs/30-advanced/25-errors.md (hunk 9 above)
Comment (dummdidumm) [reply documentation/docs/30-advanced/25-errors.md:80]: What "unexpected" means is specified in the paragraph above it, and the section is also called "unexpected errors" - I think it's fine as-is.

Comment (benmccann) [reply documentation/docs/30-advanced/25-errors.md:80]: Ah, yeah, that's probably fine in this location. It wasn't showing the paragraph above in the diff. It might not be as clear on the previous page though. I'll comment there

File: documentation/docs/30-advanced/20-hooks.md (hunk 15 above)
Comment (benmccann) [inline documentation/docs/30-advanced/20-hooks.md:142]: It might not be clear what "unexpected error" here refers to

File: packages/kit/src/exports/node/index.js (hunk 3 above)
Comment (Rich-Harris) [reply packages/kit/src/exports/node/index.js:33]: Not at _this_ stage, no. But the thing that reads the body will either catch the error (in which case it is then responsible for setting a status code) or, more likely, the error will go uncaught. At that point, it's useful if the error was a `SvelteKitError` with a correct status code. If it's a POJO then `handleError` will be called with a 500 Internal Error.

Comment (Rich-Harris) [reply packages/kit/src/exports/node/index.js:34]: More correctly: the above applied to the second occurrence, once the stream has already started being read.

In _this_ case, we're still creating the `Request` object. Right now, every usage of `getRequest` has to be wrapped in a `try-catch`, and the `catch` clause always looks like this:

```js
res.statusCode = err.status || 400;
res.end('Invalid request body');
```

This makes no sense — there's only one possible error (the 413), and the diagnostic message gets swallowed.

I think the best solution is to throw the 'content length exceeds limit' error immediately when the stream starts. That way, `getRequest` callers don't need to `try-catch`, and we get both user-friendly and developer-friendly error messages.

**Review by Rich-Harris — APPROVED** [review]

**Comment by dummdidumm** [comment]
Was the try-catch really only applied because of the known throw inside, or was it a "who knows let's better be extra safe" precaution?

**Comment by Rich-Harris** [comment]
Because of the known throw inside. It's a bad practice to wrap code that can't error
