### PR TITLE
ignore invalid accept header values instead of throwing an error

### LINKED ISSUE #4962: Accept header parsing possibly too strict
### Describe the bug

Hi! I noticed some 500 responses in our server logs and tracked it down to this line in SvelteKit:

https://github.com/sveltejs/kit/blob/27a9888161b86bcc8418f87f93ed54959c631079/packages/kit/src/runtime/server/page/index.js#L57

The Accept header in question was `text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2`, with the part throwing the error being `*; q=.2`. 

The user agent was `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36`

### Reproduction

Here's a test:

https://github.com/dannycoates/kit/blob/33e1215a10a172f205114228aa7da829a85e11f2/packages/kit/test/apps/basics/test/test.js#L625-L636

https://github.com/dannycoates/kit/commit/33e1215a10a172f205114228aa7da829a85e11f2

IMO it should return a 200 with the `text/html` type.

### Logs

_No response_

### System Info

```shell
N/A
```

### Severity

annoyance

### Additional Information

More than an annoyance tbh. The user sees a 500 error page. We just haven't seen too many of these in our logs yet.

### PR DESCRIPTION
**Pull request by elikoga**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
  - closes #4962  
- [x] This message body should clearly illustrate what problems it solves.
  - User encountered clients sending invalid accept header values in the wild, resulting in 500 error codes in logs.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0
  - minor change, so I don't think this needs a changelog

### CODE REVIEW

File: packages/kit/src/utils/http.js [hunk 1]
```diff
@@ -29,14 +29,15 @@ export function to_headers(object) {
...
 			const match = /([^/]+)\/([^;]+)(?:;q=([0-9.]+))?/.exec(str);
 			if (match) {
 				const [, type, subtype, q = '1'] = match;
-				return { type, subtype, q: +q, i };
+				return [{ type, subtype, q: +q, i }];
 			}
 
-			throw new Error(`Invalid Accept header: ${accept}`);
+			// invalid header
+			return [];
```
Comment (Rich-Harris) [inline packages/kit/src/utils/http.js:40]:
```suggestion
```

File: packages/kit/src/utils/http.js [hunk 2]
```diff
@@ -29,14 +29,15 @@ export function to_headers(object) {
...
 	const parts = accept
 		.split(',')
-		.map((str, i) => {
+		.flatMap((str, i) => {
 			const match = /([^/]+)\/([^;]+)(?:;q=([0-9.]+))?/.exec(str);
 			if (match) {
 				const [, type, subtype, q = '1'] = match;
-				return { type, subtype, q: +q, i };
+				return [{ type, subtype, q: +q, i }];
 			}
```
Comment (Rich-Harris) [inline packages/kit/src/utils/http.js:38]:
```suggestion
```

**Review by Rich-Harris — COMMENTED** [review]
thank you — can we use `map` instead of `flatMap`? feels slightly circuitous to create extra arrays only to unwrap them. made suggestions in the relevant places

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you!
