### PR TITLE
fix: crawl hrefs that start with `config.prerender.origin`

### LINKED ISSUE #12271: Crawler does not crawl absolute URIs even if they are on `prerender.origin`
### Describe the bug

During Prerendering the Crawler is supposed to discover all internal links & follow them. However, if an internal link is on an absolute URI (`https://my-site.com`) or a Network-Path-refernece (`//my-site.com`) it will not be crawled, even if the origin is the same as `prerender.origin`.

I would expect these links to be crawled as well, assuming they are on the base path. 

Example: 
- `prerender.origin = "https://my-page.com"`
- `base = "/base"`
- `href = "https://my-page.com/base/some-page"` (should cause `/some-page` to be crawled)

### Reproduction

https://github.com/LorisSigrist/sveltekit-absolute-uri-crawling-repro (instructions in README)

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 1.02 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 9.0.6 - /opt/homebrew/bin/pnpm
    bun: 1.1.8 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.4.1
  npmPackages:
    @sveltejs/adapter-static: ^3.0.0 => 3.0.1 
    @sveltejs/kit: ^2.4.3 => 2.5.7 
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.1.0 
    svelte: ^4.2.7 => 4.2.15 
    vite: ^5.2.6 => 4.5.2
```

### Severity

serious, but I can work around it

### Additional Information

`<link rel="alternate"` links MUST be [absolute URIs](https://www.rfc-editor.org/rfc/rfc3986#page-27) according to [the spec](https://developers.google.com/search/docs/specialty/international/localized-versions#all-method-guidelines). 

This issue makes it impossible for the crawler to discover alternate language versions of pages if they are only linked via alternate tags.

### PR DESCRIPTION
**Pull request by LorisSigrist**
Closes #12271 

Until now the crawler would not recoginze links that start with the value of `config.prerender.origin` as internal links & would not crawl them. This PR fixes that. 

For example: A link `<a href="https://my-site/base/some-page"` would not be crawled, even if `prerender.origin` was set to `https://my-site` in `svelte.config.js`. 

This is important since `<link rel="alternate"` requires links to be absolute URIs that include the protocol, so until now it was impossible for the crawler to discover pages that were linked to in valid `<link rel="alternate"` links. 

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/core/postbuild/prerender.js [hunk 1]
```diff
@@ -276,7 +276,18 @@ async function prerender({ out, manifest_path, metadata, verbose, env }) {
...
-			for (const href of hrefs) {
+			/** @param {string} href */
+			const removePrerenderOrigin = (href) => {
+				if (href.startsWith(config.prerender.origin)) {
+					if (href === config.prerender.origin) return '/';
+					if (href.at(config.prerender.origin.length) !== '/') return href;
+					return href.slice(config.prerender.origin.length);
+				} else {
+					return href;
+				}
```
Comment (benmccann) [inline packages/kit/src/core/postbuild/prerender.js:287]:
```suggestion
				}
				return href;
```

**Review by benmccann — APPROVED** [review]
thanks!!
