### PR TITLE
fix: don't stash away original `history` methods so other libs can monkeypatch it

### LINKED ISSUE #11499: Google Analytics (GA4) not working in SvelteKit 2
### Describe the bug

Google Analytics (GA4) should automatically collect pageviews based on browser history events. Pre 2.0 SvelteKit projects do this without a problem. Pageviews are triggered automatically by `history.pushState()` on route navigation.

In SvelteKit 2 pageviews are no longer triggered on route change, only on a full page refresh.

None of the solutions in "SvelteKit & Google Analytics" tutorials, blogs, videos are working at the moment.

### Reproduction

Minimal project with a Google Analytics tracking code in `+layout.svelte` and 2 routes to navigate between: https://github.com/hesselmid/ga4

### Logs

_No response_

### System Info

```Shell
"@sveltejs/kit": "^2.0.0"
```

### Severity

blocking an upgrade

### Additional Information

Understandably a lot of the Svelte community suggest to use another analytics tool like Plausible of Fathom, but a lot of real world clients are dependent on GA because of historic data, an e-commerce tracking setup or an integration with an ad platform.

### PR DESCRIPTION
**Pull request by dummdidumm**
Some other libraries might hook into `history.replaceState/pushState` to do additional work. This no longer works since the introduction of shallow routing because we're stashing away the original history methods. This PR adjusts the DEV time check logic so that this is no longer necessary.
Fixes #11499
Fixes https://github.com/vercel/analytics/issues/121

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -64,29 +64,37 @@ const scroll_positions = storage.get(SCROLL_KEY) ?? {};
...
 	const warn = () => {
 		if (warned) return;
+
+		// Avoid stashing away the original history methods which prevents monkeypatching by other libs,
+		// instead inspect the stack trace to see if we're being called from within SvelteKit.
+		let stack = new Error().stack?.split('\n');
+		if (!stack) return;
+		if (!stack[0].includes('https:') && !stack[0].includes('http:')) stack = stack.slice(1); // Chrome includes the error message in the stack
+		stack = stack.slice(2); // remove `warn` and the place where `warn` was called
+		if (stack[0].includes('src/runtime/client/client.js')) return;
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/client.js:79]: maybe this, just to make it slightly more resilient against file renames and whatnot? tested and it works

```suggestion
		if (stack[0].includes(import.meta.url)) return;
```

**Review by Rich-Harris — APPROVED** [review]
one small suggestion but otherwise LGTM

File: packages/kit/src/runtime/client/client.js [hunk 2]
```diff
@@ -64,29 +64,37 @@ const scroll_positions = storage.get(SCROLL_KEY) ?? {};
...
-const original_replace_state = BROWSER ? history.replaceState : () => {};
-
 if (DEV && BROWSER) {
 	let warned = false;
 
 	const warn = () => {
 		if (warned) return;
+
+		// Avoid stashing away the original history methods which prevents monkeypatching by other libs,
+		// instead inspect the stack trace to see if we're being called from within SvelteKit.
```
Comment (benmccann) [inline packages/kit/src/runtime/client/client.js:74]: I might reword this slightly in case "stashing away" isn't clear
```suggestion
		// Rather than saving a pointer to the original history methods, which would prevent monkeypatching by other libs,
		// inspect the stack trace to see if we're being called from within SvelteKit.
```

**Review by benmccann — APPROVED** [review]
thank you for fixing this!!

**Comment by lukasmalkmus** [comment]
This PR, released as part of `v2.3.4` results in a new warning that wasn't previously there: `[Warning] Avoid using `history.pushState(...)` and `history.replaceState(...)` as these will conflict with SvelteKit's router. Use the `pushState` and `replaceState` imports from `$app/navigation` instead. (client.js, line 2580)`

I'm not using `history` as suggested by the warning. I'm using `goto` in a couple of places, from `$app/navigation`. I haven't changed anything. The warning is not present with `v2.3.3`.

From a quick test, commenting out all the `goto` calls still resulted in the warning.
