### PR TITLE
[fix] rename dotfiles to avoid template problems

### LINKED ISSUE #2952: [bug] `npm init svelte@next` - some files missing
### Describe the bug

I don't get any warning using npm 6 and Node 12 on Ubuntu. If I create an `.npmrc` with `engine-strict=true` then it will fail. We try to do that today:

https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/skeleton/.npmrc
https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/.npmrc

But those files don't get created for some reason

### Reproduction

If I run `npm init svelte@next my-test-app` I don't see an `.npmrc` file being created in the new app

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Conduitry**
Fixes #2952.

Rather than adding another special case for `.npmrc` like there already is for `.gitignore`, this simply renames all dotfiles to instead begin with `DOT-` when the `create-svelte` package is being built, and un-renames them when bootstrapping a new project with the CLI. This doesn't currently handle dotfiles other than at the top level of a particular template, but we don't have any of those. I didn't include that for simplicity, but if other folks think that would be a good idea to handle now while we're thinking of it, I'd be amenable to that.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by ignatiusmb — APPROVED** [review]

**Review by bluwy — APPROVED** [review]

**Comment by dummdidumm** [comment]
I don't see the renamed dot-files in this PR

**Comment by Conduitry** [comment]
They're not renamed in this repo, and they shouldn't need to be. They're renamed as they're copied into the `dist` folder that gets packaged up, and then renamed back by the CLI when they're copied to the user's directory. Try this out locally and examine the contents of `npm pack` and the results of running the CLI.

**Review by dummdidumm — APPROVED** [review]
Ah now I understand, thanks!

File: packages/create-svelte/bin.js [hunk 1]
```diff
@@ -134,7 +134,7 @@ async function main() {
  */
 function write_template_files(template, typescript, name, cwd) {
 	const dir = dist(`templates/${template}`);
-	copy(`${dir}/assets`, cwd, (name) => name.replace('gitignore', '.gitignore'));
+	copy(`${dir}/assets`, cwd, (name) => name.replace('DOT-', '.'));
```
Comment (dreitzner) [inline packages/create-svelte/bin.js:137]: Maybe use regex here too, for the off chance that there will ever be any file containing `DOT-` in it's name...
```suggestion
	copy(`${dir}/assets`, cwd, (name) => name.replace(/^DOT-/, '.'));
```

**Review by dreitzner — APPROVED** [review]
LGTM

File: packages/create-svelte/bin.js (hunk 1 above)
Comment (dreitzner) [reply packages/create-svelte/bin.js:137]: `DOT-` could also be extracted as constsant into `packages/create-svelte/utils.js`

**Comment by benmccann** [comment]
I didn't review, but with four approvals, this seems safe to merge :smile:
