### PR TITLE
fix: ensure static error page is loaded correctly for custom user errors

### LINKED ISSUE #13951: TypeError: Cannot read properties of undefined (reading 'replace') at escape_html
### Describe the bug

Instead of an error page, I'm getting a blank page (no HTML even, just text) with the content:

> TypeError: Cannot read properties of undefined (reading 'replace') at escape_html (eval at runInlinedModule (file:///C:/Users/.../node_modules/vite/dist/node/module-runner.js:1062:11), :55:26) at static_error_page (eval at runInlinedModule (file:///C:/Users/.../node_modules/vite/dist/node/module-runner.js:1062:11), :46:94) at handle_fatal_error (eval at runInlinedModule (file:///C:/Users/.../node_modules/vite/dist/node/module-runner.js:1062:11), :68:10) at async respond (eval at runInlinedModule (file:///C:/Users/.../node_modules/vite/dist/node/module-runner.js:1062:11), :336:12) at async file:///C:/Users/.../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:540:22

I've looked a bit into the functions from the stacktrace and it seems this function is the problem:

https://github.com/sveltejs/kit/blob/217fc24f2d86eb0b29ab0565d89a4ef620ef5338/packages/kit/src/runtime/server/utils.js#L99-L116

It promises to return an object that always has a string `message` property, but in case of an `HttpError` (first if statement in the function), this is not true. The error is defined by `App.Error`, which is user-arbitrary.

### Reproduction

Throw `error(400, { code: 123 })` in the `handle` hook. This is allowed by TypeScript if using custom error using something like this in `app.d.ts`:

```ts
declare namespace App {
    // ...

    interface Error {
        code: number
        message?: string
    }
}
```

### Logs

```Shell

```

### System Info

```Shell
-
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by rChaoz**
Closes #13951

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/server/utils.js [hunk 1]
```diff
@@ -98,7 +98,8 @@ export async function handle_fatal_error(event, options, error) {
  */
 export async function handle_error_and_jsonify(event, options, error) {
 	if (error instanceof HttpError) {
-		return error.body;
+		// @ts-expect-error custom user errors may not have a message field if App.Error is overwritten
+		return { message: "Unknown Error", ...error.body };
```
Comment (benmccann) [inline packages/kit/src/runtime/server/utils.js]: You should run `pnpm format`. I'm assuming it's failing because of the double quotes
```suggestion
		return { message: 'Unknown Error', ...error.body };
```
