### PR TITLE
fix: serialize server `load` data before passing to universal load alternative

### LINKED ISSUE #14291: Streaming a custom class promise from server to client fails when a `load` function is in `+page.ts`
### Describe the bug

I have a custom class `Point`:
```ts
// lib/point.ts
export class Point {
	private _x: number
	private _y: number

	constructor(x: number, y: number) {
		this._x = x,
		this._y = y
	}

	get x() { return this._x }
	get y() { return this._y }
}
```

I have created the following `transport` definition for the class `Point`:
```ts
// hooks.ts
import type { Transport } from "@sveltejs/kit";
import { Point } from "$lib/point.ts";

export const transport: Transport = {
    Point: {
	    encode: (value) => value instanceof Point && { x: value.x, y: value.y },
	    decode: ({ x, y }) => new Point(x, y)
    }
};
```

I am streaming the custom class from the server:
```ts
// routes/+page.server.ts
import { Point } from "$lib/point.ts"
import { sleep } from "$lib/sleep.ts"

const createPoint = async (x: number, y: number) => {
	await sleep(1000)
	return new Point(x, y)
}

export const load = async () => {
	const point_promise = createPoint(5,6);
	return { point_promise };
};
```

```svelte
<script>
        // +page.svelte
	let { data } = $props();
</script>

<h1>
	Coordinates:
	{#await data.point_promise}
		...loading...
	{:then point} 
		x: {point.x}
		y: {point.y}
	{/await}
</h1>
```

All this works! But if i add a `load` function inside of `+page.ts` and just pass the data along:
```ts
export async function load({ data }) {
	return { ...data }
}
```

The function fails due to the following error:
```
Error: Data returned from `load` while rendering / is not serializable: Cannot stringify arbitrary non-POJOs (point_promise). If you need to serialize/deserialze custom types, use transport hooks: https://svelte.dev/docs/kit/hooks#Universal-hooks-transport
        at get.data (node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:211:23)
        at load (src/routes/+page.ts:4:23)
```

### Reproduction

https://www.sveltelab.dev/93mw77a659044tg

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.62 GB / 15.79 GB
  Binaries:
    Node: 22.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (139.0.3405.102)
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1
    @sveltejs/adapter-node: ^5.2.10 => 5.3.1
    @sveltejs/kit: ^2.0.0 => 2.36.1
    @sveltejs/vite-plugin-svelte: ^4.0.0-next.6 => 4.0.4
    svelte: ^5.38.1 => 5.38.1
    vite: ^5.0.3 => 5.4.19
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by PatrickG**
Alternative to #14268
Fixes #14291

CC @Rich-Harris

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/server/page/index.js [hunk 1]
```diff
@@ -192,6 +199,13 @@ export async function render_page(
 					throw load_error;
 				}
 			});
+
+			void promise.then((server_data) => {
+				data_serializer.serialize(i, server_data);
```
Comment (PatrickG) [inline packages/kit/src/runtime/server/page/index.js]: I think if `data_serializer.serialize()` throws an error, it needs to be catched here and rethrown after the load promises are resolved.

**Comment by PatrickG** [comment]
Finally all green.

**Comment by Rich-Harris** [comment]
Please resist the temptation to make drive-by tidy-ups, especially ones as large as these! It drowns out the substance of the PR and makes it much harder to understand what has actually changed. My tendency as a reviewer is to put PRs with large diffs in the 'ugh... later' pile, and I suspect a lot of maintainers are the same way.

Now that I've reverted all those changes I can get to work on the actual review :)

**Comment by PatrickG** [comment]
Sorry, it wasn't a temptation, it happened automatically on save. I usually undo these myself before committing, must have forgotten.

**Comment by Rich-Harris** [comment]
Ah, interesting. FWIW they _were_ good changes — the imports are very raggedy. Would just be nice to update them all en masse (and maybe add similar tooling to keep them organised afterwards), once there are no open PRs that doing so would create merge conflicts with

**Review by Rich-Harris — APPROVED** [review]
awesome work, thank you!

**Comment by PatrickG** [comment]
Nice solution for that nonce thing
