### PR TITLE
fix: layout load data not serialized on error page

### LINKED ISSUE #14387: Layout data lost on +error.svelte
### Describe the bug

I noticed something yesterday after upgrading on of my SvelteKit projects from 2.37.0 to 2.37.1.

I created a repo that reproduces the issue as described below, repo can be found here: https://github.com/ReindDooyeweerd/sveltekitbug

**The issue:**
In my +layout.server.ts i normally fetch some data that is used throughout the whole website like menu data etc, this works great.

In the repo posted above i created a [slug] with a +page.server.ts which also fetches some data so https://localhost:5173/ shows the data fetched in the layout and https://localhost:5173/a shows both the data from +layout.server.ts and +page.server.ts => https://share.cleanshot.com/FV2B0qQYx2nNRLFS7mfQ

So far so good. Then i created a [slug_2] inside [slug], added a fetch also BUT i make sure that doesn't return any data and throw a 404. So https://localhost:5173/a/b should end up on +error.svelte

```
if (!fetchedPageData || Object.keys(fetchedPageData).length === 0) {
  error(404, 'Page not found');
}
```

This renders the +error.svelte but now the weird stuff happens since 2.37.1, the layout data becomes empty also: https://share.cleanshot.com/fx5VwqlRWJ67cLlKMKmz

While on version 2.37.0 with the exact same code i get this: https://share.cleanshot.com/x5bFFgz84gTjNJxVxjpR

### Reproduction

1. Clone https://github.com/ReindDooyeweerd/sveltekitbug
2. npm install && npm run dev
3. visit https://localhost:5173 => layout data in pre tags
4. visit https://localhost:5173/a => layout data + page data in pre tags
5. visit https://localhost:5173/a/b => fetch is empty, +error.svelte is rendered and both pre tags are empty
6. change sveltekit version to 2.37.0 in package.json and start from 2 and on 5. you will see that the layout data is still available while pagedata is empty as expected

### Logs

```Shell
Nothing in the browser console or terminal
```

### System Info

```Shell
System:
    OS: macOS 15.6.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 641.34 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.17.0 - ~/.nvm/versions/node/v22.17.0/bin/node
    npm: 10.9.2 - ~/.nvm/versions/node/v22.17.0/bin/npm
  Browsers:
    Chrome: 140.0.7339.80
    Safari: 18.6
  npmPackages:
    @sveltejs/adapter-auto: ^6.1.0 => 6.1.0 
    @sveltejs/kit: ^2.37.0 => 2.37.1 
    @sveltejs/vite-plugin-svelte: ^6.1.4 => 6.1.4 
    svelte: ^5.38.7 => 5.38.7 
    vite: ^7.1.5 => 7.1.5
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by PatrickG**
Fixes #14387

I made a mistake in #14298
When a load function errors, we still need the serialized data of the successfully run layout load functions.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/server/page/data_serializer.js [hunk 1]
```diff
@@ -95,6 +100,10 @@ export function server_data_serializer(event, event_state, options) {
 			const open = `<script${csp.script_needs_nonce ? ` nonce="${csp.nonce}"` : ''}>`;
 			const close = `</script>\n`;
 
+			if (max_nodes > -1) {
+				strings.length = max_nodes;
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/data_serializer.js]: probably fine because we're not using `get_data` multiple times, but theoretically you could set `max_nodes` to something else and call `get_data` again, and then have a wrong result. Should we do `max_nodes > -1 ? strings.slice(0, max_nodes) : strings` within `data:` below instead?

File: packages/kit/src/runtime/server/page/data_serializer.js [hunk 2]
```diff
@@ -95,6 +100,10 @@ export function server_data_serializer(event, event_state, options) {
...
+			}
+
 			return {
 				data: `[${strings.join(',')}]`,
 				chunks: promise_id > 1 ? iterator.iterate((str) => open + str + close) : null
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/data_serializer.js]: somewhat convoluted, but could it be possible that these chunks stream resolutions for data that is cut off now - and if so, would it crash or be harmless because the "promise for this doesn't exist"-case is a noop and not a runtime crash?

Comment (PatrickG) [reply packages/kit/src/runtime/server/page/data_serializer.js]: Good point.
Looks like it would result in an infinite loop: https://github.com/sveltejs/kit/blob/54e10cf07ab2bf06c6ec6d2ea225c34936c5d2e8/packages/kit/src/runtime/server/page/render.js#L398-L401

Any ideas?

Comment (PatrickG) [reply packages/kit/src/runtime/server/page/data_serializer.js]: How about [that](https://github.com/sveltejs/kit/pull/14395/files/d0f6a59d1911ac20fdbe35cea98775137ca3ef35..7331cba4177672c10936e3ea1d944fcac5795575)?
