### PR TITLE
fix: allow calling `fetch` for any scheme

### LINKED ISSUE #10657: fetch with data URL throws error when used in SvelteKit
### Describe the bug

I have a web app that takes a zlib-compressed and base64-encoded blob as user input. I validate the data on the client, before sending it to the server, where it is validated again. 

The validation happens by passing the base64-encoded blob to `fetch()` as a data URL, which returns a `ReadableStream` that is then deflated using a `DecompressionStream`. The validation function works in the browser and in node.js, which was a priority to not have nearly identical duplicate code.

Adding the function call on the server side (`+page.server.ts`) raises an exception.

```
Error: Cannot use relative URL (data:application/octet-stream;base64,eNrtfV1vXMm…) with global fetch — use `event.fetch` instead: https://kit.svelte.dev/docs/web-standards#fetch-apis
    at globalThis.fetch …
```

Svelte is mistakenly identifying a data URL as a relative URL.
And forcibly raising an error when global `fetch()` is used is a problem as well, because this prevents the use of functions that are designed to work in both environments, client and server.

### Reproduction

Run this line in nodejs and in a `+page.server.js` file.

```js
await fetch("data:application/octet-stream;base64,eNrtfV==")
```

### Logs

_No response_

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 16.37 GB / 31.75 GB
  Binaries:
    Node: 20.3.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 7.25.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    svelte: ^4.0.5 => 4.2.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by danielniccoli**
Fixes https://github.com/sveltejs/kit/issues/10657

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by danielniccoli** [comment]
Continuation of https://github.com/sveltejs/kit/pull/10656

> That sounds fine, but I think your translation from text to reflex omitted uppercase letters and "+"

_Originally posted by @benmccann in https://github.com/sveltejs/kit/issues/10656#issuecomment-1712495436_

The "+" is in there, hidden in plain sight. `\d+` does match on digits and plus because its within square brackets.

The uppercase letters are also matched due to insensitive flag.

**Comment by benmccann** [comment]
Thanks. This looks good to me, but could we refactor this shared logic into a util method like `is_relative_url` probably in `src/utils/url.js`?

**Comment by danielniccoli** [comment]
@benmccann, I have put some thought into your suggestion and I think it would be better to not have a function and accept that this regex will be used at two places. The test answers the questions "Is this a relative URL?" with an approximation that is just good enough for the specific case. For example, it will tell you that "mailto:jon.doe@example.com" is an absolute URL. But it's a URI and neither absolute nor relative. Putting this into a function may encourage devs to use it elsewhere, which could cause unintentional side effects.

I do not have an alternative suggestion. I added some comments to the two lines to clarify what is tested and why.

Let me know your thoughts. If you think the concerns are negligible, I will refactor.

**Comment by benmccann** [comment]
That's a fair point. How about extracting the regex out into a constant like `SCHEME_REGEX` in `utils/url.js` or something along those lines?

**Comment by danielniccoli** [comment]
@benmccann I like that. There's already a `scheme` variable declared, but it's not exported, so I think we can get away with an additional exported constant? (I don't want to rewrite the already present one, because I don't know what `resolve()` does and where it's used.)

```js
import { BROWSER } from 'esm-env';

// <<<<<<<<<<<<<<<
/** @constant - Matches a URI scheme (https://www.rfc-editor.org/rfc/rfc3986#section-3.1)
    @type {RegExp}
    @default
*/
export const SCHEME = /^[a-z][a-z\d+\-.]+:/i;
// >>>>>>>>>>>>>>>

const absolute = /^([a-z]+:)?\/?\//;
const scheme = /^[a-z]+:/;

/**
 * @param {string} base
 * @param {string} path
 */
export function resolve(base, path) {
```

**Comment by benmccann** [comment]
Just go ahead and update the existing one. `resolve` is used during prerendering. I don't think anything should be negatively affected by updating the existing `scheme` regex with a more accurate one

**Comment by danielniccoli** [comment]
Refactored.

File: packages/kit/src/utils/url.js [hunk 1]
```diff
@@ -1,14 +1,19 @@
 import { BROWSER } from 'esm-env';
 
+/** @constant - Matches a URI scheme (https://www.rfc-editor.org/rfc/rfc3986#section-3.1)
+    @type {RegExp}
+    @default
+*/
```
Comment (benmccann) [inline packages/kit/src/utils/url.js:6]: updating the formatting here and removing tags that tsc doesn't know about https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
```suggestion
/**
 * Matches a URI scheme. See https://www.rfc-editor.org/rfc/rfc3986#section-3.1
 * @type {RegExp}
 */
```

File: packages/kit/src/runtime/server/page/render.js [hunk 2]
```diff
@@ -151,7 +152,11 @@ export async function render_response({
 			const fetch = globalThis.fetch;
 			let warned = false;
 			globalThis.fetch = (info, init) => {
-				if (typeof info === 'string' && !/^\w+:\/\//.test(info)) {
+				// The regex below does not strictly check if a URL is absolute, but checks for the existance
+				// of a scheme, which implies that it is absolute when the scheme is e.g., http or https.
+				// And it will accept data URLs, which don't require a network request.
+				// Regex based on scheme definition at https://www.rfc-editor.org/rfc/rfc3986#section-3.1
```
Comment (benmccann) [inline packages/kit/src/runtime/server/page/render.js:158]: this seems pretty self-explanatory from the nice variable name we have now and the link is already included in that variable's description
```suggestion
```

File: packages/kit/src/exports/vite/dev/index.js [hunk 3]
```diff
@@ -31,7 +32,11 @@ export async function dev(vite, vite_config, svelte_config) {
 
 	const fetch = globalThis.fetch;
 	globalThis.fetch = (info, init) => {
-		if (typeof info === 'string' && !/^\w+:\/\//.test(info)) {
+		// The regex below does not strictly check if a URL is absolute, but checks for the existance
+		// of a scheme, which implies that it is absolute when the scheme is e.g., http or https.
+		// And it will accept data URLs, which don't require a network request.
+		// Regex based on scheme definition at https://www.rfc-editor.org/rfc/rfc3986#section-3.1
```
Comment (benmccann) [inline packages/kit/src/exports/vite/dev/index.js:38]:
```suggestion
```

**Review by benmccann — APPROVED** [review]

**Comment by benmccann** [comment]
Thanks for the great PR!
