### PR TITLE
breaking: generate plaintext 404.html for Cloudflare Pages, instead of SPA-style fallback

### LINKED ISSUE #9386: @sveltejs/adapter-cloudflare v2.2.0 always triggers hooks on build
### Describe the bug

Took a while to track down the cause of this, but I recently updated to adapter-cloudflare 2.2.0 and my builds started to break.

It appears a change from 2.1.0 to 2.2.0 now always triggers `hooks.server.js` to run, even if there are no configured prerenderable routes, which then triggers my auth middleware which redirects the user to another domain if they have no authentication cookie set (see `hooks.server.js` in the repro repo).

v2.1.0 works fine and I can build without the hook getting triggered by the adapter, but now in 2.2.0 it always triggers and thus breaks the build. AFAIK this means that there is no way to build for CloudFlare anymore if you have such an auth hook in place.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-g2rzrj?file=src/hooks.server.js

Run `npm run build` to see the issue. Downgrade to `2.1.0` to see it go away

### Logs

```Shell
> Using @sveltejs/adapter-cloudflare
file:///Users/my-app/node_modules/@sveltejs/kit/src/core/postbuild/fallback.js:53
        throw new Error(`Could not create a fallback page — failed with status ${response.status}`);
              ^

Error: Could not create a fallback page — failed with status 302
    at generate_fallback (file:///Users/my-app/node_modules/@sveltejs/kit/src/core/postbuild/fallback.js:53:8)
    at async process.<anonymous> (file:///Users/my-app/node_modules/@sveltejs/kit/src/utils/fork.js:25:17)
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///Users/my-app/node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 740.67 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/Library/Caches/fnm_multishells/80853_1678404247439/bin/node
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/80853_1678404247439/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 111.0.5563.64
    Firefox: 103.0
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: 2.0.0 => 2.0.0 
    @sveltejs/adapter-cloudflare: 2.1.0 => 2.1.0 
    @sveltejs/kit: 1.11.0 => 1.11.0 
    svelte: 3.55.1 => 3.55.1 
    vite: 4.1.4 => 4.1.4
```

### Severity

breaks production builds, no work around except downgrading

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
Alternative to #9762. Closes #9386. Instead of generating an SPA-style fallback page, we render a plaintext `Not Found` page, which is sufficient for the case where a request is made for a missing asset that is covered by an `exclude` rule. For all other requests, we will hit the worker, which will generate the correct 404 page.

Today:

- [/missing](https://kit-5ry.pages.dev/missing)
- [/_app/immutable/missing](https://kit-5ry.pages.dev/_app/immutable/missing)

With this PR:

- [/missing](https://b91f918d.kit-5ry.pages.dev/missing) (same as before)
- [/_app/immutable/missing](https://b91f918d.kit-5ry.pages.dev/_app/immutable/missing) (plaintext 404)

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Review by eltigerchino — APPROVED** [review]
Looks good! The issue has always been because of the wildcard exclude of our immutable assets and this solves that (albeit we don’t get the nice looking error page but it’s unlikely someone navigated to /_app/* anyway)

**Review by RowanAldean — APPROVED** [review]
Looks functional, not ideal. Seems safe to merge.

File: packages/adapter-cloudflare/index.d.ts [hunk 1]
```diff
@@ -4,6 +4,18 @@ import './ambient.js';
 export default function plugin(options?: AdapterOptions): Adapter;
 
 export interface AdapterOptions {
+	/**
+	 * Whether to render a plaintext 404.html page, or a rendered SPA fallback page. This page will
+	 * only be served when a request that matches an entry in `routes.exclude` fails to match an asset.
+	 *
+	 * Most of the time `plaintext` is sufficient, but if you are using `routes.exclude` to manually
+	 * exclude a set of prerendered pages without exceeding the 100 route limit, you may wish to
+	 * use `spa` instead.
```
Comment (benmccann) [inline packages/adapter-cloudflare/index.d.ts:13]: is there anything we should say here about what the behavior might be if you try to use exclude without spa?

**Review by benmccann — APPROVED** [review]
maybe a little weird to have one path that behaves differently, but really shouldn't matter. I'm fine with this if it helps simplify things

File: packages/adapter-cloudflare/index.d.ts (hunk 1 above)
Comment (Rich-Harris) [reply packages/adapter-cloudflare/index.d.ts:13]:
```suggestion
	 * use `spa` instead to avoid showing an unstyled 404 page to users.
```
