### PR TITLE
security: Stop automatically adding URLs from server-side `load` `fetch` calls to dependencies

### LINKED ISSUE #9803: Secrets exposed in server only `load` fetch dependencies
### Describe the bug

Thanks for the awesome open source work. 

I'm quite new to Svelte and SvelteKit and recently decided to use in a project to learn it more. I think, I've discovered some bug or issue in SvelteKit with my very limited experience using it. 

I'm loading some data in `+layout.server.ts` from an external url which requires sending api key as query param. I've stored the api key in `.env` file. I'm loading the data in `+layout.server.ts` specifically because I don't want to expose api key to the client. But even this file is also exposing it to client as part of url dependency for the `fetch`.

I tried calling `depends` inside `load` but it adds additional dependencies along with fetch url. I couldn't find any way to prevent SvelteKit using url as dependency. 

As an alternate solution to this, I could've created an internal api route which calls the external api with api key but I think `+layout.server.ts` shouldn't expose the url (and secrets certainly not) to client as it guarantees to run the code only server side. I don't see any benefit of using server only load of `+layout.server.ts` over universal load in `+layout.ts`, if it exposes the url (and secrets) to client.

### Reproduction

1. Create an `.env` file and add a secret such as `API_KEY=top-secret-key`.
2. Create a load function in `+layout.server.ts` which uses `fetch` to load data from external api. Import and pass `API_KEY` environment variable to fetch url as query param.
3. Use the server fetched data in `+layout.svelte`.
4. Open the browser dev tools and view source. At the bottom in `script` tag, you'll find that your secret `API_KEY` is exposed to the client.

```javascript
const data = [
	{
		type: 'data',
		data: {
			todos: [
				{ id: 1, title: 'one' },
				{ id: 2, name: 'two' }
			]
		},
		uses: {
			dependencies: [
				'https://jsonplaceholder.typicode.com/todos?api_key=top-secret-key'        // <---- Secret exposed
			]
		}
	},
	null
]
```

Here's a demo project I've created to reproduce this issue:
https://stackblitz.com/edit/sveltejs-kit-template-default-eeb3rv?file=src/routes/+layout.server.js

Also note that in my testing with `@sveltejs/kit@next` version the `dependencies` array is empty which is what I was expecting.

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.15.9
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.3.0 => 4.3.3
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tcc-sejohnson**
Closes #9803. This is a breaking change for security purposes.

This PR prevents server `load` function from implicitly depending on URLs passed to `fetch`. This is because dependencies from server `load` functions have to be sent to the client in order to be invalidated, which can leak secrets (if they're in the search params, for example).

If you understand the risk and want to keep the old behavior, you can set `config.kit.dangerZone.trackServerFetchesPotentiallyExposingSecrets` to `true`.

TODO:
- [x] Tests
- [x] Docs

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/types/index.d.ts [hunk 1]
```diff
@@ -340,6 +340,16 @@ export interface KitConfig {
...
 	};
+	/**
+	 * Here be dragons. Enable at your peril.
+	 */
+	dangerZone?: {
+		/**
+		 * Automatically add server-side `fetch`ed URLs to the `dependencies` map of `load` functions. This will expose secrets
+		 * to the client if your URL contains them.
+		 */
+		trackServerFetchesPotentiallyExposingSecrets?: boolean;
```
Comment (Rich-Harris) [inline packages/kit/types/index.d.ts:351]: I think we can trim the option name down to `trackServerFetches` — we can explain the details in the inline documentation, and the `dangerZone` makes it clear that this is 'know what you're doing' territory

```suggestion
		/**
		 * Mark server `load` functions that call `fetch(url)` as depending on `url`, allowing you to
		 * call `invalidate(url)` from the client. The URL, including e.g. sensitive query parameters,
		 * will be visible to the client. This option will be removed in version 2; use `depends` instead
		 */
		trackServerFetches?: boolean;
```

Comment (tcc-sejohnson) [reply packages/kit/types/index.d.ts:351]: I dunno, I like explicitly requiring users to acknowledge what they're doing -- there's no guarantee they understand why this is dangerous. Happy to make the change, but I personally think the annoyance of typing a gigantic and explicit config value is worth it, especially since it's not going to be around forever.

**Review by Rich-Harris — APPROVED** [review]
