### PR TITLE
fix: realign state.branch on the client on hydration

### LINKED ISSUE #9745: Enhanced form action error is only shown when a layout is present.
### Description
When submitting a form an error is thrown but it is only displayed when a layout is present. Without the layout, the error is not displayed unless the `use:enhance` option is removed.

### Expected Behavior

The error should be displayed regardless of whether a layout is present or `use:enhance` is used.

### Actual Behavior

The error is only displayed when a layout is present, or when `use:enhance` is removed.

### Steps to Reproduce

1. Create a form with use:enhance.
2. Create a form action that throws an error.
3. Submit the form.
4. If a layout is present, the error is displayed. If not, the error is not displayed unless `use:enhance` is removed.

I create a setup here:

repository: https://github.com/eduardolagoeiro/sk-error-form-enhance
form: http://localhost:5173/my-form

To see the bug, remove the use:enhance and/or rename the `src/my-form/_+layout.svelte` to `src/my-form/+layout.svelte`

### Logs

_No response_

### System Info

```Shell
System:
  OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Memory: 11.10 GB / 15.47 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
Browsers:
  Chrome: 112.0.5615.49
  Firefox: 112.0.1
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
  @sveltejs/kit: ^1.5.0 => 1.15.7 
  svelte: ^3.54.0 => 3.58.0 
  vite: ^4.2.0 => 4.3.1
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gtm-nayan**
fixes #9745

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/test/apps/basics/test/test.js [hunk 1]
```diff
@@ -1066,6 +1066,13 @@ test.describe('Actions', () => {
 
 		await expect(page.locator('h1')).toHaveText('400');
 	});
+
+	test.only('errors are rendered at the correct level', async ({ page }) => {
```
Comment (gtm-nayan) [inline packages/kit/test/apps/basics/test/test.js:1070]:
```suggestion
	test('errors are rendered at the correct level', async ({ page }) => {
```

File: packages/kit/src/runtime/client/client.js [hunk 2]
```diff
@@ -1734,14 +1734,30 @@ export function create_client(app, target) {
...
 				});
 
+				/** @type {Array<import('./types').BranchNode | undefined>} */
+				const branch = await Promise.all(branch_promises);
+
+				const parsed_route = routes.find(({ id }) => id === route.id);
+
+				// server-side will have compacted the branch, reinstate empty slots
+				// so that error boundaries can be lined up correctly
+				if (parsed_route) {
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/client.js:1744]: Instead of having this additional code to un-compact it, wouldn't it be less code to not compact the branch server-side for the initial request?

Comment (gtm-nayan) [reply packages/kit/src/runtime/client/client.js:1744]: Need to litter quite a few null checks to do it from the server side, https://github.com/sveltejs/kit/commit/cb3dcdeca69268042814997ac50089a6a5c2047a

I was thinking it'd better to have slightly more code in a perma-cached asset than adding empty slots for the node_ids and the corresponding server data nodes in every SSR'ed response.

**Review by dummdidumm — APPROVED** [review]
