### PR TITLE
[fix] unselect before navigation

### LINKED ISSUE #1054: Text selection is kept when switching between svelte routers - should be resetting?
Text selection is kept when switching between svelte routers(If it is in `$layout.svelte`). I don't know if this shouldn't be cleared by the router by default either?

The `router.js` file just executes `document.body.focus();` every time the router is rebooted:
https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L245
And for the scroll position (conditionally):
https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L254
Should text selection be treated the same?

`document.body.focus();` and `scrollTo(0, 0);` is to simulate a full website refresh.
Should `router.js` be run with a line that resets the text selection:
```javascript
window.getSelection().empty();
```

I emphasize: This is NOT needed directly by me, but I noticed this behavior during experiments with sveltekit.

### PR DESCRIPTION
**Pull request by treenoder**
fixes #1054

### Before submitting the PR, please make sure you do the following
- *[x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- *[x] This message body should clearly illustrate what problems it solves.
- *[x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- *[x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- *[x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/client/utils.js [hunk 1]
```diff
@@ -9,3 +9,13 @@ export function get_base_uri(doc) {
...
+
+/** @param {Window} win */
+export function unselect_all(win) {
+	if (win.getSelection) {
+		const selection = win.getSelection();
+		if (selection) {
+			selection.removeAllRanges();
+		}
+	}
+}
```
Comment (bluwy) [inline packages/kit/src/runtime/client/utils.js:21]: I believe the global variable `window` is generally avoided in the router code. We could probably simplify this as:

```js
getSelection()?.removeAllRanges()
```

With this one line, maybe we don't need a function after all.

File: packages/kit/src/runtime/client/router.js [hunk 2]
```diff
@@ -250,8 +250,8 @@ export class Router {
 	 * @param {string} [hash]
 	 */
 	async _navigate(url, scroll, keepfocus, chain, hash) {
+		unselect_all(window);
```
Comment (bluwy) [inline packages/kit/src/runtime/client/router.js:253]: Assuming after we inline the code, I'm not sure if placing the unselect logic here is correct. I have a feeling it should be at [this line](https://github.com/sveltejs/kit/blob/93726c38d2118b1dc136f3ef659c5ae6bb039138/packages/kit/src/runtime/client/renderer.js#L277), but @benmccann may know better where this fits.

File: packages/kit/test/apps/basics/src/routes/selection/_tests.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
+import * as assert from 'uvu/assert';
+
+/** @type {import('test').TestMaker} */
+export default function (test) {
+	test('reset selection', '/selection/a', async ({ page, clicknav }) => {
+		await page.waitForTimeout(50);
```
Comment (bluwy) [inline packages/kit/test/apps/basics/src/routes/selection/_tests.js:6]: Is there a reason to wait for timeout? We have tried to avoid this if possible. If it's really needed, we should add a comment explaining it..

File: packages/kit/test/apps/basics/src/routes/selection/_tests.js [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+					selection.removeAllRanges();
+					selection.addRange(range);
+					return selection.rangeCount;
+				}
+				return 0;
+			}),
+			1
+		);
+		await clicknav('[href="/selection/b"]');
+		await page.waitForTimeout(50);
```
Comment (bluwy) [inline packages/kit/test/apps/basics/src/routes/selection/_tests.js:22]: And the timeout here too.

Comment (treenoder) [reply packages/kit/test/apps/basics/src/routes/selection/_tests.js:22]: Test was inconsistent without that timeout, on my setup at least. Maybe someone can run tests to confirm.

Comment (treenoder) [reply packages/kit/test/apps/basics/src/routes/selection/_tests.js]: Can't reproduce inconsistencies so waitForTimeout calls was removed. By the way, is there a docker file or something for contributors, to build/test project?

Comment (bluwy) [reply packages/kit/test/apps/basics/src/routes/selection/_tests.js]: > By the way, is there a docker file or something for contributors, to build/test project?

There isn't one that I know of, but I don't have much issues with local test inconsistencies in the past. Playwright ships its own chromium browser IIRC so that should eliminate most of the cross-machine quirks.

File: packages/kit/src/runtime/client/router.js [hunk 5]
```diff
@@ -251,7 +251,6 @@ export class Router {
 	 */
 	async _navigate(url, scroll, keepfocus, chain, hash) {
 		const info = this.parse(url);
-
```
Comment (bluwy) [inline packages/kit/src/runtime/client/router.js:254]: Would be great to leave this file untouched.

**Review by bluwy — APPROVED** [review]
I have one small request below, but otherwise this looks good to me! Tests seem to pass too. I'll wait for Ben's comment on my question above before merging.

File: packages/kit/src/runtime/client/renderer.js [hunk 6]
```diff
@@ -275,6 +275,8 @@ export class Renderer {
 			this._init(navigation_result);
 		}
 
+		getSelection()?.removeAllRanges();
+
```
Comment (benmccann) [inline packages/kit/src/runtime/client/renderer.js:279]: not exactly related to your change, but `if (!opts)` shouldn't the `document.body.focus()` line still be called? I don't quite get what that check is doing and wonder if it should be removed? maybe i'm just sleep deprived enough that I'm making a dumb mistake in reading this code...

Comment (bluwy) [reply packages/kit/src/runtime/client/renderer.js:279]: I'm actually quite confused of the part inside `if (!opts)` too. When I refactored that, I tried to keep it as before. That means `document.body.focus()` and scrolling only happens if `opts` exist, I thought it was intentional.

If it wasn't, maybe we should refactor that again, and always do focusing and scrolling regardless of `opts`. We can do that in a separate PR though.

**Comment by Rich-Harris** [comment]
excellent, thank you!

File: packages/kit/test/apps/basics/src/routes/selection/_tests.js [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+					selection.removeAllRanges();
+					selection.addRange(range);
+					return selection.rangeCount;
+				}
+				return 0;
+			}),
+			1
+		);
+		await clicknav('[href="/selection/b"]');
+		assert.equal(
```
Comment (benmccann) [inline packages/kit/test/apps/basics/src/routes/selection/_tests.js:21]: i'm worried this might introduce flakiness, which is why you sometimes needed the timeout. I wonder if you need to wait until the selection is present instead of simply checking that it is

**Comment by rmunn** [comment]
This is probably causing #2853.
