### PR TITLE
fix: prevent stale values after invalidation

### LINKED ISSUE #10123: depends() stops working as expected after form submission
### Describe the bug

Registering a custom dependency with `depends('load:child')` within a page's load function, and calling `invalidate('load:child')` with `setInterval` in the sibling `+page.svelte` in order to mimic a single polling behaviour, causes `+layout.server`'s load function to be called as well **after submitting form** on same page.

### Reproduction

https://github.com/themajashurka/depends-repro

Go to /child. You should see periodic logs on server about child load function being called.
Submit form. Now layout load function is called too.

### Logs

server-side

```
root load runs
layout load runs
child load runs
child load runs
child load runs
child load runs
child load runs
child load runs
layout load runs
child load runs
layout load runs
child load runs
layout load runs
child load runs
layout load runs
child load runs
layout load runs
```

### System Info

```Shell
System:
    OS: macOS 11.7.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 879.37 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.20.2 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.9
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### LINKED ISSUE #11446: Outdated return value from invalidated load function on navigation
### Describe the bug

I've been trying to get data from a nested `+layout.server.ts` to invalidate using a custom identifier.

I have a file structure like this:
```
routes/
|- counter/
	|- +layout.server.ts   	<-- `depends('increment:counter')`
	|- [id]/
		|- +page.server.ts 	<-- loads more data and lets sveltekit merge the returned value
		|- +page.svelte 	<-- has a button that calls `invalidate('increment:counter')` and a link to change the `id` param
```

Since SvelteKit v2, calling `invalidate` in the nested `+page.svelte` will increase the counter, but a navigation to a different subroute of `/counter/` will reset the counter to the value it had on initial load

This doesn't happen with `invalidateAll` but it will increment the first time you navigate after calling it, this is unexpected to me.

Adding a call to `parent` in the `+page.server.ts` and manually merging it into the returned data will stop the counter resetting but it will now increment on every navigation.

Is there a reason why the `+page.server.ts` is using the outdated value of `counter` instead on using the value from the last invalidation?

### Reproduction

SvelteKit v2: https://stackblitz.com/edit/sveltejs-kit-template-default-7psjuw?file=package.json

SvelteKit v1: https://stackblitz.com/edit/sveltejs-kit-template-default-3ju85k?file=package.json 

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.1 
    @sveltejs/kit: ^2.0.0 => 2.0.5 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10
```

### Severity

serious, but I can work around it

### Additional Information

This was introduced in SvelteKit v2, here is a v1 reproduction that doesn't have the issue: https://stackblitz.com/edit/sveltejs-kit-template-default-3ju85k?file=package.json

### PR DESCRIPTION
**Pull request by dummdidumm**
Current was not updated after invalidation, which resulted in the previous values getting used on next navigation
fixes #11446
We also didn't set `force_invalidate` back to `false`
fixes #10123

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -312,16 +312,17 @@ async function _invalidate() {
 
 	if (navigation_result) {
```
Comment (benmccann) [inline packages/kit/src/runtime/client/client.js:313]: you could change the previous line to `if (nav_token !== token  || !navigation_result) return;` to simplify things

File: packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.svelte [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+	/** @type {import('./$types').PageData} */
+	export let data;
+</script>
+
+<p class="layout">{data.layoutDate}</p>
+<p class="page">{data.pageDate}</p>
+<button
+	type="button"
+	class="invalidate"
+	on:click={() => (window.promise = invalidate('invalidate-depends:goto'))}
```
Comment (benmccann) [inline packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.svelte:13]: why isn't this just?
```suggestion
	on:click={async () => await invalidate('invalidate-depends:goto')}
```

if it needs to be two separate statements the test could use a comment explaining

making this `window.promise` makes me a bit nervous you might inadvertently end up with two tests using that name that stomp on each other. I feel like you might almost need to make it be something like `window.invalidate_then_goto_promise`

Comment (dummdidumm) [reply packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.svelte:13]: See the corresponding test - this global is awaited. You're right that it should be a unique name.

Comment (benmccann) [reply packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.svelte:13]: Right, I saw that it's awaited. I guess my question is will Svelte not await async handlers? There's no mention on https://svelte.dev/docs/element-directives of what you should do if you need to call an async function from a click handler. This is something I actually encountered just yesterday in real Svelte code and felt a bit lost as to what would/should happen there. We might need to update those docs a bit. Is this how users should write it in their code as well or is some of the way we're writing it here caused by invoking it through Playwright?

Comment (dummdidumm) [reply packages/kit/test/apps/basics/src/routes/load/invalidation/invalidate-then-goto/+page.svelte:13]: But this isn't what this is about at all, your suggestion would break the test because the test awaits `window.promise`, and your change would make so that this is no longer the case.

File: packages/kit/test/apps/basics/test/client.test.js [hunk 3]
```diff
@@ -594,6 +594,29 @@ test.describe('Invalidation', () => {
...
+		const _page = await page.textContent('p.page');
+		expect(layout).toBeDefined();
+		expect(_page).toBeDefined();
+
+		await page.click('button.invalidate');
+		await page.evaluate(() => window.promise);
+		const next_layout_1 = await page.textContent('p.layout');
+		const next_page_1 = await page.textContent('p.page');
+		expect(next_layout_1).not.toBe(layout);
+		expect(next_page_1).toBe(_page);
```
Comment (benmccann) [inline packages/kit/test/apps/basics/test/client.test.js:610]: I think the Playwright way to write this would be something like below where it uses its auto waiting functionality to wait until the conditions are true. I have to run, so didn't have time to check if these are the APIs with that auto waiting built-in (some of the APIs have it and some don't as I recall)
```suggestion
		await page.click('button.invalidate');
		expect(page.textContent('p.layout')).not.toBe(layout);
		expect(page.textContent('p.page')).toBe(_page);
```

Comment (Conduitry) [reply packages/kit/test/apps/basics/test/client.test.js:610]: https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text would be the assertion to probably use here for auto-waiting.

File: packages/kit/src/runtime/client/client.js [hunk 4]
```diff
@@ -312,16 +312,17 @@ async function _invalidate() {
...
+			return _goto(new URL(navigation_result.location, current.url).href, {}, 1, nav_token);
 		}
-	}
 
-	invalidated.length = 0;
+		if (navigation_result.props.page) {
+			page = navigation_result.props.page;
+		}
+		current = navigation_result.state;
+		invalidated.length = 0;
```
[the remark this answers is not in the document]
Comment (dummdidumm) [reply packages/kit/src/runtime/client/client.js:322]: `load_route` always returns a navigation result (or will cause a hard reload), it's the intent which could be falsy.

File: packages/kit/src/runtime/client/client.js [hunk 5]
```diff
@@ -312,16 +312,17 @@ async function _invalidate() {
...
+		force_invalidation = false;
```
[the remark this answers is not in the document]
Comment (dummdidumm) [reply packages/kit/src/runtime/client/client.js:323]: done

File: packages/kit/test/apps/basics/test/client.test.js (hunk 3 above)
Comment (dummdidumm) [reply packages/kit/test/apps/basics/test/client.test.js:610]: Still doesn't change the fact that we gotta save the text to a variable to use it in the next comparison

Comment (benmccann) [reply packages/kit/test/apps/basics/test/client.test.js:610]: But it does save you from having to do the promise dance, which would be nice to avoid

File: packages/kit/test/apps/basics/test/client.test.js [hunk 6]
```diff
@@ -594,6 +594,29 @@ test.describe('Invalidation', () => {
...
+
+		await page.click('button.goto');
+		await page.evaluate(() => window.promise);
+		const next_layout_2 = await page.textContent('p.layout');
+		const next_page_2 = await page.textContent('p.page');
+		expect(next_layout_2).toBe(next_layout_1);
+		expect(next_layout_2).not.toBe(layout);
+		expect(next_page_2).not.toBe(next_page_1);
```
Comment (benmccann) [inline packages/kit/test/apps/basics/test/client.test.js:618]: you could write it like this:
```suggestion
		await page.click('button.invalidate');
		expect(page.locator('p.layout').textContent()).not.toBe(layout);
		expect(page.locator('p.page').textContent()).toBe(_page);

		const layout2 = await page.textContent('p.layout');
		const page2 = await page.textContent('p.page');
		await page.click('button.goto');
		expect(page.locator('p.page')).not.toBe(page2);
		expect(page.locator('p.layout')).toBe(layout2);
```

File: packages/kit/test/apps/basics/test/client.test.js (hunk 3 above)
Comment (dummdidumm) [reply packages/kit/test/apps/basics/test/client.test.js:610]: We still need to save the string into a variable for comparison later. This would make the test read very weird (first compare text content, then save that same selector to a variable).
Also this mimicks the other tests in that suite, and frankly if this is the only thing holding up this PR then I'd rather discuss this separately and merge this PR because it's an important bug to fix.

File: packages/kit/test/apps/basics/test/client.test.js (hunk 6 above)
Comment (dummdidumm) [reply packages/kit/test/apps/basics/test/client.test.js:618]: I don't know, it reads weird to me (first compare text content, then save that same selector to a variable). It also is missing one `expect` check at the end.
Also the present test mimicks the other tests in that suite, and frankly if this is the only thing holding up this PR then I'd rather discuss this separately and merge this PR because it's an important bug to fix.

File: packages/kit/test/apps/basics/test/client.test.js [hunk 7]
```diff
@@ -594,6 +594,29 @@ test.describe('Invalidation', () => {
...
+		const next_page_1 = await page.textContent('p.page');
+		expect(next_layout_1).not.toBe(layout);
+		expect(next_page_1).toBe(_page);
+
+		await page.click('button.goto');
+		await page.evaluate(() => window.promise);
+		const next_layout_2 = await page.textContent('p.layout');
+		const next_page_2 = await page.textContent('p.page');
+		expect(next_layout_2).toBe(next_layout_1);
+		expect(next_layout_2).not.toBe(layout);
```
Comment (benmccann) [inline packages/kit/test/apps/basics/test/client.test.js:617]: This check doesn't do anything does it? On the previous line we checked that it's `next_layout_1`, so if we make it this far I believe we already know that it's not `layout`
```suggestion
```

File: packages/kit/test/apps/basics/test/client.test.js (hunk 6 above)
Comment (benmccann) [reply packages/kit/test/apps/basics/test/client.test.js:618]: If we do leave it as is then we were going to rename `window.promise` to something more unique, right?

**Review by benmccann — APPROVED** [review]
