### PR TITLE
fix: create new URL when calling `goto(...)`, to handle case where URL is mutated

### LINKED ISSUE #13187: page.url not reactive on the new $app/state module.
### Describe the bug

When you try to hear for changes on `page.url` using `$derived` it won't work. For example If ones has a `+page.svelte` that wants the value of a `searchParams` like this:
 
```typescript
const currentPage = $derived(page.url.searchParams.get("page") || "");
```

And then you update the `searchParams` using `goto`:

```typescript
const { url } = page;

url.searchParams.set('page', newPage);

goto(url, { replaceState: true, noScroll: true, keepFocus: true, invalidateAll: true })
```

The value of `currentPage` won't be updated it. I tried multiple combinations of this, and the only thing that works is listening to another value of `page`. For example something like this:

```typescript
const currentPage = $derived.by(() => {
  page.state;

  return page.url.searchParams.get('page') || '';
});
```

Now if I change the `searchParams` my `currentPage` will be updated to the correct value.

Also this used to work using the `$app/store` module:

```typescript
// This works.
const currentPage = $derived($page.url.searchParams.get('page') || '');
```

### Reproduction

https://replit.com/@GonzaloCaballe1/Reproduction

+page.svelte:

```svelte
<script>
  import { page } from "$app/state";
  import { goto } from "$app/navigation";

  const currentPage = $derived(page.url.searchParams.get("page") || "");

  const currentPageWorking = $derived.by(() => {
    page.state;
    return page.url.searchParams.get("page") || "";
  });
</script>

<div>
  <label for="current_page">Current Page:</label>
  <input
    id="current_page"
    bind:value={
      () => page.url.searchParams.get("page"),
      (newPage) => {
        const { url } = page;

        url.searchParams.set("page", newPage);

        goto(url, {
          replaceState: true,
          noScroll: true,
          keepFocus: true,
          invalidateAll: true,
        });
      }
    }
  />
</div>

<h1>Current Page Not Working: {currentPage}</h1>
<h1>Current Page Working: {currentPageWorking}</h1>
```

### Logs

_No response_

### System Info

```shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 105.55 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
  npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  pnpm: 9.14.2 - ~/Library/pnpm/pnpm
  bun: 1.1.9 - ~/.bun/bin/bun
npmPackages:
  svelte: 5.14.1 => 5.14.1
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #13187. should probably get a test before we merge it and don't have time for it just now, but wanted to push the fix up anyway

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Review by eltigerchino — APPROVED** [review]
Added the test

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -1741,7 +1741,7 @@ export function goto(url, opts = {}) {
 		throw new Error('Cannot call goto(...) on the server');
 	}
 
-	url = resolve_url(url);
+	url = new URL(resolve_url(url));
```
Comment (Leonidaz) [inline packages/kit/src/runtime/client/client.js:1744]: no big deal but thought maybe it's worth saving creating another instance if one was already created.
```suggestion
  const resolved = resolve_url(url);
  // force new URL for page.url reactivity
  url = url === resolved ? new URL(resolved) : resolved;
```

Comment (Rich-Harris) [reply packages/kit/src/runtime/client/client.js:1744]: this isn't a hot code path, brevity is a higher priority
