### PR TITLE
fix: skip navigation if only url hash change

### LINKED ISSUE #2667: CSS psuedo selector ':target' issue
### Describe the bug

CSS 3 pseudo selector :target fails to work when it should. When the target of an anchor fragment link e.g. `<a href="#p1">` is clicked, the url shows the #p1 but 
CSS target electors fail until it is clicked a second time.

Works fine in svelte, so must be something to do with routing in sveltekit? 

### Reproduction

Paste this into any .svelte in sveltekit project:
```svelte
<h3>Target test</h3>
<ol>
 <li><a href="#p1">Jump to the first paragraph!</a></li>
 <li><a href="#p2">Jump to the second paragraph!</a></li>
 <li><a href="#nowhere">This link goes nowhere,
   because the target doesn't exist.</a></li>
</ol>

<h3>My Fun Article</h3>
<p id="p1">You can target <i>this paragraph</i> using a
  URL fragment. Click on the link above to try out!</p>
<p id="p2">This is <i>another paragraph</i>, also accessible
  from the links above. Isn't that delightful?</p>


<style>
p:target {
  background-color: gold;
}
</style>
```
### Logs

_No response_

### System Info

```shell
Package.json
{
  "name": "sveltekit_ssg_tw",
  "version": "0.0.1",
  "scripts": {
    "dev:only": "svelte-kit dev",
    "build:only": "svelte-kit build",
    "preview": "svelte-kit preview",
    "tailwind:watch": "cross-env TAILWIND_MODE=watch cross-env NODE_ENV=development postcss src/styles/tailwind.css -o src/styles/tailwind-output.css -w",
    "tailwind:build": "cross-env TAILWIND_MODE=build cross-env NODE_ENV=production postcss src/styles/tailwind.css -o src/styles/tailwind-output.css",
    "dev": "concurrently \"npm run dev:only\" \"npm run tailwind:watch\"",
    "build": "npm run tailwind:build && npm run build:only"
  },
  "devDependencies": {
    "@sveltejs/adapter-netlify": "^1.0.0-next.32",
    "@sveltejs/adapter-static": "^1.0.0-next.20",
    "@sveltejs/kit": "next",
    "autoprefixer": "^10.3.6",
    "concurrently": "^6.2.2",
    "cross-env": "^7.0.3",
    "postcss-cli": "^9.0.1",
    "svelte": "^3.43.1",
    "svelte-fa": "^2.3.3",
    "tailwindcss": "^2.2.16"
  },
  "type": "module",
  "dependencies": {
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@tailwindcss/forms": "^0.3.4"
  }
}
```

### Severity

annoyance

### Additional Information

_No response_

### LINKED ISSUE #3105: Focus broken when navigating with hash
### Describe the bug

In an effort to make tab navigation better on my site, I was implementing a skip to content button which would skip the navbar and directly go to the content. I have implemented it as it is normally implemented but I am running into a small problem. Normally, focussing on the skip to content button and then pressing enter gets you to the content, and pressing the tab key after that makes you cycle through the content. In my implementation, I am brought to the skip to content button twice before I can cycle through the site's content. 

### Reproduction

Add a skip to content link to a page (basically a link that is the first thing to come into focus and shows up when tabbed on landing on the website and else remains hidden). Set the `href` to an id the link points to (usually something like `main` or `content` that is after that page's navbar/header). Navigate to the site, press tab, press enter, again press tab and the skip to content link will again show up.

### Logs

```shell
None. Check additional information for screen recording, details on code, source code, and a hosted site where it can be reproduced.
```

### System Info

```shell
System:
    OS: Linux 5.15 Pop!_OS 21.10
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.19 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Browsers:
    Brave Browser: nightly
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/kit: next => 1.0.0-next.201 
    svelte: ^3.44.0 => 3.44.2
```

### Severity

serious, but I can work around it

### Additional Information

Hosted Preview - https://portfolio-nlaow838l-anishde12020.vercel.app/
Source code (THIS SPECIFIC COMMIT) - https://github.com/AnishDe12020/portfolio/commit/d2406ffeb65e0f1da29d6d95e8a2c323051dd3b6

<details>
<summary>Details on the code</summary>
I have added a button to the layout of my website, that is in `__layout.svelte`. Here is the code:

```svelte
<script>
  import "../app.css";
  import WipBanner from "../components/wip-banner.svelte";
  import Header from "../components/header.svelte";
  import Footer from "../components/footer.svelte";
  import BackToTop from "../components/back-to-top.svelte";
  import Socials from "../components/socials.svelte";
  import data from "../data.json";
</script>

<div class="max-w-[1920px] mx-auto">
  <a href="#content" class="skip-content-link">Skip To Content</a> <!-- the skip to content button -->
  <BackToTop />
  <WipBanner />
  <Header />
  <slot />
  <Footer />
  <Socials
    socialsData={data.socials}
    classNames="fixed bottom-8 left-8 flex-col space-y-6 hidden md:flex"
    showText
  />
</div>
```

I have added some styles in `app.css` for the same:

```css
.skip-content-link {
  position: absolute;
  transform: translateY(-100%);
  background: #1d3dae;
  padding: 1rem 0.5rem;
  border-radius: 0rem 0rem 1rem 0rem;
}

.skip-content-link:focus {
  transform: translateY(0%);
}
```

At last, I have given the content an `id` of `content` in `index.svelte` so that it can be scrolled down to whenever the skip to content button is engaged:

```svelte
<main id="content">
  <Hero />
  <BlogPosts blogPosts={data.blogPosts} blogBaseUrl={data.blogBaseUrl} />
  <Projects projects={data.projects} />
  <Skills skillsData={data.skills} />
  <Contact emailAddress={data.emailAddress} />
</main>
```

Note: I was following this article on css-tricks: https://css-tricks.com/how-to-create-a-skip-to-content-link/

</details>

For more context, here is a screen recording - 

https://user-images.githubusercontent.com/63192115/147273364-a8b1ec40-e08a-4018-bc87-6b7cfdf8aeb4.mp4

Also, I have tried this on another SvelteKit project and had faced the same issue.

Discussion we are coming from - https://github.com/sveltejs/kit/discussions/3098

**Currently using a workaround as suggested in https://github.com/sveltejs/sites/pull/245**

### PR DESCRIPTION
**Pull request by bluwy**
Fixes #3105
Fixes #2667

If only the URL hash change when navigating via anchor tags, e.g. `<a href="#foo">`, skip router navigation and let the default browser behaviour to kick in.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/test/apps/basics/src/routes/routing/_tests.js [hunk 1]
```diff
@@ -188,15 +188,64 @@ export default function (test, is_dev) {
...
 		'back button returns to previous route when previous route has been navigated to via hash anchor',
 		'/routing/hashes/a',
-		async ({ page, clicknav, back }) => {
-			await clicknav('[href="#hash-target"]');
+		async ({ page, clicknav }) => {
+			await page.click('[href="#hash-target"]');
 			await clicknav('[href="/routing/hashes/b"]');
 
-			await back();
+			await page.goBack();
```
Comment (bluwy) [inline packages/kit/test/apps/basics/src/routes/routing/_tests.js:195]: Changed this to `page.click` and `page.goBack` since the `clicknav` and `back` utils rely on `sveltekit:navigation-end` to resolve, which these hash-only anchor tags would skip, resulting in timeout.

Using playwright's builtin functions to avoid it.

File: packages/kit/test/apps/basics/src/routes/routing/_tests.js [hunk 2]
```diff
@@ -188,15 +188,64 @@ export default function (test, is_dev) {
...
+		'/routing/hashes/target#p2',
+		async ({ page }) => {
+			await page.keyboard.press('Tab');
+			assert.equal(
+				await page.evaluate(() => (document.activeElement || {}).textContent),
+				'next focus element'
+			);
+		},
+		// Does not work in nojs
+		{ nojs: false }
```
Comment (bluwy) [inline packages/kit/test/apps/basics/src/routes/routing/_tests.js:211]: In no-js, the default page focus after `Tab` is the document body. I'm not entirely clear why it works in js, but I'm skipping this for now.

File: packages/kit/src/runtime/client/router.js [hunk 3]
```diff
@@ -157,16 +157,16 @@ export class Router {
 
 			if (!this.owns(url)) return;
 
-			const noscroll = a.hasAttribute('sveltekit:noscroll');
+			// Check if new url only differs by hash
+			if (url.href.split('#')[0] === location.href.split('#')[0]) {
+				// Delay pushState, otherwise the browser default behaviour would not kick in
+				setTimeout(() => history.pushState({}, '', url.href));
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/router.js:163]: If we're returning without preventing the event default, do we still need to push state?

File: packages/kit/src/runtime/client/router.js [hunk 4]
```diff
@@ -157,16 +157,16 @@ export class Router {
 
 			if (!this.owns(url)) return;
 
-			const noscroll = a.hasAttribute('sveltekit:noscroll');
+			// Check if new url only differs by hash
+			if (url.href.split('#')[0] === location.href.split('#')[0]) {
```
Comment (babichjacob) [inline packages/kit/src/runtime/client/router.js:161]: `(some url).href.split('#')[0]` -> `(some url).hash`? (It will include the leading `#`)

File: packages/kit/src/runtime/client/router.js (hunk 3 above)
Comment (bluwy) [reply packages/kit/src/runtime/client/router.js:163]: Yeah. The `pushState` is so that we keep a new history entry of the new url with hash so that we can go back to it. There were tests for this behaviour specifically. I forgot to add a comment regarding this though.

Comment (bluwy) [reply packages/kit/src/runtime/client/router.js:164]: Updated in 79350cb

**Review by Rich-Harris — APPROVED** [review]
