### PR TITLE
fix: improve ordering of `head` elements

### LINKED ISSUE #15224: Link preload should be in front of inlined CSS
### Describe the bug

When CSS is inlined in `<head>`, it will go before the `<link>` preloads.  And this CSS can be huge depending on user settings, so it would make sense to hint the browser of other network requests to do before making it parse it.
Interestingly the favicon is placed after the preloads even when inlined.

### Reproduction

Enable CSS inlining in svelte.config.js:
```js
export default {
  kit: {
    adapter: adapter(),
    inlineStyleThreshold: Infinity,
  },
}
```

### Logs

```Shell

```

### System Info

```Shell
Binaries:
    Node: 20.19.2 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  Browsers:
    Firefox: 140.7.0esr
    Firefox Developer Edition: 140.7.0esr
  npmPackages:
    @sveltejs/adapter-static: ^3.0.10 => 3.0.10 
    @sveltejs/kit: ^2.50.1 => 2.50.1 
    svelte: ^5.48.3 => 5.48.3 
    vite: ^7.3.1 => 7.3.1
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by elliott-with-the-longest-name-on-github**
Closes #15224 

While I was fixing the above, I noticed that it's kind of hard to see where the `head` is being constructed, and also hard to figure out what order that's happening in. This is just a drive-by improvement to add a bit more structure -- smash stuff into `head`, build it at the end, and everything will always be in the optimal order.

The new order is:
1. HTTP equivalent metatags (only applies on prerender pages)
2. Link tags (also only applies in prerendering)
3. Script preloads
4. User content
5. Style tags
6. Stylesheet links (these are all "disabled" and only exist to instruct Vite)

I'm open to suggestions on reordering this if there's a better order, but it seemed better to put the network-request-creating stuff earlier than the others.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [ ] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by kiwixz** [comment]
Hi, and first of all thanks for fixing this so quickly!

I wonder if "user content" should go between preload (3) and styles (4).
I'm not sure what else could be in there, but I would imagine titles, metatags, preloads, favicons; which all would benefit from being a little earlier in the order.

File: packages/kit/src/runtime/server/page/render.js [hunk 1]
```diff
@@ -672,3 +650,78 @@ export async function render_response({
...
+	}
+
+	build() {
+		return [
+			...this.#http_equiv,
+			...this.#link_tags,
+			...this.#script_preloads,
+			...this.#style_tags,
+			...this.#stylesheet_links,
+			this.#rendered
```
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/src/runtime/server/page/render.js]:
```suggestion
			this.#rendered,
			...this.#style_tags,
			...this.#stylesheet_links
```
