### PR TITLE
[fix] reset scroll when navigated from scrolled page

### LINKED ISSUE #2733: Page scroll position not reset to top on navigation (regression)
### Describe the bug

When navigating to a new page, if you are already scrolled partway down the page, the next page load will keep the current scroll position and not scroll back to the top.

I believe this broke with next-193. When I install next-192, this does not happen -- navigating to a new page always scrolls to the top, just like regular browser navigation.

### Reproduction

Init the SvelteKit demo project. Add the following paragraph in `about.svelte` after the last paragraph.

```html
<p>Go <a href="/">home</a></p>
```

Make the browser window small enough so that the page scrolls and scroll to the bottom of the page. Click the Home link. The Home page loads, but does not scroll to the top (i.e. the nav bar is not visible).

scroll-bug.

Tested in Chrome and Firefox on Windows 10.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 7.79 GB / 12.40 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.1.1 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.193 => 1.0.0-next.193
    svelte: ^3.34.0 => 3.44.1
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bluwy**
Fixes #2733 and maybe #2664

Move the scroll to top logic before the new route mounts so that we can properly compare the `pageYOffset === 0`. This works because scroll position is preserved between route changes by default.

I also updated our `isVisble()` tests to `is_intersecting_viewport()`, since `isVisble` checks for visibility anywhere in the document. `is_intersecting_viewport` makes sure they are in the viewport.

Nonetheless, @mquandalle and @mikenikles I'd appreciate if y'all can try to see if this branch fixes your issue as well.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/client/renderer.js [hunk 1]
```diff
@@ -275,8 +275,15 @@ export class Renderer {
...
-		if (!opts?.keepfocus) {
-			document.body.focus();
+		if (opts) {
+			if (!opts.keepfocus) {
+				document.body.focus();
+			}
+
+			// Scroll to top so we can compare the pageYOffset below. We cannot
+			// compare by recording the pageYOffset here as there is a possiblity
+			// it will change, e.g. different scroll heights
```
Comment (benmccann) [inline packages/kit/src/runtime/client/renderer.js:285]: what do you mean by different scroll heights? do you mean different page heights?

could you use the minimum of `pageYOffset` and the page height?

Comment (bluwy) [reply packages/kit/src/runtime/client/renderer.js:285]: Yeah page heights sounds clearer :+1: 

> could you use the minimum of pageYOffset and the page height?

I'm not too sure what you mean here, are you talking about the words to use for documentation?

**Comment by bluwy** [comment]
> Could this result in a behavior of jumping to the top of the page and the down to the final scroll position?

This would technically happen from the code flow, but it happens between an `await 0` so it should be fast enough that it's not noticeable, but otherwise I don't see another way around this unfortunately, unless we can hook into an event loop where the component is mounted but not yet called `onMount()`.

File: packages/kit/src/runtime/client/renderer.js (hunk 1 above)
Comment (bluwy) [reply packages/kit/src/runtime/client/renderer.js]: Fixed in 47ea554

File: packages/kit/src/runtime/client/renderer.js [hunk 2]
```diff
@@ -275,14 +275,21 @@ export class Renderer {
...
 
-		if (!opts?.keepfocus) {
-			document.body.focus();
+		if (opts) {
+			if (!opts.keepfocus) {
+				document.body.focus();
+			}
+
+			// Scroll to top so we can compare the `pageYOffset` below. We cannot
+			// compare by recording the `pageYOffset` here as there is a possiblity
```
Comment (benmccann) [inline packages/kit/src/runtime/client/renderer.js:284]:
```suggestion
			// compare by recording the `pageYOffset` here as there is a possibility
```

File: packages/kit/src/runtime/client/renderer.js [hunk 3]
```diff
@@ -275,14 +275,21 @@ export class Renderer {
...
 		}
 
-		if (!opts?.keepfocus) {
-			document.body.focus();
+		if (opts) {
+			if (!opts.keepfocus) {
+				document.body.focus();
+			}
+
+			// Scroll to top so we can compare the `pageYOffset` below. We cannot
```
Comment (benmccann) [inline packages/kit/src/runtime/client/renderer.js:283]: > We cannot compare by recording the `pageYOffset` here as there is a possiblity it will change, e.g. different page heights

I don't know if this is quite true? What I meant in my last comment about using the min of `pageYOffset` and the page height is that I wonder if you could check something like `if (pageYOffset === Math.min(oldPageYOffset, newPageHeight))` to see if the user has not scrolled

Comment (bluwy) [reply packages/kit/src/runtime/client/renderer.js:283]: Ah great idea. I think that might work too, I'll try that when I get the time.

Comment (bluwy) [reply packages/kit/src/runtime/client/renderer.js]: That seems to work! The code looks a lot cleaner now. Pushed the changes.

**Review by benmccann — APPROVED** [review]
thanks for updating these tests!
