### PR TITLE
fix: use validated args in batch resolver (alternative approach)

### LINKED ISSUE #15112: `query.batch` returned function input type is mismatched
### Describe the bug

From the docs, `query.batch` accepts a validator, which lets say accepts `TypeA` and validates it to `TypeB` (e.g. `string` to `Date`), the remote func will accept an array of `TypeB`, it will fetch all of them in a single db call, and then it must return a function, which accepts two params, first of type `TypeB` and second index of type `number`. The batch function itself should be called with a single `TypeA` variable.

Typescript does confirm this behavior, and the returned function's argument type is supposed to be validated `TypeB`, but this is not the case, and it is `TypeA` regardless of the validation library and the method of validation.

### Reproduction

1. Create a sveltekit project, enable remote functions and async
2. Make a `query.batch`  function that has a `v.pipe(v.string(), v.toDate())` or `z.coerce.date<string>()` or similar two-type validator.
3. Check the expected vs actual type of the first parameter in the return function

REPL Link: https://stackblitz.com/edit/sveltejs-kit-template-default-w1gdqvws?file=src%2Froutes%2Ftest.remote.ts

Uncommenting line 17 results in an internal error, since `x` is actually a string, as opposed to a date.

### Logs

```Shell
4:04:18 PM [vite] (ssr) page reload src/routes/test.remote.ts
[
  2026-01-01T00:00:00.000Z,
  2025-12-01T00:00:00.000Z,
  2025-11-01T00:00:00.000Z
] object
{
  '2026-01-01T00:00:00.000Z': 2026,
  '2025-12-01T00:00:00.000Z': 2025,
  '2025-11-01T00:00:00.000Z': 2025
}
X 2026-01-01 string
X 2025-12-01 string
X 2025-11-01 string
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^7.0.0 => 7.0.0 
    @sveltejs/kit: ^2.49.2 => 2.49.2 
    @sveltejs/vite-plugin-svelte: ^6.2.1 => 6.2.1 
    svelte: ^5.46.1 => 5.46.1 
    vite: ^7.2.2 => 7.3.0
```

### Severity

serious, but I can work around it

### Additional Information

The system info is from the repl, please tell me if I need to provide mine. I am already using the latest versions of svelte* packages.

### PR DESCRIPTION
**Pull request by Rich-Harris**
Closes #15114
Fixes #15112

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/app/server/remote/query.js [hunk 1]
```diff
@@ -190,18 +209,20 @@ function batch(validate_or_fn, maybe_fn) {
 					batching = { args: [], resolvers: [] };
 
 					try {
+						/** @type {any[]} */
+						let validated = [];
+
 						const get_result = await run_remote_function(
```
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/src/runtime/app/server/remote/query.js]: Why don't we use `__.run` here instead of another (identical) `run_remote_function` call?
