### PR TITLE
fix: suppress console spam for chrome devtools requests

### LINKED ISSUE #13743: SvelteKitError: Not found: /.well-known/appspecific/com.chrome.devtools.json
### Describe the bug

I'm suddently getting this in my terminal during dev mode. No idea what's caused it or whether it's actually impacting anything. I am reading a value from localStorage in my root +layout.json file, but that's the only interaction with localstorage in the app, other than setting that value on user sign in. 

Best of luck...

SvelteKitError: Not found: /.well-known/appspecific/com.chrome.devtools.json
    at resolve (C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\server\respond.js:582:13)
    at C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\server\respond.js:370:7
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at with_event (C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\app\server\event.js:49:20)
    at resolve (C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\server\respond.js:369:6)
    at init_promise.#options.hooks.handle (C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\server\index.js:76:56)
    at C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\server\respond.js:364:18
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at with_event (C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\app\server\event.js:49:20)
    at respond (C:\devprojects\learning\pwa-ktt\node_modules\@sveltejs\kit\src\runtime\server\respond.js:363:26) {
  status: 404,
  text: 'Not Found'
}

### Reproduction

I wouldn't now how to provide a reproduction for this other than providing my actual repo, because I don't know what originally caused this issue. 

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1345U
    Memory: 18.01 GB / 31.66 GB
  Binaries:
    Node: 22.13.1 - C:\nvm4w\nodejs\node.EXE
    npm: 10.9.2 - C:\nvm4w\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.89)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/adapter-auto: ^4.0.0 => 4.0.0 
    @sveltejs/kit: ^2.16.0 => 2.20.3 
    @sveltejs/vite-plugin-svelte: ^5.0.0 => 5.0.3 
    svelte: ^5.0.0 => 5.25.6 
    vite: ^6.0.0 => 6.2.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
Closes #13743. As an alternative, we might consider responding with some data (which is the intended behaviour), but I'm not familiar with it and we would need to think through any security implications or whatever

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/server/respond.js [hunk 1]
```diff
@@ -573,6 +573,13 @@ export async function respond(request, options, manifest, state) {
 			// if this request came direct from the user, rather than
 			// via our own `fetch`, render a 404 page
 			if (state.depth === 0) {
+				// In local development, Chrome requests this file for its 'automatic workspace folders' feature,
+				// causing console spam. TODO should we instead respond with some actual data?
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/respond.js:577]: could always delegate to https://github.com/ChromeDevTools/vite-plugin-devtools-json

File: packages/kit/src/runtime/server/respond.js [hunk 2]
```diff
@@ -573,6 +573,13 @@ export async function respond(request, options, manifest, state) {
...
+				// https://chromium.googlesource.com/devtools/devtools-frontend/+/main/docs/ecosystem/automatic_workspace_folders.md
```
Comment (benmccann) [inline packages/kit/src/runtime/server/respond.js:578]:
```suggestion
				// causing console spam. If users want to serve this file they can install
				// https://github.com/ChromeDevTools/vite-plugin-devtools-json
```

**Review by benmccann — COMMENTED** [review]
I don't think we need to add a TODO. I'm not sure I really need Chrome acting as an editor. lgtm other than that though

File: packages/kit/src/runtime/server/respond.js (hunk 1 above)
Comment (benmccann) [reply packages/kit/src/runtime/server/respond.js:577]: I sent https://github.com/vitejs/awesome-vite/pull/1030 to make it easier to find again if we need to track it down

**Comment by Rich-Harris** [comment]
I just tried adding the plugin and it _is_ pretty useful. The plugin is extremely straightforward. I'm tempted to integrate it. Is there any real reason not to?

**Comment by benmccann** [comment]
Maybe I should give it a try. What did you find useful about it?

**Comment by benmccann** [comment]
Ah, I hadn't checked Discord yet. Will take a look there

**Comment by MathiasWP** [comment]
Not sure where to post this, but i just got an unexpected error in my page load method, and the reason was that `.well-known`, `appspecific` and `com.chrome.devtools.json` came in as params in my load method.

I have this load function:

```ts
export const load: PageLoad = async function ({ parent, params }) {
	const { githubClient } = await parent();
	const { owner, repo, provider } = params;

	async function getData() {
		const [pullRequests, user] = await Promise.all([
			githubClient.getPullRequests(owner, repo),
			githubClient.getAuthenticatedUser()
		]);

		return {
			pullRequests,
			user
		};
	}

	return {
		streamed: {
			data: getData()
		},
		owner,
		repo,
		provider
	};
};
```

And for some reason provider in my params was `.well-known`, owner was `appspecific` and repo was `com.chrome.devtools.json`.

_Update_: It seems that adding https://github.com/ChromeDevTools/vite-plugin-devtools-json fixed it

**Comment by Rich-Harris** [comment]
please open a new issue

**Comment by MathiasWP** [comment]
> please open a new issue

https://github.com/sveltejs/kit/issues/13863
