### PR TITLE
fix: better error when `.remote.ts` files are used without the `experimental.remoteFunctions` flag

### LINKED ISSUE #14111: Better error when importing from `$app/server` in `.remote` file
### Describe the problem

This is a bit cryptic:

> Cannot use `form` from `$app/server` without the experimental flag set to true. Please set kit.experimental.remoteFunctions to `true` in your config.

Also, I noticed that you can freely import `$app/server` into universal code (stuff just fails cryptically when you actually call it). It should be treated as a [server-only module](https://svelte.dev/docs/kit/server-only-modules).

### Describe the proposed solution

Ideally I think any import chain from a client module to a server module (including `$app/server`) should result in an error, but if the import chain goes through a `.remote.ts` file the error should be this instead of the normal one:

> To enable remote functions (src/routes/blah.remote.ts), add the following to your `svelte.config.js`
>
> ```
> kit: {
>   experimental: {
>     remoteFunctions: true
>   }
> }
> ```

Not 100% sure if that's currently possible (i.e. if the import chain is available in dev) but I'm sure we can make it work

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #14111

## before

image

## after

image

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/exports/vite/utils.js [hunk 1]
```diff
@@ -206,9 +206,9 @@ export function error_for_missing_config(feature_name, path, value) {
 		return acc.replace(hole, `${indent}${part}: ${rhs}`);
 	}, hole);
 
-	throw new Error(
+	throw stackless(
 		dedent`\
-			To enable \`${feature_name}\`, add the following to your \`svelte.config.js\`:
+			To enable ${feature_name}, add the following to your \`svelte.config.js\`:
 
 			\`\`\`js
```
Comment (teemingc) [inline packages/kit/src/exports/vite/utils.js]: Wondering if we should remove the code block language here since it doesn't do anything.
  
    
      
        Suggested change
      
    
    
      
          
            
            			\`\`\`js
          
          
            
            			\`\`\`

Comment (Rich-Harris) [reply packages/kit/src/exports/vite/utils.js]: maybe we should remove the fence altogether, i'm not sure it adds much. any objections @elliott-with-the-longest-name-on-github?
