### PR TITLE
fix: deep partial `.value()` and `.set(...)` types for forms

### LINKED ISSUE #14835: Remote forms: incorrect typing for `form.fields.value()` and `form.fields.<fieldname>.value()`
### Describe the bug

The return values of `form.fields.value()` and `form.fields.<fieldname>.value()` are typed according to the schema used when defining the remote function.

However, this does not reflect runtime reality. The return value of `form.fields.value()` is an empty object until the user either interacts with the associated form input or values are set programmatically using `form.fields.set()`. Likewise, `form.fields.<filedname>.value()` returns `undefined` initially.

### Reproduction

Full working reproduction: https://github.com/siim-m/sk-remote-form-type-issue

```typescript
// src/lib/forms.remote.ts
import { form } from '$app/server';
import * as z from 'zod';

export const myForm = form(
  z.object({
    someString: z.string(),
  }),
  async (input) => {
    console.log('input', input);
  }
);
```

```svelte
<script lang="ts">
  // src/routes/+page.svelte
  import { myForm } from '$lib/forms.remote';

  // Until the user enters anything in the input, TypeScript types don't reflect runtime reality:
  // - `values` is typed as `{ someString: string }` but is an empty object
  // - `someString` is typed as `string` but is `undefined` at runtime

  const values = $derived(myForm.fields.value());

  const someString = $derived(myForm.fields.someString.value());
</script>

<form {...myForm}>
  <input {...myForm.fields.someString.as('text')} />
</form>

<p>values:</p>
<pre>{JSON.stringify(values, null, 2)}</pre>
<hr />
<p>typeof someString:</p>
<pre>{typeof someString}</pre>

```

Image

### Logs

```Shell
(nothing printed to console)
```

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04.3 LTS 24.04.3 LTS (Noble Numbat)
    CPU: (8) x64 QEMU Virtual CPU version 2.5+
    Memory: 42.96 GB / 62.66 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.19.0 - /home/siim/.config/nvm/versions/node/v22.19.0/bin/node
    npm: 11.6.0 - /home/siim/.config/nvm/versions/node/v22.19.0/bin/npm
    bun: 1.3.0 - /home/siim/.bun/bin/bun
  npmPackages:
    @sveltejs/adapter-auto: ^6.1.0 => 6.1.1
    @sveltejs/kit: 2.48.2 => 2.48.2
    @sveltejs/vite-plugin-svelte: ^6.2.0 => 6.2.1
    svelte: 5.40.2 => 5.40.2
    vite: ^7.1.7 => 7.1.12
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sillvva**
fixes #14835 

The form's default values are an empty object `{}` when defaults are not provided by `.set()`. Therefore, the `.value()` getter should return a deep partial of the schema type as all values are initially undefined.

Plus, deep partial `.set()` allows setting _some_, but not _all_ values initially.

[`DeepPartial` Demo](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true#code/C4TwDgpgBAIhFgAoEMBOwCWyA2AeAKgHxQC8AsAFACQ+UEAHsBAHYAmAzlAEoQDGA9qla5EqfpHQgA0hBAAaKAFdmAa2b8A7s2IAfJavVaA2gF1KVKgH4oAb3MWqRqVAzMoK2fwBmUfCcsAXL5OJnSMLBzcfILCouIQkjLy+mqa2lB6yqnGodZwCCjoWHj4IcRBpVImANz2VAC+9hUZ+qwQXq4QrLUUlALM7MBQTINB+UhomDi4dhRQ81D8AEYAVkE2wxCjsMhMUPVylAtQaKjrm9uDqK4A5vumh3MLqHxBPAJCuFe3Ct-MN4RKPViCRbJQgeCKCNgAA6ZYrSww6GUAD0KIWAD1LJRoTDToijAAGfxIrbAVHo+ZYnFkmEvXiI5EUNGY7G9Cj9QYXYAAJjG8AmRWmfwBpCgACJxRTjligA)

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by dummdidumm** [comment]
Thank you! For `value()` this makes sense, for `set(...)` it's debateable because it may be better to require you to provide everything that's, well, required.

**Comment by sillvva** [comment]
You're not really validating on `.set()`, though. Sometimes forms only have one initial value set. And having to provide the entire form, including a bunch of empty strings/undefined is more cumbersome.

If the user tries to submit the form with the initial values, it would make sense the validation would fail.

File: packages/kit/types/index.d.ts [hunk 1]
```diff
@@ -2402,7 +2402,16 @@ declare module '@sveltejs/kit' {
...
+	type DeepPartial<T> = T extends Record<PropertyKey, unknown> | unknown[]
+		? {
+				[K in keyof T]?: T[K] extends Record<PropertyKey, unknown> | unknown[]
+					? DeepPartial<T[K]>
+					: T[K];
+			}
+		: T | undefined;
+  
 	type IsAny<T> = 0 extends 1 & T ? true : false;
+
```
Comment (teemingc) [inline packages/kit/types/index.d.ts]:
```suggestion
```

File: .changeset/nice-chairs-switch.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': patch
+---
+
+fix: deep partial `.value()` and `.set(...)` types for forms
```
Comment (teemingc) [inline .changeset/nice-chairs-switch.md]:
```suggestion
fix: use deep partial types for form remote functions `.value()` and `.set(...)`
```
