### PR TITLE
Check ports in a more cross-platform way.

### LINKED ISSUE #2020: svelte-kit should choose new port on EADDRINUSE like sirv
### Describe the problem

I was surprised when I tried to set up the skeleton project and it failed because port 3000 ist already bound.

When I went to check the webserver it was svelte-kit, not sirv, so I have to look up how to change the port.

This shouldn't be that complicated, so I think this should be changed.

```
❯ npm run dev

> ~TODO~@0.0.1 dev /home/coafin/Weidmueller/jws-toolkit
> svelte-kit dev


  SvelteKit v1.0.0-next.137

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network



events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ~TODO~@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ~TODO~@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coafin/.npm/_logs/2021-07-27T06_59_36_177Z-debug.log
```

### Describe the proposed solution

I would like to see the post chosen randomly if the default port is already bound.

### Alternatives considered

Change the port after looking up how :

- run `svelte-kit --help
- fail because PATH
- run `npx svelte-kit --help`
- read
- run `npx svelte-kit dev --help`
- read
- change `svelte-kit dev` to `svelte-kit dev --port <something>` in package.json

### Importance

nice to have

### Additional Information

Low priority and I hope to provide a pull request for a project that I like if I find the time

### PR DESCRIPTION
**Pull request by Karlinator**
related to #2020

We were using `ports.blame()` to check for port usage for the pretty error messages, but this silently fails on any system which does not have `lsof`. This PR instead uses `ports.check()`, which tries to listen to a port, as a more robust way to check if the port is in use. It still uses `ports.blame()` to find the process id using the port if possible.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/cli.js [hunk 1]
```diff
@@ -200,16 +200,21 @@ prog.parse(process.argv, { unknown: (arg) => `Unknown option: ${arg}` });
...
+		const n = await ports.blame(port); // Only works on systems with `lsof`.
+		if (n) {
+			// prettier-ignore
+			console.log(
+				`Terminate process ${colors.bold(n)} or specify a different port with ${colors.bold('--port')}\n`
+			);
+		} else {
+			// prettier-ignore
+			console.log(
+				`Terminate the process using it or specify a different port with ${colors.bold('--port')}\n`
```
Comment (benmccann) [inline packages/kit/src/cli.js:215]: I'm not sure what "it" is here. Terminate the process using itself?
```suggestion
				`Terminate the process or specify a different port with ${colors.bold('--port')}\n`
```

File: packages/kit/src/cli.js [hunk 2]
```diff
@@ -200,16 +200,21 @@ prog.parse(process.argv, { unknown: (arg) => `Unknown option: ${arg}` });
 
 /** @param {number} port */
 async function check_port(port) {
-	const n = await ports.blame(port);
-
-	if (n) {
+	if (!(await ports.check(port))) {
```
Comment (benmccann) [inline packages/kit/src/cli.js:203]: you could reverse this check so that there's less code indentation and you don't have everything wrapped in a big `if`:
```
if (await ports.check(port)) {
  return;
}
```

File: packages/kit/src/cli.js (hunk 1 above)
Comment (Karlinator) [reply packages/kit/src/cli.js:215]: "It" is the port, as in "terminate the process currently using that port". I think it makes mare sense in the context of the preceding log message.
```
Port 3000 is occupied
Terminate the process using it or specify a different port with --port
```

But I can see it's kind of clunky. "Terminate the process occupying the port"?

**Review by benmccann — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you!
