### PR TITLE
reset scroll before resetting focus

### LINKED ISSUE #9189: Jagged scroll behaviour on navigation
### Describe the bug

SvelteKit's client-side navigation seems to introduce jagged scroll behaviour, where the scroll position of the previous page is kept for a very short period of time, before it correctly scrolls to the top. This is demonstrated in the video below of [kit.svelte.dev](https://kit.svelte.dev/docs), which was recorded in Firefox, although the same behaviour occurs (for me) on Chrome. The same is occurring in my own SvelteKit apps, and also in the simple reproduction linked below. Do note that is does not always occur, although I have not been able to find a pattern.

It may be related to #2733, although it is a separate problem: the page scroll position *is* always reset to top, but not quickly enough. My apologies if this has been addressed before, or if it is simply a limitation of CSR, as it's my first issue opened here. 

**Example:**

https://user-images.githubusercontent.com/33397397/221026050-d409cfd5-65ad-4a29-a19a-742055415bf1.mp4

### Reproduction

Nothing complicated here, just two scrollable pages.
https://github.com/Coretteket/jagged-scroll-repro

### Logs

_No response_

### System Info

```Shell
System:
    OS: Windows 11 10.0.22623
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 1000.01 MB / 7.39 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1325.0), Chromium (110.0.1587.46), ChromiumDev (111.0.1660.13)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-vercel: ^2.1.0 => 2.1.0
    @sveltejs/kit: ^1.8.3 => 1.8.3
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.1.4 => 4.1.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #9189. This fix is pleasingly simple. No tests because I don't think it would be possible to write one for this

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -404,6 +394,17 @@ export function create_client(app, target) {
...
+
+			const changed_focus =
+				// reset focus only if any manual focus management didn't override it
+				document.activeElement !== activeElement &&
+				// also refocus when activeElement is body already because the
+				// focus event might not have been fired on it yet
+				document.activeElement !== document.body;
+
+			if (!keepfocus && !changed_focus) {
+				await reset_focus();
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/client.js:406]: this probably was introduced through this `await` which wasn't there before, but was needed to introduce to fix a focus bug

**Review by dummdidumm — APPROVED** [review]
