### PR TITLE
[fix] discover new routes in dev server

### LINKED ISSUE #2046: Dev server don't autodiscover new routes
### Describe the bug

If the dev server is running, SvelteKit don't see newly added routes, and result in 404 when navigating to them.

### Reproduction

- Create a new project (`npm init svelte@next my-app` + select the `Skeleton project`, should also be true for demo app)
- Install the project (`npm install`)
- Start the dev server (`npm run dev`)
- Add a new page in `src/routes` (ex: `src/routes/test.svelte`)
- Try to navigate to the route (with the previous example: `http://localhost:3000/test`)

### Logs

```shell
// Server console side
09:50:09 [vite] page reload .svelte-kit/dev/generated/manifest.js

// Browser side
404
Not found: /test
Error: Not found: /test
    at render_page (file:///private/tmp/sk/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1318:11)
    at async resolve (file:///private/tmp/sk/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1663:12)
    at async respond (file:///private/tmp/sk/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1614:10)
    at async Immediate.<anonymous> (file:///private/tmp/sk/my-app/node_modules/@sveltejs/kit/dist/chunks/index.js:3458:22)
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 78.90 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - /opt/local/bin/node
    Yarn: 1.22.10 - /opt/local/bin/yarn
    npm: 6.14.8 - /opt/local/bin/npm
  Browsers:
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.139
    svelte: ^3.34.0 => 3.41.0
```

### Severity

serious, but I can work around it

### Additional Information

The file `.svelte-kit/dev/generated/manifest.js` is correctly generated.

But SvelteKit don't seem to reload it (it is only load at here: `.svelte-kit//dev/runtime/internal/start.js`)

A simple workaround is to stop and restart server every times a new route is created, in DX point of view it's not ideal

----

_Initial Discord message: https://discord.com/channels/457912077277855764/819723698415599626/870925145554952222_

### PR DESCRIPTION
**Pull request by jasonlyu123**
### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

Fixes #2046. The manifest data passed into the server handler it's the initial manifest.  And the manifest won't be mutated by reference but resigned. This PR changes to pass a get function to the handler so it'll get the up-to-date manifest.

### CODE REVIEW

File: packages/kit/test/apps/basics/src/routes/routing/_tests.js [hunk 1]
```diff
@@ -238,4 +241,27 @@ export default function (test) {
...
+		// hash the filename so that it won't conflict with
+		// future test file that it has the same name
+		const route = 'bar' + new Date().valueOf();
+		const content = 'Hello new route';
+		const __dirname = path.dirname(fileURLToPath(import.meta.url));
+		const filePath = path.join(__dirname, `${route}.svelte`);
+
+		try {
+			fs.writeFileSync(filePath, `<h1>${content}</h1>`);
+			await Promise.resolve();
```
Comment (jasonlyu123) [inline packages/kit/test/apps/basics/src/routes/routing/_tests.js:259]: Don't know if there is any way to wait for the manifest update. Maybe I should just wait for a few seconds. It might also let tests pass in js. I currently disable the test in js because it has to wait for the dev server to send updates to the client.

File: .changeset/tall-jeans-hear.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': minor
```
Comment (ignatiusmb) [inline .changeset/tall-jeans-hear.md:2]:
```suggestion
'@sveltejs/kit': patch
```

File: packages/kit/src/core/dev/index.js [hunk 3]
```diff
@@ -177,7 +177,15 @@ class Watcher extends EventEmitter {
 
 		this.vite = await vite.createServer(merged_config);
 
-		handler = await create_handler(this.vite, this.config, this.dir, this.cwd, this.manifest);
+		const getManifest = () => {
```
Comment (ignatiusmb) [inline packages/kit/src/core/dev/index.js:180]: This should be snake_cased

File: packages/kit/src/core/dev/index.js [hunk 4]
```diff
@@ -177,7 +177,15 @@ class Watcher extends EventEmitter {
...
+			if (!this.manifest) {
+				throw new Error("Shouldn't clear manifest after server initialized");
+			}
```
Comment (ignatiusmb) [inline packages/kit/src/core/dev/index.js:183]: Will there be a situation where this will eventually throw?

**Review by ignatiusmb — COMMENTED** [review]
Looks like the tests are finally passing, this would be a really nice improvement for the dev server!

File: packages/kit/src/core/dev/index.js (hunk 4 above)
Comment (jasonlyu123) [reply packages/kit/src/core/dev/index.js:183]: Doesn't see a current path that it will throw. It should only be undefined before the init method call. It's more likely to throw in line 92. It's just because init is async so we can't enforce it to be not nullable unless we have an empty object in the constructor.

File: packages/kit/src/core/dev/index.js [hunk 5]
```diff
@@ -177,7 +177,15 @@ class Watcher extends EventEmitter {
 
 		this.vite = await vite.createServer(merged_config);
 
-		handler = await create_handler(this.vite, this.config, this.dir, this.cwd, this.manifest);
+		const get_manifest = () => {
+			if (!this.manifest) {
+				throw new Error("Shouldn't clear manifest after server initialized");
```
Comment (benmccann) [inline packages/kit/src/core/dev/index.js:182]: We use single quotes for all strings
```suggestion
				throw new Error('Manifest is not available');
```

**Review by benmccann — APPROVED** [review]
awesome!
