### PR TITLE
fix: wait an extra microtask in dev before calling `$$_init_$$`

### LINKED ISSUE #14515: False positive remote `export is invalid` error
### Describe the bug

Hey @sveltejs Team 👋,

I got this annoying error with the dev server since a few releases, and I'm surprised no one has reported this before (I thought someone would report this since then).

Even if the exports of my `ledger.remote.ts` are only remotes. I'm sure this is a bug, because if I change just 1 character inside this file (even just by adding a space in the code), everything works perfectly again until the next `vite dev` restart.

### Reproduction

I tried for a few hours to reproduce this in a new repository, but I couldn't get to make this bug appear. I will continue to try, but I created this issue in the meantime. Maybe someone in the svelte team directly sees the origin?

Also, it is very easily reproducible in my codebase.

### Logs

```shell
[500] GET /forex/ledger
2025-09-23T09:41:55.609048680Z Error: `getLedgerTable` exported from src/routes/(app)/forex/ledger/ledger.remote.ts is invalid — all exports from this file must be remote functions
2025-09-23T09:41:55.609052014Z     at init_remote_functions (file:/usr/src/app/node_modules/@sveltejs/kit/src/exports/internal/remote-functions.js:20:10)
2025-09-23T09:41:55.609054139Z     at eval (src/routes/(app)/forex/ledger/ledger.remote.ts:259:49)
2025-09-23T09:41:55.609056139Z     at async ESModulesEvaluator.runInlinedModule (file:/usr/src/app/node_modules/vite/dist/node/module-runner.js:910:3)
2025-09-23T09:41:55.609058222Z     at async SSRCompatModuleRunner.directRequest (file:/usr/src/app/node_modules/vite/dist/node/module-runner.js:1119:59)
2025-09-23T09:41:55.609212139Z     at async SSRCompatModuleRunner.directRequest (file:/usr/src/app/node_modules/vite/dist/node/chunks/dep-M_KD0XSK.js:18863:22)
2025-09-23T09:41:55.609237305Z     at async SSRCompatModuleRunner.cachedRequest (file:/usr/src/app/node_modules/vite/dist/node/module-runner.js:1037:73)
2025-09-23T09:41:55.609240972Z     at async eval (src/routes/(app)/forex/ledger/+page.server.ts:1:1)
```

### System Info

```shell
System:
  OS: macOS 26.0
  CPU: (10) arm64 Apple M4
  Memory: 135.67 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 24.5.0 - /opt/homebrew/bin/node
  Yarn: 1.22.22 - /usr/local/bin/yarn
  npm: 11.5.1 - /opt/homebrew/bin/npm
  bun: 1.2.2 - /usr/local/bin/bun
Browsers:
  Safari: 26.0
npmPackages:
  @sveltejs/adapter-node: ^5.3.2 => 5.3.2 
  @sveltejs/kit: ^2.39.1 => 2.43.1 
  @sveltejs/vite-plugin-svelte: ^6.2.0 => 6.2.0 
  svelte: ^5.38.10 => 5.39.4 
  vite: ^7.1.5 => 7.1.7
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by paoloricciuti**
Closes #14515 

TBF this seems like a bug in vite rather than something we should work around here, but I wasn't able to create a minimal repro so in the meantime I'll open this PR and we can discuss.

Basically what happens is that if a client module and a server module import the same remote function during preloading, the module will basically be requested at the same time. This confuses vite and the self_import contains all the exports as undefined, triggering the error within `init_remote_functions`. If the module is imported by itself, this error doesn't occur.

I can spend a bit more time trying to figure out if that's an actual vite issue or if someone has better ideas we can implement those, but this feels like a simple easy fix that it's not too heavy considering it's only in dev.

I really have no idea how to test this tho 😬
---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by l0uisgrange** [comment]
Hello, thanks @paoloricciuti for proposing this fix 👌. Truly sorry to bother, but do you have an update on the situation?

**Comment by teemingc** [comment]
I can't seem to reliably reproduce the issue, so I can't add a test or verify if this fixes it either. Maybe it's worth merging anyway? I think the Vite environment API might have fixed this race condition so we could also add a note that this _could_ be removed in Kit 3.0?

File: packages/kit/src/exports/vite/index.js [hunk 1]
```diff
@@ -698,13 +698,21 @@ async function kit({ svelte_config }) {
 			remotes.push(remote);
 
 			if (opts?.ssr) {
+				// we need to add an `await Promise.resolve()` because if the user imports this function
+				// on the client AND in a load function when loading the client module we will trigger
+				// an ssrLoadModule during dev. During a link preload the the module can be mistakenly
```
Comment (teemingc) [inline packages/kit/src/exports/vite/index.js]:
```suggestion
				// an ssrLoadModule during dev. During a link preload, the module can be mistakenly
```
