### PR TITLE
fix: include `hooks.server` and `hooks.universal` as entrypoints to give them stable manifest identifiers

### LINKED ISSUE #15157: Dynamic Imports Break Server Asset Discovery in hooks.server.ts
### Describe the bug

Inside the hooks.server.ts file we import a file using the ?url syntax.
Everythings worked fine and the file was included in the build, copied to the asset folder with its hashed name, and was added to the server_assets list in the manifest.

```ts
import productsFileUrl from '$lib/assets/Products.xlsx?url';
```

We also use better-auth inside hooks.server.ts.
After the recent update (exact version better-auth 1.4.3 to 1.4.4 and above) better-auth uses dynamic imports to load different adapters and dialects. This results in a different result inside the generated manifest.json file inside the `.sveltekit/output/server/.vite/manifest.json`

Before the update:

```js
{
  'src/hooks.server.ts': {
    file: 'chunks/hooks.server.js',
    name: 'hooks.server',
    src: 'src/hooks.server.ts',
    isDynamicEntry: true,
    imports: [
      '_environment.js',
      '_shared-server.js',
      '_range.util.js',
      '_assert.util.js',
      '_zod.utils.js',
      '_loc.utils.js',
      '_RedisService.js',
      '_private.js',
      '_client.js',
      '_index2.js'
    ],
    assets: [ '_app/immutable/assets/Products.BmxPNQzs.xlsx' ]
  },
}
```

After the update:

```js
{
  '_hooks.server.js': {
    file: 'chunks/hooks.server.js',
    name: 'hooks.server',
    isDynamicEntry: true,
    imports: [
      '_environment.js',
      '_shared-server.js',
      '_range.util.js',
      '_assert.util.js',
      '_zod.utils.js',
      '_loc.utils.js',
      '_RedisService.js',
      '_index3.js',
      '_private.js',
      '_client.js',
      '_index2.js'
    ],
    dynamicImports: [
      '../../node_modules/.pnpm/better-auth@1.4.4_@sveltejs_2c05c91d5a58d8cc4c49e85a8498fc30/node_modules/better-auth/dist/bun-sqlite-dialect-4d24xHgm.mjs',
      '../../node_modules/.pnpm/better-auth@1.4.4_@sveltejs_2c05c91d5a58d8cc4c49e85a8498fc30/node_modules/better-auth/dist/node-sqlite-dialect-7hOpXgTN.mjs',
      '../../node_modules/.pnpm/better-auth@1.4.4_@sveltejs_2c05c91d5a58d8cc4c49e85a8498fc30/node_modules/better-auth/dist/adapters/memory-adapter/index.mjs',
      '../../node_modules/.pnpm/better-auth@1.4.4_@sveltejs_2c05c91d5a58d8cc4c49e85a8498fc30/node_modules/better-auth/dist/adapters/kysely-adapter/index.mjs',
      '../../node_modules/.pnpm/better-auth@1.4.4_@sveltejs_2c05c91d5a58d8cc4c49e85a8498fc30/node_modules/better-auth/dist/adapters/kysely-adapter/index.mjs'
    ],
    assets: [ '_app/immutable/assets/Products.BmxPNQzs.xlsx' ]
  },
}
```

Observations:
- Only the better-auth package was updated. Node, Vite, SvelteKit versions remain the same.  
- Better-auth now uses dynamic imports
- The asset is still correctly included in the build and copied to the asset folder with its hashed name.
- The name of the hooks.server entry in the manifest changed from `src/hooks.server.ts` to `_hooks.server.js`

> **Note:** I don't believe better-auth is the root cause here. The issue lies in how `find_server_assets.js` discovers assets. It only looks for the original `src/hooks.server.ts` key, but Vite may rename this entry when dynamic imports are present. This is why I'm opening this issue in the SvelteKit repository.

Workaround:

```js
  // src\core\generate_manifest\find_server_assets.js:

	// This is -> src/hooks.server.ts
	if (build_data.manifest_data.hooks.server) {
		add_assets(build_data.manifest_data.hooks.server);
	}
```

I can manually add the `_hooks.server.js` entry to the server_assets inside `find_server_assets.js` as a workaround, but this feels wrong and fragile:

```js
	// I added this line to find the server assets from hooks.server.ts
	add_assets("_hooks.server.js");
```

### Reproduction

Open this stackblitz to reproduce the issue: 

It comes with better-auth preinstalled and the problematic hooks.server.ts file.
This node adapter is used to make sure its a server build.

The `/release/server/manifest.js` does not anything under server_assets.

https://stackblitz.com/~/github.com/Tjomas/sveltejs-kit-template-default-cv6bgzj3  

Change the better-auth version to 1.4.3 in the `package.json` and do another build.
Run `npm install` and `npm run build` again.

Now the `/release/server/manifest.js` contains the correct server_assets entry.

### Logs

```Shell

```

### System Info

```Shell
System:
  OS: Windows 11 10.0.26200
  CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
  Memory: 31.51 GB / 63.63 GB
Binaries:
  Node: 24.12.0 - C:\Users\USERNAME\AppData\Local\mise\installs\node\24.12.0\node.EXE
  npm: 11.6.2 - C:\Users\USERNAME\AppData\Local\mise\installs\node\24.12.0\npm.CMD
  pnpm: 10.27.0 - C:\Users\USERNAME\AppData\Local\mise\installs\pnpm\10.27.0\pnpm.EXE
  bun: 1.2.6 - C:\Users\USERNAME\.bun\bin\bun.EXE
  Deno: 2.1.4 - C:\Users\USERNAME\.deno\bin\deno.EXE
Browsers:
  Chrome: 143.0.7499.170
  Edge: Chromium (143.0.3650.66), ChromiumDev (144.0.3719.7)
  Firefox: 145.0.2 - C:\Program Files\Mozilla Firefox\firefox.exe
  Internet Explorer: 11.0.26100.7309
```

### Severity

serious, but I can work around it

### Additional Information

The issue exists in Windows and Docker Linux environment.

### PR DESCRIPTION
**Pull request by elliott-with-the-longest-name-on-github**
Fixes #15157 

This one was a little convoluted. Basically, when `hooks.server` had dynamic imports, Vite started changing its key in `manifest.json`. Prior to the dynamic imports, its key would match the `hooks.server` configuration. For some reason, after adding dynamic imports (even transitively), the manifest key would be renamed to `_hooks.server.js`, which would make the lookup in `resolve_symlinks` fail. Adding `hooks.server` as an entrypoint gives it a stable ID in the manifest, which means we can look it up and resolve it when discovering assets. I did the same for `hooks.universal` as the problem can crop up there, too.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/core/generate_manifest/find_server_assets.js [hunk 1]
```diff
@@ -49,5 +48,9 @@ export function find_server_assets(build_data, routes) {
 		add_assets(build_data.manifest_data.hooks.server);
 	}
 
+	if (build_data.manifest_data.hooks.universal) {
```
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/src/core/generate_manifest/find_server_assets.js:51]: I noticed this wasn't referenced here... but if it runs on the server, it's possible it could `import foo from 'bar?url'` right? In which case we would want to add the assets from it?

File: packages/kit/src/exports/vite/index.js [hunk 2]
```diff
@@ -848,6 +848,14 @@ async function kit({ svelte_config }) {
 						input[name] = path.resolve(file);
 					});
 
+					// ...and the hooks files
+					if (manifest_data.hooks.server) {
+						input['entries/hooks.server'] = path.resolve(manifest_data.hooks.server);
+					}
+					if (manifest_data.hooks.universal) {
```
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/src/exports/vite/index.js:855]: same q as above. If we're not adding assets from here anyway, we don't need it as an entrypoint

**Review by teemingc — APPROVED** [review]
Looks good! Vite seems to also only store the original filename if it's an entry point. Otherwise, we could have just used the `src` attribute.

I'm wondering if there's any benefit of adding a test for this and at the same time if there's any easy way to get Vite to chunk the server hook to reproduce this.
