### PR TITLE
Bugfix: Fix #15004 by applying MDN recommended fix when proxying Response in page_load

### LINKED ISSUE #15004: TypeError: Cannot read private member #state from an object whose class did not declare it
### Describe the bug

Hi there. After upgrading from Node 22 to Node 24, I am receiving an error which I believe is being caused by SvelteKit code. Here's my stack trace:

```
TypeError: Cannot read private member #state from an object whose class did not declare it
    at Proxy.clone (node:internal/deps/undici/undici:10027:31)
    at UsersApi.fetchApi (file:///app/build/server/chunks/runtime-dxfODUb-.js:186:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async UsersApi.request (file:///app/build/server/chunks/runtime-dxfODUb-.js:106:22)
    at async UsersApi.getCurrentUserDashboardRaw (file:///app/build/server/chunks/UsersApi-D-qxiCS_.js:126:22)
    at async UsersApi.getCurrentUserDashboard (file:///app/build/server/chunks/UsersApi-D-qxiCS_.js:142:22)
    at async load$1 (file:///app/build/server/chunks/12-P4O7ql4U.js:33:23)
    at async Object.apply (file:///app/node_modules/.pnpm/@sentry+sveltekit@10.26.0_@sveltejs+kit@2.49.0_@opentelemetry+api@1.9.0_@sveltejs+vite-_2a2da8f703a2aecb97ce46eb7011b4c0/node_modules/@sentry/sveltekit/build/esm/server-common/load.js:29:16)
    at async fn (file:///app/build/server/chunks/index-BZtNkblE.js:3087:14)
    at async load_data (file:///app/build/server/chunks/index-BZtNkblE.js:3078:18)
```

My code is not fairly irrelevant – the important thing is it is using server-side `fetch` then doing `response.clone()`. It is this clone that is failing as it tries to clone the `#state` within undici's `Response` class, but it seems to be unable to access the private member, possibly due to this issue: https://github.com/nodejs/undici/issues/4290.

If I downgrade to node:22, the error disappears. I think undici only introduced the #state private member in the Response class in the version bundled w/ Node v24 so that bit makes sense. I tried v25 and it has the same issue as v24. I'm surprised that no-one else has raised this as an issue as this doesn't seem to be anything new – I see no reason this issue should be specific to me, it should happen whenever you call `response.clone()` on a response generated using the `fetch` from a page load when using Node v24+.

I made a Proxy of the `globalThis.Proxy` constructor which showed that the only code that was creating a proxy of a response is https://github.com/sveltejs/kit/blob/main/packages/kit/src/runtime/server/page/load_data.js#L318-L432.

Based on the GitHub issue in undici it seems like the issue is that the proxy that SvelteKit creates does not properly bind the method that it is returning in the `get()` to the `response` instance. The [recommended solution according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#no_private_field_forwarding) is the following which seems to fix is for me (based on my manually patching the file in `node_modules` and re-running vite):

`src/runtime/server/page/load_data.jsL430`
```diff
- return Reflect.get(response, key, response);
+ const value = Reflect.get(response, key, response);
+ 
+ if (value instanceof Function) {
+ 	return function (...args) {
+ 		return value.apply(this === receiver ? response : this, args);
+ 	}
+ }
+ 
+ return value;
```

### Reproduction

Reproduction for me is 100% when using Node v24+.

```ts
import type { LayoutServerLoad } from "./$types";

export const load = (async ({ fetch }) => {
  const response = await fetch("http://localhost:8000/health");
  console.log("Response clone:", response.clone());
}) satisfies LayoutServerLoad;
```

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: macOS 15.7.2
    CPU: (12) arm64 Apple M3 Pro
    Memory: 80.42 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.11.1 - /Users/drew.silcock/.local/state/fnm_multishells/90252_1764352408561/bin/node
    npm: 11.6.2 - /Users/drew.silcock/.local/state/fnm_multishells/90252_1764352408561/bin/npm
    pnpm: 10.24.0 - /Users/drew.silcock/Library/pnpm/pnpm
    Deno: 2.5.6 - /opt/homebrew/bin/deno
  Browsers:
    Chrome: 142.0.7444.176
    Firefox: 145.0.2
    Firefox Developer Edition: 146.0
    Safari: 26.1
  npmPackages:
    @sveltejs/adapter-node: ^5.4.0 => 5.4.0
    @sveltejs/kit: ^2.49.0 => 2.49.0
    @sveltejs/vite-plugin-svelte: ^6.2.1 => 6.2.1
    svelte: ^5.43.14 => 5.43.14
    vite: ^7.2.4 => 7.2.4
```

### Severity

serious, but I can work around it

### Additional Information

I'll put up a PR with the patch I mentioned in the issue above.

### PR DESCRIPTION
**Pull request by drewsilcock**
On Node v24+, the undici library used for HTTP has a Response class with a private element. Proxying the response therefore fails when calling clone() as the method returned by the proxy cannot access the private state element.

In the linked issue, I mention the MDN version of this fix using a simple `function (...any) { ... }` but I opted for the slightly more comprehensive one using `Reflect.apply()` and `Object.defineProperties()` as it ensures the returned function is identical to introspection (according to https://github.com/nodejs/undici/issues/4290#issuecomment-3004281206, anyway).

See: #15004.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

I included a page in the test apps that reproduces the error (only on Node v24+, obviously). You can reproduce this error by visiting this test page with the fix from this PR reverted.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/server/page/load_data.js
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/src/runtime/server/page/load_data.js:1]: programming is magic, we just have to say the correct incantations, and you can't convince me otherwise 😆 

thanks for fixing this! really glad I didn't have to track this down myself

File: .changeset/tangy-donkeys-knock.md [hunk 1]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': patch
+---
+
+fix: fix TypeError when doing response.clone() in page load
```
Comment (elliott-with-the-longest-name-on-github) [inline .changeset/tangy-donkeys-knock.md]:
```suggestion
fix: TypeError when doing response.clone() in page load
```

File: packages/kit/src/runtime/server/page/load_data.js
Comment (drewsilcock) [reply packages/kit/src/runtime/server/page/load_data.js:1]: Yeah this was not fun to debug, I'm not going to lie 😄 

Programs are basically spells, written in an arcane language decipherable only by those who study it closely, which we give breath to by running lightning through sand so yeah – if you showed this to someone from 1,000 years ago, you could not convince them that was it not magic
