### PR TITLE
fix: add support for trailing slashes in typed routes

### LINKED ISSUE #14047: resolve() lacks a trailing slash when using trailingSlash = always
### Describe the bug

The following code no longer works when using `resolve()` for `href` and `export const trailingSlash = 'always';`. I was using `base` before but it is now being deprecated.

``` js
<Link href={resolve('/dashboard/settings/')} label="SETTINGS" />
```

`resolve()` always gets rid of the trailing slash

**link.svelte component:**

``` svelte
<script>

	import { page } from '$app/stores';

	let { href, label } = $props();

</script>

<a href={href} class="header-button font-medium" class:selected-link={$page.url.pathname === href} aria-label={label}>

	{label}

</a>
```

`$page.url.pathname === href` is never the same, one has a trailing slash, the other doesn't. 

`href` = `/portal/dashboard/settings` and `$page.url.pathname` = `/portal/dashboard/settings/`

If using `trailingSlash = always`, `resolve()` should add it too IMO.

I tried using `page` from `$app/state` and I get the same result. I'm using `let hrefWithSlash = $derived(${href}/);` as a simple workaround

### Reproduction

Sorry (really), reproducing this issue will likely be somewhat difficult for me. I hope the explanation above will do.

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Linux 6.15 Arch Linux
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 27.42 GB / 31.02 GB
    Container: Yes
    Shell: 5.3.3 - /bin/bash
  Binaries:
    Node: 24.4.1 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 11.5.1 - /usr/bin/npm
    pnpm: 8.14.0 - /usr/bin/pnpm
  Browsers:
    Chromium: 138.0.7204.168
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yuki0418**
Fixes #14047 

Add pathnames with a trailing slash when generating typed routes.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/core/sync/write_types/index.js [hunk 1]
```diff
@@ -82,10 +82,21 @@ export function write_all_types(config, manifest_data) {
 			dynamic_routes.push(route_type);
 
 			const pathname = remove_group_segments(route.id);
-			pathnames.add(`\`${replace_required_params(replace_optional_params(pathname))}\` & {}`);
+			const replaced_pathname = replace_required_params(replace_optional_params(pathname));
+			pathnames.add(`\`${replaced_pathname}\` & {}`);
+
+			if (pathname !== '/') {
```
Comment (yuki0418) [inline packages/kit/src/core/sync/write_types/index.js]: I want to add trailing slash only when `export const trailingSlash = 'always';` is in a file.
But I couldn't find a way to check it.

File: packages/kit/src/core/sync/write_types/index.js [hunk 2]
```diff
@@ -82,10 +82,21 @@ export function write_all_types(config, manifest_data) {
...
+				// Support trailing slash
+				pathnames.add(`\`${replaced_pathname + '/'}\` & {}`);
```
Comment (yuki0418) [inline packages/kit/src/core/sync/write_types/index.js]: Also I just add a trailing slash to `type Pathname` because user would not enter Router Id in `href`.
Sorry if I'm wrong.

**Comment by Rich-Harris** [comment]
I wonder if we should try and statically analyse the `trailingSlash` option where possible (@eltigerchino laid the groundwork in #13684) so that we don't add a pathname with a trailing slash if we know that it doesn't need one (and vice versa one day, though it would be a breaking change to do that now)

**Comment by teemingc** [comment]
> I wonder if we should try and statically analyse the `trailingSlash` option where possible (@eltigerchino laid the groundwork in #13684) so that we don't add a pathname with a trailing slash if we know that it doesn't need one (and vice versa one day, though it would be a breaking change to do that now)

It might make the type generation process longer if we needed to analyse every node to get those page options for all pages. Right now it's not noticeable because we do it lazily in development and only for one route when the user accesses it. It's probably not the same for type generation

**Comment by Rich-Harris** [comment]
> It might make the type generation process longer

Fair enough, I'll file this under nice-to-have rather than letting it continue to block this PR

**Review by Rich-Harris — APPROVED** [review]

**Comment by yuki0418** [comment]
Sorry I couldn't find a better solution, I will continue to find it (I study about a compiler nowadays).
Anyway thank you for merging.

**Comment by charbelnicolas** [comment]
Will this work for plain javascript? I'm still having this issue (https://github.com/sveltejs/kit/issues/14047). I even had to update the derived to check if the pathname has an ending slash for the base href.

```js
import { page } from '$app/stores';

let { href, icon, size, label } = $props();

let hrefWithSlash = $derived(

	href.endsWith('/') ? href : `${href}/`

);

$inspect($page.url.pathname, hrefWithSlash);
```
Console 
```
init /store/dashboard/orders/ /store/
link.svelte:11 init /store/dashboard/orders/ /store/dashboard/
link.svelte:11 init /store/dashboard/orders/ /store/dashboard/orders/
link.svelte:11 init /store/dashboard/orders/ /store/dashboard/tasks/
link.svelte:11 init /store/dashboard/orders/ /store/dashboard/products/
link.svelte:11 init /store/dashboard/orders/ /store/dashboard/users/
link.svelte:11 init /store/dashboard/orders/ /store/dashboard/settings/
```

```js
import { page } from '$app/stores';

let { href, icon, size, label } = $props();

let hrefWithSlash = $derived(

	`${href}/`

);

$inspect($page.url.pathname, hrefWithSlash);

```
Console
```
update /store/ /store//
utils.js:236 update /store/ /store/dashboard/
utils.js:236 update /store/ /store/dashboard/orders/
utils.js:236 update /store/ /store/dashboard/tasks/
utils.js:236 update /store/ /store/dashboard/products/
utils.js:236 update /store/ /store/dashboard/users/
utils.js:236 update /store/ /store/dashboard/settings/
```

Now I get `/store//`

This is my `svelte.config.js`
```js
import adapter from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		paths: {
			base: '/store',
			relative: false
		},
		adapter: adapter({
			precompress: true
		})
	}
};

export default config;
```

Is there antoher way I should be doing this?

**Comment by teemingc** [comment]
> Will this work for plain javascript? I'm still having this issue (#14047). I even had to update the derived to check if the pathname has an ending slash for the base href.
> 
> ```js
> import { page } from '$app/stores';
> 
> let { href, icon, size, label } = $props();
> 
> let hrefWithSlash = $derived(
> 
> 	href.endsWith('/') ? href : `${href}/`
> 
> );
> 
> $inspect($page.url.pathname, hrefWithSlash);
> ```
> 
> Console
> 
> ```
> init /store/dashboard/orders/ /store/
> link.svelte:11 init /store/dashboard/orders/ /store/dashboard/
> link.svelte:11 init /store/dashboard/orders/ /store/dashboard/orders/
> link.svelte:11 init /store/dashboard/orders/ /store/dashboard/tasks/
> link.svelte:11 init /store/dashboard/orders/ /store/dashboard/products/
> link.svelte:11 init /store/dashboard/orders/ /store/dashboard/users/
> link.svelte:11 init /store/dashboard/orders/ /store/dashboard/settings/
> ```
> 
> ```js
> import { page } from '$app/stores';
> 
> let { href, icon, size, label } = $props();
> 
> let hrefWithSlash = $derived(
> 
> 	`${href}/`
> 
> );
> 
> $inspect($page.url.pathname, hrefWithSlash);
> ```
> 
> Console
> 
> ```
> update /store/ /store//
> utils.js:236 update /store/ /store/dashboard/
> utils.js:236 update /store/ /store/dashboard/orders/
> utils.js:236 update /store/ /store/dashboard/tasks/
> utils.js:236 update /store/ /store/dashboard/products/
> utils.js:236 update /store/ /store/dashboard/users/
> utils.js:236 update /store/ /store/dashboard/settings/
> ```
> 
> Now I get `/store//`
> 
> This is my `svelte.config.js`
> 
> ```js
> import adapter from '@sveltejs/adapter-node';
> 
> /** @type {import('@sveltejs/kit').Config} */
> const config = {
> 	kit: {
> 		paths: {
> 			base: '/store',
> 			relative: false
> 		},
> 		adapter: adapter({
> 			precompress: true
> 		})
> 	}
> };
> 
> export default config;
> ```
> 
> Is there antoher way I should be doing this?

You should try to create a new discussion in GitHub or visit the [Svelte Discord](https://discord.com/invite/svelte) to ask for help.
