### PR TITLE
Workaround for the DOM clobbering for use:enhance

### LINKED ISSUE #7593: Form Actions throw error if one if the form field name is also `action`
### Describe the bug

When we have one of the form field name as `action` it is conflicting with the form's action and throw following error 

image

### Reproduction

create a form with one of the field  name as `action`
```html
<form class="space-y-6" method="POST" action="?/save" use:enhance>
      <input type="text" name="action"  id="action"    value={policy.action} />
      <button>Save</button>
</form>
```

### Logs

```Shell
forms.js?v=360cc9a6:50 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at HTMLFormElement.handle_submit (forms.js?v=360cc9a6:50:18)
    at HTMLFormElement.sentryWrapped (helpers.ts:98:1)
```

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 30.77 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.87 => 1.0.0-next.87 
    @sveltejs/adapter-node: 1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/adapter-static: 1.0.0-next.48 => 1.0.0-next.48 
    @sveltejs/kit: 1.0.0-next.538 => 1.0.0-next.538 
    svelte: 3.52.0 => 3.52.0 
    vite: 3.2.3 => 3.2.3
```

### Severity

annoyance

### Additional Information

I have this form before migrating to the new `Form Actions` to create/update my form data. I was using `svelte-forms-lib` and using fetch to post data before and was working. now when I am trying Form Actions, I noticed this bug

```ts
export const actions: Actions = {
	save: async ({ request }) => {
		const formData = await request.formData();
		console.log('save action formData:', formData);
		return {
			success: true
		};
	}
};
```

### PR DESCRIPTION
**Pull request by repsac-by**
Fixes #7593

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dummdidumm** [comment]
How in the world does that fix the error? What kind of weird browser behavior is this?

**Comment by repsac-by** [comment]
Because cloning is not deep, but only the form element itself without children.

**Comment by dummdidumm** [comment]
I see, makes sense!

File: packages/kit/src/runtime/app/forms.js [hunk 1]
```diff
@@ -49,9 +50,10 @@ export function enhance(form, submit = () => {}) {
 
 		const action = new URL(
 			// We can't do submitter.formAction directly because that property is always set
+			// We do form.cloneNode() for avoid DOM clobbering - https://github.com/sveltejs/kit/issues/7593
 			event.submitter?.hasAttribute('formaction')
 				? /** @type {HTMLButtonElement | HTMLInputElement} */ (event.submitter).formAction
-				: form.action
+				: /** @type {HTMLFormElement} */ (form.cloneNode()).action
```
Comment (Conduitry) [inline packages/kit/src/runtime/app/forms.js:56]: Someone could conceivably have an `<input name="cloneNode">` which would still break this, no?

What are the performance implications of this clone? I'm hoping not huge, because it's not a deep clone.

Comment (repsac-by) [reply packages/kit/src/runtime/app/forms.js]: > Someone could conceivably have an <input name="cloneNode"> which would still break this, no?

That's a good question. We'll call it through the prototype as well.

> What are the performance implications of this clone? I'm hoping not huge, because it's not a deep clone.

Hopefully this will not affect performance too much, because as noted above it is not a deep cloning.

Comment (Rich-Harris) [reply packages/kit/src/runtime/app/forms.js]: Not remotely worried about the performance impact — if it was more than a fraction of a millisecond I'd be astonished (tried it just now with some `console.time(...)` calls and yep, it's basically free)

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you!
