### PR TITLE
fix: avoid inlining raw/url CSS imports

### LINKED ISSUE #9924: Sveltekit Static Asset import ...css?url failure
### Describe the bug

Sveltekit  is assuming on a CSS file that is JS and throwing errors on trying to preprocess the file

### Reproduction

I have a basic sveltekit v1.16.3 project with a css file like this

````css
.mdc-image-list__image-aspect-container {
    padding-bottom: calc(100% / 1);
}
````
i have a svelte Component like this with [Explicit URL Imports](https://vitejs.dev/guide/assets.html#explicit-url-imports)

````svelte
<script lang="ts">
    import testCSS from './test.css?url'
    console.log(testCSS)
</script>
<svelte:head>
    <link rel="stylesheet" href="{testCSS}">
</svelte:head>
````

why dose vite preprocess the css at all? 
why is it trying to process the css as js?

i made a [Stackblitz](https://stackblitz.com/edit/github-azacgn?file=src%2Froutes%2F%2Bpage.svelte)

from my understanding the issue is because i made a `import testCSS from './test.css?url'` and sveltkit adds a query pram `import testCSS from './test.css?url=&inline='` to it 

i tried to make a plain vite ts project if i add `&inline=` it happens the same issue so i think that sveltekit should stop to add inline query on assists let vite do the job

### Logs

```Shell
when i run i am getting this error


/src/routes/test.css
Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .css?url=&inline= file format, or if it's an asset, add "**/*.css?url=&inline=" to `assetsInclude` in your configuration.
  Plugin: vite:import-analysis
  File: /home/projects/parilmppm.github/src/routes/test.css?url=&inline=:2:36
  1  |  .mdc-image-list__image-aspect-container {
  2  |      padding-bottom: calc(100% / 1);
     |                                     ^
  3  |  }
```

### System Info

```Shell
I reproduced it in StackBlit Results from StackBlit
success Install finished in 1.002s


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.1 => 2.0.1 
    @sveltejs/kit: ^1.16.3 => 1.16.3 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.5 => 4.3.5
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gtm-nayan**
fixes #9924

I pulled it out of one the vite tests but the `?direct` option doesn't seem well documented. I'll add tests and changesets after a resolution on this.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by tcc-sejohnson** [comment]
Does this fix #9923 as well? Looks like it might be the same cause...

**Comment by gtm-nayan** [comment]
Whoops, I was checking #9923 with a sligtly different CSS and realized this doesn't fully solve the original problem either an import with ?url also inlines the CSS, which causes FOSC instead 😅

File: packages/kit/src/exports/vite/dev/index.js [hunk 1]
```diff
@@ -176,20 +176,18 @@ export async function dev(vite, vite_config, svelte_config) {
 							const styles = {};
 
 							for (const dep of deps) {
-								const url = new URL(dep.url, 'http://localhost/');
+								if (/[?&](?:raw|url|inline)\b/.test(dep.url)) continue;
```
Comment (dominikg) [inline packages/kit/src/exports/vite/dev/index.js:179]: this has a slight chance for false positives, move the check to after url parse and test query?

**Comment by gtm-nayan** [comment]
Kit also inlines CSS dependencies from dynamically imported modules and dynamically imported CSS, #7229 that's one case.

File: packages/kit/test/apps/basics/test/cross-platform/test.js [hunk 2]
```diff
@@ -24,6 +24,12 @@ test.describe('CSS', () => {
 		expect(await get_computed_style('.also-styled', 'color')).toBe('rgb(0, 0, 255)');
 	});
 
+	test('does not apply raw and url', async ({ page, get_computed_style }) => {
+		await page.goto('/css');
+		await page.pause();
```
Comment (gtm-nayan) [inline packages/kit/test/apps/basics/test/cross-platform/test.js:29]:
```suggestion
```

File: packages/kit/src/exports/vite/dev/index.js (hunk 1 above)
Comment (bluwy) [reply packages/kit/src/exports/vite/dev/index.js]: Vite also does a loose check like this, so I don't think we need to refactor this. Though now it's checking by the search params instead which I'm also indifferent.

File: packages/kit/src/exports/vite/dev/index.js [hunk 3]
```diff
@@ -176,20 +176,17 @@ export async function dev(vite, vite_config, svelte_config) {
...
 								) {
-									// setting `?inline` to load CSS modules as css string
-									query.set('inline', '');
-
 									try {
-										const mod = await loud_ssr_load_module(
-											`${url.pathname}${url.search}${url.hash}`
-										);
+										query.set('inline', '');
+										const mod = await vite.ssrLoadModule(`${url.pathname}${url.search}${url.hash}`);
```
[the remark this answers is not in the document]
Comment (gtm-nayan) [reply packages/kit/src/exports/vite/dev/index.js:189]: > Also, is there a reason you changed loud_ssr_load_module to vite.ssrLoadModule?

Because of the comment in the catch block below,
if errors are expected there then I don't think we'd want to log those errors through loud_ssr_load_module either.

**Review by bluwy — APPROVED** [review]
