### PR TITLE
include as many static assets as possible in exclude list

### LINKED ISSUE #7640: adapter-cloudflare: only including `_app` content in `_routes.json`
### Describe the bug

The adapter should include any assets inside the `client` output folder instead `_app` only (`kit.appDir`).

Latest changes in kit allow plugins to emit/generate assets in the client folder: `@vite-pwa/sveltekit`, `sitemap`...

The problem is here: https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare/index.js#L42 (should include the client folder)

### Reproduction

~~no, sorry, just reported from Discord here: https://discord.com/channels/937808017016119440/937973377883336704/1041084393239891988~~

https://github.com/hazre/neosvr-mod-manager/tree/fix/pwa

### Logs

_No response_

### System Info

```Shell
NA
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The app is using the new `@vite-pwa/sveltekit` plugin to add the PWA, cloudflare returns 404 for the service worker and webmanifest assets.

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #7640. ~~need to check that prerendered pages (with/without trailing slashes) will still work with this setup.~~

cc @jrf0110 — this causes all static assets to bypass functions (or rather, as many as can fit in the `_routes.json` limit, which will be plenty for some but insufficient for others). I know you initially said you wanted people to be able to apply custom headers and so on, but a) the consensus seems to be that people want to avoid the cost of invoking functions for every request, and b) we don't currently have a way to add any custom logic when the worker serves a static file _anyway_, and I'm not aware of any requests for that behaviour

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/adapter-cloudflare/index.js [hunk 1]
```diff
@@ -62,29 +62,34 @@ export default function () {
...
-				// protect certain things (e.g. a PDF that requires auth),
-				// then we wouldn't want to prevent those requests from going
-				// to the user functions worker.
-				// We do want to show an example of a _routes.json that
-				// excludes more than just /_app/immutable/*, and favicons
-				// are a reasonable choice
-				.filter((file) => file.startsWith('favicon'))
-				.map((file) => `/${file}`)
-		]
+		exclude: exclude.slice(0, 99)
```
Comment (benmccann) [inline packages/adapter-cloudflare/index.js:92]: `.slice(0, 99)`? Is there a limit of 100 items? We should at least log a warning if we hit that condition

Comment (Rich-Harris) [reply packages/adapter-cloudflare/index.js]: yep, there's a limit (left a comment a few lines earlier to explain it; the limits are documented [here](https://developers.cloudflare.com/pages/platform/functions/routing/#limits)). Added a warning

File: packages/adapter-cloudflare/index.js [hunk 2]
```diff
@@ -62,29 +62,53 @@ export default function () {
...
+	}
+
+	for (const path of builder.prerendered.paths) {
+		if (!builder.prerendered.redirects.has(path)) {
+			exclude.push(path);
+		}
+	}
+
+	if (excess) {
+		const message = `Static file count exceeds _routes.json limits (see https://developers.cloudflare.com/pages/platform/functions/routing/#limits). Accessing some files ${excess} will cause function invocations.`;
```
Comment (benmccann) [inline packages/adapter-cloudflare/index.js:102]: it might read better if "files" were removed or changed to "files for"

**Review by benmccann — APPROVED** [review]

File: packages/adapter-cloudflare/index.js (hunk 2 above)
Comment (Rich-Harris) [reply packages/adapter-cloudflare/index.js]: that was just a typo, `files` shouldn't be there at all

**Review by dummdidumm — APPROVED** [review]
(not merging yet as we may want to wait on the CC'd person's response)

**Comment by jrf0110** [comment]
LGTM! Please do reach out if y'all have any issues.

Follow-up - is it possible to configure sveltekit to have a single directory for all static files? e.g. `/static/*` Then we could consolidate the exclusion rule list to a single glob

**Comment by Rich-Harris** [comment]
Not really, no — it's common to use `static` to contain things like `robots.txt` and `.well-known` files. But even if we did, would that mean that if someone requested `/static/non-existent-file`, they'd see a platform 404 instead of the app 404?

**Comment by jrf0110** [comment]
Depends on what you mean by platform 404. In that case, the 404 behavior would be in control of the developer.

Supposing we had a `_routes.json` with:

```tsx
{
  "exclude": ["/static/*"]
}
```

And someone performed:

```
GET /static/non-existent-file
```

That means the request would bypass the Cloudflare Pages Function - i.e. the SvelteKit server - And passthrough to the Cloudflare Pages Asset Server where the default 404 behavior would kick-in. If the deployment [provides a 404 page](https://developers.cloudflare.com/pages/platform/serving-pages/#not-found-behavior), that will get served up. Otherwise, the index page will be served by default (SPA-mode rendering).

**Comment by ajgeiss0702** [comment]
Found an issue using this branch. It seems to add a lot of `null`s to the _routes.json, which then causes it to reach the 100 limit and send a warning.

Here is the file it generates: https://pastebin.com/raw/4KqcrRwd

---

I'm not sure if its related, but for some reason it doesnt seem to generate a _worker.js file? (causing the build to fail)
Build log: https://pastebin.com/raw/gDhQSaC6

**Comment by Rich-Harris** [comment]
@ajgeiss0702 I can't reproduce that, and I can't figure out how it could be happening. Any chance you can whip up a repro?

**Comment by Rich-Harris** [comment]
(For the second thing, about not generating a `_worker.js` file, that's probably because you need to run `pnpm build` inside `packages/adapter-cloudflare`)

**Comment by ajgeiss0702** [comment]
> @ajgeiss0702 I can't reproduce that, and I can't figure out how it could be happening. Any chance you can whip up a repro?

Of course. Might take me a few days as I currently cannot share the repo that it is actively happening on so I'll need to extract some parts until I can reproduce the issue with a basic create-svelte project.


> (For the second thing, about not generating a `_worker.js` file, that's probably because you need to run `pnpm build` inside `packages/adapter-cloudflare`)

Ah, I knew I was doing something wrong. Running that allowed it to build.

**Comment by ajgeiss0702** [comment]
It turns out I was able to reproduce it faster than I thought it would take.

The issue occurs if the site has more than ~50 static assets (assets in the static folder and prerendered pages)

In this repo, I basically just generated a bunch of prerendered pages until the issue occurred. Adding more assets to the static folder lowers the number of prerendered pages required for the issue to appear.
**WARNING:** I set adapter-cloudflare to be downloaded from **my** site. If this is too scary for you, feel free to change it to your own (its not modified from this branch other than running `npm run build`)
https://github.com/ajgeiss0702/null-routes

**Comment by Rich-Harris** [comment]
Ah, I see what's happening — it's counting contents of `_app` individually towards the total, but those are all grouped together under `_app/*`. Fix inbound

**Comment by ajgeiss0702** [comment]
When attempting to deploy to cloudflare pages, the build succeeds, but on the last step I get this:
```
Error: Failed to publish your Function. Got error: Error 8000057: Rules must start with '/' in `_routes.json`. Refer to https://cfl.re/3FsE4aF.
```

It appears that the assets from the static folder are the ones that do not start with `/`

**Comment by korywka** [comment]
Seems like broken for routes that are NOT excluded (direct URL gives 404).
removing `export const trailingSlash = 'always';` fixed that.

@Rich-Harris FYI.

**Comment by korywka** [comment]
If you need sample repo to reproduce, please ping me and I will open the private repo. But looks like 101+ route with `trailingSlash ` option works only with JS redirect, and not by direct route.

**Comment by benmccann** [comment]
@korywka @ajgeiss0702 can you file an issue? I'm afraid comments on a closed PR are likely to get lost. Thanks for tracking down the cause though as that will be a big help!

**Comment by korywka** [comment]
@benmccann done, thanks!

**Comment by ajgeiss0702** [comment]
@benmccann Rich fixed that problem right away in #8618 

korywka's problem is separate from mine, so I agree that there should be an issue for that

**Comment by eweren** [comment]
Is there a way to set those include/excludes manually? We have slug-urls that are longer than 100 characters (another limit of cloudflare) so that this PR breaks the build. Would be awesome to set (or generate) some include/exclude routes by pattern, so that we won't have that many characters for each route and instead just say `exclude: ["courses/[handle]"]`. @Rich-Harris

**Comment by dummdidumm** [comment]
Could you open a new issue for that?

**Comment by eweren** [comment]
https://github.com/sveltejs/kit/issues/8827 hope bug report was correct 🤷
