### PR TITLE
fix: separate framework code from app code

### LINKED ISSUE #8464: `$env/dynamic/public` isn't available in `hooks.client.js` in prod
### Describe the bug

Values from `env` from `$env/dynamic/public` should be available in `hooks.client.js` after build just like in other client-side code, but `env` is empty `{}`.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-yf9uq9?file=src/hooks.server.js

1. Open browser terminal.
2. Run `npm run build && npm run preview` in stackblitz project terminal;
3. View into browser console.

Expected:
```
hooks.server.js: dynamic.PUBLIC_VARIABLE = value ✅
hooks.server.js: static.PUBLIC_VARIABLE = value ✅
hooks.client.js: dynamic.PUBLIC_VARIABLE = value ❌ // undefined
hooks.client.js: static.PUBLIC_VARIABLE = value ✅
```

### Logs

```Shell
hooks.server.js: dynamic.PUBLIC_VARIABLE = value
hooks.server.js: static.PUBLIC_VARIABLE = value
hooks.client.js: dynamic.PUBLIC_VARIABLE = undefined
hooks.client.js: static.PUBLIC_VARIABLE = value
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (7) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.11 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

Workaround is accessing `env` inside root layout script.

### PR DESCRIPTION
**Pull request by Rich-Harris**
This is an alternative to #8803, and closes #8464 albeit via a somewhat larger change.

Essentially this splits out the app code from the framework code, and passes app information to the framework via the `start(...)` call. This gives us an opportunity to set environment variables before any app code runs, but it also has a nice side-effect — the framework code now resides in its own chunk, with a stable hash. This will make cache hits more frequent, since the `start.js` chunk will only be invalidated when there's a new framework version, _not_ when there's a new app version.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Flummoxed by the test failure. Happens reliably, but not locally.

**Comment by dummdidumm** [comment]
I added some console.logs to see where the failure might be. Seems like `app` is imported and loaded properly, and it hangs somewhere inside `_hydrate` of `client.js`

**Comment by Rich-Harris** [comment]
I'm at such a loss. According to the traces it's consistently hanging while requesting a `__data.json` file, but there's absolutely no reason for that to suddenly start happening after this change

**Comment by Rich-Harris** [comment]
Ok bumping the timeout worked. I think what must have happened is this: because we now load the app lazily, it's slightly slower to start up, and that pushed us over a magic threshold. I don't think this is cause for alarm, because the slowdown only happens in dev (because there's no modulepreload) and slowdowns of this magnitude presumably only really apply when you're trying to run a whole bunch of stuff in parallel on an underpowered VM

**Comment by Conduitry** [comment]
Can we control the timeout separately for different tests, so that it's only bumped up for these `defer` ones? It's presumably still valuable to be able to fail the other tests faster.

**Review by dummdidumm — APPROVED** [review]

**Comment by DoisKoh** [comment]
Are we there yet?

File: packages/kit/src/runtime/server/page/render.js [hunk 1]
```diff
@@ -291,8 +284,8 @@ export async function render_response({
 
 	if (page_config.csr) {
 		const opts = [
+			`app: import(${s(prefixed(client.app.file))})`,
 			`assets: ${s(assets)}`,
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/page/render.js:288]: `assets` and `version` should get the same treatment as `env`. that way we can import `app` eagerly, and everything will be a bit simpler

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/page/render.js:288]: ok this was a less straightforward change than i initially imagined. will take a run at it tomorrow

File: packages/kit/src/runtime/client/client.js [hunk 2]
```diff
@@ -1311,6 +1310,21 @@ export function create_client({ target }) {
 		after_navigate();
 	}
 
+	/**
+	 * @param {unknown} error
+	 * @param {import('types').NavigationEvent} event
+	 * @returns {import('../../../types/private.js').MaybePromise<App.Error>}
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/client.js:1316]:
```suggestion
	 * @returns {import('types').MaybePromise<App.Error>}
```

Comment (gtm-nayan) [reply packages/kit/src/runtime/client/client.js]: Unrelated to this path change but since handle_error doesn't await the user's handleError, if they have an async one that doesn't return anything it might break stuff because `Promise<undefined>` passes the `??`,

I checked the client file and there isn't anywhere that's affected by that currently but is that something to be defensive about or would it be considered user error?
