### PR TITLE
[fix] show more descriptive error if data returned from `load` is a non-POJO

### LINKED ISSUE #7262: More informative error if someone returns a `Response` from `load`
### Describe the problem

Per https://github.com/sveltejs/kit/discussions/7259 — if someone does this...

```js
import { json } from '@sveltejs/kit';

export function load() {
  return json({ answer: 42 });
}
```

...they will get a cryptic error:

> DevalueError: Cannot stringify arbitrary non-POJOs

### Describe the proposed solution

It would be easy to catch this case and provide a more specific error:

> `load` must return a plain object rather than a `Response`

For bonus points, it should identify the `load` function in question.

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by errmayank**
Closes #7262

- Tested it out with return `json`

Screenshot 2022-10-25 at 17 44 12
Screenshot 2022-10-25 at 17 42 52

- with `new Error`

Screenshot 2022-10-25 at 17 43 58
Screenshot 2022-10-25 at 17 43 15

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/server/page/render.js [hunk 1]
```diff
@@ -182,6 +182,19 @@ export async function render_response({
 				`Data returned from \`load\` while rendering ${event.routeId} is not serializable: ${error.message} (data.${match[2]})`
 			);
 		}
+
+		const nonPojoError = /pojo/i.exec(error.message);
+
+		if (nonPojoError) {
+			const constructorName = branch[0]?.server_data?.data?.constructor?.name;
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/render.js:189]: This could be from server_data deeper in the load tree, so I think it should be 
```suggestion
			const constructorName = branch.find(({ server_data }) => server_data?.data?.constructor?.name)?.server_data.data.constructor.name;
```

File: packages/kit/src/runtime/server/page/render.js [hunk 2]
```diff
@@ -182,6 +182,19 @@ export async function render_response({
...
+
+			throw new Error(
+				`Data returned from \`load\` must be a plain object${
+					constructorName ? ` rather than ${constructorName} constructor` : ''
+				}`
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/render.js:194]:
```suggestion
				`Data returned from \`load\` (while rendering ${event.routeId}) must be a plain object${
					constructorName ? ` rather than an instance of ${constructorName}` : ''
				}`
```

**Review by dummdidumm — COMMENTED** [review]
Thanks, looks mostly good, added some small comments

**Comment by errmayank** [comment]
Thanks @dummdidumm, i've updated it.

**Comment by errmayank** [comment]
Thanks @dummdidumm, updated.

**Comment by dummdidumm** [comment]
Could you add a changeset by running `npx changeset` in the root and following the prompts (patch release)? Then we're good to go 👍

**Comment by errmayank** [comment]
Added changeset

**Review by dummdidumm — APPROVED** [review]
Thank you!
