### PR TITLE
fix server-side fetch URL replacement

### LINKED ISSUE #1952: server-side endpoint fetch fails if both `paths.base` and `paths.assets` are specified
### Describe the bug

Innocuous code like this...

```svelte
<script context="module">
  import { base } from '$app/paths';

  export async function load({ fetch }) {
    const data = await fetch(`${base}/data.json`).then(r => r.json());

    return {
      props: { data }
    }
  }
</script>
```

...will fail if _both_ `base` and `assets` are set. The internal `fetch` wrapper gets confused about what the proper URL should be.

### Reproduction

https://github.com/Rich-Harris/endpoint-fetch-repro

### Logs

```shell
> 404 /custom-base/endpoint.txt (fetched from /)
Error: 404 /custom-base/endpoint.txt (fetched from /)
    at error (file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/chunks/index6.js:94:11)
    at file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/chunks/index6.js:197:6
    at Map.forEach (<anonymous>)
    at visit (file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/chunks/index6.js:179:17)
    at async prerender (file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/chunks/index6.js:245:5)
    at async Object.prerender (file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/chunks/index6.js:312:5)
    at async adapt (file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/chunks/index6.js:338:2)
    at async file:///Users/richard/Development/SVELTE/KIT/repros/endpoint-fetch/node_modules/@sveltejs/kit/dist/cli.js:905:5
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.71 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.21.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 90.0
    Safari: 13.1.3
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: next => 1.0.0-next.131 
    svelte: ^3.34.0 => 3.38.3
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Incoming PR

### PR DESCRIPTION
**Pull request by Rich-Harris**
Fixes #1952. Haven't added tests yet

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
In fact I don't know if we _can_ add tests to the current suite; I don't think we have a good way to test the `paths` config. This is an urgent blocking issue for me so I'm tempted to let it slide for now

File: packages/kit/src/runtime/server/page/load_node.js [hunk 1]
```diff
@@ -86,24 +84,91 @@ export async function load_node({
...
-					// when running `start`, or prerendering, `assets` should be
-					// config.kit.paths.assets, but we should still be able to fetch
-					// assets directly from `static`
-					url = url.replace(options.paths.assets, '');
-				}
-
-				if (url.startsWith('//')) {
-					throw new Error(`Cannot request protocol-relative URL (${url}) in server-side fetch`);
-				}
+				const [path, search] = url.split('?');
```
Comment (antony) [inline packages/kit/src/runtime/server/page/load_node.js:87]: could this use `URL` rather than doing this with split?

**Review by antony — APPROVED** [review]

**Review by benmccann — APPROVED** [review]
