### PR TITLE
fix: handle non-semver-style dependency versions

### LINKED ISSUE #13836: @sveltejs/package fails with "Invalid comparator" when using Bun workspace catalogs
## Describe the bug

`@sveltejs/package` fails to build when `package.json` dependencies use Bun's workspace catalog syntax (e.g., `"svelte": "catalog:svelte"`). The tool attempts to parse catalog references as semver ranges, causing a build failure.

## Context

1. Set up a Bun workspace with catalogs in root `package.json`:
```json
{
  "workspaces": {
    "catalogs": {
      "svelte": {
        "svelte": "^5.23.1",
        "@sveltejs/kit": "^2.16.0"
      }
    }
  }
}
```

2. Create a package using `@sveltejs/package` with catalog references:
```json
{
  "name": "my-package",
  "devDependencies": {
    "@sveltejs/package": "^2.3.7",
    "svelte": "catalog:svelte",
    "@sveltejs/kit": "catalog:svelte"
  },
  "scripts": {
    "build": "svelte-package"
  }
}
```

3. Run `bun run build`

## Expected behavior

`@sveltejs/package` should either:
1. Resolve catalog references to their actual versions before processing, or
2. Gracefully handle non-semver dependency specifications

## Actual behavior

```bash
> Invalid comparator: catalog:svelte
at Comparator.parse (/path/to/node_modules/semver/classes/comparator.js:41:13)
at new Comparator (/path/to/node_modules/semver/classes/comparator.js:25:10)
at /path/to/node_modules/semver/classes/range.js:154:47
at Array.map (<anonymous>)
at Range.parseRange (/path/to/node_modules/semver/classes/range.js:154:35)
at /path/to/node_modules/semver/classes/range.js:42:22
at Array.map (<anonymous>)
at new Range (/path/to/node_modules/semver/classes/range.js:42:8)
at Object.intersects (/path/to/node_modules/semver/ranges/intersects.js:5:8)
at emit_dts (file:///path/to/@sveltejs/package/src/typescript.js:31:30)
```

## Additional context

This appears to happen in the TypeScript declaration generation step where `@sveltejs/package` tries to use the `semver` library to parse dependency versions. Bun's catalog syntax (`catalog:catalog-name`) is not a valid semver range.

Current Workaround: Use explicit versions in packages that need `@sveltejs/package`, manually keeping them in sync with catalog definitions.

### Reproduction

https://github.com/handlebauer/sveltejs-package-bun-catalog-repro

### Logs

```Shell
> Invalid comparator: catalog:svelte
at Comparator.parse (/path/to/node_modules/semver/classes/comparator.js:41:13)
at new Comparator (/path/to/node_modules/semver/classes/comparator.js:25:10)
at /path/to/node_modules/semver/classes/range.js:154:47
at Array.map (<anonymous>)
at Range.parseRange (/path/to/node_modules/semver/classes/range.js:154:35)
at /path/to/node_modules/semver/classes/range.js:42:22
at Array.map (<anonymous>)
at new Range (/path/to/node_modules/semver/classes/range.js:42:8)
at Object.intersects (/path/to/node_modules/semver/ranges/intersects.js:5:8)
at emit_dts (file:///path/to/@sveltejs/package/src/typescript.js:31:30)
```

### System Info

```Shell
- `@sveltejs/package`: 2.3.7
- `bun`: 1.2.14
- `node`: 20.x
- OS: macOS (Sequoia 15.3.2)
```

### Severity

blocking an upgrade

### Additional Information

https://x.com/bunjavascript/status/1925074467518353452

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #13836

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/package/src/typescript.js [hunk 1]
```diff
@@ -28,7 +28,13 @@ export async function emit_dts(input, output, final_output, cwd, alias, files, t
 	const require = createRequire(import.meta.url);
 	const pkg = load_pkg_json(cwd);
 	const svelte_dep = pkg.peerDependencies?.svelte || pkg.dependencies?.svelte || '3.0';
-	const no_svelte_3 = !semver.intersects(svelte_dep, '^3.0.0');
+	let no_svelte_3;
+	try {
+		no_svelte_3 = !semver.intersects(svelte_dep, '^3.0.0');
+	} catch (e) {
```
Comment (dummdidumm) [inline packages/package/src/typescript.js]:
```suggestion
	} catch (_) {
```

File: packages/package/src/typescript.js [hunk 2]
```diff
@@ -28,7 +28,13 @@ export async function emit_dts(input, output, final_output, cwd, alias, files, t
 	const require = createRequire(import.meta.url);
 	const pkg = load_pkg_json(cwd);
 	const svelte_dep = pkg.peerDependencies?.svelte || pkg.dependencies?.svelte || '3.0';
-	const no_svelte_3 = !semver.intersects(svelte_dep, '^3.0.0');
+	let no_svelte_3;
+	try {
+		no_svelte_3 = !semver.intersects(svelte_dep, '^3.0.0');
+	} catch (_) {
```
Comment (dummdidumm) [inline packages/package/src/typescript.js]:
```suggestion
	} catch {
```

**Review by benmccann — COMMENTED** [review]
I think this makes sense in the `latest` or `next` case, but a bit less in the workspace case described in https://github.com/sveltejs/kit/pull/13553. Maybe we can check the value? If it's a workspace value it would be nice to resolve it or at least log that we're just making an assumption about what value to use whereas in the `latest` or `next` case you probably want to just silently proceed as is being done here

**Comment by jycouet** [comment]
héhé, my PR is very close to this one! ^^ _(with a warn already)_

---

`catalog*` stuff is a nice feature, but it's quite new and package manager specific today. Maybe the fallback & warning is good enough for now?

**Comment by dummdidumm** [comment]
I don't think we need a warning - this is about checking for Svelte 3, which is rarely used these days. People using catalogs are certainly using a newer version of Svelte, too.

**Comment by jycouet** [comment]
Almost made it to the repo :p
I'll close my PR 👍

Thank you
