### PR TITLE
fix: Add support for vite.config.ts

### LINKED ISSUE #5443: Add `vite.config.ts` to generated tsconfig `include`
### Describe the problem

vite supports using typescript for its config: <https://vitejs.dev/config/#config-intellisense>, but eslint + typescript will complain that `vite.config.ts` is not included in the current project

### Describe the proposed solution

if it exists, add `../vite.config.ts` to the `include` section of generated tsconfigs

### Alternatives considered

manually specify `"include": ["vite.config.ts", "src/**/*", "src/**/*.svelte"]` in tsconfig

### Importance

nice to have

### Additional Information

image

### PR DESCRIPTION
**Pull request by bfanger**
When using a vite.config.ts (instead of a vite.config.js) TypeScript generates an error:
```
error TS2307: Cannot find module '@sveltejs/kit/vite' or its corresponding type declarations.

1 import { sveltekit } from "@sveltejs/kit/vite";
                            ~~~~~~~~~~~~~~~~~~~~

Found 1 error in vite.config.ts:1
```

Adding the **vite.config.ts** to the includes fixes this issue.

Also closes #5443

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [X] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [X] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]

File: packages/kit/src/core/sync/write_tsconfig.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ export function write_tsconfig(config, cwd = process.cwd()) {
 	/** @param {string} file */
 	const config_relative = (file) => posixify(path.relative(config.outDir, file));
 
-	const include = ['ambient.d.ts'];
+	const include = ['ambient.d.ts', config_relative('vite.config.ts')];
```
Comment (benmccann) [inline packages/kit/src/core/sync/write_tsconfig.js:49]: will this cause any issues if `vite.config.ts` is not present? do we need to list `vite.config.js` as well to make the `check` command check the `.js` version of the file?

Comment (dummdidumm) [reply packages/kit/src/core/sync/write_tsconfig.js:49]: If something isn't present then that's no problem for TS. We don't need to include `vite.config.js` just because we include the TS version. It's included so ESBuild knows about it so it can bundle the config prior to execution (I believe that's how Vite gets away with that)

**Review by benmccann — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thanks!

**Comment by Layendan** [comment]
I am still getting this error, even in the new version.

I ran `vite build` as well as reloaded the window after updating; however, the error still appears.

Although I doubt that the missing module error is linked to [this issue](https://github.com/sveltejs/kit/issues/6166). They did appear in my repository at the same time.

image

[Gihub Repo](https://github.com/Layendan/NineAnimator-Tauri)

```
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 103.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: 1.0.0-next.429 => 1.0.0-next.429 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```
