### PR TITLE
fix: use jpg as a fallback format

### LINKED ISSUE #15242: enahnced-img: png as a fallback format doesn't make sense.
### Describe the problem

In enhanced-img the formats served are avif, webp, and one more fallback format for browsers that don't support those two. The fallback format is jpg, unless the original image is png, webp, or avif. I guess the reasoning was, that those formats are the ones that support lossless compression and we don't want to lossily compress images that might have been losslessly encoded in the first place. Except it doesn't really make sense because on modern browsers, the user will still receive avif/webp, compressed images, and that compression will be lossy. So all it does, is generate inefficient images. Also, pretty much all images displayed on the web are lossy anyways, and assuming that if the original image is webp/avif it's probably lossless is a stretch. And even if it was lossless, the user using enhanced-img implies that they want to optimize their image, and know that it means some lossy compression. 

### Describe the proposed solution

Just make the formats always `avif;webp;jpg`. Even if the original image is png. If user needs a lossless image they can specify `?format=avif;webp;png&lossless`

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by blt-r**
closes #15242 

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by blt-r** [comment]
We can check `metadata.hasAlpha`? The only downside I can see to that, is that we'll always need to `await metadata()` and now we only do that when `imgWidth` is not passed. It is passed when user sets manually `width` prop, which is rare anyway. Even if it isn't, I don't think awaiting the metadata is much of a performance hit

File: packages/enhanced-img/src/index.js [hunk 1]
```diff
@@ -13,26 +12,27 @@ export function enhancedImages() {
...
-	'.png': 'png',
-	'.tiff': 'jpg',
-	'.webp': 'png'
-};
+/**
+ * @param {import('sharp').Metadata} meta
+ * @returns {string}
+ */
+function fallback_format(meta) {
+	if (meta.format === 'gif') return 'gif';
```
Comment (benmccann) [inline packages/enhanced-img/src/index.js]:
```suggestion
	if (meta.pages > 1) {
		return meta.format === 'tiff' ? 'tiff' : 'gif';
	}
```

**Comment by benmccann** [comment]
> The only downside I can see to that, is that we'll always need to await metadata() and now we only do that when imgWidth is not passed.

We could skip doing that if the extension is `.jpg` or `.jpeg`, which it will be quite frequently. In that case, there's no need to check the metadata because we know the image cannot be animated or transparent and so we will need to stick to the jpg format

File: packages/enhanced-img/src/index.js (hunk 1 above)
Comment (blt-r) [reply packages/enhanced-img/src/index.js]: Actually, animated images don't work at all?? By default sharp only reads the first page, and to make it read all pages you need to use `animated: true` option, which vite-imagetools doesn't do. So animated images of any kind just don't work. Also, even if you do open it with `animated: true`, only exporting to webp or gif actually makes an animated image. Sharp doesn't support animated avif or apng, so exporting to those types just results in a tall image with all frames on top of each other.

**Comment by blt-r** [comment]
> We could skip doing that if the extension is .jpg or .jpeg

I don't think that's necessary, I've just looked at the source code and vite-imagetools caches the metadata object and later uses it itself to clamp the sizes to the intrinsic size of the image, unless allowUpscale is passed. So if we don't read the metadata it will be read later anyways.

**Comment by benmccann** [comment]
> later uses it itself to clamp the sizes to the intrinsic size of the image, unless allowUpscale is passed. So if we don't read the metadata it will be read later anyways.

It looks like that's only true if `w` or `h` are manually specified

File: packages/enhanced-img/src/index.js (hunk 1 above)
Comment (benmccann) [reply packages/enhanced-img/src/index.js]: Thanks for that investigation! I updated my suggestion. We could account for multi-page `tiff` images, which probably should be rendered as a tall image. Otherwise `gif` is a good fallback for animated images. I expect this block would be triggered quite rarely and you're right that animated images aren't supported yet. But I'd rather avoid adding barriers to supporting them and make our best effort here at doing the right thing

**Comment by blt-r** [comment]
`w` is always manually specified, in the `defaultDirectives`

**Comment by blt-r** [comment]
is there anything else? i think this can be merged

File: packages/enhanced-img/src/index.js [hunk 2]
```diff
@@ -13,26 +12,31 @@ export function enhancedImages() {
...
+}
 
 function imagetools_plugin() {
 	/** @type {Partial<import('vite-imagetools').VitePluginOptions>} */
 	const imagetools_opts = {
 		defaultDirectives: async ({ pathname, searchParams: qs }, metadata) => {
 			if (!qs.has('enhanced')) return new URLSearchParams();
 
+			const meta = await metadata();
+
```
Comment (benmccann) [inline packages/enhanced-img/src/index.js]:
```suggestion
```

File: .changeset/witty-chefs-shave.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/enhanced-img': minor
```
Comment (benmccann) [inline .changeset/witty-chefs-shave.md]:
```suggestion
'@sveltejs/enhanced-img': patch
```

File: .changeset/witty-chefs-shave.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/enhanced-img': patch
+---
+
+feat: use jpg as a fallback format when source doesn't have an alpha channel
```
Comment (benmccann) [inline .changeset/witty-chefs-shave.md]:
```suggestion
fix: use jpg as a fallback format when source doesn't have an alpha channel
```
