### PR TITLE
fix: allow access to root-level issues in schema-less forms

### LINKED ISSUE #14892: Cannot access root-level `.issues()` in schema-less form
### Describe the bug

When you have a form with no schema, like this:
```ts
export const test = form((invalid) => {
	throw invalid('testing');
});

test.fields.issues(); // type error
//   ^? never
```
The `invalid` method is available, but `form.fields` is of type `never`, preventing access to the root-level issues.

### Reproduction

Copy this into any `*.remote.ts` file:
```ts
export const test = form((invalid) => {
	throw invalid('testing');
});

test.fields.issues(); // type error
//   ^? never
```
It works, but it has an incorrect type error.

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: macOS 26.0.1
    CPU: (16) arm64 Apple M4 Max
    Memory: 1.23 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - /Users/sillvva/.nvm/versions/node/v22.12.0/bin/node
    npm: 10.9.0 - /Users/sillvva/.nvm/versions/node/v22.12.0/bin/npm
    pnpm: 10.19.0 - /Users/sillvva/.nvm/versions/node/v22.12.0/bin/pnpm
    bun: 1.2.20 - /Users/sillvva/.bun/bin/bun
  Browsers:
    Firefox: 144.0
    Safari: 26.0.1
  npmPackages:
    @sveltejs/kit: ^2.47.1 => 2.48.4
```

### Severity

annoyance

### Additional Information

Proposed solution. Change this:
https://github.com/sveltejs/kit/blob/9909a2975436fb6d8d629d4469441666d5e38d7d/packages/kit/src/exports/public.d.ts#L2061
To this:
```ts
	fields: Input extends void
		? {
				issues(): RemoteFormIssue[] | undefined;
			}
		: RemoteFormFields<Input>;
```

### PR DESCRIPTION
**Pull request by sillvva**
fixes #14892 

When you have a form with no schema, the `invalid` method is available, but `form.fields` is of type `never`, preventing access to the root-level issues.
```ts
export const test = form((invalid) => {
	throw invalid('testing');
});

test.fields.issues(); // type error
//   ^? never
```

Lint test added to `remote.test.ts` for the `f8` form.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/exports/public.d.ts [hunk 1]
```diff
@@ -2058,7 +2059,16 @@ export type RemoteForm<Input extends RemoteFormInput | void, Output> = {
...
+	fields: IsAny<Input> extends true
+		? RecursiveFormFields
+		: Input extends void
+			? {
+					/** Validation issues, if any */
+					issues(): RemoteFormIssue[] | undefined;
+					/** Validation issues belonging to this or any of the fields that belong to it, if any */
+					allIssues(): RemoteFormIssue[] | undefined;
+				}
+			: RemoteFormFields<Input>;
```
Comment (dummdidumm) [inline packages/kit/src/exports/public.d.ts]: I wonder if we can simplify this by just doing this:

```suggestion
	fields: RemoteFormFields<Input>;
```

Yes, you'll have `set` and `value` on a void form but you cannot really do anything with it anyway, so it's fine.

Comment (sillvva) [reply packages/kit/src/exports/public.d.ts]: 🤔 Personally I'm fine with that. If the `void` type doesn't make that clear and people make issues, it can be revisited. I'll simplify it.

```ts
// RemoteFormFields<void> ✅
const test: RemoteFormFieldMethods<void> & {
    allIssues(): RemoteFormIssue[] | undefined;
} & void

const test: {
    value: () => void;
    set: (input: void) => void;
    issues: () => RemoteFormIssue[] | undefined;
    allIssues: () => RemoteFormIssue[] | undefined;
}

// RemoteFormFields<any> ✅
const test: RecursiveFormFields

const test: {
    [key: string]: UnknownField<any>;
    [key: number]: UnknownField<any>;
    value: () => any;
    set: (input: any) => any;
    issues: () => RemoteFormIssue[] | undefined;
    allIssues: () => RemoteFormIssue[] | undefined;
}
```
