### PR TITLE
breaking: return bound `query` instance from `requested`

### LINKED ISSUE #15696: Remote function query does not update when using schema transforms
### Describe the bug

Hi!

I started experiencing some issues of queries not updating when I call `.updates()` on them and after a lot of testing I found the cause.
If you use a schema that transforms the input (like valibot's `v.transform()`) sveltekit fails to update the query, I assume because the backend sends to the frontend the transformed input and the frontend tries to find the query instance that has that input but it can't cause it was transformed.

If you remove the `v.transform` it works as it should.

I'm not sure if this a known issue, couldn't find anything about this.

Let me know if you want a reproduction repo.

Thank you!

### Reproduction

Here is a quick example (you need to install valibot `npm i -D valibot`):
```ts
// the remote functions
import { command, query, requested } from "$app/server";
import * as v from "valibot";

let myList: number[] = [];

export const addToMyList = command(async () => {
  myList.push(0);
  await requested(getMyList, 1).refreshAll();
});

export const getMyList = query(
  v.pipe(
    v.number(),
    v.transform((n) => String(n)),
  ),
  (n) => {
    return myList;
  },
);
```
The client code:
```svelte
<script lang="ts">
  import { addToMyList, getMyList } from "$lib/test.remote";
</script>

<button onclick={async () => await addToMyList().updates(getMyList(1))}>Add</button>

<p>{(await getMyList(1)).join(", ")}</p>
```
Has you can see, `1` is passed both to the `await getMyList(1)` and to the `updates(getMyList(1))` but it doesn't get refreshed when you click "Add".

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (28) x64 13th Gen Intel(R) Core(TM) i7-13850HX
    Memory: 12.89 GB / 31.55 GB
  Binaries:
    Node: 25.9.0 - C:\Users\z0057a7a\AppData\Local\pnpm\node.EXE
    npm: 11.12.1 - C:\Users\z0057a7a\AppData\Local\pnpm\npm.CMD
    pnpm: 10.33.0 - C:\Users\z0057a7a\AppData\Local\pnpm\pnpm.CMD
    bun: 1.3.11 - C:\Users\z0057a7a\scoop\shims\bun.EXE
  Browsers:
    Edge: Chromium (145.0.3800.65)
  npmPackages:
    @sveltejs/adapter-node: ^5.5.4 => 5.5.4
    @sveltejs/kit: ^2.57.0 => 2.57.1
    @sveltejs/vite-plugin-svelte: ^7.0.0 => 7.0.0
    svelte: ^5.55.2 => 5.55.2
    vite: ^8.0.7 => 8.0.8
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by elliott-with-the-longest-name-on-github**
Alternative to #15738
Closes https://github.com/sveltejs/kit/issues/15696

I realized while reviewing that there's a fundamental problem: If the query's validator lossily changes the input, there's no way to map the validated input back to the correct argument. Consider a validator that calls `Math.floor` on its input number, then consider the following:

```ts
// from the client, we request `query(1.2)` and `query(1.8)`,
// but both `arg`s are `1`
for await (const arg of requested(my_query, 5)) {
  // there is no way to map `1` back to the original inputs;
  // only 1.8 would actually be refreshed because it wrote
  // to the `validated` cache last
  void my_query(arg).refresh();
}
```

This realization in hand, I further realized the only way to make this work is to somehow preserve the mapping of input arguments to validated arguments. The best way to do that is to return a bound instance of the query from `requested`:

```ts
for await (const { arg, query } of requested(my_query, 5)) {
  void query.refresh();
}
```

Problem solved; the `query` internally maintains the map of input argument => validated argument. The `arg` is still the validated argument in case you need to do something like `if (arg.id === id)`.

### CODE REVIEW

File: packages/kit/src/exports/public.d.ts [hunk 1]
```diff
@@ -2225,9 +2232,27 @@ export type RemotePrerenderFunction<Input, Output> = (
...
-) => RemoteQuery<Output>;
+) => RemoteQuery<Output>) & {
+	/**
+	 * Phantom property that exists for type inference only — it is never set at
+	 * runtime, hence the `?`. Used by
+	 * [`requested`](https://svelte.dev/docs/kit/$app-server#requested) to recover
+	 * the post-validation argument type. Do not read this property; it will always
+	 * be `undefined`. Prefixed with `~` to sort to the bottom of IntelliSense.
+	 */
+	readonly ['~validated']?: Validated;
```
Comment (dummdidumm) [inline packages/kit/src/exports/public.d.ts]: Our internal code doesn't use this either - is this really needed?

File: .changeset/remote-query-function-validated-generic.md [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+// getPost: RemoteQueryFunction<number, Post, string>
+//                              ^Input  ^Output ^Validated
+
+for (const { arg } of requested(getPost)) {
+	// arg is now typed as string (the post-transform value),
+	// previously it was incorrectly typed as number
+}
+```
+
+Existing code using `RemoteQueryFunction<Input, Output>` continues to work because the new parameter defaults to `Input`.
```
Comment (dummdidumm) [inline .changeset/remote-query-function-validated-generic.md]: We're normally adding more elaborate feature/breaking change descriptions to the PR itself, and the changelog entry then says "see the PR for how to migrate"

**Review by dummdidumm — COMMENTED** [review]
Stellar work, just a few comments

File: packages/kit/src/exports/public.d.ts (hunk 1 above)
Comment (elliott-with-the-longest-name-on-github) [reply packages/kit/src/exports/public.d.ts]: It does -- it's how `requested` can figure out the type of `arg`. Without this property, the post-validation output type isn't stored anywhere, so it can't be used for later inference. Does that make sense? Happy to see a better way to do this 😆

Comment (elliott-with-the-longest-name-on-github) [reply packages/kit/src/exports/public.d.ts]: Figured out how to do it without
