### PR TITLE
fix: disregard presence/absence of trailing slash in prerendered redirect

### LINKED ISSUE #12869: SvelteKit doesn't fix trailing slashes for prerendered routes
### Describe the bug

If SvelteKit receives a request for `/foo/`, and there's a `/foo` route that _doesn't_ have a trailing slash, it will redirect. 

But if `/foo` is prerendered, the route isn't added to the manifest, and so requests for `/foo/` result in a 404 instead.

### Reproduction

Go to https://svelte.dev/tutorial/

### Logs

_No response_

### System Info

```Shell
latest
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #12869. With this change, if the prerenderer encounters a redirect when rendering `/foo`, the resulting entry in `vercel.json` will have a `src` of `/foo/?` rather than `/foo` or `/foo/`.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/adapter-vercel/index.js [hunk 1]
```diff
@@ -446,7 +446,7 @@ function static_vercel_config(builder, config, dir) {
 
 	for (const [src, redirect] of builder.prerendered.redirects) {
 		prerendered_redirects.push({
-			src,
+			src: src.replace(/\/?$/, '/?'),
 			headers: {
 				Location: redirect.location
```
Comment (dummdidumm) [inline packages/adapter-vercel/index.js:451]: Is there any chance that the redirect location is the same except the trailing slash, in which case this would create an infinite loop? Maybe we should double-check that before applying the `/?` replacement

Comment (Rich-Harris) [reply packages/adapter-vercel/index.js]: Super edge case, since you can't create a `/foo` route alongside a `/foo/` route (best you could do is `/foo` alongside `/[blah]/`, but one would match over the other). But I guess you _could_ do something wacky with a `handle` hook or a custom server, and it does indeed create an infinite loop. Pushed some code to handle that case

**Review by dummdidumm — APPROVED** [review]

File: packages/adapter-vercel/index.js [hunk 2]
```diff
@@ -444,7 +444,15 @@ function static_vercel_config(builder, config, dir) {
 	/** @type {import('./index.js').ImagesConfig | undefined} */
 	const images = config.images;
 
-	for (const [src, redirect] of builder.prerendered.redirects) {
+	for (let [src, redirect] of builder.prerendered.redirects) {
+		if (src.replace(/\/$/, '') !== redirect.location.replace(/\/$/, '')) {
+			// handle the extreme edge case of a `/foo` -> `/foo/` redirect,
```
Comment (benmccann) [inline packages/adapter-vercel/index.js:449]: I'm on mobile, so maybe I'm just misreading, but I feel like this comment should apply to the `if` statement rather than this line

This line could probably use a different comment about disregarding the presence/absence of trailing slash in prerendered redirect

Comment (Rich-Harris) [reply packages/adapter-vercel/index.js]: yeah the position of the comment is tricky because even if it's outside the `if` it looks like it's describing what happens inside rather than when you don't get there

fixed slightly unconventionally: inverted the condition and made the antecedent a no-op, just the comment

Comment (benmccann) [reply packages/adapter-vercel/index.js]: lol. that works

I probably would have done it by changing the wording to something like "only apply if we're not hitting the extreme edge case of..."

but I guess I'm happy with this too. maybe the bundler will make them the same anyway :laughing:

**Review by benmccann — APPROVED** [review]
