### PR TITLE
fix: consistently use bare import for internals

### LINKED ISSUE #14505: Cannot use `getRequestEvent` in kit 2.43.0
### Describe the bug

After upgrading from `@sveltejs/kit` 2.42.2 to 2.43.0, I get the following error in my local dev environment. It is hitting this error in one of my `hooks.server.ts` handles. 
```
Internal Error {
  error: Error: Can only read the current request event inside functions invoked during `handle`, such as server `load` functions, actions, endpoints, and other server hooks.
      at getRequestEvent (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/exports/internal/event.js:39:9)
      at run (/Users/sillvva/Projects/ddal-svelte/src/lib/server/effect/runtime.ts:48:16)
      at authHandler (/Users/sillvva/Projects/ddal-svelte/src/hooks.server.ts:43:2)
      at file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:103:7
      at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
      at with_request_store (file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/exports/internal/event.js:65:20)
      at fn (file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:102:19)
      at Object.record_span (/Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/runtime/telemetry/record_span.js:9:10)
      at apply_handle (file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:97:25)
      at resolve (file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.43.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.39.4_vite@7.1.7_@types_357898af6df0adae12b9a5a39d6c1d29/node_modules/@sveltejs/kit/src/exports/hooks/sequence.js:128:12),
```
The `run` function is a custom function getting called in the handle that calls `getRequestEvent` to get the locals. I use `getRequestEvent`, because the `run` function is used in multiple places, not just hooks.
```ts
const authHandler: Handle = async ({ event, resolve }) =>
	run(function* () {
		const Auth = yield* AuthService;
		const auth = yield* Auth.auth();
		return svelteKitHandler({ event, resolve, auth, building });
	});
```
Downgrading to 2.42.2 fixes the error.

### Reproduction

In the reproduction, I get a slightly different error:
https://stackblitz.com/edit/sveltejs-kit-template-default-yym6ubrm?file=src%2Froutes%2F%2Blayout.svelte
```
Error: Could not get the request store. This is an internal error.
    at get_request_store (node_modules/@sveltejs/kit/src/exports/internal/event.js:54:9)
    at wrapper (node_modules/@sveltejs/kit/src/runtime/app/server/remote/query.js:80:71)
    at eval (src/routes/+page.svelte:18:78)
    at Renderer.child (node_modules/svelte/src/internal/server/renderer.js:141:18)
    at Renderer.async (node_modules/svelte/src/internal/server/renderer.js:119:8)
    at eval (src/routes/+page.svelte:17:15)
    at Renderer.child (node_modules/svelte/src/internal/server/renderer.js:141:18)
    at Renderer.component (node_modules/svelte/src/internal/server/renderer.js:166:22)
    at _page (src/routes/+page.svelte:15:13)
```

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: macOS 26.0
    CPU: (16) arm64 Apple M4 Max
    Memory: 1.12 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    pnpm: 10.11.0 - ~/.nvm/versions/node/v22.12.0/bin/pnpm
    bun: 1.2.20 - ~/.bun/bin/bun
  Browsers:
    Safari: 26.0
  npmPackages:
    @sveltejs/adapter-node: ^5.3.2 => 5.3.2 
    @sveltejs/kit: ^2.42.2 => 2.42.2 
    @sveltejs/vite-plugin-svelte: ^6.2.0 => 6.2.0 
    svelte: ^5.39.4 => 5.39.4 
    vite: ^7.1.7 => 7.1.7
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
In #14447 I broke a cardinal rule — code in `src/runtime` should only ever import code from `src/exports` via the public bare imports made available via `pkg.exports`. Otherwise, there's a danger that a given module will be loaded through both Vite _and_ Node, causing breakage.

I ignored that rule because I was trying to deal with some tricky resolution bug, and #14505 was my reward. Luckily I think the tricky resolution bug is solved by not having a nested `pkg.exports` map, and instead abusing `pkg.imports` to achieve the intended outcome.

This is one of those things that's extremely hard to test for from within the workspace, because of how Vite works. But I _think_ this solution is good. Closes #14505.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
(Tested the repro in #14505 with the pkg.pr.new version from this PR, and it does indeed appear to be fixed)

**Review by dominikg — APPROVED** [review]

File: packages/kit/src/runtime/app/paths/server.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { base, assets, relative } from './internal/server.js';
```
Comment (teemingc) [inline packages/kit/src/runtime/app/paths/server.js:1]: What's the reason for this import not using the import map `$apps/paths/internal/server` instead? Does the rule only apply to internal paths using the export map?
