### PR TITLE
fix: use correct cache result when fetching same url multiple times

### LINKED ISSUE #12351: svelte fetch causes api results to be cached
### Describe the bug

Using svelte fetch causes the same data to be returned.

```ts
// +page.ts
export const load = async ({ fetch }) => {
	const values: string[] = [];

	for (let i = 0; i < 5; i++) {
		const res = await fetch('https://api.chucknorris.io/jokes/random');
		const { value } = await res.json();
		values.push(value);
	}

	return { values };
};
```
```svelte
<script lang="ts">
	export let data;
	const values = data.values;
</script>

{#each values as value, index}
	<h1>{index}: {value}</h1>
{/each}
```

### Reproduction

```bash
npx degit https://github.com/sacrosanctic/bug-with-svelte-fetch
npm i
npm run dev
```
`routes/a/+page.svelte` should demonstrate the bug

### Logs

_No response_

### System Info

```Shell
.
```

### Severity

annoyance

### Additional Information

https://discord.com/channels/457912077277855764/1251255888598274138

related conversation on discord

### PR DESCRIPTION
**Pull request by PatrickG**
Fix #12351

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by eltigerchino** [comment]
LGTM but I'd wait for another maintainer that's more familiar with the universal fetch code to review this too.

**Review by eltigerchino — APPROVED** [review]

File: packages/kit/src/runtime/client/fetcher.js [hunk 1]
```diff
@@ -90,6 +90,7 @@ export function initial_fetch(resource, opts) {
 
 	const script = document.querySelector(selector);
 	if (script?.textContent) {
+		script.remove();
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/fetcher.js:93]:
```suggestion
		script.remove(); // In case multiple script tags match the same selector
```

**Review by dummdidumm — COMMENTED** [review]
I'm wondering if
- a) this might have a non-neglible performance impact since we're mutating the DOM during hydration (it's without reflow though)
- b) we should instead properly deduplicate such cases (possibly a counter of some sorts)
- c) handle the case were the same request has the same response, and deduplicate that (I'm not sure how often this would really happen)

File: packages/kit/src/runtime/client/fetcher.js [hunk 2]
```diff
@@ -90,6 +90,7 @@ export function initial_fetch(resource, opts) {
 
 	const script = document.querySelector(selector);
 	if (script?.textContent) {
+		script.remove(); // In case multiple script tags match the same selector
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/fetcher.js:93]: What about this? Someone should benchmark which is faster (I would guess just reading is much faster)
```suggestion
	const [script, next_script] = document.querySelectorAll(selector);
	if (script?.textContent) {
		if (next_script) script.remove(); // In case multiple script tags match the same selector
```

Comment (dummdidumm) [reply packages/kit/src/runtime/client/fetcher.js:93]: Scratch that, I perfed it an querySelectorAll is much slower

**Comment by Rich-Harris** [comment]
very late obviously but: I'm good with this solution, I think — we _could_ dedupe repeat requests with identical responses, but given gzip/brotli it probably doesn't save you that much. And given our push for remote functions, it's likely that use of `event.fetch` will lessen over time, so it's probably not a good use of engineering effort. thank you!

**Review by Rich-Harris — APPROVED** [review]
