### PR TITLE
fix: ignore target=_blank links

### LINKED ISSUE #8482: beforeNavigate shouldn't trigger when <a target="_blank">
### Describe the bugs

I've grouped together two behavioural issues as they feel related:

1. Links that open in a new tab / window should not trigger beforeNavigate.

2. It would be useful to be notified whether `navigation.cancel()` will trigger the browser `beforeunload` behaviour.
  Or, if we could choose whether to trigger that behaviour.
  As it stands it's not possible to know whether to handle the beforeUnload event with our own UI. In my first (naive) use of `navigation.cancel()`, I created my own confirmation UI in Svelte. The final result was that _some_ navigation events would have just my UI, and others would have the native UI *and* my UI.

### Reproduction

https://github.com/oodavid/sveltekit-beforeUnload - instructions 

https://www.loom.com/share/3fbc000bbbaa4e65b1e64f304d0fddee - video explanation

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 32.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Edge: 108.0.1462.76
    Firefox: 105.0.1
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.11 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
Also some docs on how to know when native confirmation dialog appears
fixes #8482

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by Conduitry** [comment]
Are there other `target`s we should also be ignoring? I'm aware of `_self` and `_blank` and (I think) `_top` plus whatever other custom names you want to have if you're using frames. What do we want to have happen when someone uses `target='_self'`

I know we probably don't want to think too hard about people using frames, but is there another check here we could perform that would cover more cases a little better? (I'm not saying this because I'm already pretty sure there is one. I'm just asking.)

**Comment by Rich-Harris** [comment]
Is this logic right? We want to skip `beforeNavigate` when links open in a new tab, which IIUC means this:

```html
<!-- should skip beforeNavigate -->
<a href="/other" target="_blank">...</a>
<a href="/other" target="other">...</a>

<!-- should NOT skip beforeNavigate -->
<a href="/other" target="_self">...</a>
<a href="/other" target="_top">...</a>
<a href="/other" target="_parent">...</a>
```

**Comment by Rich-Harris** [comment]
Actually on a closer read, I _think_ the only change we need is to respect user-defined targets

**Comment by dummdidumm** [comment]
Oh right, I forgot about those, yeah the if condition needs to be adjusted

File: packages/kit/types/ambient.d.ts [hunk 1]
```diff
@@ -243,7 +243,8 @@ declare module '$app/navigation' {
 
 	/**
 	 * A navigation interceptor that triggers before we navigate to a new URL, whether by clicking a link, calling `goto(...)`, or using the browser back/forward controls.
-	 * Calling `cancel()` will prevent the navigation from completing.
+	 * Calling `cancel()` will prevent the navigation from completing. If the navigation would have directly unloaded the current page, calling `cancel` will trigger the native
+	 * browser unload confirmation dialog. This is the case for type `unload` and for `popstate` if the next url is not part of the app.
```
Comment (Rich-Harris) [inline packages/kit/types/ambient.d.ts:247]: is this right? `popstate` would _only_ fire for internal navigations, surely? if clicking the back button would cause us to go back to a different document then type would be `unload`. 

```suggestion
	 * Calling `cancel()` will prevent the navigation from completing. If the navigation would have directly unloaded the current page, calling `cancel` will trigger the native
	 * browser unload confirmation dialog. In these cases, `navigation.willUnload` is `true`.
```

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
suggested a change to the docs because i'm not sure the popstate stuff is right

File: packages/kit/src/runtime/client/client.js [hunk 2]
```diff
@@ -1389,10 +1389,17 @@ export function create_client({ target, base }) {
...
 
-				const { url, external, has } = get_link_info(a, base);
-				const options = get_router_options(a);
+				const { url, external, target } = get_link_info(a, base);
 				if (!url) return;
 
+				// bail out before `beforeNavigate` if link opens in a different tab
+				if (target === '_parent' || target === '_top') {
+					if (window.parent !== window) return;
+				} else if (target === '_blank' || target?.startsWith('_')) {
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/client.js:1398]: Are underscored names reserved or could someone do `_google` (in which case the logic would need to be adjusted)?

Comment (Rich-Harris) [reply packages/kit/src/runtime/client/client.js:1398]: ah you're right, it should probably just be this

```suggestion
				} else if (target && target !== '_self') {
```

**Review by Rich-Harris — APPROVED** [review]
