### PR TITLE
fix: prevent conflict between Netlify Identity and edge function rendering

### LINKED ISSUE #5235: Netlify Identity not working when using Edge Functions
### Describe the bug

When using `adapter-netlify` and enabling the experimental Edge Functions, Netlify Identity doesn't work. The `https://example.com/.netlify/identity` path gets a 404 from SvelteKit, but it should be handled by Netlify (or at least I think so).

Using the adapter without the Edge Functions enabled doesn't break Netlify Identity.

### Reproduction

[Stackblitz fork](https://stackblitz.com/edit/sveltejs-kit-template-default-yn2ycz?file=svelte.config.js).

1. Create a project on Netlify.
2. Enable [Identity](https://docs.netlify.com/visitor-access/identity/) and [Git Gateway](https://docs.netlify.com/visitor-access/git-gateway/).
3. Try to login at /admin (or invite yourself and try to accept the invite)

### Logs

```shell
The Firefox browser console shows `[XHR] GET https://example.com/.netlify/identity/settings [HTTP/2 404 Not Found 31ms]`
```

### System Info

```shell
System:
  OS: macOS 12.4
  CPU: (8) arm64 Apple M1
  Memory: 81.97 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn: 1.22.15 - /opt/homebrew/bin/yarn
  npm: 8.5.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
Browsers:
  Chrome: 102.0.5005.115
  Firefox: 101.0.1
  Safari: 15.5
  Safari Technology Preview: 15.4
npmPackages:
  @sveltejs/adapter-netlify: next => 1.0.0-next.64 
  @sveltejs/kit: next => 1.0.0-next.350 
  svelte: ^3.48.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by serhalp**
Fixes #5235.

When using edge functions with Netlify, the generated edge function was configured to run against all paths. This conflicted with the expectation that paths under `.netlify/` (such as `.netlify/identity/settings`) are ignored by the framework.

At the time #5235 was opened, this was difficult to solve, but Netlify now supports path exclusions in edge function configuration, hence this PR.

While I was here, I also added an exclusion to avoid unnecessarily invoking this edge function on static files. Currently it's [just a no-op](https://github.com/sveltejs/kit/blob/80386437030c5c79913e859e3c32fd194613e1b6/packages/adapter-netlify/src/edge.js#L18-L22), but it's still nice to avoid the unnecessary invocation.

Testing this is a bit involved, but I was able to repro the issue in #5235 and to confirm this fixes it. We should probably add proper integration tests here eventually.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests

- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets

- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/adapter-netlify/index.js [hunk 1]
```diff
@@ -13,15 +13,19 @@ import toml from '@iarna/toml';
  */
 
 /**
+ * TODO(serhalp) Replace this custom type with an import from `@netlify/edge-functions`,
+ * once that type is fixed to include `excludedPath` and `function`.
```
Comment (serhalp) [inline packages/adapter-netlify/index.js:17]: FYI I'm working on this as well. I should have a follow-up PR soon.

**Comment by serhalp** [comment]
Hi @benmccann, nice to meet you! Is there anything I need to do to get this PR merged and released? Please let me know. Thanks!

**Review by dummdidumm — COMMENTED** [review]
Sorry for leaving this without a review for so long! From a first glance it looks good. One questions though: What happens if `paths.base` (SvelteKit) is set, does that have any influence on this (or in other words would it break)?

@eltigerchino can you have another look at this (checking what happens with a base path, and also investigate whether we can remove the code in `is_static_file`?

File: .changeset/witty-teachers-film.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/adapter-netlify': patch
+---
+
+Fix: Avoid unnecessary Netlify edge function invocations for static files, which resolves a conflict between Netlify Edge Functions and Netlify Identity
```
Comment (eltigerchino) [inline .changeset/witty-teachers-film.md:5]:
```suggestion
fix: avoid unnecessary Netlify edge function invocations for static files, which resolves a conflict between Netlify Edge Functions and Netlify Identity
```

**Comment by eltigerchino** [comment]
Having a base path seems to work fine with this PR.

File: packages/adapter-netlify/index.js [hunk 3]
```diff
@@ -122,18 +126,21 @@ async function generate_edge_functions({ builder }) {
 
 	builder.mkdirp('.netlify/edge-functions');
 
-	// Don't match the static directory
-	const pattern = '^/.*$';
-
-	// Go doesn't support lookarounds, so we can't do this
-	// const pattern = appDir ? `^/(?!${escapeStringRegexp(appDir)}).*$` : '^/.*$';
+	const path = '/*';
```
Comment (eltigerchino) [inline packages/adapter-netlify/index.js:129]: Wonder if we should add the base path to this:
```js
const path = `${builder.config.kit.paths.base}/*`;
```

File: packages/adapter-netlify/src/edge.js [hunk 4]
```diff
@@ -51,6 +52,7 @@ function is_static_file(request) {
 		// ignore
 	}
 
+	// TODO(serhalp) Now that edge function config supports `excludedPath`, could we replace all these checks?
```
[the remark this answers is not in the document]
Comment (eltigerchino) [reply packages/adapter-netlify/src/edge.js]: Seems like Netlify handles trailing slash redirects automatically so we can remove the `is_static_file` check if we just exclude the paths that would have been checked by it e.g., `/foo`, `/foo/`, and `/foo/index.html`.

File: packages/adapter-netlify/index.js [hunk 5]
```diff
@@ -126,10 +126,42 @@ async function generate_edge_functions({ builder }) {
...
+	const { assets } = (await import(`${tmp}/manifest.js`)).manifest;
+
 	const path = '/*';
+	// We only need to specify paths without the trailing slash because
+	// Netlify will handle the optional trailing slash for us
 	const excludedPath = [
 		// Contains static files
 		`/${builder.getAppPath()}/*`,
+		...builder.prerendered.paths,
+		...Array.from(assets).flatMap((asset) => {
```
Comment (dummdidumm) [inline packages/adapter-netlify/index.js:155]: the previous logic also checked within `manifest._.server_assets`, this one does not - oversight or on purpose?

Comment (eltigerchino) [reply packages/adapter-netlify/index.js:155]: We could add `manifest._.server_assets` too but they're currently included in the immutable assets path too `/${builder.getAppPath()}/*` because we copy the server assets there and make them public. I'm not sure if that will change in the future.

**Review by dummdidumm — APPROVED** [review]

File: packages/adapter-netlify/index.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (eltigerchino) [reply packages/adapter-netlify/index.js:18]: Looking at https://www.npmjs.com/package/@netlify/edge-functions?activeTab=code the `ManifestFunction` type contains the correct definition if we want to use those types.
