### PR TITLE
fix: allow `HandleServerError` hook to access the ` getRequestEvent`

### LINKED ISSUE #13654: Using `getRequestEvent` inside `HandleServerError` hook fails
### Describe the bug

I am wondering if there's a particular reason `getRequestEvent` is not available in `HandleServerError` hook? I would expect it to work here along side the other server function and handles.

```Can only read the current request event inside functions invoked during `handle`, such as server `load` functions, actions, and server endpoints.```

Thanks 🙌 

### Reproduction

Example in `hooks.server.js`. Visit invalid page e.g. `/invalid`.
https://stackblitz.com/edit/sveltejs-kit-template-default-wwnmlhej?file=src%2Fhooks.server.js

### Logs

```Shell
Error: Can only read the current request event inside functions invoked during `handle`, such as server `load` functions, actions, and server endpoints.
    at getRequestEvent (/home/projects/sveltejs-kit-template-default-wwnmlhej/node_modules/@sveltejs/kit/src/runtime/app/server/event.js:37:9)
    at Object.handleError (/home/projects/sveltejs-kit-template-default-wwnmlhej/src/hooks.server.js:7:67)
    at handle_error_and_jsonify (/home/projects/sveltejs-kit-template-default-wwnmlhej/node_modules/@sveltejs/kit/src/runtime/server/utils.js:73:30)
    at respond_with_error (/home/projects/sveltejs-kit-template-default-wwnmlhej/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:97:67)
    at async resolve (/home/projects/sveltejs-kit-template-default-wwnmlhej/node_modules/@sveltejs/kit/src/runtime/server/respond.js:442:16)
    at async respond (/home/projects/sveltejs-kit-template-default-wwnmlhej/node_modules/@sveltejs/kit/src/runtime/server/respond.js:261:22)
    at async eval (file:///home/projects/sveltejs-kit-template-default-wwnmlhej/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:564:22)
```

### System Info

```Shell
Latest versions, see Stackblitz above
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by geodask**
Resolves #13654: Allow `HandleServerError` hook to access `getRequestEvent`.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by eltigerchino** [comment]
Have we also checked if `getRequestEvent` works in the server `handleFetch` hook too?

File: packages/kit/src/runtime/app/server/event.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ import('node:async_hooks')
 	});
 
 /**
- * Returns the current `RequestEvent`. Can be used inside `handle`, `load` and actions (and functions called by them).
+ * Returns the current `RequestEvent`. Can be used inside `handle`, `handleError`, `load` and actions (and functions called by them).
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/server/event.js:18]:
```suggestion
 * Returns the current `RequestEvent`. Can be used inside server hooks, `load` and form actions (and functions called by them).
```

Comment (eltigerchino) [inline packages/kit/src/runtime/app/server/event.js:18]:
```suggestion
 * Returns the current `RequestEvent`. Can be used inside server hooks, `load` and actions (and functions called by them).
```

File: packages/kit/src/runtime/app/server/event.js [hunk 2]
```diff
@@ -25,7 +25,7 @@ export function getRequestEvent() {
 
 	if (!event) {
 		let message =
-			'Can only read the current request event inside functions invoked during `handle`, such as server `load` functions, actions, and server endpoints.';
+			'Can only read the current request event inside functions invoked during `handle`, such as server `load` functions, actions, and server endpoints, and `handleError`.';
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/server/event.js:28]:
```suggestion
			'Can only read the current request event inside functions invoked during `handle`, such as server `load` functions, actions, endpoints, and other server hooks.';
```

File: packages/kit/types/index.d.ts [hunk 3]
```diff
@@ -2417,7 +2417,7 @@ declare module '$app/server' {
 	 */
 	export function read(asset: string): Response;
 	/**
-	 * Returns the current `RequestEvent`. Can be used inside `handle`, `load` and actions (and functions called by them).
+	 * Returns the current `RequestEvent`. Can be used inside `handle`, `handleError`, `load` and actions (and functions called by them).
```
Comment (eltigerchino) [inline packages/kit/types/index.d.ts:2420]:
```suggestion
	 * Returns the current `RequestEvent`. Can be used inside server hooks, server `load` functions, actions, and endpoints (and functions called by them).
```

**Review by eltigerchino — APPROVED** [review]
Thank you!
