### PR TITLE
fix: skip calling `respond` for server-side `fetch` on prerendered pages

### LINKED ISSUE #12739: Global slug overrides prerendered route when accessed from another route with event.fetch, but ok from client?
### Describe the bug

I have a web app that has a mix of prerendered pages and dynamic pages. The app also contains a REST endpoint that has `export const prerender = true`. The prerendered endpoint fetches data from a CMS, containing a bunch of metadata needed for a another endpoint that depends on. This fetch is done at build time, as the metadata itself doesn't change very often (but often enough that it can't be a static file), so we slapped the prerender flag on it.

Basic layout:

```
src/routes/[...slug]          Pages from the CMS
src/routes/api/route1         Component endpoint to get some data. Depends on route2.json
src/routes/api/route2.json    Prerendered metadata from the CMS
```

`route1` requests data from `route2.json` and does stuff with it. All of this works great in dev mode, but it stops working in preview mode and also when deployed to the host. `route2.json` actually works fine when accessing thru the browser; however, it does not work when using `event.fetch()` from within `route1`. Instead it returns the HTML from our 404 page. `route2.json` also works without the prerender, but that means it needs to fetch the data from the CMS at runtime, which is what we're trying to avoid.

I have made a repo to demonstrate the problem: https://github.com/x0rsw1tch/sk-route-prerender-test. Reproduction steps included.

### Using minimal reproduction repo

1. Clone my repo
1. Run `npm i && npm run dev`
1. Access `http://localhost:5173/`
1. Browser output: `Result: {"something":true,"somethingElse":true}` (working as intended here)
1. Shutdown dev
1. Run `npm run build && npm run preview`
1. Access `http://localhost:4173/`
1. Browser output: `Result: {"something":true}` (not working as intended here)

### Manually

1. Create a new SvelteKit app
2. Create a route for `/api/route2.json` that is `prerender = true`  that outputs some JSON
3. Create a route for `/api/route1` that outputs some JSON, 
4. Have `/api/route` use `event.fetch` to retrieve data from `/api/route2.json`, and merge the JSON objects
5. Create a new route at root named `[...slug]` with param file containing:

```
export const match = (param) => {
  return /^[a-z0-9-]+$/.test(param);
};
```

6. Under `[...slug]/+page.svelte` Do a fetch at onMount fetching `/api/route1` . Output the response to body to see what comes back from the fetch.

---

Expected result:

Output from `/api/route1` has output from itself and from `/api/route2.json` in dev mode and preview mode.

Actual results:

- Output from `/api/route1` has output from itself and from `/api/route2.json` in dev mode, but preview mode throws an error.
- If `/api/route2.json` is accessed from the client, the output is correct, it's only incorrect when accessing the endpoint using `event.fetch`. Error is thrown (see logs). When doing `event.fetch('/api/route2.json')`, it's not routing correctly, instead it's fetching from the "slug" endpoint returning HTML, not JSON.

### Logs

```Shell
Node logs:


SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at fullyReadBody (node:internal/deps/undici/undici:1447:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5309:7)
    at async GET (file:///D:/Projects-Ethode/sk-predender-test/.svelte-kit/output/server/entries/endpoints/api/route1/_server.js:8:3)
    at async render_endpoint (file:///D:/Projects-Ethode/sk-predender-test/.svelte-kit/output/server/index.js:260:20)
    at async resolve2 (file:///D:/Projects-Ethode/sk-predender-test/.svelte-kit/output/server/index.js:2802:22)
    at async respond (file:///D:/Projects-Ethode/sk-predender-test/.svelte-kit/output/server/index.js:2697:22)
```
```


### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 7900X 12-Core Processor
    Memory: 25.10 GB / 63.18 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.5 
    @sveltejs/adapter-vercel: ^5.1.0 => 5.4.4 
    @sveltejs/kit: ^2.0.0 => 2.5.28 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.2
    svelte: ^4.2.12 => 4.2.19
    vite: ^5.0.3 => 5.4.6
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### LINKED ISSUE #12778: Infinite loop when accessing prerendered `+server.js` from matching non-prerendered `+server.js`
### Describe the bug

Given this structure
```
[id].json/+server
examples.json/+server
```
with `examples.json` being prerendered and `[id].json` fetching `examples.json`, the server is fine at dev time but crashes in prod. The manifest seems to not properly resolve the correct route, instead of fetching the prerendered `examples.json` it recursively calls itself in `[id].json`. My guess is that the runtime first tries to find a matching "live" route before checking if a prerendered one exists.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-fhjdvp?file=src%2Froutes%2F%2Bpage.server.js

### Logs

_No response_

### System Info

```Shell
SvelteKit 2.6.3
```

### Severity

annoyance

### Additional Information

can be worked around by making sure the routes don't match

### PR DESCRIPTION
**Pull request by aloisklink**
Server-side `fetch()` (e.g. when `isSubRequest: true`) currently has a few bugs when called on a `prerendered` route.

1. When a non-prerendered route also matches the same URL as the prerendered route, the non-prerendered routes are taking precedence (e.g. if `export const prerender = 'auto'`)
2. Prerendered routes still have `hooks.server.js` run on them, but only when `isSubRequest: true`

I've fixed both of these issues by adding a `prerendered_routes: Set<string>` to the manifest. Then, we instantly call a real HTTP `fetch()` if the path matches, just like when calling server-side `fetch()` on assets (when the adapter doesn't support reading assets from the file-system).

During dev/build, there are no `prerendered_routes`, so it's left empty in the manifest (although that does mean the `manifest-full.js` also excludes it!)

Fixes #12778
Fixes #12739

### Potential issues

- According to the docs for `prerendered.paths` (which I'm using to set `prerendered_routes`), it only has the routes without a trailing slash. Would this be an issue? If so, the code might get a lot more complicated! https://github.com/sveltejs/kit/blob/873a09eac86817d1cbb53bf3f9c8842d7346d20d/packages/kit/src/types/private.d.ts#L189-L190 
- In the future, we might want to make a new entry like `prerendered_redirects`, so that we can follow the redirect chain without having to make a real HTTP request, but I think that should be fine if this is under the private `_` field in the `manifest.js` file.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
  - Fixes #12739. I'm not super sure if this implementation is the best way to fix it, though!
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`
  - `pnpm test` fails on `main` locally for me, so let's see if the CI passes on it!

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.
  - I've made two separate changesets for both the bugs I've fixed! Let me know if you want me to combine them (or if I should add more info to them, since I've just copied my commit message title, which are 50 chars long)

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/core/adapt/builder.js [hunk 1]
```diff
@@ -138,6 +138,7 @@ export function create_builder({
 						generateManifest: ({ relativePath }) =>
 							generate_manifest({
 								build_data,
+								prerendered: null,
```
Comment (dummdidumm) [inline packages/kit/src/core/adapt/builder.js:141]:
```suggestion
								prerendered: [],
```

File: packages/kit/src/core/generate_manifest/index.js [hunk 2]
```diff
@@ -14,11 +14,12 @@ import { find_server_assets } from './find_server_assets.js';
  * build process, to power routing, etc.
  * @param {{
  *   build_data: import('types').BuildData;
+ *   prerendered: import('types').Prerendered | null;
```
Comment (dummdidumm) [inline packages/kit/src/core/generate_manifest/index.js:17]:
```suggestion
 *   prerendered: string[];
```

File: packages/kit/src/core/generate_manifest/index.js [hunk 3]
```diff
@@ -113,6 +114,7 @@ export function generate_manifest({ build_data, relative_path, routes }) {
 						`;
 					}).filter(Boolean).join(',\n')}
 				],
+				prerendered_routes: new Set(${s(prerendered === null ? [] : prerendered.paths)}),
```
Comment (dummdidumm) [inline packages/kit/src/core/generate_manifest/index.js:117]:
```suggestion
				prerendered_routes: new Set(${s(prerendered)}),
```

File: packages/kit/src/core/adapt/builder.js [hunk 4]
```diff
@@ -185,6 +186,7 @@ export function create_builder({
 		generateManifest({ relativePath, routes: subset }) {
 			return generate_manifest({
 				build_data,
+				prerendered,
```
Comment (dummdidumm) [inline packages/kit/src/core/adapt/builder.js:189]:
```suggestion
				prerendered: prerendered.paths,
```

File: packages/kit/src/exports/vite/index.js [hunk 5]
```diff
@@ -795,6 +795,7 @@ Tips:
 					manifest_path,
 					`export const manifest = ${generate_manifest({
 						build_data,
+						prerendered: null,
```
Comment (dummdidumm) [inline packages/kit/src/exports/vite/index.js:798]:
```suggestion
						prerendered: [],
```

File: packages/kit/src/exports/vite/index.js [hunk 6]
```diff
@@ -917,6 +918,7 @@ Tips:
...
```
Comment (dummdidumm) [inline packages/kit/src/exports/vite/index.js:921]:
```suggestion
						prerendered: [],
```

File: packages/kit/src/exports/vite/index.js [hunk 7]
```diff
@@ -948,6 +950,7 @@ Tips:
 					`${out}/server/manifest.js`,
 					`export const manifest = ${generate_manifest({
 						build_data,
+						prerendered,
```
Comment (dummdidumm) [inline packages/kit/src/exports/vite/index.js:953]:
```suggestion
						prerendered: prerendered.paths,
```

File: packages/kit/src/runtime/server/fetch.js [hunk 8]
```diff
@@ -112,6 +112,17 @@ export function create_fetch({ event, options, manifest, state, get_cookie_heade
...
 				}
 
+				if (
+					manifest._.prerendered_routes.has(decoded) ||
+					(decoded.at(-1) === '/' && manifest._.prerendered_routes.has(decoded.slice(0, -1)))
+				) {
+					// the prerendered logic is different for each adapter,
+					// (except maybe for prerendered redirects)
+					// so we need to make an actual HTTP request
+					// We do it here to avoid calling server-side hooks for prerendered routes
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/fetch.js:122]:
```suggestion
					// The path of something prerendered could match a different route
					// that is still in the manifest, leading to the wrong route being loaded.
					// We therefore bail early here. The prerendered logic is different for
					// each adapter, (except maybe for prerendered redirects)
					// so we need to make an actual HTTP request
```

**Review by dummdidumm — APPROVED** [review]
thank you!

**Comment by aloisklink** [comment]
Thanks for handling the case where there is a trailing slash (and passing an array is a lot simpler!).

> Re the trailing slash problematics: that could indeed be problematic in the sense of you would get a false negative if you request `/foo/` - I would say we just remove the trailing slash in this case. I cannot image anyone having a dynamic route on `/foo/` but a prerendered one on `/foo` or vice versa.

I was thinking of the same edge case :laughing:. I suspect it might happen due to a bug in somebody's code, but in the worst case, we're just adding the overhead of an extra HTTP call, so I doubt anybody would complain.
