### PR TITLE
redirect when previewing prerendered pages

### LINKED ISSUE #8839: Trailing slash redirect does not work for prerendered pages
### Describe the bug

After building the app, trailing slash redirects do not work, returning a 404 instead.

The `server.respond` trailing slash redirect only works for non-prerendered routes.
This is because it checks the SSR manifest first but prerendered routes were removed from it in https://github.com/sveltejs/kit/pull/7541

### Reproduction

https://stackblitz.com/edit/github-vabxnk-zdpsdn?file=src%2Froutes%2Ftest%2F%2Bpage.svelte,src%2Froutes%2F%2Bpage.svelte

1. Run `pnpm build && pnpm preview`
2. Navigate to `/test/` and refresh the page.

#### Expected
Redirect from `/test/` to `/test`.

#### Actual
404 not found.

### Logs

```Shell
Error: Not found: /test/
    at resolve (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3232:18)
    at resolve (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3099:34)
    at #options.hooks.handle (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3276:59)
    at respond (file://file:///home/projects/github-vabxnk-zdpsdn/.svelte-kit/output/server/index.js:3097:43)
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.2 => 1.0.2 
    @sveltejs/kit: ^1.3.8 => 1.3.8 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

### Additional Information

1. Netlify implements its own trailing slash redirect logic as the adapter has none and we can tell SvelteKit isn't handling it because it omits the `x-sveltekit-normalise` header in the redirect.
https://whimsical-croquembouche-bf1ae0.netlify.app/test/
2. `adapter-cloudflare` should allow sveltekit to handle it instead of the logic I implemented [here](https://github.com/sveltejs/kit/blob/089c405041b0267356281fc8ea5f19ecc331178b/packages/adapter-cloudflare/src/worker.js#L62).
3. `adapter-vercel` is unaffected because it uses static redirects from a vercel config file (`adapter-cloudflare` should do the same to bypass worker runs but that's for another day).
4. `adapter-node` currently never reaches `server.respond` because the handler before it doesn't differentiate between `about.html` and `about/index.html`.
5. Not sure which community adapters are affected by this.

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #8839. No tests as we don't really have a great place to put them

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/exports/vite/preview/index.js [hunk 1]
```diff
@@ -108,8 +108,31 @@ export async function preview(vite, vite_config, svelte_config) {
...
+					} else if (has_trailing_slash) {
+						if (is_file(filename.slice(0, -1) + '.html')) {
+							redirect = pathname.slice(0, -1);
+						}
+					} else if (is_file(filename + '/index.html')) {
+						redirect = pathname + '/';
+					}
+
+					if (redirect) {
+						res.writeHead(308, {
```
Comment (dummdidumm) [inline packages/kit/src/exports/vite/preview/index.js:128]: Should we make this a temporary redirect, since this is during preview and you might have other things on localhost which would result in confusing redirects later?

**Review by dummdidumm — APPROVED** [review]
