### PR TITLE
ensure correct case is used for static assets

### LINKED ISSUE #4931: Asset extension matching not consistent between DEV and PREVIEW
### Describe the bug

Preview build of sveltekit doesn't match asset paths the same way as dev build.

### Reproduction

Put let's say image.PNG inside of static then in index.svelte `` and let's run npm run dev, then run build and preview and the image won't be displayed anymore.

### Logs

_No response_

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 6.21 GB / 15.94 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (97.0.1072.76)
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40
    @sveltejs/kit: next => 1.0.0-next.328
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #4931

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/core/dev/plugin.js [hunk 1]
```diff
@@ -195,9 +195,15 @@ export async function create_plugin(config) {
 							const file = config.kit.files.assets + pathname;
 
 							if (fs.existsSync(file) && !fs.statSync(file).isDirectory()) {
-								req.url = encodeURI(pathname); // don't need query/hash
-								asset_server(req, res);
-								return;
+								const has_correct_case = fs
+									.readdirSync(path.dirname(file))
+									.includes(path.basename(file));
```
Comment (mrkishi) [inline packages/kit/src/core/dev/plugin.js:200]: How about using `realpath.native` instead?

```suggestion
								const has_correct_case = fs.realpathSync.native(file) === path.resolve(file);
```

File: packages/kit/test/apps/basics/test/test.js [hunk 2]
```diff
@@ -2570,6 +2570,11 @@ test.describe.parallel('Static files', () => {
 		const response = await request.get(path);
 		expect(response.status()).toBe(200);
 	});
+
+	test('Filenames are case-sensitive', async ({ request }) => {
+		let response = await request.get('/static.JSON');
```
Comment (mrkishi) [inline packages/kit/test/apps/basics/test/test.js:2575]:
```suggestion
		const response = await request.get('/static.JSON');
```

**Review by mrkishi — APPROVED** [review]

File: packages/kit/src/core/dev/plugin.js (hunk 1 above)
Comment (anarchodin) [reply packages/kit/src/core/dev/plugin.js]: I started getting unexpected 404s after updating SvelteKit today. As it turns out, if you have a symlinked subdirectory in `static`, realpath and resolve _don't_ give you the same result.

Monkey-patching the check to use the initial version stopped the 404s, since the directory _does_ indeed contain a file by that name. You might want to double-check this fix.

(As a detail, this was happening on Windows, but it seems like it should also bite POSIX systems.)

(Also, considering this is merged and resolved, I should probably ensure @mrkishi and @Rich-Harris get pinged about this. 😃)
