### PR TITLE
fix: prerender optional parameters as empty when `entries` contains `'*'`

### LINKED ISSUE #11133: Crawler doesn't discover `/` if there is an optional parameter at the base
### Describe the bug

The Crawler for prerendering does not discover the `/` path, if there is an optional Parameter at the base. 
This is a common scenario in multi-language pages. 

```
routes
|- layout.js //enable prerender
|- [[lang]]
    |- +page.svelte //Not found
```

I would expect `/` to get crawled, and further pages to be discovered from there.
The workaround is to add `/` to the entries in `svelte.config.js`

### Reproduction

https://github.com/LorisSigrist/sk-crawler-optional-param-at-base-reproduction

### Logs

```Shell
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /[[lang]]
```

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 101.14 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/bin/npm
    pnpm: 8.11.0 - /opt/homebrew/bin/pnpm
    bun: 0.8.1 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Chrome Canary: 121.0.6153.0
    Safari: 17.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/kit: ^1.27.4 => 1.27.6 
    svelte: ^4.2.7 => 4.2.7 
    vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by LorisSigrist**
Closes #11133 

Currently, any routes with parameters are only prerendered if they are discovered through crawling, or export `entries`. 
This makes sense for required parameters, since it's not possible to know which values they accept otherwise. 
For optional parameters, we do know that not passing a value _is_ valid. With this PR routes with optional parameters that are marked as prerenderable will be crawled with no value by default.

Examples:
- `/some-route/[[optionalParam]]/a` will be crawled with `/some-route/a`
- `/some-route/[[optionalParam]]/a/[[optionalParam2]]/b` will be crawled with `/some-route/a/b`

A common situation where this causes frustration is on multi-langauge pages with a `[[lang]]` parameter at the root. In that case `/` won't be crawled. It needs to be manually specified in the entries, which feels silly.  

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/core/postbuild/prerender.js [hunk 1]
```diff
@@ -429,8 +429,12 @@ async function prerender({ out, manifest_path, metadata, verbose, env }) {
 		if (entry === '*') {
 			for (const [id, prerender] of prerender_map) {
 				if (prerender) {
-					if (id.includes('[')) continue;
-					const path = `/${get_route_segments(id).join('/')}`;
+					//Remove optional parameters from the route
```
Comment (benmccann) [inline packages/kit/src/core/postbuild/prerender.js:432]:
```suggestion
					// remove optional parameters from the route
```

File: .changeset/good-jars-relax.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': patch
+---
+
+fix: Prerender optional parameters without value
```
Comment (benmccann) [inline .changeset/good-jars-relax.md:5]:
```suggestion
fix: prerender optional parameters as empty when `entries` contains `'*'`
```

**Comment by LorisSigrist** [comment]
Will do!

File: packages/kit/src/exports/public.d.ts [hunk 3]
```diff
@@ -498,7 +498,7 @@ export interface KitConfig {
 		 */
 		crawl?: boolean;
 		/**
-		 * An array of pages to prerender, or start crawling from (if `crawl: true`). The `*` string includes all non-dynamic routes (i.e. pages with no `[parameters]`, because SvelteKit doesn't know what value the parameters should have).
+		 * An array of pages to prerender, or start crawling from (if `crawl: true`). The `*` string includes all non-dynamic routes (i.e. pages with no `[parameters]`, because SvelteKit doesn't know what value the parameters should have), as well as routes with optional parameters which are included with no value.
```
Comment (benmccann) [inline packages/kit/src/exports/public.d.ts:501]: just shortening this up slightly
```suggestion
		 * An array of pages to prerender, or start crawling from (if `crawl: true`). The `*` string includes all routes containing no required `[parameters]`  with optional parameters included as being empty (since SvelteKit doesn't know what value any parameters should have).
```

**Review by benmccann — APPROVED** [review]
