### PR TITLE
fix: keep resolve relative to initial base during prerender

### LINKED ISSUE #14512: Crawling resolves to incorrect URL
### Describe the bug

```svelte
<script>
  import { resolve } from "$app/paths";
</script>

<!-- 
  [404] GET /lv1/lv1
  
  node:internal/event_target:1101
    process.nextTick(() => { throw err; });
                             ^
  Error: 404 /lv1/lv1 (linked from /lv1/lv2)
-->

<!-- Link works in vite dev -->
<a href="{resolve('/lv1')}">Hey</a>
```

### Reproduction

https://github.com/hyunbinseo/svelte-kit-14512

### Logs

```shell
pnpm build
```

```
[404] GET /lv1/lv1

node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /lv1/lv1 (linked from /lv1/lv2)
```

```shell
pnpm i @sveltejs/kit@2.42 && pnpm build
```

```
> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://svelte.dev/docs/kit/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
```

### System Info

```Shell
System:
  OS: Windows 11 10.0.26100
  CPU: (8) x64 Intel(R) Core(TM) Ultra 7 258V
  Memory: 5.24 GB / 31.48 GB
Binaries:
  Node: 24.8.0 - ~\AppData\Local\fnm_multishells\42720_1758590779869\node.EXE
  Yarn: 1.22.22 - ~\AppData\Local\fnm_multishells\42720_1758590779869\yarn.CMD
  npm: 11.6.0 - ~\AppData\Local\fnm_multishells\42720_1758590779869\npm.CMD
  pnpm: 10.17.1 - ~\AppData\Local\fnm_multishells\42720_1758590779869\pnpm.CMD
Browsers:
  Edge: Chromium (140.0.3485.54)
npmPackages:
  @sveltejs/adapter-auto: ^6.1.0 => 6.1.0
  @sveltejs/kit: ^2.43.1 => 2.43.1
  @sveltejs/vite-plugin-svelte: ^6.2.0 => 6.2.0
  svelte: ^5.39.4 => 5.39.4
  vite: ^7.1.7 => 7.1.7
```

### Severity

blocking an upgrade

### PR DESCRIPTION
**Pull request by LeeWxx**
Fixes #14512 

Fixed $app/paths.resolve so prerendered builds no longer duplicate paths.base, and added a regression test that verifies the helper emits the correct relative href.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/app/paths/internal/server.js [hunk 1]
```diff
@@ -5,6 +5,8 @@ export const relative = __SVELTEKIT_PATHS_RELATIVE__;
 
 const initial = { base, assets };
 
+export const initial_base = initial.base;
```
Comment (dummdidumm) [inline packages/kit/src/runtime/app/paths/internal/server.js:12]:
```suggestion
/**
 * `base` could be overridden during rendering to be relative;
 * this one's the original non-relative base path
 */
export const initial_base = initial.base;
```

File: packages/kit/src/runtime/app/paths/server.js [hunk 2]
```diff
@@ -16,7 +16,8 @@ export function resolve(id, params) {
 		const store = try_get_request_store();
 
 		if (store && !store.state.prerendering?.fallback) {
-			const segments = store.event.url.pathname.slice(base.length).split('/').slice(2);
+      const after_base = event.url.pathname.slice(initial_base.length);
```
Comment (dummdidumm) [inline packages/kit/src/runtime/app/paths/server.js]:
```suggestion
			const after_base = event.url.pathname.slice(initial_base.length);
```

File: packages/kit/src/runtime/app/paths/server.js [hunk 3]
```diff
@@ -16,7 +16,8 @@ export function resolve(id, params) {
 		const store = try_get_request_store();
 
 		if (store && !store.state.prerendering?.fallback) {
-			const segments = store.event.url.pathname.slice(base.length).split('/').slice(2);
+			const after_base = event.url.pathname.slice(initial_base.length);
```
Comment (dummdidumm) [inline packages/kit/src/runtime/app/paths/server.js]: oops
```suggestion
			const after_base = store.event.url.pathname.slice(initial_base.length);
```
