### PR TITLE
fix: make illegal server-only import errors actually useful

### LINKED ISSUE #14153: illegal server-only module errors are very bad
### Describe the bug

If a universal module/component imports server-only code...

```svelte
<!-- +page.svelte -->
<script>
  import { getRequestEvent } from '$app/server';
</script>
```

...you get this error at dev time:

Image

It's annoying that you don't see the import chain until `build`, and _maybe_ we could fix that. But when you _do_ build, you get this:

Image

There's so much going on here:

- it's the _same freaking error_, which still says 'try building your app' to get a better error message
- it appears twice — once with a `[vite-plugin-sveltekit-compile] [vite-plugin-sveltekit-virtual-modules]` prefix, once with only a `[vite-plugin-sveltekit-virtual-modules]` prefix. Huh?
- it prints the entire file path, instead of one that's relative to your project folder (and hence much more readable)
- it includes a useless noisy stack trace

Separately: if a dependency in `node_modules` illegally imports a server-only module, you don't find out until build time. Would be nice if there was a way to detect those a bit earlier, though IIUC Vite doesn't give us the necessary metadata. Something to worry about another time, I guess

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #14153. The one part I'm slightly nervous about is manipulating the errors that occur during the secondary build to avoid double-logging, though it's _probably_ okay?

This is a radical simplification from what we had before. It results in consistent errors between dev and prod (no more 'build the app to figure out the import chain'), more readable errors (better formatting, more concise message, no useless stack trace), co-locates code better, is more efficient (instead of walking the entire module graph from the universal entry points, it walks _up_ from a server-only module if/when one is found), and is a lot less code.

One very minor trade-off: it's no longer possible to differentiate between static and dynamic imports. I don't think this matters.

~~Not require ready to merge yet because FUCKING WINDOWS~~

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I actually think we can get the import chain in development too, by inspecting the dev server's module graph. Tinkering on that locally

File: packages/kit/src/exports/vite/utils.js [hunk 1]
```diff
@@ -155,4 +159,16 @@ export function normalize_id(id, lib, cwd) {
 	return posixify(id);
 }
 
+/**
+ * For times when you need to throw an error, but without
+ * displaying a useless stack trace (since the developer
+ * can't do anything useful with it)
+ * @param {string} message
```
Comment (teemingc) [inline packages/kit/src/exports/vite/utils.js:166]: Useful for getting the proceeding lines greyed out in the editor after using this method since it throws
```suggestion
 * @param {string} message
 * @returns {never}
```

File: packages/kit/test/apps/dev-only/test/test.js [hunk 2]
```diff
@@ -12,116 +12,69 @@ const __dirname = path.dirname(fileURLToPath(import.meta.url));
 test.describe.serial('Illegal imports', () => {
 	test.skip(({ javaScriptEnabled }) => !process.env.DEV || !javaScriptEnabled);
 
-	test('$env/dynamic/private is not statically importable from the client', async ({ page }) => {
+	test('$env/dynamic/private is not importable from the client', async ({ page }) => {
 		await page.goto('/illegal-imports/env/dynamic-private', {
-			wait_for_started: false
+			// wait_for_started: false
```
Comment (teemingc) [inline packages/kit/test/apps/dev-only/test/test.js]:
```suggestion
```
Probably need to remove the options object altogether if this option is commented out.

**Review by eltigerchino — APPROVED** [review]
LGTM. Might be good to also have a test for a transitive server import as I noticed that most of the tests are just a direct import.

File: packages/kit/src/exports/vite/index.js [hunk 3]
```diff
@@ -574,23 +545,89 @@ Tips:
...
+			// skip .server.js files outside the cwd or in node_modules, as the filename might not mean 'server-only module' in this context
+			const is_internal = id.startsWith(normalized_cwd) && !id.startsWith(normalized_node_modules);
+
+			const normalized = normalize_id(id, normalized_lib, normalized_cwd);
+
+			const is_server_only =
+				normalized === '$env/static/private' ||
+				normalized === '$env/dynamic/private' ||
+				normalized === '$app/server' ||
+				normalized.startsWith('$lib/server') ||
```
Comment (teemingc) [inline packages/kit/src/exports/vite/index.js:585]: I wonder if we can easily change this to only match `$lib/server/` directories or `$lib/server.*` files to fix https://github.com/sveltejs/kit/issues/14069 but I guess that can be its own PR after this one

File: packages/kit/src/exports/vite/utils.js (hunk 1 above)
Comment (Rich-Harris) [reply packages/kit/src/exports/vite/utils.js:166]: oops it should actually be returning, not throwing

File: packages/kit/src/exports/vite/utils.js [hunk 4]
```diff
@@ -155,4 +159,16 @@ export function normalize_id(id, lib, cwd) {
...
+ */
+export function stackless(message) {
+	const error = new Error(message);
+	error.stack = '';
+	throw error;
```
Comment (Rich-Harris) [inline packages/kit/src/exports/vite/utils.js]:
```suggestion
	return error;
```

File: packages/kit/test/apps/dev-only/test/test.js (hunk 2 above)
Comment (Rich-Harris) [reply packages/kit/test/apps/dev-only/test/test.js]: I'm actually not sure why it's commented out — if I remove all those options from this file tests start flaking. I'm just gonna uncomment it

```suggestion
			wait_for_started: false
```

File: packages/kit/src/exports/vite/index.js (hunk 3 above)
Comment (Rich-Harris) [reply packages/kit/src/exports/vite/index.js:585]: ah yeah this should really just add a trailing slash. We don't state anywhere that `$lib/server.ts` should be considered a server-only module — [just this](https://svelte.dev/docs/kit/server-only-modules#Your-modules):

> You can make your own modules server-only in two ways:
>
> - adding `.server` to the filename, e.g. `secrets.server.js`
> - placing them in `$lib/server`, e.g. `$lib/server/secrets.js`

Unfortunately we _do_ currently regard `$lib/server.ts` as server-only, so the simple fix would be a breaking change. I think we should fix that in SvelteKit 3 and warn on it in the meantime. Will do it as a separate PR

Comment (Rich-Harris) [reply packages/kit/src/exports/vite/index.js:585]: Actually I've changed my mind. If we think it's okay to fix #14069 in a patch release then the same is true of `$lib/server.ts`. Just gonna update `.startsWith('$lib/server')` to `.startsWith('$lib/server/')`
