### PR TITLE
fix: ensure remote form fields.set triggers reactivity

### LINKED ISSUE #14643: Programmatic preflight `validate()`
### Describe the bug

```svelte
<button
  type="button"
  onclick={() => {
    addId.fields.uuid.set(self.crypto.randomUUID());
    addId.validate();
  }}
>
  Generate
</button>
```

1. UUID is set then validated. But the validation input is still `123`
2. `form.fields.input.set()` hangs. Have to do multiple clicks for it to work
3. After submission, the validation result says the input is always `''`

https://github.com/user-attachments/assets/adcb11ac-76b2-4580-bf5c-70d65cc661b6

### Reproduction

- https://github.com/hyunbinseo/svelte-kit-template/tree/mre-kit-14643
- https://github.com/hyunbinseo/svelte-kit-template/commit/da5d8983a217474069c2ee1d82e35fe4f5531788

### Logs

```Shell

```

### System Info

```Shell
System:
  OS: Windows 11 10.0.26100
  CPU: (8) x64 Intel(R) Core(TM) Ultra 7 258V
  Memory: 6.02 GB / 31.48 GB
Binaries:
  Node: 24.9.0 - C:\Users\hyunb\AppData\Local\fnm_multishells\35956_1759867104840\node.EXE
  Yarn: 1.22.22 - C:\Users\hyunb\AppData\Local\fnm_multishells\35956_1759867104840\yarn.CMD
  npm: 11.6.0 - C:\Users\hyunb\AppData\Local\fnm_multishells\35956_1759867104840\npm.CMD
  pnpm: 10.18.1 - C:\Users\hyunb\AppData\Local\fnm_multishells\35956_1759867104840\pnpm.CMD
  Deno: 2.4.0 - C:\Users\hyunb\.deno\bin\deno.EXE
Browsers:
  Chrome: 141.0.7390.55
  Edge: Chromium (140.0.3485.54)
  Firefox: 143.0.4 - C:\Program Files\Mozilla Firefox\firefox.exe
npmPackages:
  @sveltejs/adapter-auto: ^6.1.1 => 6.1.1
  @sveltejs/kit: ^2.46.2 => 2.46.2
  @sveltejs/vite-plugin-svelte: ^6.2.1 => 6.2.1
  svelte: ^5.39.10 => 5.39.10
  vite: ^7.1.7 => 7.1.7
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### LINKED ISSUE #14650: `field.value()` doesn't reactively update after calling `field.set(...)`
### Describe the bug

When using the `form` remote function, calling `form.fields.field.set(...)` doesn't cause `form.fields.field.value()` to reactively return a new value.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-cfztyihe?file=src%2Froutes%2F%2Bpage.svelte

Press the button to call `field.set(...)` and see that the value isn't updated reactively unless we create a `$state` and set it ourselves.

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^6.0.0 => 6.1.1 
    @sveltejs/kit: ^2.22.0 => 2.46.2 
    @sveltejs/vite-plugin-svelte: ^6.0.0 => 6.2.1 
    svelte: ^5.25.0 => 5.39.10 
    vite: ^7.0.4 => 7.1.9
```

### Severity

annoyance

### Additional Information

I need to programatically set the value when using custom selects from shadcn-svelte. The value needs to be reflected in the trigger element text which is a button.

### PR DESCRIPTION
**Pull request by LeeWxx**
Fixes #14643
Fixes #14650 

Ensure remote form `fields.set()` triggers reactivity, so DOM and validation update immediately after programmatic changes.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/client/remote-functions/form.svelte.js [hunk 1]
```diff
@@ -537,8 +537,22 @@ export function form(id) {
 						(path, value) => {
 							if (path.length === 0) {
 								input = value;
+								update_all_versions();
+								return;
```
Comment (teemingc) [inline packages/kit/src/runtime/client/remote-functions/form.svelte.js]:
```suggestion
```

File: .changeset/easy-plants-remain.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': patch
+---
+
+fix: ensure remote form fields.set triggers reactivity
```
Comment (teemingc) [inline .changeset/easy-plants-remain.md]:
```suggestion
fix: ensure `form` remote functions' `fields.set` triggers reactivity
```

**Comment by alesvaupotic** [comment]
Much needed, thanks!
