### PR TITLE
fix: set headers when throwing redirect in handle

### LINKED ISSUE #8643: Cookies API doesn't work with redirect helper in hooks
### Describe the bug

I have an auth token stored in cookies, and use hooks to validate the token.
When the token expires, it should clear the cookie and then redirect to the login page.
But it does not, the redirect is successful but the cookies still exist.
```
if (token_is_expired(token) {
  event.cookies.delete('auth');  // doesn't work
  event.cookies.set('auth', '', { maxAge: 0 });  // doesn't work either
  throw redirect(303, '/login');
}
```

### Reproduction

https://github.com/peng-devs/sveltekit-hooks-issue
1. `npm run dev` and visit `http://localhost:5173/login`
2. Click the login button
3. You'll be automatically returned to the login page (to simulate the token expired situation).
4. If the cookie is deleted, you'll see the login button, otherwise you'll only see the text 'already logged in'.

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.69 GB / 7.72 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2
    @sveltejs/kit: ^1.0.0 => 1.2.2
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by s3812497**
fixes #8643

Adds headers and cookies to the response when using `throw redirect` in `handle` so that it behaves similarly to returning a new redirect `Response` in `handle`.

I'm sure there's a more elegant approach to this fix and the test, but I can't quite figure it out (this is my first time writing a test). Would appreciate any suggested changes.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/server/respond.js [hunk 1]
```diff
@@ -296,7 +300,15 @@ export async function respond(request, options, manifest, state) {
 			if (is_data_request) {
 				return redirect_json_response(e);
 			} else {
-				return redirect_response(e.status, e.location);
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/respond.js:299]: you can keep the `redirect_response` function and add the headers to it.
```js
const response = redirect_response(..);
add_cookies_to_headers(..);
return response;
```

**Review by dummdidumm — COMMENTED** [review]
Thank you! I think we need to apply the same logic to the case where it's a `__data.json` request (the if branch above the changed code)

File: packages/kit/src/runtime/server/respond.js (hunk 1 above)
Comment (s3812497) [reply packages/kit/src/runtime/server/respond.js:299]: This would only add the cookies to the response.
I wanted to do it this way originally but wasn't sure if only cookies should be added or to include the headers from `setHeaders()` too. 

I also didn't want a `location` header from `setHeaders` to overwrite the thrown redirect location.

Maybe I can extend the `redirect_response()` helper to optionally accept a `headers` option?
I noticed there were similar redirect responses in the file not using the helper just so that it could add other headers to it.

**Review by dummdidumm — APPROVED** [review]

**Comment by dummdidumm** [comment]
Thank you!

**Comment by s3812497** [comment]
Thanks for the guidance!
Note that the current implementation only appends the `set-cookie` header and not other headers. But I forgot to change that in the changeset notes. My bad
