### PR TITLE
fix: remove unnecessary path validation which breaks fetch with custom path base

### LINKED ISSUE #11078: fetch() does not work properly on the server when base path is set
### Describe the bug

When using sveltekit on the same host as an external api, fetching like this in load functions works -
(using sveltekit's fetch)
`fetch('/products/...')`
that is, when in svelte.config.js paths.base is not set or set to ''. 

If however the base path is set to something other than '', all server side requests (in load functions) to an 'external' path fail, making it impossible to ssr pages with calls to e.g. `/api/...` from `/base/ `. 

### Reproduction

https://github.com/thet0ast3r/kit-fetch-bug

Here is a minimal example.
Please note that this repo proxies requests to /products to dummyjson, to simulate an external api that has the same domain. 

run `npm run dev`

click on 'navigate to someroute' 
click on 'navigate to home/base'
reload home '/test' to prompt ssr

in svelte.config.js, change base to '', and repeat the last 3 steps. 
Notice how ssr now works correctly.

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 56.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/kit: ^1.27.4 => 1.27.6 
    svelte: ^4.0.5 => 4.2.5 
    vite: ^4.4.2 => 4.5.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by goulinkh**
closes #11078

When having a custom base path:
```js
{
  kit: {
  	paths: {
  		base: '/ui'
  	}
  }
}
```

And making a request to a different server hosted on the same domain, `+layout.server.ts`:
```ts
export const load: LayoutServerLoad = async ({ fetch }) => {
  const workingResponse = await fetch('/ui/api'); // works if api is defined in sveltekit
  const failingResponse = await fetch('/profile'); // returns 404, instead of making request and providing cookies
}
```

Making a request to the same origin but to a different server not with the configured `paths.base`, currently doesn't work but this should be allowed and possible as they share the same domain name.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by PatrickG** [comment]
I don't think this is the correct fix.
The request shouldn't even be handled by the `respond` function.
It must be fixed somewhere in the `fetch` function in `src/runtime/server/fetch.js`

Maybe changing https://github.com/sveltejs/kit/blob/8a59a0d4e7ef59b7c1a88a9e628c86cace21d98e/packages/kit/src/runtime/server/fetch.js#L58 to something like
```js
if (url.origin !== event.url.origin || (paths.base && !decodeURIComponent(url.pathname).startsWith(paths.base))) {
```

**Comment by goulinkh** [comment]
Hi @PatrickG, apologies for the quick fix attempt, I lack knowledge in sveltekit codebase but tried to file the fix.

Your suggestion makes sense, I've applied it and it seems to work locally.

Cheers!

File: packages/kit/src/runtime/server/fetch.js [hunk 1]
```diff
@@ -55,7 +55,10 @@ export function create_fetch({ event, options, manifest, state, get_cookie_heade
 					request.headers.delete('origin');
 				}
 
-				if (url.origin !== event.url.origin) {
+				if (
+					url.origin !== event.url.origin ||
+					(paths.base && !decodeURIComponent(url.pathname).startsWith(paths.base))
+				) {
```
Comment (PatrickG) [inline packages/kit/src/runtime/server/fetch.js:63]:
```suggestion
				const decoded = decodeURIComponent(url.pathname);
				if (
					url.origin !== event.url.origin ||
					(paths.base && !decoded.startsWith(paths.base))
				) {
```

Comment (PatrickG) [reply packages/kit/src/runtime/server/fetch.js:63]: You could move the `decoded` declaration from line 83 to here.

Comment (goulinkh) [reply packages/kit/src/runtime/server/fetch.js:63]: Done, I've also added a `/` at the end of `paths.base` check otherwise, this will be considered false positive in the scenario:
```
base: /ui

request: /ui/test OK
request: /uitest KO
```

Only the second case should be considered external fetch.

File: packages/kit/src/runtime/server/fetch.js [hunk 2]
```diff
@@ -55,7 +55,11 @@ export function create_fetch({ event, options, manifest, state, get_cookie_heade
 					request.headers.delete('origin');
 				}
 
-				if (url.origin !== event.url.origin) {
+				const decoded = decodeURIComponent(url.pathname);
+				if (
+					url.origin !== event.url.origin ||
+					(paths.base && !decoded.startsWith(`${paths.base}/`))
```
[the remark this answers is not in the document]
Comment (PatrickG) [reply packages/kit/src/runtime/server/fetch.js]: I think to take the root route (without a trailing slash) into account, it would need to be
```suggestion
					(paths.base && decoded !== paths.base && !decoded.startsWith(`${paths.base}/`))
```

But I'm not sure if it is even possible to navigate to the root route without a trailing slash.

[the remark this answers is not in the document]
Comment (goulinkh) [reply packages/kit/src/runtime/server/fetch.js]: I have tried the latest sveltekit version, for `paths.base` set to `/ui`:
1. `fetch`: works with and without trailing slash:
   - `fetch('/')` internally resolved to `http://localhost/ui`
   - `fetch('')` is relative, it calls the current context's URL
2. The design is confusing because it's unclear how to format an external request to the host root (`http://localhost/`)

[the remark this answers is not in the document]
Comment (goulinkh) [reply packages/kit/src/runtime/server/fetch.js]: I have added some cases in `packages/kit/test/apps/options`, at:
- http://localhost:5173/path-base/fetch/link-root/
- http://localhost:5173/path-base/fetch/link-outside-base/

I ran the project with the following command: `pnpx vite dev -c ./vite.custom.config.js`.

[the remark this answers is not in the document]
Comment (goulinkh) [reply packages/kit/src/runtime/server/fetch.js]: I have figured this out, so `fetch('/')` redirects in dev mode to `/ui` and in production it returns a `404`.
Which clarifies point 2,  in production `fetch('/')` will make request to the external host `http://localhost/` and if you want to request root of sveltekit it should be `fetch('/ui')`.

File: packages/kit/test/apps/dev-only/src/routes/request-abort/+page.svelte [hunk 3]
```diff
@@ -11,7 +11,7 @@
 			fetch('/request-abort', { headers: { accept: 'application/json' } }).then(
 				async (r) => (result = await r.json())
 			);
-		}, 100);
+		}, 50);
```
Comment (teemingc) [inline packages/kit/test/apps/dev-only/src/routes/request-abort/+page.svelte:14]: Why was this reduced?

File: .changeset/honest-cobras-jog.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': major
```
Comment (teemingc) [inline .changeset/honest-cobras-jog.md]:
```suggestion
'@sveltejs/kit': patch
```
It should only be major for a breaking change (of a previously valid behaviour?). However, I don't think anyone would purposely try to have the load fetch trigger the SvelteKit server response if it's requesting an entirely different path

File: packages/kit/test/apps/options/test/paths-assets.test.js [hunk 5]
```diff
@@ -77,6 +77,42 @@ test.describe('base path', () => {
 		expect(page.url()).toBe(`${baseURL}/path-base/resolve-route/resolved/`);
 		expect(await page.textContent('h2')).toBe('resolved');
 	});
+
+	test('fetch outside base path succeeds', async ({ page, baseURL }) => {
+		await page.goto('/path-base/fetch/link-outside-base/');
+		expect(await page.locator('[data-testid="fetch-url"]').textContent()).toContain(
+			`${baseURL}/not-base-path/`
+		);
+		expect(await page.locator('[data-testid="fetch-response"]').textContent()).toContain(
```
Comment (teemingc) [inline packages/kit/test/apps/options/test/paths-assets.test.js]: Passing a locator and awaiting the `expect` is the recommended Playwright API
```suggestion
		await expect(page.locator('[data-testid="fetch-url"]')).toHaveText(
			`${baseURL}/not-base-path/`
		);
		await expect(page.locator('[data-testid="fetch-response"]')).toHaveText(
```

File: packages/kit/test/apps/options/test/paths-assets.test.js [hunk 6]
```diff
@@ -77,6 +77,42 @@ test.describe('base path', () => {
...
+		expect(await page.locator('[data-testid="fetch2-response"]').textContent()).toBe('relative');
+
+		// fetch to root with custom base path with trailing slash
+		expect(await page.locator('[data-testid="fetch3-url"]').textContent()).toBeFalsy();
+		expect(await page.locator('[data-testid="fetch3-response"]').textContent()).toBe('root');
+
+		// fetch to root with custom base path without trailing slash
+		expect(await page.locator('[data-testid="fetch4-url"]').textContent()).toBeFalsy();
+		expect(await page.locator('[data-testid="fetch4-redirect"]').textContent()).toBe('/path-base/');
+	});
```
Comment (teemingc) [inline packages/kit/test/apps/options/test/paths-assets.test.js]: I'm not sure if we need this test. It doesn't help validate that the non-base path URL is fetchable. Does this test fail before the fix is applied?

File: packages/kit/test/apps/dev-only/src/routes/request-abort/+page.svelte (hunk 3 above)
Comment (goulinkh) [reply packages/kit/test/apps/dev-only/src/routes/request-abort/+page.svelte:14]: The test was flaky, it was failing randomly in the CI and locally, reducing the abort signal timing helped.

Should I revert this change?

File: packages/kit/test/apps/options/test/paths-assets.test.js (hunk 6 above)
Comment (goulinkh) [reply packages/kit/test/apps/options/test/paths-assets.test.js]: no it was working before as well, I will remove the base path URL fetches 👍

File: packages/kit/test/apps/dev-only/src/routes/request-abort/+page.svelte (hunk 3 above)
Comment (teemingc) [reply packages/kit/test/apps/dev-only/src/routes/request-abort/+page.svelte:14]: Oh that's interesting. I thought increasing it would reduce the flakiness but apparently not. Should be fine to keep this change then.

File: packages/kit/test/apps/options/test/paths-assets.test.js [hunk 7]
```diff
@@ -77,6 +77,32 @@ test.describe('base path', () => {
 		expect(page.url()).toBe(`${baseURL}/path-base/resolve-route/resolved/`);
 		expect(await page.textContent('h2')).toBe('resolved');
 	});
+
+	test('fetch outside base path succeeds', async ({ page, baseURL }) => {
```
Comment (teemingc) [inline packages/kit/test/apps/options/test/paths-assets.test.js]:
```suggestion
	test('server load fetch without base path does not invoke the server', async ({ page, baseURL }) => {
```

File: packages/kit/test/apps/options/test/paths-assets.test.js [hunk 8]
```diff
@@ -77,6 +77,32 @@ test.describe('base path', () => {
...
+		await page.goto('/path-base/fetch/link-outside-base/');
+		await expect(page.locator('[data-testid="fetch-url"]')).toHaveText(`${baseURL}/not-base-path/`);
+		await expect(page.locator('[data-testid="fetch-response"]')).toContainText(
+			'did you mean to visit'
+		);
+	});
+
+	test('fetch to root succeeds', async ({ page, baseURL }) => {
```
Comment (teemingc) [inline packages/kit/test/apps/options/test/paths-assets.test.js]:
```suggestion
	test('server load fetch to root does not invoke the server', async ({ page, baseURL }) => {
```

File: packages/kit/test/apps/options/test/paths-assets.test.js [hunk 9]
```diff
@@ -77,6 +77,32 @@ test.describe('base path', () => {
...
+		// fetch to root with trailing slash
+		await expect(page.locator('[data-testid="fetch1-url"]')).toHaveText(`${baseURL}/`);
+		const fetch1Response = await page.locator('[data-testid="fetch1-response"]').textContent();
+		const fetch1Redirect = await page.locator('[data-testid="fetch1-redirect"]').textContent();
+		expect(
+			// production
+			fetch1Response?.includes('did you mean to visit') ||
+				// dev
+				fetch1Redirect === '/path-base'
+		).toBe(true);
```
Comment (teemingc) [inline packages/kit/test/apps/options/test/paths-assets.test.js]:
```suggestion
		if (process.env.DEV) {
			await expect(page.locator('[data-testid="fetch1-redirect"]').toHaveText('/path-base');
		} else {
			await expect(page.locator('[data-testid="fetch1-response"]').toHaveText('did you mean to visit');
		}
```
Might be a little cleaner to explicitly check if we're running for dev/prod

Comment (goulinkh) [reply packages/kit/test/apps/options/test/paths-assets.test.js]: I agree, I will add the check.
