### PR TITLE
Set correct `$page.status` when using `enhance` and result is of type `'error'`

### LINKED ISSUE #8072: $page.status 500 when using use:enahnce
### Describe the bug

use:enhance always returns $page.status 500 after throwing whatever error() in page endpoint

### Reproduction

https://github.com/KarolusD/sveltekit-error-status/tree/main/src/routes

page endpoint:
```
export const actions: Actions = {
	default: () => {
		throw error(400, { code: 400, message: 'hey' });
	}
};
```

results in throwing 500 page status in +error.svelte page
```
<h1>{$page.status}</h1>
<p>{$page?.error?.message}</p>
<p>{$page?.error?.code}</p>
```
image

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 338.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90
    @sveltejs/kit: next => 1.0.0-next.581
    svelte: ^3.54.0 => 3.54.0
    vite: ^4.0.0 => 4.0.0
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by PatrickG**
Fixes #8072 

I wanted to create a `+error.svelte` in `test/apps/basic/src/routes/actions/enhance` for this test, but somehow it is not mounted in the "js"-test. I also tried to put it in `test/apps/basic/src/routes/actions`, that also didn't work.
Furthermore, I've tried to debug with playwright debug, but couldn't find any reason why it does not work.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -1387,7 +1387,7 @@ export function create_client({ target, base }) {
 						url,
 						params: current.params,
 						branch: branch.slice(0, error_load.idx).concat(error_load.node),
-						status: 500, // TODO might not be 500?
+						status: result.status || 500,
```
Comment (pilcrowOnPaper) [inline packages/kit/src/runtime/client/client.js:1390]: I'm not sure if anyone would use status 0 but a nullish coalescing operator might be a better option?

**Review by dummdidumm — APPROVED** [review]
Thank you! (type check error is unrelated)
