### PR TITLE
Vercel externals

### LINKED ISSUE #3588: Vercel Build Fails as Can't Set EsBuild Externals
### Describe the bug

My vercel build has been failing since the removal of the esBuild config options in @sveltejs/adapter-vercel.

I've continued developing using the following package versions (last working):
```
"@sveltejs/adapter-vercel": "1.0.0-next.32",
"@sveltejs/kit": "1.0.0-next.206",
```

However, that's definitely less than ideal as I'm continuing to build around an outdated API for both @sveltejs/kit & @sveltejs/adapter-vercel.

The dependency causing my build issues (@napi-rs/*) is a package required indirectly as a dependency of a package in a shared monorepo used in the frontend. (Backend defines db schema, controllers, autogen type definitions, etc. that are used both in the frontend and for writing real time data scraped from various sources to the db, hence the monorepo greatly streamlines the dev process).

I'd previously built the frontend project successfully using both Vite resolve.alias and via installing the pnpm symlinked version of the built package as a dependency during the build process (setting pnpm to shamefully-hoist when building on Vercel) using the following esBuild config options:
```
adapter({
  esbuild(defaultOptions) {
    return {
      ...defaultOptions,
      plugins: [],
      external: ['@napi-rs/*']
    };
  }
})
```

Following the breaking API changes, I've tested with updated versions of @sveltejs/kit & @sveltejs/adapter-vercel using at least the following Vite config settings (both individually and in varying combinations), but to no avail. 

Vite Config Options Tested:
```
  vite.ssr.noExternal: ['@napi-rs/*']
  ssr.external:  ['@napi-rs/*']
  vite.optimizeDeps.exclude: ['@napi-rs/*']
```
(I think I'd tried setting it as a rollup external as well using Vite config options, but that also failed to resolve the issue)

Build always fails with the following error:
```
error: No loader is configured for ".node" files
```

Any solutions for getting this build to work with the latest versions of @sveltejs/kit and @sveltejs/adapter-vercel?

### Reproduction

I'm more than happy to setup a minimal reproduction of the issue if necessary, but iirc this is something @Rich-Harris is aware of per the checklist in [PR #2931](https://github.com/sveltejs/kit/pull/2931#issue-1064802827).

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 138.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-vercel: 1.0.0-next.32 => 1.0.0-next.32 
    @sveltejs/kit: 1.0.0-next.206 => 1.0.0-next.206 
    svelte: ^3.46.2 => 3.46.2
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #3588, by adding an `external` option that gets passed to esbuild 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by bluwy — APPROVED** [review]

File: packages/adapter-vercel/index.d.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
 import { Adapter } from '@sveltejs/kit';
 
-declare function plugin(): Adapter;
+declare function plugin({ external }?: { external?: string[] }): Adapter;
```
Comment (bluwy) [inline packages/adapter-vercel/index.d.ts:3]: I wonder if it's worth having the param as `plugin(options?: Options)` instead to simplify the type signature for intellisense, and conforms with the docs wording of "You can pass an `options` argument". But this PR is fine with the current type too.

Comment (Rich-Harris) [reply packages/adapter-vercel/index.d.ts]: make sense, i made that change
