### PR TITLE
fix: prevent code execution order issues around SvelteKit's `env` modules

### LINKED ISSUE #14590: ReferenceError: Cannot access 'private_env' before initialization when importing `$env/dynamic/private`
### Describe the bug

As of `@sveltejs/kit` `2.43.7`, accessing the `env` object from `$env/dynamic/private` seems to cause a `ReferenceError: Cannot access 'private_env' before initialization` during the build process's analysis phase.

Downgrading to `2.43.6` fixes this.

I believe this is because of #14571 

The error occurs in this file:
`src/lib/server/db/index.ts`:
```ts
import { env } from "$env/dynamic/private";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";

const { DATABASE_URL } = env;

const client = postgres(DATABASE_URL);

export const db = drizzle(client, { schema });
export type DB = typeof db;
```

Error trace:
```
node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: Cannot access 'private_env' before initialization
    at file:///website/.svelte-kit/output/server/chunks/chunk-2.js:5:26
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async analyse (file:///website/node_modules/.pnpm/@sveltejs+kit@2.43.7_@sveltejs+vite-plugin-svelte@6.2.1_svelte@5.39.8_vite@7.1.8_@types_7425f1e03e58a0dfb323af8897124f46/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:51:19)
    at async MessagePort.<anonymous> (file:////website/node_modules/.pnpm/@sveltejs+kit@2.43.7_@sveltejs+vite-plugin-svelte@6.2.1_svelte@5.39.8_vite@7.1.8_@types_7425f1e03e58a0dfb323af8897124f46/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)
```

### Reproduction

https://github.com/DarthGigi/sveltekit-mvce-env-vars

Please note that the exact error is hard to reproduce as I believe it's a chunking issue as stated above.

Wether you get `Error: DATABASE_URL is not set` or the `private_env` error, both are the cause of the same problem.

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: macOS 26.0.1
    CPU: (14) arm64 Apple M4 Pro
    Memory: 1.33 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - /opt/homebrew/opt/node@22/bin/node
    npm: 10.9.3 - /opt/homebrew/opt/node@22/bin/npm
    pnpm: 10.17.1 - ~/Library/pnpm/pnpm
    bun: 1.2.23 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 141.1.83.108
    Chrome: 141.0.7390.55
    Safari: 26.0.1
  npmPackages:
    @sveltejs/adapter-node: ^5.3.3 => 5.3.3 
    @sveltejs/enhanced-img: ^0.8.3 => 0.8.3 
    @sveltejs/kit: ^2.43.7 => 2.43.7 
    @sveltejs/vite-plugin-svelte: ^6.2.1 => 6.2.1 
    svelte: ^5.39.8 => 5.39.8 
    vite: ^7.1.8 => 7.1.8
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
With #14571 we hoped to have solved the chunk/code execution order issues, but they snuck back in.

The problem, it turns out (read https://rollupjs.org/configuration-options/#output-manualchunks very carefully), is that dependencies of a manual chunk might get pulled into that manual chunk, too. If the dependency happens to be our env module, this can cause issues since the module might eagerly access the env.

Luckily Rollup has recently solved this via a dedicated option (that will be the default in version 5 and is hence deprecated right away) named `onlyExplicitManualChunks` (https://github.com/rollup/rollup/pull/6087). This solves our problems around chunk ordering. For users not on the latest version yet we do a best-effort fallback by extracting env into its own chunk. This should solve most issues people encounter but the general problem can still occur, which is only fixed with the new option (hence we warn if the rollup version is not up to date).

Fixes #14590

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by Rich-Harris — APPROVED** [review]
worth a try!

File: packages/kit/src/exports/vite/index.js [hunk 1]
```diff
@@ -707,6 +728,11 @@ async function kit({ svelte_config }) {
 					}
 				}
 			};
+
+			if (!is_outdated_rollup) {
+				// @ts-expect-error only exists in more recent Rollup versions https://rollupjs.org/configuration-options/#output-onlyexplicitmanualchunks
+				config.build.rollupOptions.onlyExplicitManualChunks = true;
```
Comment (am283721) [inline packages/kit/src/exports/vite/index.js:734]: Should this be `config.build.rollupOptions.output.onlyExplicitManualChunks = true;` ?

Comment (am283721) [reply packages/kit/src/exports/vite/index.js:734]: For reference, building a project produces the following warning and then continues to produce the `env` errror: `Unknown input options: onlyExplicitManualChunks`

**Comment by vipero07** [comment]
While this fixes the env bug, this seems to cause a circular dependency now, on both the latest rollup, and rolldown. What I'm seeing (and I'm not sure I can make a repro just because the library is large) is the generated `internal.js` is importing a `remote-12p15ba` which is importing `remote-1m580o4` which is importing `remote-12p15ba`. I'm trying to figure out how to reproduce.

I do think this is probably an extremely unlikely build for an app though. For reasons I don't want to get into, there is data in two separate databases (both being accessed by drizzle) and the svelte-kit backend is essentially zippering the two together.

**Comment by dummdidumm** [comment]
if files import each other could it be that the circular dependency also exist in the original source? I'm having trouble understanding how else Rollup would order them that way, since no dependencies will be inlined with the strict setting
