### PR TITLE
comment out empty interfaces

### LINKED ISSUE #3839: "An empty interface is equivalent to `{}`" lint error on new empty project
### Describe the bug

The SvelteKit demo app application with TypeScript enabled fails the `npm run lint` phase:
```
$ npm run format
...
$ npm run lint

> my-app@0.0.1 lint
> prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .

Checking formatting...
All matched files use Prettier code style!

/home/ufo/workspaces/temp/my-app/src/app.d.ts
  10:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface
  12:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface
  14:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface

/home/ufo/workspaces/temp/my-app/src/lib/form.ts
  68:15  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 4 problems (3 errors, 1 warning)
```

### Reproduction

- Create a new project from scratch with: `npm init svelte@next my-app`
- Select "SvelteKit demo app", Typescript `yes`, ESLint `yes`, Prettier `yes`
- run `npm run format`
- run `npm run lint`

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 6.41 GB / 31.31 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/Programs/node/bin/node
    Yarn: 1.22.17 - ~/Programs/node/bin/yarn
    npm: 8.1.2 - ~/Programs/node/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Chromium: 98.0.4758.80
    Firefox: 96.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.265 
    svelte: ^3.46.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ignatiusmb**
Following TS approach when generating a `tsconfig.json`, it starts out with all the options commented out with some brief description besides and above it. Since this is just an interface, having a link that points to the docs that explains everything should be enough. Having some brief descriptions would be redundant with the docs and may lead to out-of-sync details later on.

Fixes #3839 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/create-svelte/templates/skeleton/src/app.d.ts [hunk 1]
```diff
@@ -3,11 +3,11 @@
...
-	interface Session {}
-
-	interface Stuff {}
+	// interface Locals {}
+	//
+	// interface Platform {}
+	//
+	// interface Session {}
+	//
+	// interface Stuff {}
```
Comment (Rich-Harris) [inline packages/create-svelte/templates/skeleton/src/app.d.ts:12]:
```suggestion
	// interface Locals {}

	// interface Platform {}

	// interface Session {}

	// interface Stuff {}
```

**Review by Rich-Harris — APPROVED** [review]

**Comment by ignatiusmb** [comment]
Ah @Rich-Harris, I probably should've commented earlier on that additional `//`. I committed it separately in 9d94d44 because it would collapse itself since it's become an empty namespace, and forcing a space between would fail on lint.
