### PR TITLE
fix: input name overriding form method and action checks

### LINKED ISSUE #8467: `use:enhance` breaks HMR and routing in dev with `<input name="method" />`
### Describe the bug

Creating a form with and input with the name of "method" breaks both hot module reloading and routing in development mode. The pages build and run just fine on preview, but you get this message in the developer's console and navigating to and from this page freezes navigation (again only in development mode). It seems to stem from [these lines](https://github.com/sveltejs/kit/blob/9c01c32ef72bbed630fadcb8283f8f8533ced5e1/packages/kit/src/runtime/app/forms.js#L28-L31), where it checks form.method

 
Image of Issue

### Reproduction

https://github.com/awenzel5/sveltekit-enhance-method

### Logs

```
forms.js?v=80aa9393:30 Uncaught (in promise) Error: use:enhance can only be used on <form> fields with method="POST"
    at enhance (forms.js?v=80aa9393:30:9)
    at mount (+page.svelte? [sm]:8:41)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=80aa9393:291:24)
    at mount_component (index.mjs:1949:26)
    at Object.update [as p] (root.svelte? [sm]:41:39)
    at update_slot_base (index.mjs:100:14)
    at Object.update [as p] (layout.svelte?v=80aa9393:40:6)
    at update (index.mjs:1209:36)
    at flush (index.mjs:1169:17)
```
### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 21.68 GB / 24.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.11 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by s3812497**
fixes #8467

Replaces `form.method` with `form.getAttribute('method')` to avoid collisions with `<input name="method">` in the same form.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by Conduitry — CHANGES_REQUESTED** [review]
`form.getAttribute('method')` will not normalize the method name like `form.method` will. If someone has `method="POST"`, the code here will not catch that. I don't know whether that would just be a matter of lowercasing the attribute, or stripping whitespace, or what.

Separately, this would (I think) also be susceptible to the extremely contrived situation of an input element name `getAttribute`. Similar to #7599, we should probably be using `HTMLFormData.prototype` here.

**Comment by s3812497** [comment]
> `form.getAttribute('method')` will not normalize the method name like `form.method` will. If someone has `method="POST"`, the code here will not catch that. I don't know whether that would just be a matter of lowercasing the attribute, or stripping whitespace, or what.

Good catch. Just found that out myself while trying to get the tests to pass.

> Separately, this would (I think) also be susceptible to the extremely contrived situation of an input element name `getAttribute`. Similar to #7599, we should probably be using `HTMLFormData.prototype` here.

I've tested and it does seem to correctly ignore input elements named "method". But I'll change it anyways for consistency

**Comment by s3812497** [comment]
> `form.getAttribute('method')` will not normalize the method name like `form.method` will. If someone has `method="POST"`, the code here will not catch that. I don't know whether that would just be a matter of lowercasing the attribute, or stripping whitespace, or what.

Hopefully fixed this issue. I created a helper method to replicate `form.method` more consistently. Any invalid `method` attribute value such as `method="post "` or `method="abc"`, etc. will default to `get`.

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -1459,12 +1459,15 @@ export function create_client({ target, base }) {
...
+				const method =
+					submitter?.formMethod ||
+					/** @type {HTMLFormElement} */ (HTMLFormElement.prototype.cloneNode.call(form)).method;
 
 				if (method !== 'get') return;
 
 				const url = new URL(
-					(submitter?.hasAttribute('formaction') && submitter?.formAction) || form.action
+					(submitter?.hasAttribute('formaction') && submitter?.formAction) ||
+						/** @type {HTMLFormElement} */ (HTMLFormElement.prototype.cloneNode.call(form)).action
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/client.js:1470]: I don't think we need these changes, they can be reverted. `form` is already a cloned node.

**Review by dummdidumm — CHANGES_REQUESTED** [review]

File: packages/kit/src/runtime/client/client.js (hunk 1 above)
Comment (s3812497) [reply packages/kit/src/runtime/client/client.js:1470]: Whoops, you're right! Didn't notice that the form has already been cloned. That's negligence on my part. I thought to change all `form.method` and `form.action` references before just because of the possible override that happens without cloning. Changed it.

**Review by dummdidumm — APPROVED** [review]
Thank you!

**Review by Rich-Harris — APPROVED** [review]
