### PR TITLE
fix: add `Content-Type` header for `POST` requests made by `enhance`

### LINKED ISSUE #1936: Respect the form `enctype` in progressive form enhancement example
### Describe the problem

The form enhancement that ships in the demo ignores the `form[enctype]` and always posts the data as a multi-part form using `FormData`.

While the `<form>` elements in the todos component do not explicitly define the `enctype`, they inherit [the default value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-enctype) of `application/x-www-form-urlencoded`.

In other words, the behaviour differs depending on the context:

| Context | enctype | example |
| --- | --- | --- |
| JS disabled | `application/x-www-form-urlencoded` | text=Buy%20some%20milk |
| JS enabled | `multipart/form-data` |  `------WebKitFormBoundaryVXPDCeRyJsYB7s4v\nContent-Disposition: form-data; name="text"\n\nbuy some milk\n------WebKitFormBoundaryVXPDCeRyJsYB7s4v--`|

I think it would be preferable for the JS version to mirror the behaviour of native HTML form. Especially if this ends up becoming core functionality in sveltekit.

### Describe the proposed solution

Modify the enhance action so that it mirrors browser behaviour.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-enctype), `enctype` can be set on the form itself, but it can also be overridden by a `formenctype` on the submit button itself. The submit button is accessible on the [SubmitEvent](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter)

For example:
```diff
-        const body = new FormData(form);
+        const formData = new FormData(form);
+ 	     const enctype = event.submitter.formEnctype || form.enctype;
+        const body = (enctype === 'multipart/form-data')
+			? formData
+			: new URLSearchParams(formData);
```

### Notes
* `URLSearchParams` is [not available in IE](https://caniuse.com/?search=URLSearchParams)

### Alternatives considered

Documentation/comments so that developers are not caught off-guard.

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by allozaur**
This PR introduces passing the `<form>`'s `enctype` value or `formSubmitter`'s `formenctype` value to `Content-Type` header for `POST` request made when executing the `use:enhance` function and a default[^1] value of `application/x-www-form-urlencoded` when the `<form>` element doesn't have the `enctype` attribute specified or has an invalid value[^2] provided.

When the `enctype` or `formenctype` is set to `multipart/form` then we don't provide the `Content-Type` header for `fetch` request

Close #1936

[^1]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype
[^2]: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-attributes

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test:kit` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/version.js
Comment (eltigerchino) [inline packages/kit/src/version.js:1]: A release is usually cut separately from the PR. I think you can undo the changes to this file and the removal of the other changesets.

File: packages/kit/CHANGELOG.md [hunk 1]
```diff
@@ -1,5 +1,11 @@
 # @sveltejs/kit
 
+## 2.5.8
+
+### Patch Changes
+
+- feat: handle `enctype` and `formenctype` properties for enhanced forms
```
Comment (eltigerchino) [inline packages/kit/CHANGELOG.md:7]:
```suggestion
- fix: respect the form `enctype` and button `formenctype` attributes for enhanced forms
```

**Comment by eltigerchino** [comment]
Might want to also check why the ubuntu chromium tests are failing.

File: packages/kit/src/version.js
Comment (allozaur) [reply packages/kit/src/version.js:1]: got it!

File: packages/kit/CHANGELOG.md (hunk 1 above)
Comment (allozaur) [reply packages/kit/CHANGELOG.md]: Okay, although i am not sure how i should add this to changelog after i reverted the changes accordingly to [your comment](https://github.com/sveltejs/kit/pull/12198#discussion_r1596661619). Any recommendation?

Comment (eltigerchino) [reply packages/kit/CHANGELOG.md]: If you run `pnpm changeset` you should see a list of projects to select. Press `space` to select the `@sveltejs/kit` then `enter` to proceed to the next step. Next, you will be prompted if you would like to include it in a major bump, press `enter` to skip. Similarly for the minor bump prompt. Finally, you will reach a patch bump prompt. You can enter a summary of your change there "fix: ...". Completing this process creates a markdown file in the `.changeset` folder which will be included in the changelog for the next release.

Comment (allozaur) [reply packages/kit/CHANGELOG.md]: i've added a changelog entry using `pnpm changelog` according to your instructions ;)

**Comment by allozaur** [comment]
@eltigerchino i've fixed up the tests for `use:enhance` and now i've got them all working :) i think that this PR is ready for reviewing and then adding it as a part of the next release ;)

File: packages/kit/src/runtime/app/forms.js [hunk 2]
```diff
@@ -161,14 +165,29 @@ export function enhance(form_element, submit = () => {}) {
...
+			);
+
+			const headers = {
+				accept: 'application/json',
+				'Content-Type': is_valid_enctype ? enctype : 'application/x-www-form-urlencoded',
+				'x-sveltekit-action': 'true'
+			};
+
+			// @ts-expect-error
+			const body = enctype === 'multipart/form-data' ? form_data : new URLSearchParams(form_data);
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/forms.js:179]: Why do we set the body to an instance of URLSearchParams from the form data?

File: packages/kit/src/runtime/app/forms.js [hunk 3]
```diff
@@ -161,14 +165,29 @@ export function enhance(form_element, submit = () => {}) {
...
+
+			if (enctype === 'multipart/form-data' && headers['Content-Type']) {
+				// @ts-expect-error
+				delete headers['Content-Type'];
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/forms.js:183]: We could avoid the TypeScript error here (for accessing the array index with a string key) by either using the [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers) object for `headers` or by typing the object key as a string such as:
```js
/** @type {Record<string, string> */
const headers = { ... }
```

File: packages/kit/src/runtime/app/forms.js [hunk 4]
```diff
@@ -161,14 +165,29 @@ export function enhance(form_element, submit = () => {}) {
 		let result;
 
 		try {
+			const is_valid_enctype = enctype?.match(
+				/application\/x-www-form-urlencoded|multipart\/form|text\/plain/
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/forms.js:169]:
```suggestion
				/application\/x-www-form-urlencoded|multipart\/form-data|text\/plain/
```
Should it be multipart/form-data instead of multipart/form? based on the enctype from [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype)

File: packages/kit/src/runtime/app/forms.js (hunk 3 above)
Comment (allozaur) [reply packages/kit/src/runtime/app/forms.js]: i've updated it to use `Headers` constructor

File: packages/kit/src/runtime/app/forms.js (hunk 2 above)
Comment (allozaur) [reply packages/kit/src/runtime/app/forms.js:179]: @eltigerchino  We need this data format for body being sent in an HTTP request with the 'application/x-www-form-urlencoded' content type, so we are taking the already formatted `FormData()` and converting it to `URLSearchParams()` instance. Otherwise this will not work.

Comment (eltigerchino) [reply packages/kit/src/runtime/app/forms.js:179]: Thanks for explaining this! I learned something new.

File: packages/kit/src/runtime/app/forms.js [hunk 5]
```diff
@@ -161,14 +165,28 @@ export function enhance(form_element, submit = () => {}) {
...
+			);
+
+			const headers = new Headers({
+				accept: 'application/json',
+				'Content-Type': is_valid_enctype ? enctype : 'application/x-www-form-urlencoded',
+				'x-sveltekit-action': 'true'
+			});
+
+			// @ts-expect-error
+			const body = enctype === 'multipart/form-data' ? form_data : new URLSearchParams(form_data);
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/forms.js:179]:
```suggestion
			const body = enctype === 'multipart/form-data' ? form_data : new URLSearchParams(form_data);
```
Do we need the `@ts-expect-error` here? It seems that URLSearchParams is a valid body type https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#body

File: packages/kit/src/runtime/app/forms.js [hunk 6]
```diff
@@ -161,14 +165,28 @@ export function enhance(form_element, submit = () => {}) {
 		let result;
 
 		try {
+			const is_valid_enctype = enctype?.match(
+				/application\/x-www-form-urlencoded|multipart\/form-data|text\/plain/
+			);
+
+			const headers = new Headers({
+				accept: 'application/json',
+				'Content-Type': is_valid_enctype ? enctype : 'application/x-www-form-urlencoded',
```
Comment (eltigerchino) [inline packages/kit/src/runtime/app/forms.js:174]: @benmccann is it a breaking change if we start setting the `Content-Type` header for `use:enhance` POST requests where we previously didn't set this?

File: .changeset/moody-apricots-kiss.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
+---
+"@sveltejs/kit": patch
+---
+
+fix: respect `enctype`/`formenctype` HTML form attributes from form + set `application/x-www-form-urlencoded` as a default `Content-Type` for `POST` requests made by `enhance`
```
Comment (eltigerchino) [inline .changeset/moody-apricots-kiss.md:5]:
```suggestion
fix: respect HTML attributes `enctype` and `formenctype` for forms with `use:enhance`
```

Might be better to generate a second patch changeset since there are two changes:
```
fix: set default `Content-Type` header to `application/x-www-form-urlencoded` for `POST` form submissions with `use:enhance` to align with native form behaviour
```

File: packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js [hunk 8]
```diff
@@ -53,5 +59,16 @@ export const actions = {
 		});
 
 		return {};
+	},
+	send_file: async ({ request }) => {
+		const data = await request.formData();
+		const file = data.get('file');
+
+		console.log('file', file);
```
Comment (eltigerchino) [inline packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js:67]:
```suggestion
```

File: packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js [hunk 9]
```diff
@@ -53,5 +59,16 @@ export const actions = {
...
+
+		return {
+			// @ts-expect-error
+			result: 'file name:' + file.name
+		};
```
Comment (eltigerchino) [inline packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js:72]:
```suggestion
	if (file instanceof File) {
				return {
					result: 'file name:' + file.name
				};
	}
```

File: packages/kit/test/apps/basics/test/test.js [hunk 10]
```diff
@@ -1153,6 +1153,61 @@ test.describe('Actions', () => {
...
+
+		await page.locator('button.form-file-submit').click();
+
+		await expect(page.locator('pre.formdata1')).toHaveText(
+			JSON.stringify({ result: 'file name:test-file.txt' })
+		);
+		await expect(page.locator('pre.formdata2')).toHaveText(
+			JSON.stringify({ result: 'file name:test-file.txt' })
+		);
+		await expect(page.locator('input[name=username]')).toHaveValue('');
```
Comment (eltigerchino) [inline packages/kit/test/apps/basics/test/test.js:1194]:
```suggestion
```

File: packages/kit/test/apps/basics/test/test.js [hunk 11]
```diff
@@ -1153,6 +1153,61 @@ test.describe('Actions', () => {
...
+
+		await page.locator('input[name="username_2"]').fill('foo');
+		await page.locator('button.form-enctype-submit').click();
+
+		await expect(page.locator('pre.formdata1')).toHaveText(JSON.stringify({ result: 'foo' }));
+		await expect(page.locator('pre.formdata2')).toHaveText(JSON.stringify({ result: 'foo' }));
+		await expect(page.locator('input[name="username_2"]')).toHaveValue('');
+	});
+
+	test('use:enhance with `enctype="multipart/form"` attribute in `<form>`', async ({ page }) => {
```
Comment (eltigerchino) [inline packages/kit/test/apps/basics/test/test.js:1172]:
```suggestion
	test('use:enhance button with formenctype', async ({ page }) => {
```

File: packages/kit/test/apps/basics/test/test.js [hunk 12]
```diff
@@ -1153,6 +1153,61 @@ test.describe('Actions', () => {
...
+		expect(await page.textContent('pre.formdata1')).toBe(JSON.stringify(null));
+		expect(await page.textContent('pre.formdata2')).toBe(JSON.stringify(null));
+
+		await page.locator('input[name="username_2"]').fill('foo');
+		await page.locator('button.form-enctype-submit').click();
+
+		await expect(page.locator('pre.formdata1')).toHaveText(JSON.stringify({ result: 'foo' }));
+		await expect(page.locator('pre.formdata2')).toHaveText(JSON.stringify({ result: 'foo' }));
+		await expect(page.locator('input[name="username_2"]')).toHaveValue('');
+	});
```
Comment (eltigerchino) [inline packages/kit/test/apps/basics/test/test.js:1170]: We should try to test for the expected content-type request header instead. Maybe we can return the `Content-Type` request header as a the form action result and check if it is `application/x-www-form-urlencoded` by default?

File: packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js [hunk 13]
```diff
@@ -18,6 +18,12 @@ export const actions = {
 			result: fields.get('username')
 		};
 	},
+	login_2: async ({ request }) => {
+		const fields = await request.formData();
+		return {
+			result: fields.get('username_2')
+		};
+	},
```
Comment (eltigerchino) [inline packages/kit/test/apps/basics/src/routes/actions/enhance/+page.server.js:26]:
```suggestion
```

File: packages/kit/test/apps/basics/test/test.js (hunk 12 above)
Comment (eltigerchino) [reply packages/kit/test/apps/basics/test/test.js:1170]: Might be worth reusing the tests from https://github.com/sveltejs/kit/pull/7195/files now that we're resolving the content-type header automatically, whereas the tests from that PR try to resolve it manually.

File: packages/kit/test/apps/basics/test/test.js [hunk 14]
```diff
@@ -1153,6 +1153,61 @@ test.describe('Actions', () => {
...
```
[the remark this answers is not in the document]
Comment (allozaur) [reply packages/kit/test/apps/basics/test/test.js:1208]: this is handled already by previous test

File: packages/kit/test/apps/basics/test/test.js (hunk 12 above)
Comment (allozaur) [reply packages/kit/test/apps/basics/test/test.js]: @eltigerchino this has been addressed in ba87fe949f4c076565f439de8b74bf21aab0c0c0

File: packages/kit/src/runtime/app/forms.js [hunk 15]
```diff
@@ -161,14 +165,28 @@ export function enhance(form_element, submit = () => {}) {
...
+				'x-sveltekit-action': 'true'
+			});
+
+      // @ts-expect-error `URLSearchParams(form_data)` is kosher, but typescript doesn't know that
+			const body = enctype === 'multipart/form-data' ? form_data : new URLSearchParams(form_data);
+
+			if (enctype === 'multipart/form-data' && headers.get('Content-Type')) {
+				headers.delete('Content-Type');
+			}
```
[the remark this answers is not in the document]
Comment (allozaur) [reply packages/kit/src/runtime/app/forms.js]: so this was actually needed due to serialization of `mutlipart/form-data` requests. if we are using this type of request for our form, explicitly defining the `Content-Type` will prevent the serialization to happen and thus it will break the form's functionality.

But still, to have the code more clear and clean i've rewritten this bit with e22c88c478e247a0b3cf004e057961c034f358c5

File: .changeset/moody-apricots-kiss.md (hunk 7 above)
Comment (allozaur) [reply .changeset/moody-apricots-kiss.md:5]: Addressed with 63af8eec634006b2bfef1aee63ce6af4bbd7dddc

File: packages/kit/src/runtime/app/forms.js (hunk 6 above)
Comment (allozaur) [reply packages/kit/src/runtime/app/forms.js]: @eltigerchino i modified this logic a bit in e22c88c478e247a0b3cf004e057961c034f358c5

We need to explicitly set this if we want to pass the value of `enctype` / `formenctype`

File: packages/kit/src/runtime/app/forms.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (eltigerchino) [reply packages/kit/src/runtime/app/forms.js]: Thanks for that. I've learned something new again.
For future reference:
> When using FormData to submit POST requests using [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) or the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) with the multipart/form-data content type (e.g. when uploading files and blobs to the server), do not explicitly set the [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header on the request. Doing so will prevent the browser from being able to set the Content-Type header with the boundary expression it will use to delimit form fields in the request body.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects#sending_files_using_a_formdata_object

**Review by eltigerchino — APPROVED** [review]

**Comment by eltigerchino** [comment]
Thank you so much! This should be good to merge once CI passes
