### PR TITLE
[fix] Lazy load Svelte components to reenable no-ssr use cases

### LINKED ISSUE #5909: SPA mode fails when importing code with client-side only variables (worked prior 1.0.0-next.405)
### Describe the bug

Importing code into a Svelte file that contains client-side only variables like `location` will cause vite errors in dev and build.

### Reproduction

Uses: `@sveltejs/adapter-static` and SSR: false 

https://stackblitz.com/github/rob-balfre/sveltekit-static-bug?file=src%2Froutes%2F%2Bpage.svelte

Running dev will show `location is not defined`.

Only errors if `location` is called via an import. 

### Logs

```shell
❯ npm install && npm run dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.064s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 13 dependencies. For more information use `--verbose`.
└ Completed in 0.948s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 0.186s
info security We found `install` scripts which turbo skips for security reasons. For more information see
https://turbo.sh/install-scripts.
├─ @sveltejs/kit@1.0.0-next.408
└─ esbuild@0.14.54
info Some packages were automatically replaced with polyfills. For more information see
https://turbo.sh/polyfills.
└─ esbuild@0.14.54 => esbuild-wasm@0.14.54

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 1.23s
$ vite dev

  VITE v3.0.7  ready in 1600 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
location is not defined
ReferenceError: location is not defined
    at /src/lib/foo.js:2:10
    at instantiateModule (file:///home/projects/kkviylzwo.github/node_modules/vite/dist/node/chunks/dep-0f13c890.js:50549:15)
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 85.89 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 96.0
    Safari: 15.6
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: 1.0.0-next.408 => 1.0.0-next.408 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.7
```

### Severity

blocking an upgrade

### Additional Information

Worked fine prior to 1.0.0-next.405.

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #5909

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/vite/build/build_server.js [hunk 1]
```diff
@@ -239,6 +239,8 @@ export async function build_server(options, client) {
 		/** @type {string[]} */
 		const imports = [];
 
+		// String representation of
+		/** @type {import('types').SSRNode} */
```
Comment (benmccann) [inline packages/kit/src/vite/build/build_server.js:243]: this is kind of a confusing way to write the comment. maybe something like this?
```suggestion
		// String representation of types.SSRNode
```

Comment (dummdidumm) [reply packages/kit/src/vite/build/build_server.js:243]: I specifically wrote it like this so that you can do "find usages" on the type and it takes you to this place. This would have been helpful to me to find the correct places I need to change quicker.

**Comment by dummdidumm** [comment]
I feared this would happen - this CSS tests are failing, I guess because they are no longer eagerly imported so it's a FOUC in some cases.

**Review by Rich-Harris — APPROVED** [review]
