### PR TITLE
[fix] properly scroll if body has margin

### LINKED ISSUE #2760: Scroll issue when navigating between pages
### Describe the bug

When scrolling down on a page then clicking a link, the next page is scrolled down when it should not be.

### Reproduction

1. Go to https://gavinr.github.io/sveltekit-scroll-issue/
2. Scroll down 75% on the page, click link ~400
3. Next page loads. 
    - Expected: page loads with scroll at top of page
    - Actual: page loads scrolled down to bottom of page.

### Logs

```shell
None
```

### System Info

```shell
System:
    OS: Have tested this on Windows 10 and Linux (Mint)
  Binaries:
    Node: 14.18.1 - /usr/bin/node
    npm: 8.1.1 - /usr/bin/npm
  Browsers:
    Have tested on chrome and Firefox (latest) - happens on both
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/kit: next => 1.0.0-next.195 
    svelte: ^3.42.6 => 3.44.1
```

### Severity

serious

### Additional Information

1. See code at https://github.com/gavinr/sveltekit-scroll-issue
2. It looks like the issue started at  version `next.193`. For example, if you clone the above repository and run `npm install @sveltejs/kit@1.0.0-next.192` it will work correctly, but if you run `npm install @sveltejs/kit@1.0.0-next.193` it will be broken.
3. This is possibly the same issue as #2720 from @NewNik - I think that one was closed in error as you can see this clear replication case the scroll issues are still happening.

### PR DESCRIPTION
**Pull request by bluwy**
Fixes #2760

### Changes

- Fixed my dumb tests update mistake from my last PR (tests were actually failing)
- Use `document.documentElement` instead of `document.body` when checking for max scroll y
- Also fixes another sizable bug I found: When scrolling to/near the end of a page, the new page after navigation would also be scrolled to/near the end of the page by the browser regardless of the new page scroll height. Added extra checks for that.

Note: We may need to find a robust way to check for scrolling before the page `onMount()` runs. The `pageYOffset` trick is starting to bite us.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by benmccann — APPROVED** [review]

**Comment by bluwy** [comment]
@benmccann I made quite a big change since your review. The main takeaways are noted in the PR description, and in the code comments. I feel like the implementation is starting to get hacky, but unless we find a better way, we may have to stick with it for now.

File: packages/kit/test/apps/basics/src/routes/anchor-with-manual-scroll/anchor.svelte [hunk 1]
```diff
@@ -11,6 +11,7 @@
 	<p id="go-to-element">The browser scrolls to me</p>
 </div>
 <p id="abcde">I take precedence</p>
+<div />
```
Comment (bluwy) [inline packages/kit/test/apps/basics/src/routes/anchor-with-manual-scroll/anchor.svelte:14]: Note: I added this here our extra checks now brings a false positive to this case, where if the `onMount()` scrolls to the bottom of the page, we assumed that no scrolling happened.

Unless we can find a different check, this would be a known limitation for now. FWIW, if the `onMount()` scrolls to the top of the page, we had also assumed no scrolling happened in the past.

Extra note: "no scrolling happened" also means "run our custom scroll handling"

**Comment by gavinr** [comment]
Can I help this PR to land by testing or anything? Or are we just waiting on a review?

**Comment by bluwy** [comment]
Thanks @gavinr. Yeah I'm currently waiting for Ben's review as he has more experience with the router. If you can help test this branch, that would be nice as well to bring more confidence in the PR.

**Review by gavinr — APPROVED** [review]
I have tested this with the reproduction case in #2760 and it does resolve that issue. Thank you!

**Comment by Rich-Harris** [comment]
niiiice, amazing work

**Comment by antony** [comment]
game changer! @wolfr check this.
