### PR TITLE
breaking: serve public env dynamically, prevent use of dynamic env vars during prerendering

### LINKED ISSUE #10008: $env/dynamic/public becomes $env/static/public for pre-rendered pages, breaking app and exposing information
### Describe the bug

The docs for `$env/dynamic/public` state:

> This module provides access to **runtime environment variables**, as **defined by the platform you're running on**.

For pre-rendered pages though, this is incorrect and misleading. They actually behave more like `$env/static/public` with values coming from build-time `.env` files used. Not only does this risk exposing information that wasn't _intended_ to be exposed but the behavior of the app becomes indeterminate because the values used in the app depend on the order of page navigation.

As an example, I'm using `$env/dynamic/public` to read Firebase config from runtime environment values set in Google Cloud Run. Every so often Firebase auth on the client would fail, but a page refresh would always fix it. It depended on which page was initially viewed and exposed development-use configuration that was not intended to be exposed.

### Reproduction

See [https://github.com/CaptainCodeman/svelte-kit-10008](https://github.com/CaptainCodeman/svelte-kit-10008)

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 36.28 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/Library/pnpm/node
    npm: 8.19.2 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 113.0.5672.126
    Chrome Canary: 115.0.5786.0
    Firefox: 111.0.1
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4 
    @sveltejs/kit: ^1.18.0 => 1.18.0 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.8 => 4.3.8
```

### Severity

annoyance (had to disable pre-rendered pages for correct functionality)

### Additional Information

Maybe related to https://github.com/sveltejs/kit/issues/8946

### PR DESCRIPTION
**Pull request by Rich-Harris**
Fixes #10008. This does two things:

- prevents the use of `$env/dynamic/public` while prerendering (use `$env/static/public` instead)
- when landing on a prerendered page, populates `$env/dynamic/public` from a new dynamically rendered `/_env.js` module, instead of populating it with stale build-time values

TODO:

- [x] allow `%sveltekit.env.PUBLIC_WHATEVER%` to continue working (seems reasonable that this would be an exception to the 'you can't use dynamic public env vars during prerendering' rule)
- [x] nicer code
- [x] I guess it also makes sense to prevent use of `$env/dynamic/private` during prerendering
- [x] docs
- [x] preload `_env.js` when prerendering if we detect that `$env/dynamic/public` is used somewhere in the app
- [x] make `_env.js` configurable, via `config.kit.env.publicModule`
- [x] provide an API for `adapter-static` (and other adapters, if they want) to generate the `_env.js` module at build time
- [x] some tests, i guess

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/adapter-static/index.js [hunk 1]
```diff
@@ -62,6 +62,7 @@ See https://kit.svelte.dev/docs/page-options#prerender for more details`
 			builder.rimraf(assets);
 			builder.rimraf(pages);
 
+			builder.generateEnvModule();
```
Comment (dummdidumm) [inline packages/adapter-static/index.js:65]: If `adapter-static` uses this it needs a major version bump and a SvelteKit 2.x peer dependency bump

File: packages/kit/src/exports/vite/index.js [hunk 2]
```diff
@@ -572,7 +581,7 @@ function kit({ svelte_config }) {
 							preserveEntrySignatures: 'strict'
 						},
 						ssrEmitAssets: true,
-						target: ssr ? 'node16.14' : undefined
+						target: ssr ? 'node18.13' : 'es2022'
```
Comment (dummdidumm) [inline packages/kit/src/exports/vite/index.js:584]: Is this a drive-by adjustment?

File: packages/kit/src/runtime/server/page/render.js [hunk 3]
```diff
@@ -292,10 +296,11 @@ export async function render_response({
 
 		const blocks = [];
 
+		// TODO only populate `env` if `$env/dynamic/public` is used in the app
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/render.js:299]: Is this TODO from an earlier iteration of the PR? The below code looks like it only populates env if it's used

File: packages/kit/test/apps/basics/src/routes/prerendering/env/prerendered/+page.svelte [hunk 4]
```diff
@@ -0,0 +1 @@
+<h2>prerendered</h2>
```
Comment (dummdidumm) [inline packages/kit/test/apps/basics/src/routes/prerendering/env/prerendered/+page.svelte:1]: Is this missing a `+page.js` with `export const prerender = true`? Else this isn't actually prerendered.

File: packages/kit/src/core/config/index.spec.js [hunk 5]
```diff
@@ -72,6 +72,7 @@ const get_defaults = (prefix = '') => ({
 		embedded: false,
 		env: {
 			dir: process.cwd(),
+			publicModule: '_env.js',
```
Comment (dummdidumm) [inline packages/kit/src/core/config/index.spec.js:75]: If I'm understanding correclty this means people cannot have a `_env.js` route in their app anymore, right? Doubt that there's a conflict, but maybe there's a name that makes it even less likely?
Also, is this something we may want to use later in other places? I can't image something right now, but wanted to note that we now have a mechanism to transport other stuff across the wire this way now.

File: packages/kit/test/prerendering/basics/src/routes/env/+page.server.js [hunk 6]
```diff
@@ -1,9 +1,7 @@
 import { PRIVATE_STATIC } from '$env/static/private';
-import { env } from '$env/dynamic/private';
```
Comment (dummdidumm) [inline packages/kit/test/prerendering/basics/src/routes/env/+page.server.js:2]: This makes me wonder a bit about the `export const prerender = 'auto'` case. How would someone be able to use that on the server? Say someone does this
```js
import { env } from '$env/dynamic/private';

export const prerender = 'auto';

export function load() {
  if (!prerendering) {
    return { x: env.x }
  } else {
   return { x: 'unknown' }
  }
}
```
This would still work with the given code because the proxy does only error if you access one of the properties at runtime, right? Should we have a test for that?

File: documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md [hunk 7]
```diff
@@ -105,6 +105,14 @@ As such, SvelteKit 2 replaces `resolvePath` with a (slightly better named) funct
...
 
+## Dynamic environment variables cannot be used during prerendering
+
+The `$env/dynamic/public` and `$env/dynamic/private` modules provide access to _run time_ environment variables, as opposed to the _build time_ environment variables exposed by `$env/static/public` and `$env/static/private`.
+
+During prerendering in SvelteKit 1, they are one and the same. As such, prerendered pages that make use of 'dynamic' environment variables are really 'baking in' build time values, which is incorrect. Worse, `$env/dynamic/public` is populated in the browser with these stale values if the user happens to land on a prerendered page before navigating to dynamically-rendered pages.
+
+Because of this, dynamic environment variables can no longer be read during prerendering in SvelteKit 2 — you should use the `static` modules instead. If the user lands on a prerendered page, SvelteKit will request up-to-date values for `$env/dynamic/public` from the server (by default from a module called `_env.js` — this can be configured with `config.kit.env.publicModule`) instead of reading them from the server-rendered HTML.
```
Comment (dummdidumm) [inline documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md:114]:
```suggestion
Because of this, dynamic environment variables can no longer be read during prerendering in SvelteKit 2 — you should use the `static` modules instead. If the user lands on a prerendered page, SvelteKit will request up-to-date values for `$env/dynamic/public` from the server (by default from a module called `_env.js` — this can be configured with `config.kit.env.publicModule`) instead of reading them from the server-rendered HTML. This dynamic request logic uses top-level-await, which isn't available in older browsers.
```

**Review by dummdidumm — COMMENTED** [review]
Nice work! Some small notes, but looks good overall. Also needs a changeset (for SvelteKit and adapter-static)

File: packages/kit/src/exports/vite/index.js (hunk 2 above)
Comment (Rich-Harris) [reply packages/kit/src/exports/vite/index.js:584]: Sort of, but the `es2022` part is necessary for this PR because of the top level await thing. I guess we need to mention this in the migration notes

File: packages/adapter-static/index.js (hunk 1 above)
Comment (Rich-Harris) [reply packages/adapter-static/index.js:65]: Oops, good catch. Will fix when I'm at my desk

File: packages/kit/src/runtime/server/page/render.js (hunk 3 above)
Comment (Rich-Harris) [reply packages/kit/src/runtime/server/page/render.js:299]: Yep, this is our of date

File: packages/kit/src/core/config/index.spec.js (hunk 5 above)
Comment (Rich-Harris) [reply packages/kit/src/core/config/index.spec.js:75]: It does mean that, though I'm not too worried about conflicts (a conflict with `_app` is more likely and that's never arisen). We had talked about a dynamic endpoint for data and stuff like that, yeah. I suppose one thing we could do is reuse `_app`, and that way we don't need new config. The only thing is we'd then have both `${base}/_app` and `${assets}/_app` in the rare case that `assets` was specified, but that's probably fine now that I think about it?

File: documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md (hunk 7 above)
Comment (Rich-Harris) [reply documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md:114]: Rather than tagging individual features like this, should we just say that sveltekit 2 only supports browsers that implement es2022?

Comment (dummdidumm) [reply documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md:114]: That would certainly give us more leeway in adding other such things down the line (though I still feel a bit nervous about this, it's only been two years since these features are out)

Comment (Rich-Harris) [reply documentation/docs/60-appendix/30-migrating-to-sveltekit-2.md:114]: Browsers are either evergreen or they're not. We already didn't support non-evergreen browsers

**Comment by dummdidumm** [comment]
I just realized that the adapter-static case is a bit weird. So far we had minors for all the adapters to tell "hey we support SvelteKit 2.0 as well". adapter-static should also get that treatment for the current version, but that is swallowed by this major bump now. We should create a minor release for adapter-static from master to circumvent that.

**Comment by Rich-Harris** [comment]
Is there much value in an `adapter-static` minor? If the only new feature is SvelteKit 2 support, why not just do a major version?

**Comment by dummdidumm** [comment]
True, if someone upgrades to SvelteKit 2 they might as well upgrade to adapter-static v3. We should add that to the migration though (auto-bump the adapter-static version)

**Review by dummdidumm — APPROVED** [review]
If you want to do the `_app` change (and if it's easy) feel free to do so, else I think this is good to merge.

**Comment by CaptainCodeman** [comment]
> I guess it also makes sense to prevent use of $env/dynamic/private during prerendering

I think this might be incorrect. Even with prerendering disabled it now prevents any `handle` fn in `hooks.server.ts` from making use of dynamic env values, which might be needed at runtime.

My specific use-case is using the `@sveltejs/adapter-node` node adapter, and the env defines the 'ROOT_DOMAIN' that the site is serving, for instance `.example.com`, so that requests to `site-one.example.com` can load the appropriate site context by site ID, and redirect to the site's "proper" custom domain if it has one set. When the same request is made via the custom domain, it loads the site based on the domain name instead and doesn't redirect.

The `ROOT_DOMAIN` isn't known at build time - the same docker image can be deployed to environments that have different values (testing, staging, production).

The build initially compiles OK but then errors at the pre-render stage even with pre-rendering disabled:

+layout.server.ts:
```ts
export const prerender = false
```

Build output:
```
vite v5.0.9 building SSR bundle for production...
✓ 88 modules transformed.

vite v5.0.9 building for production...
✓ 62 modules transformed.
.svelte-kit/output/client/_app/version.json                                  0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/.vite/manifest.json                                2.66 kB │ gzip:  0.53 kB
.svelte-kit/output/client/_app/immutable/chunks/stores.OXeE6BI3.js           0.24 kB │ gzip:  0.17 kB
.svelte-kit/output/client/_app/immutable/nodes/1.a7topCIA.js                 0.79 kB │ gzip:  0.50 kB
.svelte-kit/output/client/_app/immutable/nodes/0.VoE1dcHf.js                 0.89 kB │ gzip:  0.58 kB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper.0HuHagjb.js   0.91 kB │ gzip:  0.56 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.k-kUyWhY.js        2.16 kB │ gzip:  1.02 kB
.svelte-kit/output/client/_app/immutable/nodes/2.YZTI5OQK.js                 2.48 kB │ gzip:  1.24 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.i1C8PUYA.js       2.92 kB │ gzip:  1.48 kB
.svelte-kit/output/client/_app/immutable/entry/app.WtRj-Ezm.js               5.20 kB │ gzip:  1.97 kB
.svelte-kit/output/client/_app/immutable/chunks/index.wJJws_a0.js            5.24 kB │ gzip:  2.21 kB
.svelte-kit/output/client/_app/immutable/entry/start.OF9vDRZY.js            28.00 kB │ gzip: 11.17 kB
✓ built in 404ms

node:internal/event_target:1006
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot read values from $env/dynamic/private while prerendering (attempted to read env.HOST_DOMAIN). Use $env/static/private instead
    at Object.get (file:///Users/simon/dev/temp/sk-envs/.svelte-kit/output/server/index.js:3664:11)
    at file:///Users/simon/dev/temp/sk-envs/.svelte-kit/output/server/chunks/hooks.server.js:17:33
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async Server.init (file:///Users/simon/dev/temp/sk-envs/.svelte-kit/output/server/index.js:3696:24)
    at async prerender (file:///Users/simon/dev/temp/sk-envs/node_modules/.pnpm/@sveltejs+kit@2.0.0_@sveltejs+vite-plugin-svelte@3.0.1_svelte@4.2.8_vite@5.0.9/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:102:2)
    at async MessagePort.<anonymous> (file:///Users/simon/dev/temp/sk-envs/node_modules/.pnpm/@sveltejs+kit@2.0.0_@sveltejs+vite-plugin-svelte@3.0.1_svelte@4.2.8_vite@5.0.9/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.10.0
```

It's possible to workaround it by adding tests for `building` before accessing the values, hopefully that helps anyone who has the same issue and finds this.

**Comment by ollema** [comment]
@CaptainCodeman this does seem to be an issue, see #11341.

was there a workaround? if so, could you share it in #11341 perhaps? I did not quite understand the `building` stuff you referred to
