### PR TITLE
fix: use runes in when detecting Svelte 5

### LINKED ISSUE #11022: Svelte 5: Forcing runes mode causes issues with generated code.
### Describe the bug

Setting `compilerOptions: { runes: true }` causes errors like this:

```
CompileError: Cannot use `export let` in runes mode â€” use $props instead
    at new CompileError (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/errors.js:544:3)
    at Module.error (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/errors.js:582:8)
    at ExportNamedDeclaration (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/2-analyze/validation.js:646:14)
    at go (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/visitors.js:62:5)
    at visitor (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/visitors.js:77:4)
    at go (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/visitors.js:62:5)
    at visitor (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/visitors.js:77:4)
    at Object.next (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/zimmerframe/src/walk.js:119:21)
    at go (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/visitors.js:58:29)
    at next (/home/projects/sveltejs-kit-template-default-alrzrc/node_modules/svelte/src/compiler/phases/visitors.js:68:7)
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-alrzrc?file=svelte.config.js

### Logs

_No response_

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 5.07 GB / 31.92 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.9 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: 119.0.6045.105
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.58)
    Internet Explorer: 11.0.19041.3570
```

### Severity

annoyance

### Additional Information

_No response_

### LINKED ISSUE #11027: afterUpdate in the root sveltekit component is not called after a failing action
### Describe the bug

The effect of this is that if you fail an action on a form that is using enhance the page store doesn't update. It might have other repercussions.

### Reproduction

- go to https://www.sveltelab.dev/4zr9147ftt14ndq
- follow the link in the index
- try to submit the form
- observe that the page store update
- go to `./src/[test]/+page.server.ts` and swap line 18 and 19 (return fail instead of actual data)
- try to submit the form again
- observe that the page store doesn't update

### Reproduction 2

I was able to come up with an even more minimal reproduction in the svelte 5 repl

- Go [here](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE5VVTW-bQBD9KxMUJRBhkHq0jdUqtx5aqVFPpbKwWWwa2EW7SxyL8t87-wGL7TpRTojdeW9m3nxs5xVlRYQ3_9V5NKuJN_e-NI0XevLYqB_xQipJ8F-wlm_VyVJsednIVUpTWdYN4xJ-MCah4KyG1Iti9RcZXOotJmYdZbIsymxTkbWQjJPegdyVwSCqIhKabEcggXOg30ki5ByRWer1gXYyQLSBQFCnwL3jEqxWXCdQRC5jlxBdblopGQVGt1W5fU46P0hWnWJQ6GTEbgy271eP-4xijNrrMjZwpFpqTToTTK_zSDrF0UO8QjlrlmNGJPfmkrekD0f1XaquCH_EtACDmnDgpVSGMOpoVI-1V6tj_PAAn5uMZzV0GT328JJVLYGHOKXkVRMVLd3KEpO-UFmbBqDz3zIqrLgo4uDamiwGjTnJ8iPeq6RsGU_pj77lS-W5LR5p-qht8kwSX3EHkKxUxMaDLeZFSpQc1i6tiUtBpD9eXjguskqcej61v-bTJD0H9G3iY2XeA2_phft2o3prQ3y8HN1rKlVZG70BGf1YlRvniyFU2XIKNrqRbpoUBmCJcdAK8EcKSJIEWpqToqQkh79_wTeZ391NFLtBoxESBI4LnbfUn9I5VGBHThp91OdELRt2Z2seqkKETg7Qs_PWFKjp-eASetyXVe4Wiv79_xqCrJCE_9RdpkN7ZFSSV3k-RxZmx8TtlvNTNdy22SfM_rg6zPCwikQV2_mpGfFjSXepF0zbT0SKKRrmxAgaWGYXJjKs1ybC9Tr1QhuVsb-dw9SZIhwvpk5Upw-XJxtQKY9HN7NZSrGPWV0TKjFWkPtSwKGsKqizZwLkhfAjnuHNgfFnyASgJGQrSY7whhNk674-ff8WCcnRSqWkHIZA26oK4VPQK8_GcDZTK9NU8O31aHJ4dzXu3inqsPvMVkPrp-HV8N1ETVaeunGc_r0rwL2Rd-h4U06V6NyN0tj4ZzUYju0IhbrgajQuQ7QPoXmKxj1QuK1yup_HjPwgGtrz-jpBmmF6-8Vb6usKfXAuzTPsBtMooMswabzlnmPlU6o9XG2g2ysddBnz7_4fpIhaONoIAAA=)
- click on the button "Change store"
- observe that the prop update in the console but there's no afterUpdate log happening

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.1 => 2.1.1 
    @sveltejs/kit: ^1.27.4 => 1.27.5 
    svelte: next => 5.0.0-next.1 
    vite: ^4.5.0 => 4.5.0
```

### Severity

blocking an upgrade

### Additional Information

The reason why i can say that afterUpdate is not called is because i started debugging this and went into chrome sources and added some breakpoints in the root sveltekit component.

Specifically i've added a breakpoint in the `$effect.pre` that reads the store and call set on the page store and a breakpoint inside the afterUpdate

### PR DESCRIPTION
**Pull request by dummdidumm**
- fixes #11027 (not the underlying issue, but the problem within SvelteKit)
- fixes #11022

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/core/sync/write_root.js [hunk 1]
```diff
@@ -40,28 +40,57 @@ export function write_root(manifest_data, output) {
...
 
-				$: stores.page.set(page);
-				afterUpdate(stores.page.notify);
+				${
+					isSvelte5Plus()
+						? dedent`
+							if (browser) {
+								$effect.pre(() => stores.page.set(page));
+							} else {
+								stores.page.set(page);
```
Comment (benmccann) [inline packages/kit/src/core/sync/write_root.js:75]: would this not work in the browser case as well?

**Review by Rich-Harris — APPROVED** [review]
looking forward to replacing the stores with state-based alternatives so that this dance becomes unnecessary

**Review by benmccann — COMMENTED** [review]
Why is this necessary? I don't see anything in the Svelte 4 version that's listed on the breaking changes page: https://svelte-5-preview.vercel.app/docs/breaking-changes. If I didn't miss it, then maybe there's something we need to fix in our compatibility or list on that page?

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
actually @benmccann is right, this should work. i'm rescinding my approval

@trueadm this is what i was talking about before when i was saying `afterUpdate` shouldn't be bound to render effects, it should be bound to `get`

**Comment by paoloricciuti** [comment]
> actually @benmccann is right, this should work. i'm rescinding my approval
> 
> @trueadm this is what i was talking about before when i was saying `afterUpdate` shouldn't be bound to render effects, it should be bound to `get`

I also opened an issue in the svelte REPL with a much more minimal reproduction https://github.com/sveltejs/svelte/issues/9420

File: packages/kit/src/core/sync/write_root.js (hunk 1 above)
Comment (Rich-Harris) [reply packages/kit/src/core/sync/write_root.js:75]: No, effects don't run in SSR. This is the rare case where the code inside a `$: {...}` _does_ need to run in SSR, but it's because we're having to do things in a bit of a roundabout way to begin with. This `if` is the correct way to deal with it

**Comment by dummdidumm** [comment]
> actually @benmccann is right, this should work. i'm rescinding my approval

What exactly should work? Are you saying that you also expect `$effect.pre` to run in SSR? Because we're in agreement then, I also think that should be the behavior 😄

**Comment by trueadm** [comment]
@Rich-Harris The issue with all of this (we currently do `afterUpdate` on writes) is that the signal you're reading/writing to has only a component context of where it was created. So if you create a signal like this outside of a component or in another component context, non of this will work. This is what I meant by the some of these problems are likely not to be possible to be fixed and thus we need to document these breaking changes.

**Comment by trueadm** [comment]
I'd prefer:

```js
$effect.once(fn)
```

This would be an effect that runs one on the server and once on init on the client. Which seems to handle this use-case?

**Comment by PuruVJ** [comment]
This is basically onMount, with added functionality of running on server

**Comment by dummdidumm** [comment]
It is not what's wanted here. What's wanted here is a function that runs once on the server and before every update on the client (basically `$effect.pre`)

**Comment by trueadm** [comment]
`$effect.pre` has a major downside here doing what you describe. If you run the logic on the server and it produces `x = 5` but it runs twice on the client and produces `x = 6` then you'll end up having different values before you come to entering the render effects that will hydrate the DOM – this will cause a mismatch and instantly cause hydration performance issues. This is why other frameworks are so strict to prevent this behavior from happening – it's a performance cliff like no other.

**Comment by benmccann** [comment]
I think my solution to that problem would instead be to detect in dev mode that the value on the client differs from the value on the server. Because it seems unusual to me that something would run twice on the client before hydration and once on the server and that seems like something to avoid

**Comment by trueadm** [comment]
@benmccann I mean the same logic would also run twice on the server if it could – but given we're saying that `$effect.pre` only runs once, then you get mismatches. I would just like us to understand the implications of having this and possibly causing mismatches as there's one thing detecting a mismatch in DEV vs enabling a developer to fix this problem easily. I still firmly believe we should be pushing people to the happy path.

The way other frameworks deal with this problem is to make it not possible to run effects on the server, and then making it clear there was a mismatch on the client – meaning there's a single place to look to fix it, the client code. In which case the fix is generally to make it an `$effect` rather than an `$effect.pre` – this goes to the `useLayoutEffect` vs `useEffect` case in React. Now another way of looking at that is saying the inverse – `$effect.server` only runs once on the server and you can't update state that affects UI in it, which is actually better than overloading `$effect.pre`.

This is important as I expect the majority of use-cases for `$effect.pre` to be reading the DOM before it's painted, so calculations around styling and scroll are available. These shouldn't ever run on the server, so it makes no sense to have it run there to begin with.

**Comment by benmccann** [comment]
This seems like something you'd do frequently with stores. I think another solution to this might be to replace the use of `stores.page` with runes? We could potentially provide a helper function which wraps this pattern to help people interact between the two types of reactivity

**Comment by trueadm** [comment]
@benmccann There was a suggestion to have a `$kit` rune a while back, this could just be something that lives on that rune.

**Comment by Rich-Harris** [comment]
> Are you saying that you also expect `$effect.pre` to run in SSR?

No, absolutely not

and I'm not sure what `$effect.once(fn)` would mean other than `fn()`

**Comment by dummdidumm** [comment]
We should have the "how does `afterUpdate` work correctly" discussion in https://github.com/sveltejs/svelte/issues/9420

>> Are you saying that you also expect $effect.pre to run in SSR?

>No, absolutely not

I don't understand what changes you are requesting to this PR then.

**Comment by trueadm** [comment]
> > The issue with all of this (we currently do `afterUpdate` on writes) is that the signal you're reading/writing to has only a component context of where it was created
> 
> Where the signal was created is irrelevant — what matters is where the signal is _read_. What I'm suggesting is basically this (pseudo-code):
> 
> ```js
> function get(signal) {
>   if (current_component) {
>     signal.consumers.add(current_component);
>   }
> 
>   // ...
> }
> ```

I tried that and the issue is `current_component` is always `null` after the init phase, unless you're inside an effect. In which case, if you're inside an effect, then the existing logic of handling it for render effects can be expanded to be other effects too.

**Comment by Rich-Harris** [comment]
> I don't understand what changes you are requesting to this PR then

What I'm saying is that we shouldn't need to remove the `afterUpdate` stuff. It should continue to work

**Comment by Rich-Harris** [comment]
> I tried that and the issue is `current_component` is always `null` after the init phase, unless you're inside an effect. In which case, if you're inside an effect, then the existing logic of handling it for render effects can be expanded to be other effects too.

Yeah I'm not talking about what `current_component` is or isn't at present, or the details of the implementation. I'm just describing how we can make it work correctly at a high level

**Comment by dummdidumm** [comment]
But it's deprecated, and we're encouraging people to move away from it. It sounds counter-intuitive to not use the new tools we have in runes mode. And it's a quick-fix for the issue in the context of SvelteKit, and we can look at the underlying problem in https://github.com/sveltejs/svelte/issues/9420, where - again - we should have the discussion about how to fix this.

**Comment by Rich-Harris** [comment]
The replacement code is just super nasty. I think it would be better to keep using `afterUpdate` until we can use state-based replacements for the stores (and keep the stores as a legacy interface to those replacements)

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
ok — i think we should undo the `afterUpdate` change once we get it working though, unless we want to keep it to motivate us to build a state-based `$page` etc

**Comment by trueadm** [comment]
> ok — i think we should undo the `afterUpdate` change once we get it working though, unless we want to keep it to motivate us to build a state-based `$page` etc

Yeah, let's do that. I think it makes most sense.

File: .changeset/beige-ties-allow.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@sveltejs/kit': patch
+---
+
+fix: use runes in when detecting Svelte 5
```
Comment (Conduitry) [inline .changeset/beige-ties-allow.md:5]: This changelog message appears to be missing a

Comment (dummdidumm) [inline .changeset/beige-ties-allow.md:5]:
```suggestion
fix: use runes in generated root when detecting Svelte 5
```

**Comment by benmccann** [comment]
Someone made a related issue: https://github.com/sveltejs/svelte/issues/9278
