### PR TITLE
always generate `404.html`

### LINKED ISSUE #9011: invalid static requests return index.html instead of 404
### Describe the bug

If the home page `/` is prerendered, invalid static requests (those matching the paths in `_routes.json` `excluded` but are not found) such as `/_app/abcd`, incorrectly return a `200` status code and the content of the prerendered `/index.html` file if any.

However, if a `404.html` file is found, it is returned alongside the expected 404 status code.

### Reproduction

1. Find a Cloudflare Pages website deployed with `@sveltejs/adapter-cloudflare`.
2. Navigate to a non-existent `/_app/*` URL.

For example, the URL below should return a 404 but returns the prerendered home page:

https://brgh.church/_app/doesntexist

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 142.81 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Chrome Canary: 112.0.5586.0
    Firefox: 109.0.1
    Firefox Developer Edition: 110.0
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-cloudflare: ^2.0.1 => 2.0.1 
    @sveltejs/kit: ^1.3.10 => 1.3.10 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.1.1 => 4.1.1
```

### Severity

annoyance

### Additional Information

When the root page is not prerendered, invalid requests to `/_app/*` return a blank page and a 404.
So, should the Cloudflare adapter include a `/404.html` by default to ensure this occurs consistently?
Or is it enough to document the importance of including a `404.html` page?

### PR DESCRIPTION
**Pull request by Rich-Harris**
* closes #9011
* closes #9245 (which this PR builds on)

If the user creates their own 404 route or static asset, that will be given priority.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by ajgeiss0702 — APPROVED** [review]

File: packages/adapter-cloudflare/index.js [hunk 1]
```diff
@@ -16,11 +16,13 @@ export default function (options = {}) {
 			builder.rimraf(tmp);
 			builder.mkdirp(tmp);
 
+			await builder.generateFallback(path.join(dest, '404.html'));
```
Comment (dummdidumm) [inline packages/adapter-cloudflare/index.js:19]: What happens if someone has a `404.html/+page.svelte`? Will it overwrite this fallback without issues? If yes, should we add a comment explaining it?
 ```suggestion
 			// generate 404.html first which can then be overridden by prerendering, if the user defined such a page
			await builder.generateFallback(path.join(dest, '404.html'));
```

Also: Do we need to take the base path into account here? Or can we be sure the deployment has control of the root, too, which makes this a valid global 404 fallback?

Comment (Rich-Harris) [reply packages/adapter-cloudflare/index.js:19]: We shouldn't take the base path into account, because Pages is only interested in a `404.html` file in the root

Comment (ajgeiss0702) [reply packages/adapter-cloudflare/index.js]: > We shouldn't take the base path into account, because Pages is only interested in a `404.html` file in the root

It looks like cf pages will search subdirectories too (if the 404 is on a subdirectory, it will search that first. If it doesn’t find one there, it searches the parent directly, etc. until it gets to the root 404)
https://developers.cloudflare.com/pages/platform/serving-pages/#not-found-behavior

Comment (Rich-Harris) [reply packages/adapter-cloudflare/index.js]: ah, good point. Still, there's no reason not to have the same behaviour for requests higher than the basepath

**Review by dummdidumm — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thanks @ajgeiss0702!

**Comment by danawoodman** [comment]
fwiw it appears this PR has broken adapter-cloudflare for anyone using something like an auth hook which shouldn't run during build: 

https://github.com/sveltejs/kit/issues/9386
