### PR TITLE
fix: adjust `app.d.ts` to diminish confusion about imports

### LINKED ISSUE #8276: Make global declaration the default
### Describe the problem

Seems like every day someone will have an issue with [trying to import types in `src/app.d.ts`](https://kit.svelte.dev/docs/types#app)

### Describe the proposed solution

Why not make the `declare global {` version the default?

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
closes #8276

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/create-svelte/templates/default/src/app.d.ts [hunk 1]
```diff
@@ -1,9 +1,15 @@
...
+		// interface Error {}
+		// interface Locals {}
+		// interface PageData {}
+		// interface Platform {}
+	}
 }
+
+// This line ensures this file is treated as a module.
+// It can be removed if you add an import to this file.
+export default undefined;
```
Comment (Rich-Harris) [inline packages/create-svelte/templates/default/src/app.d.ts:15]:
```suggestion
export declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface Platform {}
	}
}
```

File: packages/create-svelte/templates/skeleton/src/app.d.ts [hunk 2]
```diff
@@ -1,9 +1,15 @@
...
+		// interface Error {}
+		// interface Locals {}
+		// interface PageData {}
+		// interface Platform {}
+	}
 }
+
+// This line ensures this file is treated as a module.
+// It can be removed if you add an import to this file.
+export default undefined;
```
Comment (Rich-Harris) [inline packages/create-svelte/templates/skeleton/src/app.d.ts:15]:
```suggestion
export declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface Platform {}
	}
}
```

File: packages/create-svelte/templates/skeletonlib/src/app.d.ts [hunk 3]
```diff
@@ -1,11 +1,15 @@
...
+		// interface Error {}
+		// interface Locals {}
+		// interface PageData {}
+		// interface Platform {}
+	}
 }
+
+// This line ensures this file is treated as a module.
+// It can be removed if you add an import to this file.
+export default undefined;
```
Comment (Rich-Harris) [inline packages/create-svelte/templates/skeletonlib/src/app.d.ts:15]:
```suggestion
export declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface Platform {}
	}
}
```

File: packages/kit/types/ambient.d.ts [hunk 4]
```diff
@@ -2,41 +2,26 @@
...
- * ```ts
- * interface Locals {
- * 	user: import('$lib/types').User;
- * }
- * ```
- * Or wrap the namespace with `declare global`:
- * ```ts
- * import { User } from '$lib/types';
- *
  * declare global {
```
Comment (Rich-Harris) [inline packages/kit/types/ambient.d.ts:5]:
```suggestion
 * export declare global {
```

File: packages/kit/types/ambient.d.ts [hunk 5]
```diff
@@ -2,41 +2,26 @@
...
- * 		}
- * 		// ...
+ * 		// interface Error {}
+ * 		// interface Locals {}
+ * 		// interface PageData {}
+ * 		// interface Platform {}
  * 	}
  * }
+ *
+ * export default undefined;
```
Comment (Rich-Harris) [inline packages/kit/types/ambient.d.ts:14]:
```suggestion
```

File: packages/kit/types/ambient.d.ts [hunk 6]
```diff
@@ -2,41 +2,26 @@
...
  * ```
  *
+ * By populating these interfaces, you will gain type safety when using `event.locals`, `event.platform`, and `data` from `load` functions.
+ *
+ * Note that since it's a declaration file, you have to be careful when using `import` statements. Once you add an `import`
+ * at the top level, the declaration file is no longer considered ambient, at which point you need to wrap `App` inside `declare global`
+ * to still be available throughout the app. Opposite to that is the behavior when there's no `import`, at which point having `declare global`
+ * _prevents_ the `App` types from being available.
+ * To safe you the headache of converting between the two this we provide a dummy `export` to force the file being a module.
+ * Do not remove it unless you have an `import` statement at the top level.
```
Comment (Rich-Harris) [inline packages/kit/types/ambient.d.ts:24]:
```suggestion
```

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
Pleasantly surprised to discover that `export declare` works — solves the problem without `export default undefined` which is fugly and requires explanation. Unless there's a reason _not_ to use `export declare`?

**Comment by dummdidumm** [comment]
As discussed offline, `export declare global` is unfortunately a TS error, so is `export default {}` instead of `export default undefined` (which admittedly looks weird, but it's the shortest way to get TS to play ball).

File: packages/create-svelte/templates/skeleton/src/app.d.ts (hunk 2 above)
Comment (Rich-Harris) [inline packages/create-svelte/templates/skeleton/src/app.d.ts:15]:
```suggestion
export {};
```

File: packages/kit/types/ambient.d.ts (hunk 6 above)
Comment (Rich-Harris) [reply packages/kit/types/ambient.d.ts:24]: In fact the text is a little confusing at the moment — it basically reads

> ```ts
> declare global {...}
> ```
>
> If you add an import, you'll need to change this so it says `declare global`

Hopefully only a handful of people who started projects before this change will get tripped up by imports — everyone else has nothing to worry about

**Review by Rich-Harris — APPROVED** [review]
