### PR TITLE
Make router-handled scrolling work with CSS properties

### LINKED ISSUE #1863: hash scroll doesn't work with scroll-margin CSS property
**Describe the bug**
Actually hash scroll is performed with:
https://github.com/sveltejs/kit/blob/5b3e1e6dcb6f809b5e6d1104c7132545598b1bb7/packages/kit/src/runtime/client/router.js#L273

The problem is that using `scrollTo` the CSS property [`scroll-margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin) doesn't get respected.

**To Reproduce**
Just use hash with anchors and apply the `scroll-margin` property to the target element.

**Expected behavior**
Consider using [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to fix the issue.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  ```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 18.77 GB / 31.42 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.64)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.13
    @sveltejs/kit: next => 1.0.0-next.120
    svelte: ^3.38.3 => 3.38.3
  ```

- Browser: Chrome
</details>

**Severity**
low

### PR DESCRIPTION
**Pull request by Allezxandre**
Fixes #1863.

Using `scrollIntoView` instead `scrollTo` naturally adds
support for more CSS scrolling properties when scrolling to IDs.

Properties like `scroll-margin` and `scroll-behavior` are supported by `scrollIntoView`.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test`
- [x] Lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Allezxandre** [comment]
This PR is ready, however I can't seem to make the tests pass (on this branch or on `master`'s)

As my proposed change is tiny, I assume this isn't my change that breaks the tests?

**Comment by benmccann** [comment]
The tests are all passing on the CI. Some are a bit flaky. Maybe they flake out more often on your machine

File: packages/kit/src/runtime/client/router.js [hunk 1]
```diff
@@ -269,8 +269,10 @@ export class Router {
 		if (scroll) {
 			scrollTo(scroll.x, scroll.y);
 		} else if (deep_linked) {
-			// scroll is an element id (from a hash), we need to compute y
-			scrollTo(0, deep_linked.getBoundingClientRect().top + scrollY);
+			// Here we use `scrollIntoView` on the element instead of `scrollTo`
```
Comment (benmccann) [inline packages/kit/src/runtime/client/router.js:272]:
```suggestion
			// Here we use `scrollIntoView` on the element instead of `scrollTo` because it
```
