### PR TITLE
fix: adjust missing inner content warning

### LINKED ISSUE #11127: Svelte 5: prompt "`<slot />` missing" when using children snippet instead of `<slot />` in +layout.svelte
### Describe the bug

Svelte 5: prompt "`<slot />` missing" when using children snippet instead of `<slot />` in +layout.svelte.

image

+layout.svelte file
```
<script>
  let { children } = $props()
</script>

{@render children()}
```

### Reproduction

as above ...

### Logs

_No response_

### System Info

```Shell
kit: 1.27.6
svelte: 5.0.0-next.13
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ignatiusmb**
Alright, v2 of #11380 

Svelte 5 can still use `<slot>` and `+layout` can now accept "named slots" with snippets. I think we can safely assume _some_ content will be rendered, as long as a `{@render` tag exists in the markup, without having to check which snippet(s) also exists in the script.

Closes #11127 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/exports/vite/index.js [hunk 1]
```diff
@@ -107,10 +107,14 @@ const warning_preprocessor = {
 		if (!filename) return;
 
 		const basename = path.basename(filename);
-		if (basename.startsWith('+layout.') && !content.includes('<slot')) {
+		if (
+			basename.startsWith('+layout.') &&
+			(!content.includes('<slot') || (isSvelte5Plus() && !content.includes('{@render')))
+		) {
```
Comment (Rich-Harris) [inline packages/kit/src/exports/vite/index.js:113]: Still not quite right — this means 'if content is missing `<slot` OR is Svelte 5 and content is missing `{@render`', which will always be true for Svelte 5 (unless both were present for some reason)

```suggestion
		const has_children = content.includes('<slot') || (isSvelte5Plus() && content.includes('{@render'));

		if (basename.startsWith('+layout.') && !has_children) {
```

**Review by Rich-Harris — APPROVED** [review]
