### PR TITLE
fix: prevent routes/layouts from having conflicting files through resets or different extensions

### LINKED ISSUE #9380: Multiple +layout/+page.svelte with layout reset should be forbidden
### Describe the problem

Because of the layout reset syntax, it is currently possible to create multiple +page.svelte (or +layout.svelte)

Exemple :
```
routes/path/page/
           +page.svelte
           +page@.svelte
           +page@path.svelte
```

Sveltekit seems to accept that, and choose the most complete file (`+page@my-path.svelte` in this example).

I think this should be incorrect and generate an error.

### Describe the proposed solution

Create a page with multiples +page.svelte file using layout-reset.

Example :
https://stackblitz.com/edit/sveltejs-kit-template-default-ro1dgr?file=README.md

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### LINKED ISSUE #9501: Potential conflict with .js and .ts files causing SK to ignore .js file
### Describe the problem

I noticed  potential conflict that may occur when both a `+page.js` and a `+page.ts` file are present in the same folder of a SK project. 

It appears that SK will ignore the `.js` file and utilize the `.ts` file instead. 

This can cause confusion and frustration for developers who may not be aware of this behavior and spend time attempting to troubleshoot the issue. 

Screenshot 2023-03-24 at 3 03 34 AM

### Describe the proposed solution

@kevmodrome  recommended that there should probably be some warning for this and we all agree.
 [The origin story on twitter](https://twitter.com/cradlydev/status/1639087757514674178?s=46&t=qrPYK0Jk4KR0APaMIjFCBg)

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gtm-nayan**
This is a continuation of #9488

closes #9380 
closes #9501
added the names of the conflicting files to the error message

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/core/sync/create_manifest_data/index.js [hunk 1]
```diff
@@ -227,28 +227,70 @@ function create_routes_and_nodes(cwd, config, fallback) {
 					config.kit.moduleExtensions
 				);
 
+				/**
+				 * @param {string} type
+				 * @param {string} existingFile
```
Comment (benmccann) [inline packages/kit/src/core/sync/create_manifest_data/index.js:232]: we should rename this variable to follow the convention since it's internal
```suggestion
				 * @param {string} existing_file
```

Comment (gtm-nayan) [reply packages/kit/src/core/sync/create_manifest_data/index.js]: oops, fixed

**Review by dummdidumm — APPROVED** [review]
