### PR TITLE
fix: make $app/navigation more resilient to bundler reordering

### LINKED ISSUE #7257: Cannot read properties of undefined (reading 'disable_scroll_handling')
### Describe the bug

Just appeared out of nowhere and bricked the whole app, won't go away no matter what.  Tried deleting node_modules + .svelte-kit then reinstall and still there.

```txt
navigation.js?v=92264f1c:16 
Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling') at navigation.js?v=92264f1c:16:11


Fails on:
export const disableScrollHandling = ssr
	? guard('disableScrollHandling')
	: client.disable_scroll_handling;  <---

with message: Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling')
```

### Reproduction

<https://github.com/secretgspot/sveltekit-auth-helper-bug>

installed sveltekit latest,
installed supabase-js v2,
installed auth-helpers-sveltekit

### Logs

_No response_

### System Info

```shell
{
	"name": "myapp",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview"
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"svelte": "^3.46.0",
		"vite": "^3.1.0"
	},
	"type": "module",
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.0",
		"@supabase/auth-helpers-sveltekit": "^0.8.2",
		"@supabase/supabase-js": "^2.0.0-rc.10"
	}
}
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gtm-nayan**
fixes #7257

Testing it would require creating a new project I think, and even then it likely wouldn't be deterministic so no tests for this one.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -1354,6 +1354,7 @@ export function create_client(app, target) {
 			return invalidate();
 		},
 
+		// TODO: Why is only this camel cased?
```
Comment (Conduitry) [inline packages/kit/src/runtime/client/client.js:1357]: No particular good reason, as far as I can tell, since some other things from here that are exposed in `packages/kit/src/runtime/app/navigation.js` are snake case in this file and then camel case in that file.

Comment (Conduitry) [reply packages/kit/src/runtime/client/client.js:1357]: This was added in #6493. I assume it was just a tiny slip-up. I'd be in favor of switching to `invalidate_all`.

**Comment by Rich-Harris** [comment]
This _does_ feel like a bit it's addressing the symptoms rather than the cause — I thought we'd already gone to some lengths to ensure that the client is initialised before any user code is imported. Would love to see if we can figure out how that's breaking, though if that turns out to be a massive rabbit hole then I'm not strongly opposed to this approach

**Comment by gtm-nayan** [comment]
It works well with the default settings, no symptoms or cause there, but once you start overriding it with manualChunks or experimentalMinChunkSize, it breaks because the navigation module ends up in the same chunk as the app entry's dependencies so the exports get evaluated before client is initialized.

I tried forcing navigation into its own chunk but even that seems to mess up the order somehow and it's small enough to not warrant its own chunk.

The client hooks are one of app's dependencies, so importing `$app/navigation` currently doesn't work there, although not sure whether that's something anyone will need.

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
Ah, fair enough — guess there's really not much else we can do in that case. Merging! Thanks
