### PR TITLE
fix: correctly check URL pathname with Cloudflare adapter

### LINKED ISSUE #8708: Cloudflare 404 for not excluded files in _routes.json with trailingSlash option
### Describe the bug

If we have 100+ routes (actually ~4000) for prerender all routes that are NOT in excluded list:
```
"exclude":["/_app/*","/.DS_Store","/favicon.png","/global.css","/vite-manifest.json","/","/__data.json","/bin/vimdiff","/bin/vimdiff/__data.json"
```
like `/bin/cat` gives 404. But we have `bin/cat/index.html` file locally. So prerender works 100% correct. It is not missing file.

Removing `export const trailingSlash = 'always';` seems like fixed that. It was quite easy after finding issue #8422 and `need to check that prerendered pages (with/without trailing slashes) will still work with this setup.` statement :)

### Reproduction

This 4000+ routes are rendered from private SQLite, but I can share this project with some of your developers by email.

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: 1.0.2 => 1.0.2 
    @sveltejs/kit: 1.2.6 => 1.2.6 
    svelte: 3.55.1 => 3.55.1 
    vite: 4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### LINKED ISSUE #8736: HTML files with space `%20` in name can't be accessed on cloudflare
### Describe the bug

Routes with space in filename like `/disk utility` gives 404 on cloudflare pages.

### Reproduction

https://macosbin.com/bin/disk%20utility

But this file exists in build directory:

image

And all works correctly while `npm run dev`

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 88.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: 1.0.2 => 1.0.2 
    @sveltejs/adapter-cloudflare: ^1.1.0 => 1.1.0 
    @sveltejs/kit: 1.2.9 => 1.2.9 
    svelte: 3.55.1 => 3.55.1 
    vite: 4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

### Additional Information

It is really bad a issue cause we need to replace ` ` with some other symbol to fix that 🥹

### PR DESCRIPTION
**Pull request by s3812497**
fixes #8708 
fixes #8736

I noticed a discrepancy where trailing slashes would be removed before checking if the file exists in `manifest.prerendered`.

This caused the pages with trailing slashes to never be found in the manifest.

Hopefully this fixes the issue for prerendered trailing slash pages that go through the Cloudflare worker.

Pages that manage to fit in the 100 rule limit for `_routes.json` do not go through the worker so they don't have this issue.

EDIT: expanded the scope of the PR to fix the URI encoding issue mismatch as well. It used to check the encoded pathname against the decoded paths in the manifest.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/adapter-cloudflare/src/worker.js [hunk 1]
```diff
@@ -36,26 +37,30 @@ const worker = {
...
-				manifest.assets.has(file + '/index.html') ||
-				prerendered.has(pathname)
-			) {
+			const stripped_pathname = pathname.replace(/\/$/, '') || '';
+
+			let is_asset = false;
+			const filename = stripped_pathname.substring(1);
+			if (filename) {
+				is_asset = manifest.assets.has(filename) || manifest.assets.has(filename + '/index.html');
+			}
```
Comment (dummdidumm) [inline packages/adapter-cloudflare/src/worker.js:54]: Could there theoretically be an asset named `index.html`? What was the reason for changing this?

Comment (s3812497) [reply packages/adapter-cloudflare/src/worker.js:54]: > Could there theoretically be an asset named index.html?
If a dev decides to include one in `/static` I suppose. It helps if someone navigates to that route.
This check was already there previously, but I suppose it's good to have it since the worker has to handle all file routing.

> What was the reason for changing this?
I thought it would be a small optimisation, although I'm unsure if it has an impact.
If the url is `https://test.com/`, then the resulting filename would be `''`. This skips the manifest check.

File: packages/adapter-cloudflare/src/worker.js [hunk 2]
```diff
@@ -17,7 +18,7 @@ const worker = {
 
 		let { pathname } = new URL(req.url);
 
-		// static assets
+		// immutable app assets
```
Comment (Rich-Harris) [inline packages/adapter-cloudflare/src/worker.js:21]: `_app` includes non-immutable stuff like `version.json`, so for correctness it should probably be something like this

```suggestion
		// generated files
```

File: packages/adapter-cloudflare/src/worker.js [hunk 3]
```diff
@@ -36,26 +37,30 @@ const worker = {
...
+			} catch {
+				// ignore invalid URI
 			}
 
-			if (
-				manifest.assets.has(file) ||
-				manifest.assets.has(file + '/index.html') ||
-				prerendered.has(pathname)
-			) {
+			const stripped_pathname = pathname.replace(/\/$/, '') || '';
```
Comment (Rich-Harris) [inline packages/adapter-cloudflare/src/worker.js:48]: surely the only time you'd hit the `|| ''` case is if the returned value is _already_ `''`?

```suggestion
			const stripped_pathname = pathname.replace(/\/$/, '');
```

File: packages/adapter-cloudflare/src/worker.js [hunk 4]
```diff
@@ -36,26 +37,30 @@ const worker = {
...
+
+			let is_asset = false;
+			const filename = stripped_pathname.substring(1);
+			if (filename) {
+				is_asset = manifest.assets.has(filename) || manifest.assets.has(filename + '/index.html');
+			}
+
+			const is_prerendered = prerendered.has(pathname) || prerendered.has(stripped_pathname);
```
Comment (Rich-Harris) [inline packages/adapter-cloudflare/src/worker.js:56]: is this check too permissive? if a trailing slash is present when it shouldn't be, or vice versa, we probably want to respond with a redirect rather than `env.ASSETS.fetch`

Comment (s3812497) [reply packages/adapter-cloudflare/src/worker.js]: You're right! I hadn't even thought of that. I've now added a redirect if there a trailing slash or non-trailing slash counterpart is found.

**Review by Rich-Harris — APPROVED** [review]
