### PR TITLE
fix: do not replace headers on fetch requests with error state

### LINKED ISSUE #13340: Missing headers on SSR requests made from an error state to an external backend
### Describe the bug

When all of these conditions are met:
* SSR request with server-side fetch
* Request initiated from an error page, such as `404`
* Request endpoint is on an external backend such as a Golang backend, not a [Sveltekit route](https://svelte.dev/docs/kit/routing#server-Receiving-data)

The headers of the request are dropped in favor of `x-sveltekit-error: true`

This issue prevents me from displaying the authenticated user of my app when the user reaches a 404 page for example.

## How to reproduce
I have created this repo https://github.com/aureleoules/sveltekit-headers-bug-reproduction

To reproduce:
```
$ git clone git@github.com:aureleoules/sveltekit-headers-bug-reproduction.git /tmp/repro && cd /tmp/repro
$ npm i 
$ npm run dev # in one terminal
$ go run main.go # in another terminal

> http://localhost:5173/
```

There are two API endpoints, one using the Sveltekit backend in `src/routes/sveltekit_route` to show that it works correctly using Sveltekit.
And one in `main.go` that shows headers are not passed properly using an external backend.

Both endpoints return the request headers in the response.

### Current behavior

On normal page: all headers present (cookie and custom-header)
Image

On error page: missing cookie and custom-header
Image

### Expected behavior

Fix in #13341

On normal page: all headers present (cookie and custom-header)
Image

On error page: all headers present (cookie and custom-header)
Image

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 6.02 GB / 15.20 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
    pnpm: 9.15.4 - /usr/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.108
  npmPackages:
    @sveltejs/adapter-auto: ^4.0.0 => 4.0.0 
    @sveltejs/adapter-node: ^5.2.12 => 5.2.12 
    @sveltejs/kit: ^2.0.0 => 2.16.0 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.4 
    svelte: ^5.0.0 => 5.19.0 
    vite: ^5.4.11 => 5.4.11
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by aureleoules**
Fixes #13340.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/server/respond.js [hunk 1]
```diff
@@ -508,11 +508,9 @@ export async function respond(request, options, manifest, state) {
 			}
 
 			if (state.error && event.isSubRequest) {
-				return await fetch(request, {
-					headers: {
-						'x-sveltekit-error': 'true'
-					}
-				});
+				const headers = new Headers(request.headers);
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/respond.js:511]: I'm fine with not having a test for this, but we should have a short comment here explaining why we do this

Comment (eltigerchino) [inline packages/kit/src/runtime/server/respond.js:511]:
```suggestion
        // avoid overwriting the headers. This could be a same origin fetch request
        // to an external service from the root layout while rendering an error page
				const headers = new Headers(request.headers);
```

Comment (eltigerchino) [reply packages/kit/src/runtime/server/respond.js:511]: added a comment

File: packages/kit/src/runtime/server/respond.js [hunk 2]
```diff
@@ -508,11 +508,11 @@ export async function respond(request, options, manifest, state) {
 			}
 
 			if (state.error && event.isSubRequest) {
-				return await fetch(request, {
-					headers: {
-						'x-sveltekit-error': 'true'
-					}
-				});
+        // avoid overwriting the headers. This could be a same origin fetch request
+        // to an external service from the root layout while rendering an error page
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/respond.js:512]:
```suggestion
				// avoid overwriting the headers. This could be a same origin fetch request
				// to an external service from the root layout while rendering an error page
```
