### PR TITLE
Don't normalize paths during prerendering

### LINKED ISSUE #4758: adapter-static build with `trailingSlash: "alway"` option fails.
### Describe the bug

build command try to access a file with trailing slash. (ex. `/favicon.png` -> `/favicon.png/`)

### Reproduction

- create app  using create-svelte, 'SvelteKit demo app'.
```
npm init svelte@next my-app  # Choose default options
cd my-app
```
- Add adapter-static
```
npm add -D @sveltejs/adapter-static@next
npm rm -D @sveltejs/adapter-auto
npm install
```
- Adjust `svelte.config.js` to use adapter-static, and `trailingSlash: 'always'` option.
```diff
--- a/svelte.config.js
+++ b/svelte.config.js
@@ -1,9 +1,10 @@
-import adapter from '@sveltejs/adapter-auto';
+import adapter from '@sveltejs/adapter-static';
 
 /** @type {import('@sveltejs/kit').Config} */
 const config = {
        kit: {
                adapter: adapter(),
+               trailingSlash: 'always',
 
                // Override http methods in the Todo forms
                methodOverride: {
```
- run build
```
npm run build
```

### Logs

```shell
npm run build

> my-app@0.0.1 build
> svelte-kit build

vite v2.9.6 building for production...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/manifest.json                                             2.67 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-7a649169.js                         4.76 KiB / gzip: 1.86 KiB
.svelte-kit/output/client/_app/error.svelte-f6969740.js                                  1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/about.svelte-103011ed.js                            2.51 KiB / gzip: 1.15 KiB
.svelte-kit/output/client/_app/pages/index.svelte-1e12193f.js                            5.47 KiB / gzip: 2.42 KiB
.svelte-kit/output/client/_app/pages/todos/index.svelte-43bb6c2c.js                      6.86 KiB / gzip: 2.88 KiB
.svelte-kit/output/client/_app/chunks/index-a0e90cc4.js                                  0.43 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/chunks/singletons-d1fb5791.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/assets/pages/about.svelte-bf4528fa.css                    0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/start-08e46c80.js                                         23.34 KiB / gzip: 8.67 KiB
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-15681802.css                 4.96 KiB / gzip: 1.55 KiB
.svelte-kit/output/client/_app/chunks/index-2db0445a.js                                  11.77 KiB / gzip: 5.00 KiB
.svelte-kit/output/client/_app/assets/pages/index.svelte-d0605c9c.css                    1.43 KiB / gzip: 0.51 KiB
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-a910a02d.css              3.70 KiB / gzip: 1.03 KiB
vite v2.9.6 building SSR bundle for production...
✓ 35 modules transformed.
.svelte-kit/output/server/manifest.json                         2.32 KiB
.svelte-kit/output/server/index.js                              75.29 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.js      1.33 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js      4.60 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js     0.72 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js         1.38 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js         8.18 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js   5.92 KiB
.svelte-kit/output/server/chunks/index-19ef195d.js              3.94 KiB
.svelte-kit/output/server/chunks/hooks-0bab96cd.js              0.48 KiB
> 404 /favicon.png/ (linked from /)
    at file:///tmp/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:988:11
    at save (file:///tmp/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1208:4)
    at visit (file:///tmp/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1099:3)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
```


### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 791.54 MB / 15.38 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/bin/node
    Yarn: 1.22.11 - ~/.npm-packages/bin/yarn
    npm: 8.5.0 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
    Firefox: 99.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.322 
    svelte: ^3.46.0 => 3.47.0
```

### Severity

blocking an upgrade

### Additional Information

Downgrading from @sveltejs/kit@1.0.0-next.322 to @sveltejs/kit@1.0.0-next.321 solves issue.

### PR DESCRIPTION
**Pull request by Rich-Harris**
#4699 was described as a breaking change and I wasn't lying. Didn't expect it to break _quite_ this badly though.

This fixes #4758 by skipping naive path normalization during prerendering, and relying on `server.respond` to apply normalization with knowledge of whether a route is a page or an endpoint. With that, we can handle 3xx responses normally during prerendering, but only writing redirects to disk if they're _not_ just normalizations. (I guess we could write them to disk as well? But that would be a change from previous behaviour, so I figured I'd do it this way for now.)

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/core/build/prerender/prerender.js [hunk 1]
```diff
@@ -202,28 +201,29 @@ export async function prerender({ config, entries, files, log }) {
...
-				mkdirp(dirname(dest));
-
-				log.warn(`${response.status} ${decoded} -> ${location}`);
-
-				writeFileSync(
-					dest,
-					`<meta http-equiv="refresh" content=${escape_html_attr(`0;url=${location}`)}>`
-				);
-
 				let resolved = resolve(encoded, location);
```
Comment (benmccann) [inline packages/kit/src/core/build/prerender/prerender.js:204]:
```suggestion
				const resolved = resolve(encoded, location);
```

**Comment by benmccann** [comment]
Note that https://github.com/sveltejs/kit/pull/4751 is adding some logic to preview mode similar to the logic in dev mode that is being modified here, so if that PR is merged first then this one will need to be updated to modify the preview mode logic as well
