### PR TITLE
fix: builder.copy is not a function while building with adapter-vercel

### LINKED ISSUE #617: adapter-vercel build fails with TypeError: builder.copy is not a function
**Describe the bug**
adapter-vercel build fails with with TypeError: builder.copy is not a function

"@sveltejs/adapter-vercel": "^1.0.0-next.8",
"@sveltejs/kit": "^1.0.0-next.56",
"svelte": "^3.35.0",

**Logs**
```
> Using @sveltejs/adapter-vercel
> builder.copy is not a function
TypeError: builder.copy is not a function
    at adapt (/Users/harold/code/translate-image/node_modules/@sveltejs/adapter-vercel/index.js:24:12)
    at adapt (file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/chunks/index5.js:757:8)
    at file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/cli.js:512:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! translate-image@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the translate-image@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**To Reproduce**
1. Brand new SvelteKit repo
2. Replace node adapter with vercel adapter
3. Update dependencies
   "@sveltejs/adapter-vercel": "^1.0.0-next.8",
   "@sveltejs/kit": "^1.0.0-next.56",
   "svelte": "^3.35.0",
4. npm run build

**Expected behavior**
Successfull build

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

TypeError: builder.copy is not a function
    at adapt (/Users/harold/code/translate-image/node_modules/@sveltejs/adapter-vercel/index.js:24:12)
    at adapt (file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/chunks/index5.js:757:8)
    at file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/cli.js:512:11

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
```
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers
npx: installed 1 in 1.361s

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 196.52 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.56 => 1.0.0-next.56
    svelte: ^3.35.0 => 3.35.0
```
- Your browser
N/A

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Vercel

**Severity**
Blocking Entirely

Note: the more honest and specific you are here the more we will take you seriously.

### PR DESCRIPTION
**Pull request by chrsep**
Hi, I noticed that the `builder.copy` line was replacing a line that calls the copy function in @sveltejs/app-utils/files. I found that the same function is now exported by `@sveltejs/kit/filesystem`. So I tried replacing builder.copy with the copy function from `@sveltejs/kit/filesystem`.

I've tested this on the realworld.svelte.dev example project by temporarily replacing its adapter-node with adapter-vercel and it seems to be working.

Fixes  #617.

### CODE REVIEW

File: packages/adapter-vercel/index.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 const { writeFileSync, mkdirSync, renameSync } = require('fs');
 const { resolve, join } = require('path');
+const { copy } = require('@sveltejs/kit/filesystem');
```
Comment (wiesson) [inline packages/adapter-vercel/index.js:3]: Isn't kit using ESM (?) I'm wondering if `adapter-vercel` (cjs) can import the copy fn

**Review by antony — CHANGES_REQUESTED** [review]
Thanks, but this isn't the correct fix. We should be adding `copy` to the builder function.

See `Builder.js` where we add `rimraf` etc :)

**Comment by chrsep** [comment]
Hi @antony, I've updated the PR and added the copy function to the builder function and `builder.copy` now works.
