### PR TITLE
fix: prevent unhandled exception crashes for invalid header values

### LINKED ISSUE #9628: Bad response headers kill node process rather than 500 error
### Describe the bug

When setting response headers, if the headers contain any characters which match the regex [/[^\t\x20-\x7e\x80-\xff]/](https://github.com/nodejs/node/blob/9b1ed04f2f0cbe74dbbfa963a8fcc7f5a5148bf9/lib/_http_common.js#LL216C51-L216C51) then the entire NodeJS process will die (not just a 500).

Not sure it needs fixing as it can be avoided. I'm just curious why this exception is not caught and instead leads to the Node process dying.

### Reproduction

Plausible example of `+page.server.js` redirecting to a user-controlled value (setting Location header) which could contain null bytes or newlines.

```ts
import type { PageServerLoad } from './$types';

import { redirect } from '@sveltejs/kit';

export const load = (async ({ url }) => {
  const next = url.searchParams.get("n")
  if (next) {
    throw redirect(307, "/blah/?n=" + next);
  }
}) satisfies PageServerLoad;
```

Example repo to run https://github.com/bcaller/svelte-tip/blob/master/src/routes/%2Bpage.server.ts

Then hit `/?n=%0D` or `/?n=%00` or `/?n=%1e`.

Note that this occurs the same regardless of whether load is marked as `async` or not.

### Logs

```Shell
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["location"]
    at ServerResponse.setHeader (node:_http_outgoing:647:3)
    at ServerResponse.writeHead (node:_http_server:377:21)
    at setResponse (file:///.../node_modules/@sveltejs/kit/src/exports/node/index.js:118:6)
    at file:///.../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:529:6
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_CHAR'
}

Node.js v18.12.1
```

### System Info

```Shell
Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 2.0.0
    @sveltejs/kit: next => 1.15.2
    svelte: next => 3.58.0
    vite: ^4.2.0 => 4.2.1
```

### Severity

serious, but I can work around it

### Additional Information

Could maybe be used for Denial of Service (DoS)

### PR DESCRIPTION
**Pull request by gtm-nayan**
fixes #9628 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/exports/node/index.js [hunk 1]
```diff
@@ -105,29 +105,36 @@ export async function getRequest({ request, base, bodySizeLimit }) {
...
+				key,
+				key === 'set-cookie'
+					? set_cookie_parser.splitCookiesString(
+							// This is absurd but necessary, TODO: investigate why
+							/** @type {string}*/ (response.headers.get(key))
+					  )
+					: value
+			);
+		} catch (error) {
+			res.getHeaderNames().forEach((name) => res.removeHeader(name));
```
Comment (dummdidumm) [inline packages/kit/src/exports/node/index.js:120]: Not sure on this one - should we just remove all headers, or just the ones up until the error, or try to parse the other headers and add all but the invalid ones? Are there any security implications to this?

Comment (gtm-nayan) [reply packages/kit/src/exports/node/index.js:120]: My thinking was that it's an entirely different response because of the error and it shouldn't carry over any of the original headers.

>  should we just remove all headers, or just the ones up until the error

In its current state at least, those two would mean the same as all the headers haven't yet been copied over to the `res` object yet, in essence we're undoing earlier iterations of this loop.

File: packages/kit/test/apps/basics/test/server.test.js [hunk 2]
```diff
@@ -485,19 +494,20 @@ test.describe('setHeaders', () => {
 	test('allows multiple set-cookie headers with different values', async ({ page }) => {
 		const response = await page.goto('/headers/set-cookie/sub');
 		const cookies = (await response?.allHeaders())['set-cookie'];
-		expect(cookies.includes('cookie1=value1') && cookies.includes('cookie2=value2')).toBe(true);
+
+		expect(cookies).toMatch('cookie1=value1');
```
Comment (benmccann) [inline packages/kit/test/apps/basics/test/server.test.js:498]: should we also check that there are no unexpected values?

**Review by dummdidumm — APPROVED** [review]
