### PR TITLE
fix: prevent history change when clicking same hash link

### LINKED ISSUE #8725: Clicking hash link twice on Firefox breaks back navigation
### Describe the bug

This issue only occurs when using the desktop Firefox browser.

Clicking a hash link twice then navigating to a new page causes the browser back navigation to change the URL but no navigation occurs.

### Reproduction

https://stackblitz.com/edit/github-lxdc8e?file=src%2Froutes%2F%2Blayout.svelte

1. Preview the website in a desktop Firefox browser.
3. On the same page, click the "Go to footer" hash link twice.
4. Navigate to a different page.
5. Press the browser back button.
6. The browser does not navigate back but the URL changes.

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.76 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Chrome Canary: 111.0.5559.0
    Firefox: 109.0
    Firefox Developer Edition: 105.0
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/kit: ^1.0.0 => 1.2.8 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by trueadm**
Fixes #8725.

This PR fixes an outstanding issue with routing hash links in Firefox. Specifically, clicking a link that contains as hash and where the link is the same as the current page URL, Firefox clears the history `state`, causing browser navigation to fail thereafter. In order to tackle this, we need to detect where the URL for a hash link is the same and manually prevent any client-side routing to take place. Instead we just apply the same scrolling heuristics – fixing the issue in FF.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -1539,6 +1539,15 @@ export function create_client(app, target) {
 				// Removing the hash does a full page navigation in the browser, so make sure a hash is present
 				const [nonhash, hash] = url.href.split('#');
 				if (hash !== undefined && nonhash === location.href.split('#')[0]) {
+					// If we are trying to navigate to the same hash, we should only
+					// attempt to scroll to that element and avoid any history changes.
+					// Otherwise, this can cause Firefox to incorrectly assign a null
+					// history state value without any signal that we can detect.
+					if (current.url.hash === url.hash) {
+						event.preventDefault();
+						a.scrollIntoView();
```
Comment (gtm-nayan) [inline packages/kit/src/runtime/client/client.js:1548]: Shouldn't this be `document.getElementById(hash).scrollIntoView()` instead?

**Review by Rich-Harris — APPROVED** [review]

**Comment by flayks** [comment]
@trueadm @dummdidumm I'm using #contact and #cart hashes to open a popin over my site (a contact form and a shopping cart), but since this fix I can only open and close them once. In order to open one, I now have to close one to be able to open the other.  
Ideally I'd need the new [Shallow routing](https://github.com/sveltejs/kit/pull/9847) feature but it's still in WIP. Is there any workaround for this issue until then?

Here is how I implement it:
```tsx
// +layout.svelte - detect hashchange to change my stores that open each popin
const handleHashChange = () => {
    $showContact = window.location.hash === '#contact'
    $cartOpen = window.location.hash === '#cart'
}


// Header.svelte - close function when clicking on a button
const handleButtonClick = (event: MouseEvent, name: string) => {
    // Contact/Cart: Close popin
    if (
        (name === 'contact' && $showContact) ||
        (name === 'cart' && $cartOpen)
    ) {
        closePopin()
        event.preventDefault()
    }
}

<Button
    size="small"
    href="#cart"
    label={$cartAmount > 0 ? String($cartAmount) : null}
    on:click={event => handleButtonClick(event, 'cart')}
/>


// utils/functions.ts - closing the popin
export const closePopin = () => {
    // Remove hash from url
    history.pushState({}, '', window.location.href.split('#')[0])

    // Trigger
    window.dispatchEvent(new HashChangeEvent('hashchange'))
}
```

**Comment by trueadm** [comment]
@flayks What happens if you remove the `event.preventDefault()` from your code above?

**Comment by flayks** [comment]
@trueadm unfortunately nothing… 😅  I've tried that before thinking that it would block the click situation

**Comment by trueadm** [comment]
You shouldn't need to do `window.dispatchEvent(new HashChangeEvent('hashchange'))` if you don't prevent default.

**Comment by flayks** [comment]
I think `history.pushState({}, '', window.location.href.split('#')[0])` is not triggering a `hashchange` event if I'm correct, and I'd like to avoid an empty hash (/page#) which would jump to the top of the page

**Comment by trueadm** [comment]
If I'm not mistaken, your logic was working before because of a bug in the routing logic. I think the best approach you'd want to take, is to capture the scroll position and then re-instate it after the route change. I'm very new to SvelteKit, but maybe there's some API exposed that you can use that allows for a route change that keeps scroll position the same without needing to `pushState` manually. If not, then you can try doing that yourself?

**Comment by flayks** [comment]
I feel that even using `window.location.hash = ''` and no `event.preventDefault()` anywhere including in the `closePopin` function, this fix really prevents to open the same hash after having it triggered once.

**Comment by flayks** [comment]
I did a little test here for the contact hash:
```ts
if (name === 'contact') {
    if ($showContact) {
        closePopin()
    } else {
        window.location.hash = 'contact'
    }
}
```

When triggered manually like so, it allows to "force" the hash to change. It looks a bit counterproductive regarding the hash link of my button but that's the only workaround I found so far 🤷 

This is fine on my Header, although I have these buttons in other places and need to implement the same workaround everywhere which I really would like to avoid.

**Comment by boczpeter** [comment]
This patch introduces a killer bug in my app.
I use #hash navigation to open dialog content, which can be closed by a button (executing history.back()) or the browser's back button. Now the user cannot open the same dialog, because you disabled client navigation and the link becomes dead. This shouldn't be standard procedure.
What is the recommended workaround for this?
I need to pin the app version to 1.18.0 until it is resolved.
