### PR TITLE
Always avoid caching form submission on enhanced forms

### LINKED ISSUE #6357: Invalidatation should always query the invalid server nodes with `fetch({ cache: 'no-cache' })`
### Describe the bug

During my work of the (simple) demo of PR #6265, I have found that the "TODO" items "get stuck" in the cache in IE11, after the demo invalidation.
After digging into Kit's code, I found out that the "dumb" IE11 ignore the request headers (specifically, "x-sveltekit-invalidated") if it hit the cache, so this is why it's less likely to hit this issue on other browsers.

I must have been explaining the issue terribley now, so I'll just explain what is wrong with Kit's code. In:
https://github.com/sveltejs/kit/blob/05e8240150da446f6cd3c1f0feb4447408b2b43b/packages/kit/src/runtime/client/client.js#L716-L725
it's possible that the browser will use the cache, in the rare case that the header 'x-sveltekit-invalidated' matched to a cached request (or in the case we're on IE11 which probably ignores headers on caching), although clearly this target has been marked as invalid and must not be cached.

Solution:
Add `cache: 'no-cache'` as a parameter to `native_fetch`. This means that the browser will always query the server and check for the server response (even if it have cache), but allow the browser to cache the updated response for later. ([Source](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache#value))
I'll upload PR soon.

Might be the root reason for the failure of #6354 and #6349 .

### Reproduction

Use the simple demo I mentioned on PR #6265.
You'll notice the wrong caching behavior while trying to add/remove items in the TODO list.
After changing Kit's code at the place I mentioned, it works.

### Logs

_No response_

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 2.92 GB / 15.49 GB
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.67
    @sveltejs/kit: npm:@tal500/kit@1.0.0-next.445-legacy-builds-3 => 1.0.0-next.445 (Yeah I know, it's my fork version of Kit with the legacy support...)
    @tal500/svelte:  3.49.0-repo-advanced-1
    vite: ^3.1.0-beta.0 => 3.1.0-beta.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Tal500**
Due to the return of regular JSON requests of #7177, issue #6357 is relevant back again. Although now I couldn't reproduce the behavior, it stills problematic and needed to be fixed.

Clearly, when you simulate regular form submission, you should check that the browser never used a cached result of previous POST request.

It is unclear how browsers choose to handle this situation, see [this stackoverflow question](https://webmasters.stackexchange.com/questions/111298/what-happens-if-you-dont-set-cache-control-header).
Since browsers seems to be more careful on programically `fetch` POST requests, I couldn't catch a browser really use caching for this "no cache-control header" responses.

Currently on form submission from enhanced forms, there is no cache control header from the server, no cache guideline on the `fetch` function, so I think that the best solution is to guide the browser in the `fetch` method of the submission, to not use previously cached results.

fixes #6357 (in some sense)

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [X] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [X] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [X] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/app/forms.js [hunk 1]
```diff
@@ -86,6 +86,7 @@ export function enhance(form, submit = () => {}) {
 					accept: 'application/json',
 					'x-sveltekit-action': 'true'
 				},
+				cache: 'no-cache',
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/app/forms.js:89]: Is there a reason to use `no-cache` rather than `no-store`? My understanding is that `no-cache` (confusingly) means 'cache but don't use the cached result', while `no-store` means 'don't cache', which seems more... thorough. But if `no-cache` is preferred I will confess ignorance

```suggestion
				cache: 'no-cache',
```

Comment (Tal500) [reply packages/kit/src/runtime/app/forms.js:89]: I'm also not sure what is the best practice, I also know only the shallow definitions.

One theoretical advantage of `no-cache` comparing to `no-store`, is that if we have the following story:
1. The user post a guess for sverdle, and it's not a valid word, so the server returns "bad guess"
2. The user post another guess for sverdle, and it's also not a valid word, so the server returns "bad guess" back again.

If the cache is stored, then the browser can use the `ETag` HTTP header to check if the server response will be different, and then avoid full download.

Clearly it makes no sense in this small response, but in other cases (like server data processing) it might be useful.
On the other side, in small responses, the cache will be so small, so "who cares".

What do you think? Should it be `no-store` by default, but let the user override the cache parameter if he wishes?

Comment (Rich-Harris) [reply packages/kit/src/runtime/app/forms.js]: Ah, interesting — didn't consider the ETag case. Since the action would have to generate those ETags manually (it doesn't happen automatically, unlike with pages, though maybe we could change that? Unsure if worth it), I suspect this is more of a theoretical benefit than anything, whereas `no-store` feels a bit more belt-and-braces. I see you changed it to `no-store` in the meantime — let's roll with that for now. Thanks!

**Review by Rich-Harris — APPROVED** [review]
