### PR TITLE
fix: ensure SSR rendering gets request store context

### LINKED ISSUE #14473: All remote query functions are broken on svelte >= 5.39.1
### Describe the bug

Using any `query` function throws
```
Error: Could not get the request store. This is an internal error.
```

The issue exists on svelte version 5.39.1 and above.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-yp7ab2lr?file=src%2Froutes%2F%2Bpage.svelte

### Logs

```Shell
Error: Could not get the request store. This is an internal error.
    at get_request_store (file:/home/projects/sveltejs-kit-template-default-yp7ab2lr/node_modules/@sveltejs/kit/src/exports/internal/event.js:64:9)
    at wrapper (node_modules/@sveltejs/kit/src/runtime/app/server/remote/query.js:73:45)
    at <anonymous> (src/routes/+page.svelte:3:15)
    at child (node_modules/svelte/src/internal/server/renderer.js:112:20)
    at component (node_modules/svelte/src/internal/server/renderer.js:137:22)
    at _page (src/routes/+page.svelte:12:14)
```

### System Info

```Shell
playground
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #14473

No tests because this fix will be very short-lived and will not regress

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/server/page/render.js [hunk 1]
```diff
@@ -202,18 +202,26 @@ export async function render_response({
...
-				rendered = with_request_store({ event, state: event_state }, () =>
-					options.root.render(props, render_opts)
-				);
+				rendered = with_request_store({ event, state: event_state }, () => {
+					const result = options.root.render(props, render_opts);
+					// Svelte 5.39.0 changed the properties lazily start the rendering to be able to have the same signature for sync and async render.
+					// 5.39.1 extended that to the old class components. Rendering isn't started until one of the properties is accessed, so we do that here,
+					// else we might get errors about missing request store context
+					result.html;
+					return result;
```
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/src/runtime/server/page/render.js:211]: We can just `return { ...result }` I think, don't care too much though
