### PR TITLE
[fix] Handle `throw error/redirect` in `+server.js`

### LINKED ISSUE #5993: Incorrect response `status code` when throwing error from `+server.ts`
### Describe the bug

When throwing an error from a `+server.ts` route, the `status code` in the `response header` is set to `500` instead of the status code specified in the `error()` helper. The nearest Error Boundary does render and the `error` property in the `$page` store does have the correct status code, however the response header doesn't match.

### **+server.ts**

```
import { error, redirect } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

export const GET: RequestHandler = ({ params }) => {
	if (true) {
		throw error(404, 'Shortcode Not Found');
	}

	return redirect(301, 'https://kit.svelte.dev');
};
```

### **Response Header**

```
Status Code: 500 Internal Server Error
```

### **$page store**

```
{
  error: HttpError {
    name: 'HttpError',
    stack: undefined,
    status: 404,
    message: 'Shortcode Not Found'
  },
  params: { shortcode: 'test' },
  routeId: '[shortcode]',
  status: 500,
  url: URL {
    href: 'http://localhost:5173/test',
    origin: 'http://localhost:5173',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:5173',
    hostname: 'localhost',
    port: '5173',
    pathname: '/test',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  data: {}
}
```

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.49 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    npm: 8.16.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 104.1.42.95
    Chrome: 104.0.5112.79
    Firefox Developer Edition: 104.0
    Safari: 15.6
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64
    @sveltejs/kit: next => 1.0.0-next.417
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.8
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #5993

This results in a (in my opinion correct) change in behavior: If you `throw` an `error`, you will no longer have the message rendered in the nearest `+error.svelte`, instead it's just blank text, which is what I'd expect from querying a regular endpoint.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/server/endpoint.js [hunk 1]
```diff
@@ -29,16 +30,29 @@ export async function render_endpoint(event, route) {
...
+	} catch (error) {
+		if (error instanceof HttpError) {
+			return new Response(error.message, { status: error.status });
+		} else if (error instanceof Redirect) {
+			return new Response(undefined, {
+				status: error.status,
+				headers: { Location: error.location }
+			});
+		} else {
+			throw error;
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/endpoint.js:55]: Should this be converted into a `Response`, too? If it isn't this means unexpected errors get a regular "page" treatment and they are rendered within possible `+error.svelte` pages which seems wrong.

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/endpoint.js:55]: I think so, yeah

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/endpoint.js:55]: though actually... i wonder if that should happen at the bottom of `respond`. We already have a `TODO` comment there asking this exact question.

that way we get all the `options.handle_error` and sanitization logic centralised

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/endpoint.js:55]: gah, ok that's not possible because we want to render an error page if user code errors in `handle` (at least, that's the decision we made at some point in the past).

i do feel like there's some opportunities for simplification around error handling generally. might noodle in a separate PR. will merge this in the meantime though, no point in delaying it

**Review by Rich-Harris — APPROVED** [review]
