### PR TITLE
fix: version range handling in update_pkg function

### LINKED ISSUE #11693: svelte-migrate downgrades adapters
### Describe the bug

I just ran `npx svelte-migrate sveltekit-2` in a project to which I had already upgraded `@sveltejs/adapter-vercel` to the latest version (5.1.0). It downgraded me to 4.0.0

### PR DESCRIPTION
**Pull request by codenoid**
keep user's library version if higher than hard-defined version

fixes #11693 

---

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/migrate/utils.js [hunk 1]
```diff
@@ -215,6 +215,32 @@ export function update_pkg(content, updates) {
...
+			// Find the max version that satisfies the provided version range
+			const maxProvidedVersion = semver.maxSatisfying([version], version);
+
+			// Skip if the max existing version is greater than or equal to the max provided version
+			if (
+				maxExistingVersion &&
+				maxProvidedVersion &&
+				semver.gte(maxExistingVersion, maxProvidedVersion)
+			) {
+				return;
```
Comment (dummdidumm) [inline packages/migrate/utils.js:240]: This logic is a bit duplicative to the one that follows afterwards, can we include one logic into the other?

**Comment by codenoid** [comment]
let me add another test

File: .changeset/silly-donkeys-shout.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"svelte-migrate": minor
+---
+
+fix: version range handling in update_pkg function
```
Comment (dummdidumm) [inline .changeset/silly-donkeys-shout.md:5]:
```suggestion
"svelte-migrate": patch
---

fix: don't downgrade versions when bumping dependencies
```

File: packages/migrate/migrations/sveltekit-2/migrate.spec.js [hunk 3]
```diff
@@ -30,3 +31,22 @@ for (const sample of read_samples(new URL('./tsjs-samples.md', import.meta.url))
 		assert.equal(actual, sample.after);
 	});
 }
+
+test('Does not downgrade versions', () => {
```
Comment (dummdidumm) [inline packages/migrate/migrations/sveltekit-2/migrate.spec.js:35]: I think it would be better to have a general test in `utils.spec.js`, since this isn't specific to the SvelteKit 2 migration

File: packages/migrate/utils.js [hunk 4]
```diff
@@ -205,54 +205,65 @@ export function posixify(str) {
...
-			log_migration(`Added ${name} version ${version} ${additional}`);
-		}
-	}
-
-	for (const update of updates) {
-		update_pkg(...update);
-	}
-
-	return JSON.stringify(pkg, null, indent);
+    const indent = content.split('\n')[1].match(/^\s+/)?.[0] || '  ';
```
Comment (dummdidumm) [inline packages/migrate/utils.js:208]: formatting looks wrong (spaces instead of tabs). I just realized that the `migrate` package doesn't have the related scripts: Could you add
```json
		"lint": "prettier --check .",
		"format": "pnpm lint --write",
```
to the `package.json`? Then you can format with `pnpm format` and CI would now fail correctly with wrong formatting

**Review by dummdidumm — COMMENTED** [review]
Thank you! This looks much better, left a few comments

File: packages/migrate/utils.js (hunk 4 above)
Comment (codenoid) [reply packages/migrate/utils.js:208]: should the `pnpm format` be separated PR ? because the change is a lot

Comment (codenoid) [reply packages/migrate/utils.js:208]: maybe, I will add only related file for this PR

Comment (dummdidumm) [reply packages/migrate/utils.js:208]: From my local testing it only changes a couple of files, and only in a few places, I'm ok with that.

File: pnpm-lock.yaml [hunk 5]
```diff
@@ -1107,7 +1107,7 @@ importers:
         version: 3.1.1
       vitest:
         specifier: ^1.2.0
-        version: 1.2.0(@types/node@18.19.3)(lightningcss@1.22.1)
+        version: 1.2.1(@types/node@18.19.3)
```
Comment (dummdidumm) [inline pnpm-lock.yaml:1110]: Can you remove the changes to this lock file entirely (probably by copying over the latest lock file from main)?
