### PR TITLE
document `Output` of `RequestHandler`

### LINKED ISSUE #5468: Interfaces for shadow endpoints
### Describe the bug

https://github.com/sveltejs/kit/issues/1997 seems to still be happening - when `get()` is typed as a RequestHandler and returns data defined as an interface, Typescript throws a `JSONValue` complaint.

### Reproduction

```
// things.ts

import type {RequestHandler} from "@sveltejs/kit"
interface Thing {...} // JSONValue error
type Thing = {...} // no error

const things: Thing[] = [{...}, {...}]

export const get: RequestHandler = async () => {
    return {
        body: {
            things,
        },
    }
}
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 82.88 MB / 16.00 GB
    Shell: 3.5.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0.1
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.55
    @sveltejs/kit: next => 1.0.0-next.367
    svelte: >=3.46.0 => 3.49.0
    vite: >=2.9.13 => 2.9.14
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ignatiusmb**
Closes #5468 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by 7antra — APPROVED** [review]

File: packages/kit/types/index.d.ts [hunk 1]
```diff
@@ -246,7 +246,9 @@ export interface RequestEvent<Params extends Record<string, string> = Record<str
 /**
  * A `(event: RequestEvent) => RequestHandlerOutput` function exported from an endpoint that corresponds to an HTTP verb (`get`, `put`, `patch`, etc) and handles requests with that method. Note that since 'delete' is a reserved word in JavaScript, delete handles are called `del` instead.
  *
- * Note that you can use [generated types](/docs/types#generated-types) instead of manually specifying the `Params` generic argument.
+ * It receives `Params` as the first generic argument, which you can skip by using [generated types](/docs/types#generated-types) instead.
+ *
+ * The next generic argument `Output` is used to validate the returned `body` from your functions by passing it through `BodyValidator`, this will make sure the variable in the `body` matches what with you assign here. It defaults to `ResponseBody`, which will error when `body` receives a [custom object type](https://www.typescriptlang.org/docs/handbook/2/objects.html).
```
Comment (Rich-Harris) [inline packages/kit/types/index.d.ts:251]:
```suggestion
 * The next generic argument `Output` is used to validate the returned `body` from your functions by passing it through `BodyValidator`, which will make sure the variable in the `body` matches what with you assign here. It defaults to `ResponseBody`, which will error when `body` receives a [custom object type](https://www.typescriptlang.org/docs/handbook/2/objects.html).
```
