### PR TITLE
fix: do not mutate URL during reroute logic

### LINKED ISSUE #13220: page.url has wrong path on the client (sveltekit 2.14 regression bug)
### Describe the bug

The `$page.url.pathname` resolves differently on the server and client. 

- The bug has been introduced with version `2.14`. 
- See the video for more context

### Reproduction

https://github.com/samuelstroschein/sveltekit-page-regression-bug

1. `npm i`
2. `npm run dev`
3. open the `/pl` route
4. see how the pathname changes

https://github.com/user-attachments/assets/330922fe-dcf7-41ae-a6f8-e4771b8f44f5

### Logs

_No response_

### System Info

```Shell
Couldn't run.


npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /Users/samuel/.nvm/versions/node/v18.18.0/lib/node_modules/node/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/samuel/.nvm/versions/node/v18.18.0/lib/node_modules/node/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #13220

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Review by trueadm — APPROVED** [review]

File: packages/kit/test/apps/hash-based-routing/test/test.js [hunk 1]
```diff
@@ -72,13 +72,13 @@ test.describe('hash based navigation', () => {
...
-		expect(url.hash).toBe('#/rerouted');
+		expect(url.hash).toBe('#/reroute-a');
 
 		await page.goto('/');
 
 		await page.locator('a[href="/#/reroute-b"]').click();
 		await expect(page.locator('p')).toHaveText('rerouted');
 		url = new URL(page.url());
-		expect(url.hash).toBe('#/rerouted');
+		expect(url.hash).toBe('#/reroute-b');
```
Comment (dummdidumm) [inline packages/kit/test/apps/hash-based-routing/test/test.js:82]: turns out there even was a test that could've caught this, but the test assertion was wrong

**Comment by samuelstroschein** [comment]
Thanks for fixing the bug so quickly @dummdidumm. Enjoy the holidays!
