### PR TITLE
[fix] handle set-cookie in setHeaders

### LINKED ISSUE #6032: Cannot set set-cookie response headers multiple times
### Describe the bug

Since the `setHeaders` takes a POJO and also checks that a response header as not been already set, one cannot set multiple cookies with multiple `set-cookie` headers. 

### Reproduction

Source code for `setHeaders` checks whether an header is already been set, so can’t even call it multiple times.

### Logs

_No response_

### System Info

```shell
Any system
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #6032

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/server/index.js [hunk 1]
```diff
@@ -143,12 +143,28 @@ export async function respond(request, options, state) {
 				const lower = key.toLowerCase();
 
 				if (lower in headers) {
-					throw new Error(`"${key}" header is already set`);
+					if (lower === 'set-cookie') {
+						if (!Array.isArray(headers[lower])) {
+							headers[lower] = [/**@type{string} */ (headers[lower])];
+						}
+						const cookies = /**@type{string[]} */ (headers[lower]);
+						const new_cookies = /**@type{string[]} */ (
```
Comment (benmccann) [inline packages/kit/src/runtime/server/index.js:151]: elsewhere we've been formatting like so:
```suggestion
							headers[lower] = [/** @type{string} */ (headers[lower])];
						}
						const cookies = /** @type{string[]} */ (headers[lower]);
						const new_cookies = /** @type{string[]} */ (
```

File: packages/kit/src/runtime/server/index.js [hunk 2]
```diff
@@ -143,12 +143,28 @@ export async function respond(request, options, state) {
...
+							if (cookies.includes(new_cookie)) {
+								throw new Error(`"${key}" header already has cookie with same value`);
+							}
+							cookies.push(new_cookie);
+						}
+					} else {
+						throw new Error(`"${key}" header is already set`);
+					}
+				} else {
+					// TODO apply these headers to the response <- is this TODO outdated?
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/index.js:164]: yes it is

```suggestion
```

**Review by Rich-Harris — APPROVED** [review]
