### PR TITLE
fix(adapter-netlify)!: write output conforming to Netlify Frameworks API

### LINKED ISSUE #15169: Refactor Netlify adapter to match new serverless function expected output
### Describe the problem

Whilst investigating https://github.com/sveltejs/kit/pull/14686 , it became evident that we need to match Netlify's new serverless and edge function API or it won't work with their new dev server.

### Describe the proposed solution

Refactor the build output to more closely match the following:
- serverless: https://docs.netlify.com/build/functions/get-started/?data-tab=TypeScript#write-a-function
- edge: https://docs.netlify.com/build/edge-functions/declarations/#declare-edge-functions-inline

### Alternatives considered

_No response_

### Importance

would make my life easier

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by serhalp**
~~(Stacked on top of https://github.com/sveltejs/kit/pull/15203)~~

closes #15169

The current implementation of the Netlify adapter writes output to paths and config files that are under-documented and in some cases entirely undocumented.

18 months ago, Netlify addressed this by releasing the stable, documented Netlify Frameworks API](https://docs.netlify.com/build/frameworks/frameworks-api/).

This PR migrates the adapter to write output that conforms to this spec.

POTENTIALLY BREAKING CHANGE: Deploying and previewing with Netlify CLI now requires [v17.31.0](https://github.com/netlify/cli/releases/tag/v17.31.0) or later. Run `npm i -g netlify-cli@latest` to upgrade.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests

- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets

- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/adapter-netlify/index.js [hunk 1]
```diff
@@ -302,58 +272,48 @@ function generate_lambda_functions({ builder, publish, split }) {
...
+		const fn = `import { init } from '../serverless.js';\n\nexport default init(${manifest});\n\nexport const config = {\n\tname: "SvelteKit server",\n\tgenerator: "${get_generator_string()}",\n\tpath: "/*",\n\texcludedPath: "/.netlify/*",\n\tpreferStatic: true\n};\n`;
 
-		writeFileSync(`.netlify/functions-internal/${FUNCTION_PREFIX}render.json`, fn_config);
-		writeFileSync(`.netlify/functions-internal/${FUNCTION_PREFIX}render.mjs`, fn);
+		writeFileSync(`.netlify/v1/functions/${FUNCTION_PREFIX}render.mjs`, fn);
 		if (builder.hasServerInstrumentationFile?.()) {
 			builder.instrument?.({
-				entrypoint: `.netlify/functions-internal/${FUNCTION_PREFIX}render.mjs`,
-				instrumentation: '.netlify/server/instrumentation.server.js',
-				start: `.netlify/functions-start/${FUNCTION_PREFIX}render.start.mjs`,
```
Comment (serhalp) [inline packages/adapter-netlify/index.js:308]: TODO: I have no idea what this was yet

File: .changeset/fine-ghosts-camp.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+'@sveltejs/adapter-netlify': major
+---
+
+Write output that conforms to the stable [Netlify Frameworks API](https://docs.netlify.com/build/frameworks/frameworks-api/).
```
Comment (teemingc) [inline .changeset/fine-ghosts-camp.md]:
```suggestion
breaking: write output that conforms to the stable [Netlify Frameworks API](https://docs.netlify.com/build/frameworks/frameworks-api/).
```

File: .changeset/fine-ghosts-camp.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
...
+
+POTENTIALLY BREAKING CHANGE: Deploying and previewing with Netlify CLI now requires [v17.31.0](https://github.com/netlify/cli/releases/tag/v17.31.0) or later. `npm i -g netlify-cli@latest` to upgrade.
```
Comment (teemingc) [inline .changeset/fine-ghosts-camp.md]:
```suggestion
Deploying and previewing with Netlify CLI now requires [v17.31.0](https://github.com/netlify/cli/releases/tag/v17.31.0) or later. Run `npm i -g netlify-cli@latest` to upgrade.
```

File: packages/adapter-netlify/test/apps/basic/netlify.toml [hunk 4]
```diff
@@ -1,9 +1,7 @@
...
 publish = "build"
 
-# TODO: remove this after we refactor to the Netlify frameworks API
 # we are purposely misusing the user functions config to discover our framework
-# build output because our adapter still outputs using an older API but the new
-# Netlify dev server adheres to the new API
+# build output because the Netlify dev plugin doesn't currently detect it
 [functions]
-directory = ".netlify/functions-internal"
+directory = ".netlify/v1/functions"
```
Comment (teemingc) [inline packages/adapter-netlify/test/apps/basic/netlify.toml:8]: @serhalp is there any way we could get the Netlify dev plugin to work with the Netlify framework API so we no longer need this hack? Currently, I don't think it picks up these directories or config.json

Comment (serhalp) [reply packages/adapter-netlify/test/apps/basic/netlify.toml:8]: Yes, I'm working on it actually! I actually realized the issue is that `@netlify/dev` isn't quite designed yet for a preview/serve context. It doesn't scan _output_ directories, only source.

Comment (teemingc) [reply packages/adapter-netlify/test/apps/basic/netlify.toml:8]: Should we go ahead with this test workaround and leave a todo to remove this once `@netlify/dev` supports it?
