### PR TITLE
fix: handle target attribute on remote form redirects

### LINKED ISSUE #15197: Remote form does not respect `target="_blank"`
### Describe the bug

```svelte
<form {...redirectForm} target="_blank">
  <button>Plain Submit</button>
</form>
```

```ts
export const redirectForm = form(object({ id: optional(string()) }), () => {
  // NOTE Changing to external link works
  redirect(307, resolve('/a')); // form target is not respected
  redirect(307, 'https://svelte.dev/'); // form target is respected
});
```

### Reproduction

https://github.com/hyunbinseo/svelte-kit-templates/tree/svelte-kit-15197

### Logs

```Shell

```

### System Info

```Shell
System:
  OS: Windows 11 10.0.26200
  CPU: (8) x64 Intel(R) Core(TM) Ultra 7 258V
  Memory: 4.55 GB / 31.48 GB
Binaries:
  Node: 24.13.0 - C:\Users\hyunb\AppData\Local\fnm_multishells\20244_1769082235758\node.EXE
  npm: 11.6.2 - C:\Users\hyunb\AppData\Local\fnm_multishells\20244_1769082235758\npm.CMD
  pnpm: 10.28.1 - C:\Users\hyunb\AppData\Local\fnm_multishells\20244_1769082235758\pnpm.CMD
  Deno: 2.4.0 - C:\Users\hyunb\.deno\bin\deno.EXE
Browsers:
  Chrome: 144.0.7559.96
  Edge: Chromium (140.0.3485.54)
  Firefox: 147.0.1 - C:\Program Files\Mozilla Firefox\firefox.exe
npmPackages:
  @sveltejs/adapter-auto: ^7.0.0 => 7.0.0
  @sveltejs/kit: ^2.50.0 => 2.50.0
  @sveltejs/vite-plugin-svelte: ^6.2.4 => 6.2.4
  svelte: ^5.48.0 => 5.48.0
  vite: ^7.3.1 => 7.3.1
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ai-man-codes**
closes #15197

---

- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

---

### Problem

Remote forms with ```target="_blank"``` did not open the redirect destination in a new tab. Instead, the current tab would navigate to the redirect URL, making ```target="_blank"``` completely ignored for both internal and external redirects.

### Solution

Check the form element's target attribute before deciding how to navigate. If it's``` _blank``` or ```_new```, use ```window.open()``` instead of ```_goto()```

I have ran all the tests and there were no issues.

### CODE REVIEW

**Comment by ai-man-codes** [comment]
@teemingc can you please review this PR ? Thank you

File: packages/kit/src/runtime/client/remote-functions/form.svelte.js [hunk 1]
```diff
@@ -238,7 +238,12 @@ export function form(id) {
 							refresh_queries(refreshes, updates);
 						}
 						// Use internal version to allow redirects to external URLs
-						void _goto(form_result.location, { invalidateAll }, 0);
+						const form_target = element?.getAttribute('target');
```
Comment (teemingc) [inline packages/kit/src/runtime/client/remote-functions/form.svelte.js]: We'll need to take into account the [formtarget](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button#formtarget) attribute. So we should compute this in the onsubmit handler instead similar to https://github.com/sveltejs/kit/blob/8c5048be1c5223144a9632dd318227d145f65ead/packages/kit/src/runtime/client/remote-functions/form.svelte.js#L293

File: packages/kit/src/runtime/client/remote-functions/form.svelte.js [hunk 2]
```diff
@@ -238,7 +238,12 @@ export function form(id) {
...
+						if (form_target === '_blank' || form_target === '_new') {
```
Comment (teemingc) [inline packages/kit/src/runtime/client/remote-functions/form.svelte.js]: I don't think `_new` is a supported value. See the full list at https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/form#target

File: packages/kit/src/runtime/client/remote-functions/form.svelte.js [hunk 3]
```diff
@@ -238,7 +238,12 @@ export function form(id) {
...
+							window.open(form_result.location, form_target);
```
Comment (teemingc) [inline packages/kit/src/runtime/client/remote-functions/form.svelte.js]: I wonder if we can forego handling this ourselves by simply avoiding calling `event.preventDefault` too early at https://github.com/sveltejs/kit/blob/aebeae8d55c549a72f9b46d132014538358ef08c/packages/kit/src/runtime/client/remote-functions/form.svelte.js#L301

When we implemented form actions, we would defer handling `target="_blank"` to the browser by only calling `event.preventDefault` if it would result in a client-side navigation. See https://github.com/sveltejs/kit/blob/aebeae8d55c549a72f9b46d132014538358ef08c/packages/kit/src/runtime/client/client.js#L2619 

If we only handle validation/refreshes and defer the window opening to the browser, we won't have to worry about handling noopener/noreferrer ourselves https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel#noopener

This probably means something like calling `event.preventDefault` in all other cases except for this case we're trying to solve

File: packages/kit/test/apps/async/test/test.js [hunk 4]
```diff
@@ -154,6 +154,47 @@ test.describe('remote functions', () => {
 		await page.waitForURL('/remote');
 	});
 
+	test('remote form redirect opens in new tab when target=_blank', async ({
+		page,
+		javaScriptEnabled
+	}) => {
+		test.skip(!javaScriptEnabled, 'remote forms require JavaScript');
```
Comment (teemingc) [inline packages/kit/test/apps/async/test/test.js]: This should work regardless of JavaScript being enabled
```suggestion
```

File: packages/kit/test/apps/async/test/test.js [hunk 5]
```diff
@@ -154,6 +154,47 @@ test.describe('remote functions', () => {
...
+
+		expect(page.url()).toContain('/remote/form/redirect-target');
+		expect(page.url()).not.toContain('/destination');
+	});
+
+	test('remote form redirect navigates same tab without target=_blank', async ({
+		page,
+		javaScriptEnabled
+	}) => {
+		test.skip(!javaScriptEnabled, 'remote forms require JavaScript');
```
Comment (teemingc) [inline packages/kit/test/apps/async/test/test.js]: Same here
```suggestion
```

File: packages/kit/test/apps/async/src/routes/remote/form/redirect-target/+page.svelte [hunk 6]
```diff
@@ -0,0 +1,11 @@
+<script>
+	import { redirectForm } from './form.remote.ts';
+</script>
+
+<form {...redirectForm.for('blank')} target="_blank" data-testid="form-blank">
```
Comment (teemingc) [inline packages/kit/test/apps/async/src/routes/remote/form/redirect-target/+page.svelte:5]: We should also add a test case where where the `formTarget` attribute is on the `button` or `input`

**Comment by ai-man-codes** [comment]
Hey @teemingc, thanks for the detailed review. I have updated the code and yes there was a better way of handling this, I tried to implement that and also added an additional test.

File: packages/kit/src/runtime/client/remote-functions/form.svelte.js [hunk 7]
```diff
@@ -298,6 +298,14 @@ export function form(id) {
 					return;
 				}
 
+				const target = event.submitter?.hasAttribute('formtarget')
+					? /** @type {HTMLButtonElement | HTMLInputElement} */ (event.submitter).formTarget
+					: clone(form).target;
+
+				if (target && target !== '_self') {
```
Comment (teemingc) [inline packages/kit/src/runtime/client/remote-functions/form.svelte.js]:
```suggestion
				if (target === '_blank') {
```
