### PR TITLE
fix: more robust remote function code transformation

### LINKED ISSUE #14416: Build Error: `$$_export_$$` is not defined
### Describe the bug

It is only occuring when I run `pnpm run build`
```ts
✓ 2220 modules transformed.

node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: $$_export_$$ is not defined
    at file:///Users/sillvva/Projects/ddal-svelte/.svelte-kit/output/server/chunks/remote-1ob51s4.js:70:1
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async analyse (file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.39.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.38.10_vite@7.1.5_@type_75ca1232bd018a23d63bcc20842e9db0/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:51:19)
    at async MessagePort.<anonymous> (file:///Users/sillvva/Projects/ddal-svelte/node_modules/.pnpm/@sveltejs+kit@2.39.0_@sveltejs+vite-plugin-svelte@6.2.0_svelte@5.38.10_vite@7.1.5_@type_75ca1232bd018a23d63bcc20842e9db0/node_modules/@sveltejs/kit/src/utils/fork.js:23:16)
```
I'm guessing it has to do with my remote functions setup:
```
$lib/remote
 ∟ /admin
    ∟ /queries.remote.ts
    ∟ /actions.remote.ts
    ∟ /index.ts
```
In `index.ts`, I'm exporting the remote functions as a namespace export, so that I can import and use them like `AdminAPI.queries.logs()`. This setup seems to run fine in dev mode.
```ts
import * as actions from "./actions.remote";
import * as queries from "./queries.remote";

export default {
	actions,
	queries
};
```

### Reproduction

Run `npm run build`:
https://stackblitz.com/edit/sveltejs-kit-template-default-4pjy8rxc?file=src%2Flib%2Fremote%2Fadmin%2Fqueries.remote.ts

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: macOS 15.6.1
    CPU: (16) arm64 Apple M4 Max
    Memory: 218.00 MB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    pnpm: 10.11.0 - ~/.nvm/versions/node/v22.12.0/bin/pnpm
    bun: 1.2.20 - ~/.bun/bin/bun
  Browsers:
    Safari: 18.6
  npmPackages:
    @sveltejs/adapter-node: ^5.3.2 => 5.3.2 
    @sveltejs/kit: ^2.39.0 => 2.39.0 
    @sveltejs/vite-plugin-svelte: ^6.2.0 => 6.2.0 
    svelte: ^5.38.10 => 5.38.10 
    vite: ^7.1.5 => 7.1.5
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #14416

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/exports/vite/index.js [hunk 1]
```diff
@@ -803,7 +803,7 @@ async function kit({ svelte_config }) {
 
 				fs.writeFileSync(
 					file,
-					code.replace('$$_export_$$($$_self_$$)', () => `export default $$_self_$$;`)
+					code.replace(/\$\$_export_\$\$\((.+?)\)/, (_, name) => `export default ${name};`)
```
Comment (dummdidumm) [inline packages/kit/src/exports/vite/index.js:807]:
```suggestion
					// build process might have minified/adjusted the $$_self_$$ variable, but not the fake global $$_export_$$ function
					code.replace(/\$\$_export_\$\$\((.+?)\)/, (_, name) => `export default ${name};`)
```
