### PR TITLE
fix: respect scroll-margin when navigating to a url-supplied anchor

### LINKED ISSUE #15192: scroll-padding doesn't get respected when navigating to a page with hash
### Describe the bug

When navigating to a page with hash, the scroll-padding gets ignored.

Normally it scrolls less far, so the header doesn't cover the element I want to scroll to. This works, when loading the site directly, but not when navigating in svelte.

### Reproduction

Minimal reproduction repo: https://github.com/levi-jcbs/svelte-scroll-padding-test

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Linux 6.12 Debian GNU/Linux 13 (trixie) 13 (trixie)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 18.44 GB / 31.08 GB
    Container: Yes
    Shell: 5.2.37 - /bin/bash
  Binaries:
    Node: 20.19.2 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  Browsers:
    Chrome: 143.0.7499.192
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/adapter-node: ^5.5.1 => 5.5.1 
    @sveltejs/kit: ^2.50.0 => 2.50.0 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.4 
    svelte: ^5.0.0 => 5.47.1 
    vite: ^5.0.3 => 5.4.21
```

### Severity

annoyance

### Additional Information

Discord Thread: https://discord.com/channels/457912077277855764/1462015454095868095

### PR DESCRIPTION
**Pull request by PatrickG**
fixes #15192

When we navigate to a url-supplied anchor, we don't need to scroll to it in `reset_focus`. The `location.replace()` call already scrolls to the anchor and respects `scroll-margin-top`/`scroll-padding-top` & smooth scrolling.
The previous solution (implemented in #14569) used `getBoundingClientRect()` which does not take `scroll-margin-top`/`scroll-padding-top` into account.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -3030,7 +3022,7 @@ function reset_focus(url, scroll = null) {
 
 				// Scroll management has already happened earlier so we need to restore
```
Comment (teemingc) [inline packages/kit/src/runtime/client/client.js]:
```suggestion
				// If scroll management has already happened earlier, we need to restore
```

File: packages/kit/src/runtime/client/client.js [hunk 2]
```diff
@@ -1794,7 +1786,7 @@ async function navigate({
 		document.activeElement !== document.body;
 
 	if (!keepfocus && !changed_focus) {
-		reset_focus(url, scroll);
+		reset_focus(url, !deep_linked);
```
Comment (teemingc) [inline packages/kit/src/runtime/client/client.js:1792]:
```suggestion
    // We don't need to manually restore the scroll position if we're navigating
    // to a fragment identifier. It is automatically done for us when we set the
    // sequential navigation starting point with `location.replace`
		reset_focus(url, !deep_linked);
```

**Review by teemingc — APPROVED** [review]
LGTM! I made some suggestions to add comments that are pretty much what you've explained in the PR description. Although, I have a bit of uneasiness because I can't remember if all browsers (on different platforms) have the same behaviour for `location.replace` although I tested this many years ago. Also, sorry this took so long to get around to 😓 

Maybe @Rich-Harris would want to take a second look to see if this would regress https://github.com/sveltejs/kit/pull/14569 ? That one doesn't have a test and the PR description mentions it's difficult to reproduce (but it makes sense)

**Comment by PatrickG** [comment]
IMO this should also fix https://github.com/sveltejs/svelte.dev/issues/1693 but it still seems to be broken  in the preview svelte-docs-bot posted.
> **Preview**: https://svelte-dev-git-preview-kit-15246-svelte.vercel.app/

Wonder why.

But it fixes #15192 - see https://www.sveltelab.dev/qk496863qm9cro3

**Comment by teemingc** [comment]
> IMO this should also fix [sveltejs/svelte.dev#1693](https://github.com/sveltejs/svelte.dev/issues/1693) but it still seems to be broken in the preview svelte-docs-bot posted.
> 
> > **Preview**: [svelte-dev-git-preview-kit-15246-svelte.vercel.app](https://svelte-dev-git-preview-kit-15246-svelte.vercel.app/)

Does the Kit version need to be updated manually? I think only the docs are updated from the bot

> But it fixes #15192 - see [sveltelab.dev/qk496863qm9cro3](https://www.sveltelab.dev/qk496863qm9cro3)

This one's really strange because I couldn't reproduce it from the issue or from the sveltelab link. But I _can_ reproduce it from the test scenario in this PR

**Comment by PatrickG** [comment]
> Does the Kit version need to be updated manually? I think only the docs are updated from the bot

Ahh, makes sense. Maybe it shouldn't create a preview when the PR does not touch any docs then? :D


> This one's really strange because I couldn't reproduce it from the issue or from the sveltelab link. But I can reproduce it from the test scenario in this PR

The sveltelab link I posted uses the fix from this PR.

**Comment by teemingc** [comment]
> > Does the Kit version need to be updated manually? I think only the docs are updated from the bot
> 
> Ahh, makes sense. Maybe it shouldn't create a preview when the PR does not touch any docs then? :D

You'll have to ask @elliott-with-the-longest-name-on-github if that's possible 😆

**Comment by Rich-Harris** [comment]
very excited to apply this fix to svelte.dev 🎉
