### PR TITLE
fix: prevent overwriting of CloudFlare `_headers` file

### LINKED ISSUE #8692: adapter-cloudflare overwrites `_headers` file
### Describe the bug

Currently, the `_headers` file in `/static` will get overwritten by the adapter during build.

A simple workaround is to edit the `_headers` file after build manually or using a script, etc.

However, the adapter can also easily be modified to append the generated headers if the file already exists.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-s6tebu

1. Enter `npm run build` in the terminal.
2. Compare the contents of `static/_headers` and `.svelte-kit/cloudflare/_headers`

### Logs

_No response_

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-cloudflare: ^1.1.0 => 1.1.0 
    @sveltejs/kit: ^1.0.0 => 1.2.6 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

This makes it easier to add the header below that is recommended by Cloudflare when using a custom domain.
```
https://myproject.pages.dev/*
  X-Robots-Tag: noindex
```

### PR DESCRIPTION
**Pull request by s3812497**
fixes #8692

Adds the append flag `a` to the file writing method for `_headers`.
This appends the auto-generated headers to any existing `_headers` file copied from `/static` or creates a new one if it doesn't exist (as it did before).

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/adapter-cloudflare/index.js [hunk 1]
```diff
@@ -22,10 +22,6 @@ export default function () {
 
 			const relativePath = posix.relative(tmp, builder.getServerDirectory());
 
-			builder.log.info(
-				`adapter-cloudfare is writing its own _headers file. If you have your own, you should duplicate the headers contained in: ${dest}/_headers`
```
Comment (benmccann) [inline packages/adapter-cloudflare/index.js:26]: If people had done this previously as we advised and now we are appending them, they will end up with duplicates. I don't know how much of an issue that is. Does this need to be considered a breaking change and major release?

Comment (s3812497) [reply packages/adapter-cloudflare/index.js:26]: I think you're right about this being a breaking change. I never thought of that.
Are there any examples of existing configurations and how people get around this now?

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you!
