### PR TITLE
[fix] increase scroll debounce timeout

### LINKED ISSUE #365: SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
We've been seeing this in production, via Sentry — almost exclusively on iPhones. I assume it's related to this: https://github.com/sveltejs/kit/blob/ad9551c47727b74fcc7c31614962e7bc37792633/packages/kit/src/runtime/internal/router/index.js#L49-L63

### PR DESCRIPTION
**Pull request by bluwy**
Fixes #365 

iOS scroll event intervals happens between 30-150ms, sometimes around 200ms. So we set the debounce timeout to 200ms to prevent most false positives.

### Before submitting the PR, please make sure you do the following
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/client/router.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export class Router {
 					'sveltekit:scroll': scroll_state()
 				};
 				history.replaceState(new_state, document.title, window.location.href);
-			}, 50);
+			}, 200);
```
Comment (benmccann) [inline packages/kit/src/runtime/client/router.js:91]: should we add a comment here like:
```suggestion
			// iOS scroll event intervals happens between 30-150ms, sometimes around 200ms
			}, 200);
```

File: packages/kit/src/runtime/client/router.js [hunk 2]
```diff
@@ -88,7 +88,8 @@ export class Router {
 					'sveltekit:scroll': scroll_state()
 				};
 				history.replaceState(new_state, document.title, window.location.href);
-			}, 50);
+			// iOS scroll event intervals happens between 30-150ms, sometimes around 200ms
```
Comment (benmccann) [inline packages/kit/src/runtime/client/router.js:91]: I just noticed an extra s in the text I copied from the PR description :smile: 
```suggestion
			// iOS scroll event intervals happen between 30-150ms, sometimes around 200ms
```

Comment (bluwy) [reply packages/kit/src/runtime/client/router.js]: My grammar :see_no_evil: Fixed in the latest commit

**Comment by benmccann** [comment]
Can you explain this bug in a bit more detail? I'm not sure I understand yet exactly how it occurred

Is my understanding below correct?
- On a normal device, the scroll event is firing constantly as you scroll. Each time a new event comes in, it cancels the previous timer, and after events stop coming in for 50ms it save the state
- On iOS, scroll events are also fired constantly as you scroll, but sometimes with large gaps between them. E.g. 100ms. In that case, you will be saving the state every 100ms. Which could mean 10 times per second. Or 100 times in 10 seconds. So you would have to scroll the page non-stop for 5-10 seconds to make the bug trigger? I'm kind of surprised people would be doing that very often and so I wonder if I'm missing something

**Comment by bluwy** [comment]
Yep, that's how it is with iOS currently.

> So you would have to scroll the page non-stop for 5-10 seconds to make the bug trigger?

I won't say non-stop since it can happen intermittently, so as long as the user scrolls for 5-10s in a 30s window, it'll cause the error. And it happens really often as long as your thumb stays on screen, even the slightest scroll.

**Review by benmccann — APPROVED** [review]

**Comment by benmccann** [comment]
Ah, thanks for the explanation!!
