### PR TITLE
fix: append trailing slash in manifest

### LINKED ISSUE #1486: Invalid output and infinite redirect loop with `adapter-static` and `trailingSlash: "always"`
**Describe the bug**
Only `<meta http-equiv="refresh" content="0;url=/test/">` is written to `build/test/index.html` when using static adapter and always trailing slash.

**Logs**
None, build runs successfully, maybe just that `301 /test -> /test/` is printed during build.

**To Reproduce**

Use `npm init svelte@next test`, choose skeleton project.

Create a page `src/routes/test/index.svelte` with any content (`<p>hello</p>`). Have `svelte.config.js` like this:

```js
import adapter from "@sveltejs/adapter-static";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: "#svelte",
    adapter: adapter(),
    trailingSlash: "always",
  },
};

export default config;
```

Reproduction repo with individual setup steps in https://github.com/mvolfik/probable-disco

**Expected behavior**
No redirects should be needed at all. `build/test/index.html` should contain normal html page with `<p>hello</p>`.

**Stacktraces**
N/A

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite,@sveltejs/adapter-static --binaries --browsers

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 292.40 MB / 7.35 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 14.16.0 - ~/.local/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 7.6.3 - ~/.local/bin/npm
  Browsers:
    Chromium: 90.0.4430.212
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.9 
    @sveltejs/kit: next => 1.0.0-next.107
    svelte: ^3.34.0 => 3.38.2
```
</details>

**Severity**
Bad bad. Makes `adapter-static` unusable with `trailingSlash: "always"`.

**Additional context**
There is one similar issue #1346, but that is apparently caused by Netlify redirects, while this is only sveltekit.

### PR DESCRIPTION
**Pull request by pz-mxu**
Fixes https://github.com/sveltejs/kit/issues/1486

This will fix #1486 by adding a trailing slash to the pages' path if _config.kit.trailingSlash_ is "always".

### CODE REVIEW

File: packages/kit/src/core/adapt/prerender.js [hunk 1]
```diff
@@ -90,6 +90,19 @@ export async function prerender({ cwd, out, log, config, build_data, fallback, a
 		}
 	});
 
+	/**
+	 * @param {string} path
+	 */
+	function normalizeTrailingSlash(path) {
+		if (config.kit.trailingSlash === 'always') {
+			return path.endsWith('/') || path === '/' ? path : `${path}/`;
```
Comment (benmccann) [inline packages/kit/src/core/adapt/prerender.js:98]: you don't need `|| path === '/'` do you? I think that `path.endsWith('/')` would return `true` for it

File: packages/kit/src/core/adapt/prerender.js [hunk 2]
```diff
@@ -217,10 +233,10 @@ export async function prerender({ cwd, out, log, config, build_data, fallback, a
 	for (const entry of config.kit.prerender.pages) {
 		if (entry === '*') {
 			for (const entry of build_data.entries) {
-				await visit(entry, null);
+				await visit(normalizeTrailingSlash(entry), null);
```
Comment (benmccann) [inline packages/kit/src/core/adapt/prerender.js:236]: it seems like a lot to keep track of to need to call `normalizeTrailingSlash` wherever `visit` is called. could you just call it inside `visit` as the first line of that method instead?

File: packages/kit/src/core/adapt/prerender.js (hunk 1 above)
Comment (pz-mxu) [reply packages/kit/src/core/adapt/prerender.js:98]: True 🙈

File: packages/kit/src/core/adapt/prerender.js (hunk 2 above)
Comment (pz-mxu) [reply packages/kit/src/core/adapt/prerender.js]: Yes, that's better. Thanks. Simplified and rebased the commit.

**Review by benmccann — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thanks 👍
