### PR TITLE
prevent server-side fetch from succeeding if filename contains #

### LINKED ISSUE #2802: Svelte Kit's `fetch` and the Browser's `fetch` Produce Inconsistent Results
### Describe the bug

Calling `await fetch(url)` from Svelte Kit `load` produces different results than when calling from the browser.

In a nutshell, given at least one special case, Svelte Kit's `fetch` will be able to retrieve a file, even if the browser's `fetch` will not.

While the special case given in the reproducing repo is not a very common use case, it may still shed some light on other inconsistencies in the custom implementation of `fetch`.

### Reproduction

https://github.com/Acmion/svelte-kit-fetch-bug

### Logs

```shell
(node:1560) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /#bug.html
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at new Request (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5543:16)
    at file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5753:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5751:9)
    at loadBrowser (/src/routes/index.svelte:24:24)
    at eval (/src/routes/index.svelte:28:2)
    at Object.$$render (D:\Acmion\Temp\svelte-kit-fetch-bug\node_modules\svelte\internal\index.js:1684:22)
    at Object.default (/D:\Acmion\Temp\svelte-kit-fetch-bug\.svelte-kit\dev/generated/root.svelte:57:127)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an a
sync function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandle
d_rejections_mode). (rejection id: 2)
(node:1560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
(node:1560) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /#bug.html
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at new Request (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5543:16)
    at file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5753:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5751:9)
    at loadBrowser (/src/routes/index.svelte:24:24)
    at eval (/src/routes/index.svelte:28:2)
    at Object.$$render (D:\Acmion\Temp\svelte-kit-fetch-bug\node_modules\svelte\internal\index.js:1684:22)
    at Object.default (/D:\Acmion\Temp\svelte-kit-fetch-bug\.svelte-kit\dev/generated/root.svelte:57:127)
(node:1560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an a
sync function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandle
d_rejections_mode). (rejection id: 4)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
    Memory: 1.09 GB / 7.97 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196
    svelte: ^3.42.6 => 3.44.1
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
closes #2802

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/server/page/fetch.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ export function create_fetch({ event, options, state, route, prerender_default }
 			}
 		}
 
-		const resolved = resolve(event.url.pathname, requested.split('?')[0]);
+		const resolved = resolve(event.url.pathname, requested.split('?')[0]).replace(/#.+$/, '');
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/fetch.js:66]: would this theoretically result in a URL which exists? Also, this probably doesn't result in the same error as in the browser (404 vs some error about invalid urls). Are we ok with this difference in behavior?

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/page/fetch.js:66]: Not sure I follow? You can totally do `fetch('/foo#bar')` from the browser, the `#bar` just gets ignored. This emulates that behaviour

Comment (dummdidumm) [reply packages/kit/src/runtime/server/page/fetch.js:66]: I read the related issue as "the browser fetch says this URL is invalid, SvelteKit's fetch can deal with it fine". This change just removes everything after (and including) the `#`, which is different from throwing an "invalid url" error. It could also mean that the fetch ends up fetching something that actually exists.

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/page/fetch.js:66]: A URL with a `#` in it is totally valid with `fetch`, it just gets ignored. The confusing error in that issue was because the OP was calling `fetch` in the `<script>` block, not in `onMount`, and undici/node-fetch chokes because it's a root-relative URL

Comment (dummdidumm) [reply packages/kit/src/runtime/server/page/fetch.js:66]: Ah ok, all good then

**Review by dummdidumm — APPROVED** [review]
