### PR TITLE
feat: Support caching of responses with `Vary` header, and fix browser caching of adjacent pages/endpoints

### LINKED ISSUE #9780: Fix browser caching of endpoints instead of page
### Describe the bug

Set up: Visit a page with client side navigation, where the destination `+page.svelte` file is in the same directory as a `+server.js` GET request handler, and a `+page.js` universal load function.

Then duplicate the tab.

Expected: An identical HTML page is rendered in the new browser tab.
Actual: The JSON response from the `+server.js` is rendered.

This also happens when using back/forwards browser navigation

### Reproduction

Minimal repo:

https://github.com/oscarhermoso/bug-sveltekit-duplicate-tab/tree/main

Recording:

bug-sveltekit-duplicate-tab

### Logs

```Shell
N/A
```

### System Info

```Shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.62 GB / 15.56 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Chromium: 112.0.5615.49
    Firefox: 112.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.15.9 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.3.0 => 4.3.3
```

### Severity

annoyance

### Additional Information

This isn't related to any recent Sveltekit version - I am able to reproduce on Sveltekit 1.0.

It seems to be because of browser caching of the fetch request made on client load, because I can work-around the issue by adding Cache-Control headers to the GET request handler

```
setHeaders({
    'Cache-Control': 'No-Store',
  });
```
_No response_

### PR DESCRIPTION
**Pull request by oscarhermoso**
(fixes #9780)

Expand below to see recorded GIF of the issue - notice that on "forward" navigation the browser renders the endpoint response from cache, instead of the expected HTML response.

<details><summary>Before/after</summary>
<p>

#### Before

actual

#### After

svelte-kit-expected

</p>
</details> 

* fix: Include `Vary: Accept` header on responses to `GET` requests
* feat: Allow caching of requests with `Vary` (as long as it's not `Vary: *`)

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/server/page/serialize_data.js [hunk 1]
```diff
@@ -89,10 +89,9 @@ export function serialize_data(fetched, filter, prerendering = false) {
 	}
 
 	// Compute the time the response should be cached, taking into account max-age and age.
-	// Do not cache at all if a vary header is present, as this indicates that the cache is
-	// likely to get busted. It would also mean we'd have to add more logic to computing the
-	// selector on the client which results in more code for 99% of people for the 1% who use vary.
```
Comment (oscarhermoso) [inline packages/kit/src/runtime/server/page/serialize_data.js:94]: This logic was already implemented with #8754

File: .changeset/shy-ears-report.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+'@sveltejs/kit': minor
+---
+
+feat: Support caching of responses with `Vary` header (except for `Vary: *`)
+
+fix: Include `Vary: Accept` header to fix browser caching of adjacent pages and endpoints
```
Comment (tcc-sejohnson) [inline .changeset/shy-ears-report.md:7]:
```suggestion
feat: support caching of responses with `Vary` header (except for `Vary: *`)

fix: include `Vary: Accept` header to fix browser caching of adjacent pages and endpoints
```

idk why but we don't capitalize these  <picture data-single-emoji=":lol:" title=":lol:">:lol:</picture>

File: packages/kit/src/runtime/server/page/serialize_data.js [hunk 3]
```diff
@@ -46,16 +46,16 @@ export function serialize_data(fetched, filter, prerendering = false) {
...
 	for (const [key, value] of fetched.response.headers) {
 		if (filter(key, value)) {
 			headers[key] = value;
 		}
 
 		if (key === 'cache-control') cache_control = value;
-		if (key === 'age') age = value;
-		if (key === 'vary') vary = true;
+		else if (key === 'age') age = value;
+		else if (key === 'vary') varyAny ||= value.trim() === '*';
```
Comment (tcc-sejohnson) [inline packages/kit/src/runtime/server/page/serialize_data.js:58]: I'm slightly confused; `||=` only assigns if LHS is falsy. `varyAny` is always falsy. Can't we just:

```suggestion
		else if (key === 'vary') varyAny = value.trim() === '*';
```

**Review by tcc-sejohnson — COMMENTED** [review]
Looking good, thanks for the contribution! Just a couple of comments from me 😁

File: packages/kit/src/runtime/server/page/serialize_data.js (hunk 3 above)
Comment (oscarhermoso) [reply packages/kit/src/runtime/server/page/serialize_data.js:58]: I figured this was slightly safer, in case there was one header keyed with `Vary: *`, followed by a header keyed with `Vary: anything else`

Comment (tcc-sejohnson) [reply packages/kit/src/runtime/server/page/serialize_data.js:58]: I don't think it would matter, would it? If you set `Vary: *`, wouldn't all other `Vary` headers become meaningless?

Comment (oscarhermoso) [reply packages/kit/src/runtime/server/page/serialize_data.js]: I might be over-engineering it 😅 I've updated the code as below, hows this?

```js
else if (key === 'vary' && value.trim() === '*') varyAny = true;
```

Comment (tcc-sejohnson) [reply packages/kit/src/runtime/server/page/serialize_data.js]: noice! looks good to me 😁

File: .changeset/shy-ears-report.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+---
+'@sveltejs/kit': minor
+---
+
+feat: support caching of responses with `Vary` header (except for `Vary: *`)
+
+fix: include `Vary: Accept` header to fix browser caching of adjacent pages and endpoints
```
Comment (benmccann) [inline .changeset/shy-ears-report.md:7]: you should have two changeset files if you want to have two changeset entries rather than putting them both in the same file or else it will mess up the changelog formatting

**Review by dummdidumm — APPROVED** [review]
Thank you!

Note to self: This is now possible without any changes on the client because since #8754 we're taking headers into account for the cache key.

**Comment by jaylinski** [comment]
This change broke an app of mine. When returning a `fetch`-response (via node undici) directly to SvelteKit, undici will throw `TypeError: immutable`, because the change in this PR tries to modify the (immutable) undici-header.

Is there a good fix for this or do I have to clone the response-object so that the headers are immutable again? 🤔 

### Example for reproduction

**+server.ts**
```ts
import type { RequestHandler } from './$types';

// Proxy requests to API
export const GET = (async ({ request, url, locals }) => {
	const headers = new Headers({ Authorization: `Bearer xyz` });

	return await fetch('https://api.test/', {
		method: request.method,
		headers,
		body: request.body,
		// @ts-ignore: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1483
		duplex: 'half'
	});
}) satisfies RequestHandler;
```
