### PR TITLE
fix: reapply exports alignment

### LINKED ISSUE #8523: return fail() fails with Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs
### Describe the bug

As of sveltekit 1.0.13, returning a fail() object from an Action fails with the following error when using `npm run dev`

```
Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs
```

Everything worked fine in 1.0.12.  Also works as expected using `npm run build` / `npm run preview`

### Reproduction

`+page.server.js`
```javascript
import { fail } from '@sveltejs/kit';

/** @type {import('./$types').Actions} */
export const actions = {
	test: async () => {
		return fail(500);
	},
};
```

`+page.svelte`
```html
<form method="POST" action="?/test">
	<button>Submit</button>
</form>
```

### Logs

```Shell
Error: Data returned from action inside / is not serializable: Cannot stringify arbitrary non-POJOs
    at try_deserialize (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:262:10)
    at stringify_action_response (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:244:9)
    at Module.handle_action_json_request (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:67:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:358:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:229:20)
    at async file:///C:/Users/geoff/slingshot/slingshot-webui/frontend/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:468:22
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 33.87 GB / 63.95 GB
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.74
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/adapter-node: ^1.0.0 => 1.1.1
    @sveltejs/kit: ^1.0.12 => 1.1.0
    svelte: ^3.46.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
...after Vite dependency optimizations
fixes #8523

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/exports/vite/dev/index.js [hunk 1]
```diff
@@ -315,17 +315,31 @@ export async function dev(vite, vite_config, svelte_config) {
...
+			ActionFailure: control_module_vite.ActionFailure,
+			HttpError: control_module_vite.HttpError,
+			Redirect: control_module_vite.Redirect
+		});
+	}
+	align_exports();
+	const ws_send = vite.ws.send;
+	/** @param {any} args */
+	vite.ws.send = function (...args) {
+		console.log('ws.send', args);
```
Comment (Rich-Harris) [inline packages/kit/src/exports/vite/dev/index.js:335]: i assume this is left over?

```suggestion
```

Comment (dummdidumm) [reply packages/kit/src/exports/vite/dev/index.js:335]: woops yes

**Review by Rich-Harris — APPROVED** [review]
