### PR TITLE
[fix] handle redirects in handle hook while processing data request

### LINKED ISSUE #7787: Clientside link navigation doesn't respect redirects
### Describe the bug

When using SvelteKit's clientside link navigation, redirects are not being respected unless the link has the `data-sveltekit-reload` attribute. If a page returns a redirect, Kit just throws a 500 Internal Error for the user (no message on the server). You can verify that the responses are getting sent correctly and have 3xx status codes by checking devtools.

This happens both when redirecting from `hooks.server.ts` and `+page.server.ts`.

When using the `data-sveltekit-reload` or manually refreshing the page, the redirect works fine.

It doesn't seem to matter how the redirect is sent: Kit's `redirect()` error, `Response(null, { status: 302, headers: { Location: '/login' } })`, and `Response.redirect(event.url.origin + '/login', 302);` all give the same result.

I couldn't find any docs on this, so I assume this is either unintended behavior or I'm doing something wrong.

### Reproduction

https://github.com/styxpilled/sveltekit-navigation-redirect-issue

### Logs

_No response_

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
    Memory: 453.96 MB / 15.94 GB
  Binaries:
    Node: 18.11.0 - ~\AppData\Local\pnpm\node.EXE
    npm: 8.19.2 - ~\AppData\Local\pnpm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #7787

During fixing this, I wondered why the tests also pass without the fix, and discovered that this specific behavior will only occur if there's no root `+layout.server.js` (because then it wouldn't try to rerequest the data, failing again, resulting in a fallback to the server where the redirect would be handled correctly), which we have in the tests. I'm not sure if it's worth creating another test suite for this, so I left it like this.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by styxpilled** [comment]
Reading this surprised me, because I found this issue in a project that had `+layout.server.js`.
After some tests I here's what I found:
- if you redirect in `hooks.server.js` and you don't have `+layout.server.js`, kit will load that route. If you have `+page.server.js` in that route, it will fail with a 500 error.
- if you have `+layout.server.js`, the redirect will work.
- but then if you don't have `+page.server.js`, the redirect won't work. 
  - if you have a `+page.js` that fetches some stuff from an endpoint (which you may also be blocking with hooks) that fails, the page will fail with a 500 error.
  - if you don't have that, the page will display as normal, even though it shouldn't.

**Review by Rich-Harris — APPROVED** [review]

File: packages/kit/src/runtime/server/index.js [hunk 1]
```diff
@@ -289,10 +289,23 @@ export async function respond(request, options, state) {
 			}
 		}
 
+		// Edge case: If user does `return Response(30x)` in handle hook while processing a data request,
+		// we need to transform the redirect response to a corresponding JSON response.
+		if (is_data_request && response.status >= 300 && response.status < 309) {
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/index.js:294]: nit

```suggestion
		if (is_data_request && response.status >= 300 && response.status <= 308) {
```
