### PR TITLE
fix: Don't set defaults when parsing cookies from headers

### LINKED ISSUE #9901: cookies inside endpoints called from `event.fetch` are not correctly set
### Describe the bug

When calling an endpoint from `event.fetch` that sets a cookie with `httpOnly: false` the actual response sets the cookie with `httpOnly: true`

### Reproduction

https://github.com/david-plugge-reproductions/sveltekit-fetch-httponly-cookie

### Logs

_No response_

### System Info

```Shell
System:
  OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Memory: 11.99 GB / 15.57 GB
  Container: Yes
  Shell: 5.8.1 - /usr/bin/zsh
Binaries:
  Node: 18.16.0 - /mnt/wslg/runtime-dir/fnm_multishells/197_1683713854937/bin/node
  npm: 9.5.1 - /mnt/wslg/runtime-dir/fnm_multishells/197_1683713854937/bin/npm
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tcc-sejohnson**
Closes #9901 

Bypasses setting Kit defaults on cookies parsed from fetch response headers. To illustrate what the problem was:

- Set a cookie in `+server.ts`: `cookies.set('foo', 'bar', { httpOnly: false })`
- `fetch` this endpoint from `+page.server.ts`
- As part of `fetch`, parse the cookies from the headers
- `httpOnly` isn't set (because `false === unset`)
- Adding this cookie to the cookies causes the default `httpOnly: true` to be added

The better solution here is not to apply defaults to cookies we parse from fetch response headers. _If_ these cookies were set through `cookies.set` in a `+server.ts` endpoint, we've already set the defaults, and if they're not, we shouldn't touch them anyway.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/server/cookie.js [hunk 1]
```diff
@@ -107,13 +107,23 @@ export function get_cookies(request, url, trailing_slash) {
 		 * @param {import('cookie').CookieSerializeOptions} opts
 		 */
 		set(name, value, opts = {}) {
+			return this.set_internal(name, value, { with_defaults: true, ...opts });
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/cookie.js:110]: I don't think we need a `with_defaults` option — we can just pass the defaults from here, no?

```suggestion
			return this.set_internal(name, value, { ...defaults, ...opts });
```

**Review by Rich-Harris — COMMENTED** [review]
I think this is the right general approach, yeah (though I don't think we need `with_defaults`). 

It _does_ pain me somewhat to have an unexpected property on the `cookies` object. It may not be in the type definition but it's still visible to users, and people _will_ abuse implementation details if we expose them. Can we instead return `set_internal` as a standalone function that is passed to `create_fetch` (like `get_cookie_header`)?

File: packages/kit/src/runtime/server/cookie.js (hunk 1 above)
Comment (tcc-sejohnson) [reply packages/kit/src/runtime/server/cookie.js:110]: Ooh yeah, you're probably right...

**Review by dummdidumm — APPROVED** [review]
