### PR TITLE
[fix] skip inline cache when vary header is present

### LINKED ISSUE #8286: API endpoint, called from the server, with cache-header cannot be cleared
### Describe the bug

This is similar to, but different than https://github.com/sveltejs/kit/issues/7784 

I have an api endpoint that looks like this 

```js
export async function GET({ url, setHeaders, request }) {
	console.log('ENDPOINT', x++);

	const search = url.searchParams.get('search') || '';

	setHeaders({
		'cache-control': 'max-age=60',
		Vary: 'todos-cache'
	});
	const todos = await getTodos(search);
	return json(todos);
}
```

This endpoint is called from a SHARED loader. So the first time I view a page, the fetch is called from SvelteKit's internals, on the server. With the cache-control header, as above, these results are cached for 60 seconds. Even a call to invalidate to the api endpoint url does not clear that cached entry. Even adding a depends call in the shared loader, and called invalidate on that does not clear the cached entry. Even manually passing a different value of the header on each call (to test) does not clear the cached entry.

Is this by design? Note that I'm not talking about browser caching. I can already modify the header I'm Vary'ing on (todos-cache) on the client, and successfully clear the cache, which works.

The only workaround I've found is to just not add the cache-control header at all, depending on whether the loader is running client-side, or server-side (which I can surmise by snooping around the headers).

Again, mainly trying to surmise if this is by design. If it is, by all means close this. If not, I'd be happy to whip up a minimal repro. 

### Reproduction

n/a, for now (if this is not by design I'd be happy to make one).

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 151.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 8.18.0 - ~/Documents/node_modules/.bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.1 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #8286

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: sites/kit.svelte.dev/src/routes/api/+server.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+	console.log('ENDPOINT', x++);
+
+	const search = url.searchParams.get('search') || '';
+
+	setHeaders({
+		'cache-control': 'max-age=60',
+		Vary: 'todos-cache'
+	});
+	return json({ a: Math.random() });
+}
```
Comment (Rich-Harris) [inline sites/kit.svelte.dev/src/routes/api/+server.js:14]: is this meant to be here or was it for debugging/testing?

Comment (dummdidumm) [reply sites/kit.svelte.dev/src/routes/api/+server.js:14]: lol oops this is a leftover, I'll remove it
