### PR TITLE
fix: form action submit function callback return type

### LINKED ISSUE #13419: Form Actions: SubmitFunction callback return type
### Describe the bug

#7083 provided an `update` function to execute the default callback functionality when [customizing `use:enhance`](https://svelte.dev/docs/kit/form-actions#Progressive-enhancement-Customising-use:enhance) and providing a callback override. _However_, `update` returns `Promise<void>`, implying to a developer that they should execute `await update()` in the callback override - yet the typing for `SubmitFunction` expects the callback to be a synchronous function.

I do not think this is intentional, as the [`fallback_callback` variable in `kit/src/runtime/app/forms.js`](https://github.com/sveltejs/kit/blob/a09db8c0a11a62ee3d3cdf2921230dcf0facb6fd/packages/kit/src/runtime/app/forms.js#L89) is _asynchronous_, implying that the handling of that callback function accepts asynchronous functions in general.

This is especially frustrating when used in combination with [`@typescript-eslint/no-misused-promises`](https://typescript-eslint.io/rules/no-misused-promises/), as the following will return an error stating:
> Promise-returning function provided to return value where a void return was expected.

```typescript
use:enhance={() => {
	doSomeThing();

	return async ({ result, update }) => {
		doSomeOtherThing(result);
		await update();
	};
}}
```

### Reproduction

See above

### Logs

```Shell

```

### System Info

```Shell
N/A
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by McAllaster**
Allow for form action submit function callbacks to be asynchronous functions.

Closes #13419 

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.
    - Not sure if I need to do this for a type change?

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by McAllaster** [comment]
Apparently I was unfamiliar with the generated types, and `pnpm check` having a file _output_ (for generating types) rather than just failing if there was something wrong. I'm going to convert this to a draft for now.

File: packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte [hunk 1]
```diff
@@ -37,7 +37,9 @@
 	use:enhance={({ controller }) => {
 		previous?.abort();
 		previous = controller;
-		return () => count++;
+		return () => {
+			count++;
+		};
```
Comment (elliott-with-the-longest-name-on-github) [inline packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte:42]: Is there a reason for this :laughing:

Comment (McAllaster) [reply packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte]: Yes, this was intentional.

The return value from the function was throwing an error when running the tests. The return type is expected to be `void`, not a number.

It _should_ have been throwing an error before as well, though I will have to re-run and test that.

Comment (elliott-with-the-longest-name-on-github) [reply packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte]: Ahh gotcha, yeah, that makes sense -- I'll get it patched up and we can ship the PR. As I was investigating, I found that this type issue was actually causing a (probably inconsequential) bug where we weren't awaiting the promise returned by `fallback_callback` -- that's fixed now

Comment (McAllaster) [reply packages/kit/test/apps/basics/src/routes/actions/enhance/+page.svelte:42]: That was actually something I was going to comment asking a question about earlier -- whether or not we should be awaiting that `callback` method! I figured that I would at least keep the scope of the original PR limited, but I'm glad it surfaced that fix as well. Thanks for the quick turnaround on this ⚡
