### PR TITLE
[fix] transform links to be absolute to avoid console error when navigating

### LINKED ISSUE #3748: SvelteKit loads favicon every page request and messes up the request
### Describe the bug
I think there are two problems here:

1. favicon.png is request on each navigation (why?)
2. favicon in dev mode SOMETIMES is not found (404)

I have an API in SvelteKit structured as this
Screenshot from 2022-02-06 16-55-57

For some very strange reason SvelteKit tries to load favicon with every request  in a very weird way.
SK

Moreover when I check the params of the request with values   lang: 'en' and searched: '32015L2366'  I see that there were two requests:
The first request:
```js
Request {
  size: 0,
  follow: 20,
  compress: true,
  counter: 0,
  agent: undefined,
  highWaterMark: 16384,
  insecureHTTPParser: false,
  [Symbol(Body internals)]: {
    body: null,
    stream: null,
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Request internals)]: {
    method: 'GET',
    redirect: 'follow',
    headers: {
      accept: 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-US,en;q=0.9,cs;q=0.8',
      connection: 'keep-alive',
      referer: 'http://localhost:3000/en/favicon.png',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="98"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Linux"',
      'sec-fetch-dest': 'image',
      'sec-fetch-mode': 'no-cors',
      'sec-fetch-site': 'same-origin',
      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36'
    },
    parsedURL: URL {
      href: 'http://localhost:3000/api/en/favicon.png.json',
      origin: 'http://localhost:3000',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/api/en/favicon.png.json',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    signal: null,
    referrer: undefined,
    referrerPolicy: ''
  }
}
```

Console logged params are:
```js
{ lang: 'en', searched: 'favicon.png' }
```

The second request {correct one) is:
```js
Request {
  size: 0,
  follow: 20,
  compress: true,
  counter: 0,
  agent: undefined,
  highWaterMark: 16384,
  insecureHTTPParser: false,
  [Symbol(Body internals)]: {
    body: null,
    stream: null,
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Request internals)]: {
    method: 'GET',
    redirect: 'follow',
    headers: {
      accept: '*/*',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-US,en;q=0.9,cs;q=0.8',
      connection: 'keep-alive',
      host: 'localhost:3000',
      'if-none-match': '"1dyn90w"',
      referer: 'http://localhost:3000/en/32015L2366',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="98"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Linux"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-origin',
      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36'
    },
    parsedURL: URL {
      href: 'http://localhost:3000/api/en/32015L2366.json',
      origin: 'http://localhost:3000',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'localhost:3000',
      hostname: 'localhost',
      port: '3000',
      pathname: '/api/en/32015L2366.json',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    signal: null,
    referrer: undefined,
    referrerPolicy: ''
  }
```

Console logged params are:
```js
{ lang: 'en', searched: '32015L2366' }
```

Looks like a ghost in the shell.

### Reproduction

See the structure in the picture above.

### Logs

_No response_

### System Info

```shell
Pop!_OS 21.10 , Browser info can be seen hereabove.
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
fixes #3748. ~~This doesn't have a test because I haven't been able to observe this behaviour with anything other than a `<link rel="icon">` (and in any browser other than Chrome), and favicons are loaded somewhat unpredictably.~~ (actually, we can test that link hrefs are absolute)

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by Rich-Harris** [comment]
absolutely bewildered by these safari failures

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -1220,6 +1220,13 @@ export function create_client({ target, session, base, trailing_slash }) {
 				}
 			});
 
+			// fix link hrefs, because browsers will occasionally try to load relative
+			// URLs after a pushState/replaceState, resulting in a 404 — see
+			// https://github.com/sveltejs/kit/issues/3748
```
Comment (benmccann) [inline packages/kit/src/runtime/client/client.js:1225]: how about linking to the one comment that's actually helpful in a sea of "me too" comments :smile: 
```suggestion
			// https://github.com/sveltejs/kit/issues/3748#issuecomment-1125980897
```

File: packages/kit/test/apps/basics/test/test.js [hunk 2]
```diff
@@ -1043,15 +1043,27 @@ test.describe('$app/paths', () => {
 		);
 	});
 
-	test('replaces %sveltekit.assets% in template with relative path', async ({ page }) => {
+	test('replaces %sveltekit.assets% in template with relative path', async ({
```
Comment (benmccann) [inline packages/kit/test/apps/basics/test/test.js:1046]: I'm guessing you meant absolute instead of relative? should we include a bit of a comment here as well?
```suggestion
  // some browsers will re-request assets after a `pushState` 
  // https://github.com/sveltejs/kit/issues/3748#issuecomment-1125980897
	test('replaces %sveltekit.assets% in template with absolute path', async ({
```

File: packages/kit/src/runtime/client/client.js [hunk 3]
```diff
@@ -1220,6 +1220,13 @@ export function create_client({ target, session, base, trailing_slash }) {
...
+			for (const link of document.querySelectorAll('link')) {
+				link.href = link.href; // eslint-disable-line
```
Comment (benmccann) [inline packages/kit/src/runtime/client/client.js:1227]: should we only do this if `link.href` doesn't contain `://`? it might be more performant to avoid updating the DOM and on later navigations most links will already be absolute

File: packages/kit/test/apps/basics/test/test.js (hunk 2 above)
Comment (Rich-Harris) [reply packages/kit/test/apps/basics/test/test.js:1046]: no, `%sveltekit.assets%` is relative. that wasn't changed by this PR

File: packages/kit/src/runtime/client/client.js (hunk 3 above)
Comment (Rich-Harris) [reply packages/kit/src/runtime/client/client.js:1227]: i'm pretty sure `link.href = link.href` is just a no-op if it's already absolute. this only runs once (in `_start_router`), not on every navigation

File: packages/kit/test/apps/basics/test/test.js (hunk 2 above)
Comment (benmccann) [reply packages/kit/test/apps/basics/test/test.js:1046]: oh, I guess you're talking about the server-side replacement. I was thinking of the client-side replacement that was just introduced. I wonder if we should just say `properly handles %sveltekit.assets% in template` or something

Comment (Rich-Harris) [reply packages/kit/test/apps/basics/test/test.js:1046]:
```suggestion
	// some browsers will re-request assets after a `pushState`
	// https://github.com/sveltejs/kit/issues/3748#issuecomment-1125980897
	test('replaces %sveltekit.assets% in template with relative path, and makes it absolute in the client', async ({
```

**Review by benmccann — APPROVED** [review]
a begrudging approval :smile: I hate that we have to do this, but it seems like the best course of action

**Comment by Rich-Harris** [comment]
Unfortunately we can't merge it until we get to the bottom of those safari failures :(

**Comment by Rich-Harris** [comment]
wow. per 91049b73acab06580fcf897789de74c30dce746b, this change really is responsible for those persistent failures. **what the actual fucking hell, safari**

File: .changeset/stupid-dolls-fly.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@sveltejs/kit": patch
+---
+
+[fix] transform links to be absolute to avoid console error when navigating
```
Comment (Rich-Harris) [inline .changeset/stupid-dolls-fly.md:5]:
```suggestion
[fix] transform link[rel=icon] to be absolute to avoid console error when navigating
```

File: packages/kit/src/runtime/client/client.js [hunk 5]
```diff
@@ -1220,6 +1220,13 @@ export function create_client({ target, session, base, trailing_slash }) {
 				}
 			});
 
+			// fix link hrefs, because browsers will occasionally try to load relative
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/client.js:1223]:
```suggestion
			// fix link[rel=icon], because browsers will occasionally try to load relative
```

File: packages/kit/src/runtime/client/client.js [hunk 6]
```diff
@@ -1220,6 +1220,13 @@ export function create_client({ target, session, base, trailing_slash }) {
...
+			// URLs after a pushState/replaceState, resulting in a 404 — see
+			// https://github.com/sveltejs/kit/issues/3748#issuecomment-1125980897
+			for (const link of document.querySelectorAll('link')) {
+				if (link.rel === 'icon') link.href = link.href;
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/client.js:1227]:
```suggestion
			for (const link of document.querySelectorAll('link[rel=icon]')) {
				link.href = link.href;
```

**Comment by Rich-Harris** [comment]
ok, so it turns out that changing certain link hrefs causes scrolling to go batshit in safari. it turns out that if we only update `link[rel=icon]` everything works fine, and since the chrome bug only relates to those links, we should be fine. man, browsers are a mess

**Review by Magkoooh — APPROVED** [review]

**Review by Magkoooh — APPROVED** [review]

**Comment by benmccann** [comment]
@Magkoooh please don't approve already merged PRs as it just creates spam for the maintainers
