### PR TITLE
Parse value of srcset attribute closer to specifications

### LINKED ISSUE #3299: Regression: adapter-static build fails if url contains comma in srcset attribute on image tag
### Describe the bug

When building with adapter-static, if the srcset attribute on an image tag contains a comma, the build fails trying to fetch not the external url pointing to the image but whatever follows the comma as an internal url.
This results in a 404 and the build failing.
Example: 
not ``https://res.cloudinary.com/demo/image/upload/q_auto:best,w_864/sample.jpg`` is fetched but ``/w_864/sample.jpg``

I am pretty sure this bug was introduced by #3288 , since it doesn't occur on 1.0.0-next.223 or lower and also seems to fit the changes.

### Reproduction

Super simple reproduction of the problem: https://github.com/Theo-Steiner/crawling-external-srcset

### Logs

```shell
https://app.warp.dev/block/kmoZl6fbECWcw8hKUKyzIp
```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 97.00 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Firefox Developer Edition: 91.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.225
    svelte: ^3.44.0 => 3.46.0
```

### Severity

blocking upgrade

### Additional Information

Many image hosts use a comma in their URLs as an api for enumerating multiple transformations. Since commas are legal in URLs, we should fix this.

### PR DESCRIPTION
**Pull request by Theo-Steiner**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [X] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [X] This message body should clearly illustrate what problems it solves.
- [X] Ideally, include a test that fails without this PR but passes with it.

This PR attempts to fix #3299 which was a regression introduced by #3288 .

## Problem

The problem lies with the the specifications of the srcset attribute:

> If present, its value must consist of one or more image candidate strings, each separated from the next by a U+002C COMMA character (,). If an image candidate string contains no descriptors and no ASCII whitespace after the URL, the following image candidate string, if there is one, must begin with one or more ASCII whitespace.

Simply comma separating the value of the srcset attributes doesn't work in the case that there is a "," comma in one or more of the URLs of the srcset. Since popular image hosts like cloudinary use commas to enumerate transformations, this should be addressed, as prerendering fails when the crawler tries to crawl the resulting broken links.

## Proposed Solution

Rather than just reverting back to the previous RegularExpression, I attempted to write a primitive parser to implement the specification, as Rich made the original PR to get away from hard to understand regexes.
There are problems with my parser though: 

A. It fails in the case that there is a URL ending with a comma 
B. It is significantly slower than the previous regex solution (https://jsbench.me/mxkybbu22g/1)
C. There might be other problems I'm overlooking

I also modified the fixtures to test for this behavior

### Tests
- [X] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/core/adapt/prerender/crawl.js [hunk 1]
```diff
@@ -156,7 +156,20 @@ export function crawl(html) {
...
+										value = value.substring(i + 1).trim();
+										i = 0;
+										insideURL = true;
+									} else if (value[i] === ' ') {
+										insideURL = false;
+									}
+								}
+								candidates.push(value);
 								for (const candidate of candidates) {
 									const src = candidate.trim().split(WHITESPACE)[0];
```
Comment (Rich-Harris) [inline packages/kit/src/core/adapt/prerender/crawl.js:174]: the `trim` is no longer necessary, since it's happening on line 165

```suggestion
									const src = candidate.split(WHITESPACE)[0];
```

**Comment by Rich-Harris** [comment]
thank you!
