### PR TITLE
fix: cache mechanism for request with different headers

### LINKED ISSUE #8752: Caching issue with fetch response: Incorrect behavior observed
### Describe the bug

We ran into this issue while we were trying to do two similar GET requests to our API but with different headers. It seems that the caching system it's using only the URL and the body to create the key. Could you consider adding headers, too? Thanks

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-igyc9t?file=src%2Froutes%2F%2Bpage.js,src%2Froutes%2F%2Bpage.svelte&terminal=dev

You need to download the project to don't run into a CORS issue with the API.

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.28 GB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/kit: ^1.0.0 => 1.3.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by alejogschwind**
closes #8752 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

**Comment by benmccann** [comment]
You would need to update `packages/kit/src/runtime/server/page/serialize_data.js` as well

Also, I think we could probably have just a single hash computed from a combination of the header and body

**Comment by Rich-Harris** [comment]
Thanks! Note that `opts.headers` can be any `HeadersInit` object, so if someone does this...

```js
const headers = new Headers();
headers.append('Authorization', `Bearer ${token}`);
fetch('/blah', { headers });
```

...the hash will be all wrong because `JSON.stringify(headers) === '{}'`. The easiest solution would be along these lines (except combined with `body`, as @benmccann suggests):

```diff
if (opts?.headers) {
-  const headers = JSON.stringify(opts.headers);
+  const headers = [...new Headers(opts.headers)].join(',');
  selector += `[data-headers-hash="${hash(headers)}"]`;
}
```

File: packages/kit/test/apps/basics/test/test.js [hunk 1]
```diff
@@ -262,10 +262,10 @@ test.describe('Load', () => {
 			const payload_b = '{"status":200,"statusText":"","headers":{},"body":"Y"}';
 			// by the time JS has run, hydration will have nuked these scripts
 			const script_contents_a = await page.innerHTML(
-				'script[data-sveltekit-fetched][data-url="/load/serialization-post.json"][data-hash="3t25"]'
+				'script[data-sveltekit-fetched][data-url="/load/serialization-post.json"][data-hash="4jrjph"]'
```
Comment (alejogschwind) [inline packages/kit/test/apps/basics/test/test.js:265]: I still didn't figure out why this test is failing. I updated the hash to consider headers but it seems that the hash now it's different than the test above so maybe there is some header that I'm not considering when I hash manually.

Comment (alejogschwind) [reply packages/kit/test/apps/basics/test/test.js:265]: I found the issue, I was concatenating an ArrayBufferView + string.

To achieve this single hash computation I will need to update the hash function, I don't know if you want to do that. The other option is to concatenate the two hashes `hash(headers) + hash(body)`

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
thank you!
