### PR TITLE
Fix `global is not defined` on vercel edge

### LINKED ISSUE #6424: **Adapter Vercel**: `global is not defined` when build for edge network
### Describe the bug

When a project depends on packages (like `@trpc/client`, for example) that reference the `global` variable and in the `adapter-vercel` config you pass the `edge: true` prop, throws a runtime error when a render is hit saying: `global is not defined`.

### Reproduction

Try to deploy to vercel targeting edge functions instead of lamdba a project that imports a lib that reference the nodejs `global` variable like `@trpc/client` at any serverside point, like `+layout.server.js` or `+layout.js`, and the app should crash.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.17 undefined
    CPU: (4) x64 AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G
    Memory: 2.35 GB / 6.76 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Firefox: 99.0
```

### Severity

serious, but I can work around it

### Additional Information

I will make a PR providing a fix for this bug in a late.

### PR DESCRIPTION
**Pull request by juanvillacortac**
Closes #6424

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]

File: packages/adapter-vercel/index.js [hunk 1]
```diff
@@ -189,7 +189,8 @@ export default function ({ external = [], edge, split } = {}) {
 					platform: 'browser',
 					format: 'esm',
 					external,
-					sourcemap: 'linked'
+					sourcemap: 'linked',
+					banner: { js: 'var global = globalThis;' }
```
Comment (Rich-Harris) [inline packages/adapter-vercel/index.js:193]: this is more future-proof

```suggestion
					banner: { js: 'globalThis.global = globalThis;' }
```

**Comment by Rich-Harris** [comment]
Thanks — I don't love adding hacks like this to work around bugs in libraries, but since this bug is probably quite widespread we'll make an exception.
