### PR TITLE
fix: `$env/*/private` throws for client-side imports on Windows and Tailwind doesn't freak out

### LINKED ISSUE #5723: $env/static/private can be imported in client modules
### Describe the bug

If I understood correctly, mechanisms should be in place that prevent $env/static/private to be imported in client modules (like routes). However, this does not seem to be the case. I can import from $env/static/private and the variables get transpiled into the client side javascript modules.

My excuses if this feature is not yet supposed to work.

### Reproduction

A simple repo showing the issue:
https://github.com/aloker/sveltekit-private-env

https://github.com/aloker/sveltekit-private-env/blob/main/src/routes/index.svelte

### Logs

_No response_

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz   
    Memory: 8.81 GB / 31.81 GB
  Binaries:
    Node: 16.15.1 - c:\tools\node\node.EXE
    Yarn: 1.22.19 - c:\tools\node\yarn.CMD
    npm: 8.13.2 - c:\tools\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.396 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.3
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### LINKED ISSUE #5747: new env handling seems to break tailwindcss
### Describe the bug

while `@tailwind base` is in my app.css i get this error:

```
Error: Cannot import $env/dynamic/private.js into client-side code:
- src/routes/__layout.svelte 
  - src/routes/app.css 
    - $env/dynamic/private.js 
```

basicly the same error as https://github.com/sveltejs/kit/issues/5720

### Reproduction

https://github.com/benjaminlewandowski/sveltekit-tailwindcss-bugreport

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.18 Fedora Linux 36 (Workstation Edition)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 12.38 GB / 31.04 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.6.0 - /run/user/1000/fnm_multishells/288221_1659039694408/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.13.2 - /run/user/1000/fnm_multishells/288221_1659039694408/bin/npm
  Browsers:
    Brave Browser: 103.1.41.100
    Chrome: 103.0.5060.134
    Firefox: 102.0
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.64 => 1.0.0-next.64 
    @sveltejs/kit: 1.0.0-next.396 => 1.0.0-next.396 
    svelte: 3.49.0 => 3.49.0 
    vite: 3.0.3 => 3.0.3
```

### Severity

blocking an upgrade

### Additional Information

demo repo is a minimal setup with that error

### PR DESCRIPTION
**Pull request by tcc-sejohnson**
Closes #5723 and closes #5747. 

The paths for both Vite and Rollup's module graphs needed to be normalized, along with the illegal import paths.

Because Tailwind needs to analyze basically every file in your project, Vite thinks it imports all of them, meaning it'll almost always import `$env/*/private`, causing our helpful module analysis to be, well, unhelpful. In dev, we now ignore non-`js|ts|svelte` files. Rollup doesn't have this problem (because it doesn't have to worry about HMR), so we can be stricter and just analyze all imports. I think this strikes a happy medium. "Provide armor against footguns in dev, and provide even better armor when we try to go to prod."

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

**Comment by dominikg** [comment]
is it possible to use vite's normalizePath here? https://vitejs.dev/guide/api-plugin.html#path-normalization

**Comment by tcc-sejohnson** [comment]
I was hoping someone more knowledgeable would come along and make my day.

**Comment by tcc-sejohnson** [comment]
> I'm surprised none of the browser tests failed on Windows. Maybe we need one that uses `$env/*/private`?

The problem is that these are buildtime/dev-time errors, meaning we'd need a test project dedicated to attempting to build and ensuring the build fails. There are a number of things that'd be useful for -- I'm happy to put an implementation together, but probably not for this PR?

**Comment by benmccann** [comment]
I'm not sure you'd need anything too special or a separate test app. If you fail the build on one of the existing test apps it should turn the CI red

**Comment by tcc-sejohnson** [comment]
> I'm not sure you'd need anything too special or a separate test app. If you fail the build on one of the existing test apps it should turn the CI red

Yes, but we're trying to verify that the build _does_ fail, and the build needs to _not_ fail in order for the rest of the tests to be able to run. Hence, the "metaproject" that tries to build purposefully-failing projects and verifies that they actually do fail.

**Comment by benmccann** [comment]
Oh, right. Yeah, that'd be kind of a pain to test

**Comment by tcc-sejohnson** [comment]
Rich, there's another env var bug I want to work on tonight, but it might step on this one's toes. Easier to merge this one first, if you think it looks good.

**Comment by tcc-sejohnson** [comment]
Heads up @Rich-Harris -- I went ahead and fixed the other bug in this PR as well. It was a pretty simple change.

File: packages/kit/src/vite/utils.js [hunk 1]
```diff
@@ -257,6 +260,14 @@ export function prevent_illegal_vite_imports(node, illegal_imports, out_dir) {
 	if (chain) throw new Error(format_illegal_import_chain(chain, out_dir));
 }
 
+/*
+ * Vite does some weird things with import trees in dev
+ * for example, a Tailwind app.css will appear to import
+ * every file in the project. This isn't a problem for
+ * Rollup during build.
+ */
+const module_types = new Set(['.js', '.ts', '.svelte']);
```
Comment (dominikg) [inline packages/kit/src/vite/utils.js:269]: do we need .mts,.mjs as well? or could it be inverted to stop looking when it encounters a `.css` ? Or is there another boolean on the module graph to see if it is a css module?

This is risky. Right now there is no great support for custom extensions, but it might change and at that point .anything could be a svelte file.

Comment (benmccann) [reply packages/kit/src/vite/utils.js:269]: I had suggested inverting seems risky. What else might this happen with? Postcss, less, etc.? I don't think we should ever support giving a different extension to a `.svelte` file. That just seems weird

Comment (dominikg) [reply packages/kit/src/vite/utils.js:269]: mdsvex with `.svx` or `.md` would like a word

Comment (dominikg) [reply packages/kit/src/vite/utils.js:269]: at the end of the day this is all tailwinds fault btw. it should not declare a dependency on a private env file in the first place

Comment (dominikg) [reply packages/kit/src/vite/utils.js:269]: looks like you can add configuration to tailwind to avoid this: https://github.com/sveltejs/kit/issues/5747#issuecomment-1199121656 

imho that's better than adding this restriction that might miss something.

Comment (Conduitry) [reply packages/kit/src/vite/utils.js:269]: Is there a reason to be telling Tailwind JIT to look at JS files anyway? Is that a recommendation on their website?

I agree that updating `tailwind.config.cjs` in a project seems better than adding this escape hatch here in Kit.

Comment (benmccann) [reply packages/kit/src/vite/utils.js:269]: > Is there a reason to be telling Tailwind JIT to look at JS files anyway? Is that a recommendation on their website?

That's the default config you get when setting up a new Tailwind project. The reason for it is here: https://github.com/sveltejs/kit/issues/5747#issuecomment-1199546971

Comment (Conduitry) [reply packages/kit/src/vite/utils.js:269]: Hmm, yeah, that's unfortunate. I'm not sure what I'd suggest here. I'm not saying I _never_ want to make a change within SvelteKit to accommodate this, but I do think we should revert that change from this PR and have it just be about the fairly uncontroversial Windows fix so we can get that out the door.

Comment (tcc-sejohnson) [reply packages/kit/src/vite/utils.js:269]: I get the reticence here, but it seems better to go this route (with the extra file extensions, probably?) and fix a bug that _actually prevents using SvelteKit_ than to sit around and try to find some other upstream fix. We're still being fully strict in `build`, so at worst, users would be able to develop their app and then have to go back and adjust some imports when they try to build.

Comment (tcc-sejohnson) [reply packages/kit/src/vite/utils.js:269]: Like, this issue is preventing _me_ from upgrading to use _the feature I implemented_, and there's no other way I can think of to fix it -- Tailwind really _is_ depending on those files during dev. This bug represents a complete blocker to using Tailwind in a SK project at all.

Comment (benmccann) [reply packages/kit/src/vite/utils.js:269]: Yeah, this seems like a pretty good compromise to me. Check `.js`/`.ts`/`.svelte` files during dev. Less common stuff like `.mdx` can get checked during build

Comment (tcc-sejohnson) [reply packages/kit/src/vite/utils.js:269]: Okay, quick poll on which filetypes to consider. I think we should at least add `mts|mjs`. I don't really know why we wouldn't go ahead and add the three common mdsvex types: `svelte.md|svx|md`. That should cover virtually all bases. Anything else is such an edge case that we'll catch it in build and not have to feel bad about it.

Comment (Conduitry) [reply packages/kit/src/vite/utils.js:269]: Hm. Yeah, I guess so. If we don't run into this sort of issue during `build` (i.e., we can continue to deny all imports of forbidden modules across the board), then during `dev` it's probably better to blacklist JS/TS/Svelte files than it is to whitelist CSS/Less/SASS/etc. files.

Comment (tcc-sejohnson) [reply packages/kit/src/vite/utils.js:269]: Yeah, this is _strictly_ a dev-time limitation. I think it has something to do with HMR.

If we can get a quick consensus on the filetypes I'll make an update and it'll be good to go. I think the complete list should be:

```
ts
js
svelte
mts
mjs
cts
cjs
svelte.md
svx
md
```

That's a relatively short but (I think?) all-encompassing list that should avoid weirdness about things that aren't actually imports and provide as close to a buildtime experience as possible.

Comment (dummdidumm) [reply packages/kit/src/vite/utils.js:269]: I approve that list

Comment (benmccann) [reply packages/kit/src/vite/utils.js:269]: sounds fine to me

**Comment by tcc-sejohnson** [comment]
Okay, once we see the green christmas tree list we should be GTM @Rich-Harris

File: packages/kit/src/vite/utils.js [hunk 2]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
 	illegal_imports,
 	seen = new Set()
 ) => {
-	if (seen.has(node.id)) return;
-	seen.add(node.id);
+	const nodeId = normalizePath(node.id);
+	if (seen.has(nodeId)) return null;
+	seen.add(nodeId);
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:228]:
```suggestion
	const name = normalizePath(node.id);
	if (seen.has(name)) return null;
	seen.add(name);
```

File: packages/kit/src/vite/utils.js [hunk 3]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 
-	if (illegal_imports.has(node.id)) {
-		return [{ name: node.id, dynamic }];
+	if (illegal_imports.has(nodeId)) {
+		return [{ name: nodeId, dynamic }];
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:231]:
```suggestion
	if (illegal_imports.has(name)) {
		return [{ name, dynamic }];
```

File: packages/kit/src/vite/utils.js [hunk 4]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 	}
 
 	for (const id of node.importedIds) {
 		const child = node_getter(id);
 		const chain =
 			child && find_illegal_rollup_imports(node_getter, child, false, illegal_imports, seen);
-		if (chain) return [{ name: node.id, dynamic }, ...chain];
+		if (chain) return [{ name: nodeId, dynamic }, ...chain];
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:238]:
```suggestion
		if (chain) return [{ name, dynamic }, ...chain];
```

File: packages/kit/src/vite/utils.js [hunk 5]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 	}
 
 	for (const id of node.dynamicallyImportedIds) {
 		const child = node_getter(id);
 		const chain =
 			child && find_illegal_rollup_imports(node_getter, child, true, illegal_imports, seen);
-		if (chain) return [{ name: node.id, dynamic }, ...chain];
+		if (chain) return [{ name: nodeId, dynamic }, ...chain];
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:245]:
```suggestion
		if (chain) return [{ name, dynamic }, ...chain];
```

File: packages/kit/src/vite/utils.js [hunk 6]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 	}
+
+	seen.delete(nodeId);
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:248]:
```suggestion
	seen.delete(name);
```

File: packages/kit/src/vite/utils.js [hunk 7]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
+	'.js',
+	'.svelte',
+	'.mts',
+	'.mjs',
+	'.cts',
+	'.cjs',
+	'.svelte.md',
+	'.svx',
+	'.md'
+]);
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:280]: this hardcoded list makes me nervous. At the very least shouldn't it include `config.extensions` and `config.kit.moduleExtensions`?

File: packages/kit/src/vite/utils.js [hunk 8]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 /**
  * @param {import('vite').ModuleNode} node
- * @param {Set<string>} illegal_imports
+ * @param {Set<string>} illegal_imports Illegal module IDs -- be sure to call vite.normalizePath!
  * @param {Set<string>} seen
  * @returns {Array<import('types').ImportNode> | null}
  */
 function find_illegal_vite_imports(node, illegal_imports, seen = new Set()) {
 	if (!node.id) return null; // TODO when does this happen?
+	const nodeId = normalizePath(node.id);
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:290]:
```suggestion
	const name = normalizePath(node.id);
```

File: packages/kit/src/vite/utils.js [hunk 9]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 
-	if (seen.has(node.id)) return null;
-	seen.add(node.id);
+	if (seen.has(nodeId) || !module_types.has(path.extname(nodeId))) return null;
+	seen.add(nodeId);
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:293]:
```suggestion
	if (seen.has(name) || !module_types.has(path.extname(name))) return null;
	seen.add(name);
```

File: packages/kit/src/vite/utils.js [hunk 10]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 
-	if (node.id && illegal_imports.has(node.id)) {
-		return [{ name: node.id, dynamic: false }];
+	if (nodeId && illegal_imports.has(nodeId)) {
+		return [{ name: nodeId, dynamic: false }];
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:296]:
```suggestion
	if (name && illegal_imports.has(name)) {
		return [{ name, dynamic: false }];
```

File: packages/kit/src/vite/utils.js [hunk 11]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 	}
 
 	for (const child of node.importedModules) {
 		const chain = child && find_illegal_vite_imports(child, illegal_imports, seen);
-		if (chain) return [{ name: node.id, dynamic: false }, ...chain];
+		if (chain) return [{ name: nodeId, dynamic: false }, ...chain];
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:301]:
```suggestion
		if (chain) return [{ name, dynamic: false }, ...chain];
```

File: packages/kit/src/vite/utils.js [hunk 12]
```diff
@@ -223,59 +223,84 @@ const find_illegal_rollup_imports = (
...
 	}
 
+	seen.delete(nodeId);
```
Comment (Rich-Harris) [inline packages/kit/src/vite/utils.js:304]:
```suggestion
	seen.delete(name);
```

**Review by Rich-Harris — CHANGES_REQUESTED** [review]
we need a snake_case lint rule!

**Review by Rich-Harris — APPROVED** [review]

**Comment by Rich-Harris** [comment]
actually i rescind my approval until i'm confident that the firefox tests are just flaking
