### PR TITLE
[fix] remove Sverdle from Stackblitz template

### LINKED ISSUE #7277: The demo app does not work on Stackblitz
### Describe the bug

The Sverdle demo app does not fully function on Stackblitz. Entering a guess and hitting Enter produces the following error:

```
Unexpected token 'C', "Cross-site"... is not valid JSON
```

This is because `sverdle?/enter` returns "Cross-site POST form submissions are forbidden"

### Reproduction

Go to sveltekit.new, go to Sverdle, enter a guess, and hit enter. The error will be displayed.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.83 
    @sveltejs/kit: next => 1.0.0-next.516 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

### Severity

serious, but I can work around it

### Additional Information

In Discord, Rich suggested that maybe have a branch where CSRF protection is disabled specifically for the sveltekit.new demo. We want to keep it enabled in the normal demo case.

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #7277

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/create-svelte/scripts/update-template-repo-contents.js [hunk 1]
```diff
@@ -21,3 +21,18 @@ await create(repo, {
 	prettier: true,
 	playwright: false
 });
+
+// Remove the Sverdle from the template because it doesn't work within Stackblitz (cookies not set)
+fs.rmSync(path.join(repo, 'src', 'routes', 'sverdle'), { force: true, recursive: true });
+
+const header = fs.readFileSync(path.join(repo, 'src', 'routes', 'Header.svelte'), 'utf-8');
+fs.writeFileSync(
+	path.join(repo, 'svelte.config.js'),
```
Comment (gtm-nayan) [inline packages/create-svelte/scripts/update-template-repo-contents.js:30]: svelte.config.js?

Might wanna add some comments here, it's not immediately clear what's happening here, and for the regexes as well.

**Review by Rich-Harris — APPROVED** [review]
