### PR TITLE
fix: deal with fast consecutive promise resolutions when streaming

### LINKED ISSUE #9330: Only one promise resolves when streamed from load (using Promise.resolve)
### Describe the bug

I am using SvelteKit with the adapter/node.
I am connecting to an external API and cache the responses.
On the first request (no cache) I return the promises of the api calls.
All of them are resolved correctly.

On the second request (valid cache) I return the cache value wrapped in a `Promise.resolve()`.
If I use that for only one Promise, this promise resolves in the `{#await}` block.
If I have more than one Promise, only the first promise resolves in the `{#await}` block, all others show the loading state.

### Reproduction

Stackblitz: https://stackblitz.com/edit/sveltejs-kit-template-default-fgdj1s?file=src/routes/+page.server.js

image

the second promise never resolves

got to `/only-one` => everything resolves correctly

### Logs

_No response_

### System Info

```Shell
Should not be relevant, as it can be reproduced on stackblitz.

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics     
    Memory: 11.05 GB / 31.56 GB
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Volta\tools\image\node\18.12.1\node.EXE    
    Yarn: 1.22.18 - ~\AppData\Local\Volta\tools\image\yarn\1.22.18\bin\yarn.CMD
    npm: 8.19.2 - ~\AppData\Local\Volta\tools\image\node\18.12.1\npm.CMD       
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: ^1.2.0 => 1.2.0 
    @sveltejs/kit: ^1.10.0 => 1.10.0 
    svelte: ^3.55.0 => 3.55.1
```

### Severity

serious, but I can work around it

### Additional Information

can be worked around with a promise wrapper

```ts
const promiseWrap = <T>(value: T): Promise<T> => new Promise((resolve) => {
    setTimeout(() => resolve(value));
})
```

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #9330

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/utils/streaming.js [hunk 1]
```diff
@@ -23,22 +23,29 @@ function defer() {
...
+	let deferred = [defer()];
 
 	return {
 		iterator: {
 			[Symbol.asyncIterator]() {
 				return {
-					next: () => deferred.promise
+					next: async () => {
+						const next = await deferred[0].promise;
+						deferred.shift();
```
Comment (dummdidumm) [inline packages/kit/src/utils/streaming.js:34]: better safe than sorry - this adheres more closely to the iterator protocol
```suggestion
						if (!next.done) deferred.shift();
```

File: packages/kit/src/utils/streaming.js [hunk 2]
```diff
@@ -23,22 +23,29 @@ function defer() {
...
 	return {
 		iterator: {
 			[Symbol.asyncIterator]() {
 				return {
-					next: () => deferred.promise
+					next: async () => {
+						const next = await deferred[0].promise;
+						if (!next.done) deferred.shift();
+						return next;
+					}
```
Comment (Rich-Harris) [inline packages/kit/src/utils/streaming.js:36]:
```suggestion
					next: deferred.shift().promise
```

File: packages/kit/src/utils/streaming.js [hunk 3]
```diff
@@ -23,22 +23,29 @@ function defer() {
...
 				};
 			}
 		},
 		push: (value) => {
-			deferred.fulfil({ value, done: false });
-			deferred = defer();
+			deferred[deferred.length - 1].fulfil({
```
Comment (Rich-Harris) [inline packages/kit/src/utils/streaming.js:41]:
```suggestion
			deferred.at(-1).fulfil({
```

File: packages/kit/src/utils/streaming.js [hunk 4]
```diff
@@ -23,22 +23,29 @@ function defer() {
...
+				value,
+				done: false
+			});
+			deferred.push(defer());
 		},
 		done: () => {
-			deferred.fulfil({ done: true });
+			deferred[deferred.length - 1].fulfil({ done: true });
```
Comment (Rich-Harris) [inline packages/kit/src/utils/streaming.js:48]:
```suggestion
			deferred.at(-1).fulfil({ done: true });
```

Comment (dummdidumm) [reply packages/kit/src/utils/streaming.js:48]: I had that previously but that requires you to do a stupid type cast because TS says "this might be undefined" and that code was harder to read/longer.

File: packages/kit/src/utils/streaming.js (hunk 3 above)
Comment (dummdidumm) [reply packages/kit/src/utils/streaming.js:41]: see comment below

File: packages/kit/src/utils/streaming.js (hunk 4 above)
Comment (Rich-Harris) [reply packages/kit/src/utils/streaming.js:48]: wait TS thinks `array.at(x)` might be undefined but `array[x]` is not? the fuck?

File: packages/kit/src/utils/streaming.js (hunk 2 above)
Comment (dummdidumm) [reply packages/kit/src/utils/streaming.js:36]: This needs a type cast because TS doesn't know this is always defined, and strictly speaking it's not adhering to the spec that says you can call `next` as much as you want after it's done (it should always return `done: true` in that state).

File: packages/kit/src/utils/streaming.js (hunk 4 above)
Comment (dummdidumm) [reply packages/kit/src/utils/streaming.js:48]: I think this is mostly due to backwards compatibility to not break existing code bases. They have another flag outside the `strict` family that turns on the same behavior for `array[x]`

**Review by Rich-Harris — APPROVED** [review]
