### PR TITLE
fix: provide better error message in case of missing `+page.svelte`

### LINKED ISSUE #8270: 500 internal error using form actions from different directory when calling `fail()` (node.component is not a function)
### Describe the bug

When i return a `fail()` inside a form action which is in a different directory than the `+page.svelte` itself i throws an error saying `TypeError: node.component is not a function`

I have two identical `+page.server.js` files one inside `/routes` and one inside `/routes/auth`.
It works as expected when the `+page.server.js` and `+page.svelte` files are inside the same directory.
I believe it's because of the url changing after the form submission to `/auth?/login` so it tries to load the `+page.svelte` file from the `/auth` directory which there is not thus throwing the `node.component is not a function` error.

I hope its clear what i mean i also made a live demo here: https://sveltekit-auth-ruby.vercel.app/
The source code can be found here: https://github.com/higoka/sveltekit-auth

### Reproduction

live demo: https://sveltekit-auth-ruby.vercel.app/
source code: https://github.com/higoka/sveltekit-auth

### Logs

```Shell
node.component is not a function
TypeError: node.component is not a function
    at file:///Users/nicorickenbach/Sites/sveltekit-auth/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:82:64
    at Array.map (<anonymous>)
    at render_response (file:///Users/nicorickenbach/Sites/sveltekit-auth/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:82:41)
    at render_page (file:///Users/nicorickenbach/Sites/sveltekit-auth/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:299:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///Users/nicorickenbach/Sites/sveltekit-auth/node_modules/@sveltejs/kit/src/runtime/server/index.js:356:17)
    at async respond (file:///Users/nicorickenbach/Sites/sveltekit-auth/node_modules/@sveltejs/kit/src/runtime/server/index.js:229:20)
    at async file:///Users/nicorickenbach/Sites/sveltekit-auth/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:444:22
```

### System Info

```Shell
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 2.67 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
closes #8270

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/server/page/render.js [hunk 1]
```diff
@@ -73,6 +73,15 @@ export async function render_response({
 			: null;
 
 	if (page_config.ssr) {
+		if (!branch.at(-1)?.node.component) {
```
Comment (dummdidumm) [inline packages/kit/src/runtime/server/page/render.js:76]: Not wrapped with `DEV` because I noticed it's `false` when running `vite dev` in `sites/kit.svelte.dev`, similar to what [Rich encountered](https://github.com/sveltejs/kit/pull/8429#issuecomment-1378825746). I'm wondering if this hints at a bigger problem? Is `DEV` not working as expected after all?

Comment (benmccann) [reply packages/kit/src/runtime/server/page/render.js:76]: I filed an issue so we can have a single place to investigate: https://github.com/sveltejs/kit/issues/8492

Comment (benmccann) [reply packages/kit/src/runtime/server/page/render.js:76]: I sent a fix to Vite for the `DEV` bug

**Comment by Rich-Harris** [comment]
Is this `ssr` specific? If you create `src/routes/foo/+page.js` with `export const ssr = false` and navigate to `/foo`, you'll see a blank page, which feels like a bug. I think we probably want to insist on there being a `+page.svelte` alongside any `+page.js` or `+page.server.js` regardless of page config (and we could do that check a single time, in `create_manifest_data`)

**Comment by Rich-Harris** [comment]
Hmm, except then again I've written `+page(.server).js` like this without a `+page.svelte` file before, and it seems like a reasonable thing to be able to do:

```js
import { redirect } from '@sveltejs/kit';

export function load() {
  throw redirect(308, '/docs/introduction');
}
```

**Comment by dummdidumm** [comment]
Yes, because of that we can't just have a static check. The linked issue is handled by the implemented check, your edge case isn't thought, but I doubt that someone having only `export const ssr = false` and no `load` function or `+page.svelte` occurs that often that we should try to catch this, too. (theoretically it's possible to catch this case at runtime, too, but would require more code gymnastics than I think it's worth)

**Comment by Rich-Harris** [comment]
Yeah I had a quick go at adding logic to `client.js` but couldn't immediately see an easy way to make it work, so I'm happy to leave that as a TODO for another day

File: packages/kit/src/runtime/server/page/render.js [hunk 2]
```diff
@@ -73,6 +73,15 @@ export async function render_response({
...
+			// Can only be the leaf, layouts have a fallback component generated
+			throw new Error(
+				`+page.svelte component for route ${event.route.id} is missing. ` +
+					`It is required because route is rendered in response to ${
+						action_result ? 'a form action' : 'a navigation'
+					}.`
+			);
+		}
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/page/render.js:84]: I'm not sure the extra context is required, we can keep the message simple I think

```suggestion
			throw new Error(`Missing +page.svelte component for route ${event.route.id}`);
```

Comment (dummdidumm) [reply packages/kit/src/runtime/server/page/render.js:84]: I was debating this myself, me more I think about the more I agree

**Review by Rich-Harris — APPROVED** [review]
