### PR TITLE
fix: load CSS when using server-side route resolution

### LINKED ISSUE #13491: Server route resolution breaks styles in .svelte files
### Describe the bug

When using the new `router: { resolution: 'server' }` option to resolve routes on the server, the style tags in .svelte files will no longer work upon loading a route, at least not with `@sveltejs/adapter-node`.

### Reproduction

https://github.com/amanita-green/sveltekit-style-issue

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Linux 6.13 Arch Linux
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 45.75 GB / 62.01 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.14.0 - ~/.nvm/versions/node/v22.14.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v22.14.0/bin/npm
  Browsers:
    Brave Browser: 133.1.75.175
    Chromium: 133.0.6943.53
  npmPackages:
    @sveltejs/adapter-auto: ^4.0.0 => 4.0.0 
    @sveltejs/adapter-node: ^5.2.12 => 5.2.12 
    @sveltejs/kit: ^2.17.2 => 2.17.2 
    @sveltejs/vite-plugin-svelte: ^5.0.3 => 5.0.3 
    svelte: ^5.20.2 => 5.20.2 
    vite: ^6.1.1 => 6.1.1
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
When implementing server-side route resolution we didn't think of the CSS associated with the entry points of the pages. Since Vite isn't involved in that chain, it can't automatically wire up the imports correctly, so we gotta add code to load them ourselves.

Fixes #13491

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/runtime/client/utils.js [hunk 1]
```diff
@@ -331,3 +331,40 @@ export function is_external_url(url, base, hash_routing) {
...
+ * (which ideally we could just use directly, but it's not exported)
+ * @param {string[]} deps
+ */
+export function load_css(deps) {
+	if (__SVELTEKIT_CLIENT_ROUTING__) return;
+
+	const cspNonceMeta = /** @type {HTMLMetaElement} */ (
+		document.querySelector('meta[property=csp-nonce]')
+	);
+	const cspNonce = cspNonceMeta?.nonce || cspNonceMeta?.getAttribute('nonce');
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/utils.js:351]:
```suggestion
	const csp_nonce_meta = /** @type {HTMLMetaElement} */ (
		document.querySelector('meta[property=csp-nonce]')
	);
	const csp_nonce = csp_nonce_meta?.nonce || csp_nonce_meta?.getAttribute('nonce');
```

File: packages/kit/src/runtime/client/utils.js [hunk 2]
```diff
@@ -331,3 +331,40 @@ export function is_external_url(url, base, hash_routing) {
...
+		if (document.querySelector(`link[href="${dep}"][rel="stylesheet"]`)) {
+			continue;
+		}
+
+		const link = document.createElement('link');
+		link.rel = 'stylesheet';
+		link.crossOrigin = '';
+		link.href = dep;
+		if (cspNonce) {
+			link.setAttribute('nonce', cspNonce);
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/client/utils.js:366]:
```suggestion
		if (csp_nonce) {
			link.setAttribute('nonce', csp_nonce);
```

File: packages/kit/src/runtime/server/page/server_routing.js [hunk 3]
```diff
@@ -105,10 +105,43 @@ export function create_server_routing_response(route, params, url, manifest) {
...
+
+	for (const node of [...errors, ...layouts.map((l) => l?.[1]), leaf[1]]) {
+		if (typeof node !== 'number') continue;
+		const node_css = manifest._.client.css?.[node];
+		for (const css_path of node_css ?? []) {
+			if (assets !== '') {
+				css += `'${assets}/${css_path}',`;
+			} else {
+				css += `'${base}/${css_path}',`;
+			}
```
Comment (Rich-Harris) [inline packages/kit/src/runtime/server/page/server_routing.js:140]:
```suggestion
			css += `'${assets || base}/${css_path}',`;
```

**Review by Rich-Harris — APPROVED** [review]
