### PR TITLE
Avoid FOUC when using CSS modules in dev

### LINKED ISSUE #5019: Styles flash when using CSS Modules in the development environment
### Describe the bug

Styles flash when using CSS Modules in the development environment .
I found that in inlineStyle, the style of CSS Module was not inserted correctly, and the [object object] was incorrectly spliced.
You 
You can view source code  by running the local environment (yarn dev).
image

### Reproduction

https://github.com/anpabupa/sveltejs-kit-template-default-hf6rzq

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 475.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.44 
    @sveltejs/kit: next => 1.0.0-next.338 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by DrLoopFall**
Fixes #5019

Importing CSS modules causes flash of unstyled content, as an object is returned from Vite causing it to be injected as `[object Object]` inside the style tag.
Importing with `?inline`, allows Vite to returns the CSS  as string which can be used inside the style tag.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/exports/vite/dev/index.js [hunk 1]
```diff
@@ -175,15 +175,20 @@ export async function dev(vite, vite_config, svelte_config) {
...
 									isCSSRequest(dep.file) ||
 									(query.has('svelte') && query.get('type') === 'style')
 								) {
+									// setting `?inline` to load CSS modules as css string
+									query.set('inline', '');
+
 									try {
-										const mod = await loud_ssr_load_module(dep.url);
+										const mod = await loud_ssr_load_module(
+											`${url.pathname}${url.search}${url.hash}`
```
Comment (benmccann) [inline packages/kit/src/exports/vite/dev/index.js:190]: I think there won't ever be a `url.hash` since the browser doesn't sentdit to the server?

Comment (DrLoopFall) [reply packages/kit/src/exports/vite/dev/index.js:190]: The `dep.url` is actually from Vite imports, not from the browser.
The `url.hash` is present if we import with hash e.g. `import 'style.css?query#hash'` (Vite would throw error if hash is used without query).
I thought some plugins may use it?

File: packages/kit/src/exports/vite/dev/index.js [hunk 2]
```diff
@@ -175,15 +175,20 @@ export async function dev(vite, vite_config, svelte_config) {
...
-								const query = parsed.searchParams;
+								const url = new URL(dep.url, 'http://localhost/');
+								const query = url.searchParams;
 
 								if (
 									isCSSRequest(dep.file) ||
 									(query.has('svelte') && query.get('type') === 'style')
 								) {
+									// setting `?inline` to load CSS modules as css string
+									query.set('inline', '');
```
Comment (Rich-Harris) [inline packages/kit/src/exports/vite/dev/index.js:186]: does this have any effect outside CSS modules? am wondering if we should only do this in the CSS module case (i.e. `dep.file.endsWith('.module.css')`) or if it's safe to do it everywhere

Comment (bluwy) [reply packages/kit/src/exports/vite/dev/index.js:186]: I think it's safe to do it everywhere, and in fact importing CSS directly to get the preprocessed CSS string is deprecated in Vite 4, though looks like we missed making a warning in `ssrLoadModule`.

In Vite 4, to get preprocessed CSS string only, you'd need to use `?inline`. Because before, `.css` imports implied two things: (1) inject style to head and (2) get css string. And Vite has to hack around with the `?used` query.

File: packages/kit/src/exports/vite/dev/index.js (hunk 1 above)
Comment (bluwy) [reply packages/kit/src/exports/vite/dev/index.js:190]: I think it would be very rare for imports to contain `#` (that usually cause issues with Vite too). But I guess it wouldn't hurt to support it if we want too, for correctness.

Comment (bluwy) [reply packages/kit/src/exports/vite/dev/index.js:190]: Actually Ben might be right too as the `url` comes from the module graph, which is created from server requests, so they don't have hashes.

Comment (Rich-Harris) [reply packages/kit/src/exports/vite/dev/index.js:190]:
```suggestion
											url.pathname + url.search
```

Comment (DrLoopFall) [reply packages/kit/src/exports/vite/dev/index.js:190]: Just checked the the hash is actually present, it's also sent from `vite.ssrLoadModule` to the plugins.
Don't know if anyone uses it, can remove if needed?

Comment (Rich-Harris) [reply packages/kit/src/exports/vite/dev/index.js:190]: Yeah, I just checked this too, the hash is indeed preserved. Sorry for the runaround, the existing code is perfectly correct

**Review by Rich-Harris — APPROVED** [review]

**Comment by benmccann** [comment]
Thank you @DrLoopFall!
