### PR TITLE
throw if url.search or url.searchParams is accessed from page store during prerendering

### LINKED ISSUE #2361: `query` accessible from page store during prerendering, but shouldn't be
### Describe the bug

Building with `sveltejs/adapter-static` does not give me the correct query.

`svelte-kit dev` and `svelte-kit preview` work fine.

However, if I build with `@sveltejs/adapter-static`, I don't get the correct query parameters.
Especially after a reload.

### Reproduction

https://github.com/ssssota/sveltekit-static-query

### Logs

_No response_

### System Info

```shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 8.18 GB / 15.93 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18
    @sveltejs/kit: next => 1.0.0-next.162
    svelte: ^3.42.4 => 3.42.4
```

### Severity

serious, but I can work around it

### Additional Information

I think the hydrate part of the initialization is suspicious.

*[/build/index.html](https://github.com/ssssota/sveltekit-static-query/blob/gh-pages/index.html#L18-L41)*
```js
import { start } from "/_app/start-19affe50.js";
start({
	target: document.querySelector("#svelte"),
	paths: {"base":"","assets":""},
	session: {},
	host: location.host,
	route: true,
	spa: false,
	trailing_slash: "never",
	hydrate: {
		status: 200,
		error: null,
		nodes: [
			import("/_app/pages/__layout.svelte-e8a46f20.js"),
			import("/_app/pages/index.svelte-9233398d.js")
		],
		page: {
			host: location.host, // TODO this is redundant
			path: "/",
			query: new URLSearchParams(""), /* 🤔 */
			params: {}
		}
	}
});
```

### PR DESCRIPTION
**Pull request by Rich-Harris**
supersedes #2363, closes #2361. Ensures that people don't accidentally grab the query string during prerendering (though they could still get it via `url.href` or `url.toString()` if they really want to make life hard for themselves)

* only creates the `url` proxy if we're prerendering
* creates it for the page store as well as the `load` function

A proper prerendering test suite is still a TODO...

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpx changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/server/page/utils.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/** @param {URL} url */
+export function create_url_proxy(url) {
```
Comment (Conduitry) [inline packages/kit/src/runtime/server/page/utils.js:2]: Perhaps a different name for this? The current one doesn't suggest anything about this just being used for prerendering.

Comment (Rich-Harris) [reply packages/kit/src/runtime/server/page/utils.js]: done

**Review by Conduitry — APPROVED** [review]

**Review by bluwy — APPROVED** [review]

**Review by benmccann — APPROVED** [review]
