### PR TITLE
[fix] encode if root layout has server load

### LINKED ISSUE #6336: Layout data is cleared when url is used in +layout.ts
### Describe the bug

I was having some simple redirect logic in my application in +layout.ts:
```svelte
export const load = async ({ data, url }) => {
	const { user } = data || {};
	if (user && url.pathname === '/login') {
		throw redirect(302, '/');
	}
	if (!user && url.pathname !== '/login') {
		throw redirect(302, '/login');
	}
	return {
		user
	};
};
```

After updating to @sveltejs/kit@1.0.0-next.444, the app was fully reloading when navigating instead of client side routing. After some investigation I found out that using url in +layout causes the data passed from +layout.server to be cleared.

In the example below I am just logging url.pathname in +layout and displaying the data in the Home page. When navigating from and the back to the home page;  the data is cleared. That won't happen if console.log(url.pathname) is removed from +layout.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-bdr4bj?file=src/routes/+layout.js

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 1.63 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.11 - ~/.npm-global/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: ^1.0.0-next.423 => 1.0.0-next.444 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.9
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### LINKED ISSUE #6349: +layout.server.ts load doesn't run after invalidate()
### Describe the bug

The `invalidate()` function no longer triggers a reload of the root layout (which has changed data). It works on v443, but stopped working on v444+

### Reproduction

https://github.com/CaptainCodeman/sveltekit-example/tree/ssr

The `invalidate()` call happens after client-side auth state changes and `/session` is called to set or clear server-side cookie. `LayoutData` should reflect the `user` from that cookie.

Needs firebase emulator running to execute locally. I can make a simpler cutdown repro if needed, was just working on this example which made me notice it:

No data reloads with v444:

https://user-images.githubusercontent.com/304910/187050362-e0a2204c-d334-43dd-8f83-f4e6f4286728.mov

Same code with v443 showing layout data updates:

https://user-images.githubusercontent.com/304910/187050370-5d9d9692-2a9e-4e77-8089-4e9d33092d91.mov

### Logs

_No response_

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.97 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5265.0
    Firefox: 103.0.2
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.87 
    @sveltejs/kit: 1.0.0-next.444 => 1.0.0-next.444 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #6349
Fixes #6336

While fixing it I thought of ways to make the manifest shorter. I did that in a second commit so it can be reverted if not appropriate.

No test, I can't think of a way to test this without creating another test app, which I wanted to avoid - but can do so if we feel it's necessary.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/core/sync/write_client_manifest.js [hunk 1]
```diff
@@ -93,5 +96,6 @@ export function write_client_manifest(manifest_data, output) {
  * @param {number} id
  */
 function get_node_id(nodes, id) {
+	console.log(nodes[id]);
```
Comment (Conduitry) [inline packages/kit/src/core/sync/write_client_manifest.js:99]:
```suggestion
```

I also don't see this "second commit" you mention in the PR description.

Comment (dummdidumm) [reply packages/kit/src/core/sync/write_client_manifest.js]: oops forgot to push it - done

File: packages/kit/src/core/sync/write_client_manifest.js [hunk 2]
```diff
@@ -43,25 +43,32 @@ export function write_client_manifest(manifest_data, output) {
...
+					// are reused across pages, so we safe space by doing it this way.
+					route.page.layouts.forEach((layout) => {
+						if (layout != undefined && manifest_data.nodes[layout].server) {
+							layouts_with_server_load.add(layout);
+						}
+					});
 
-					// only include non-root layout/error nodes if they exist
-					if (layouts.length > 0 || errors.length > 0) array.push(`[${layouts.join(',')}]`);
+					array.push(`[${layouts.join(',')}]`);
```
Comment (dummdidumm) [inline packages/kit/src/core/sync/write_client_manifest.js:70]: Just realized, with the manifest adjustment the if that was there before can be reinstated

**Review by Rich-Harris — APPROVED** [review]
