### PR TITLE
Accumulate `data`

### LINKED ISSUE #5994: Accumulate data into `export let data`
### Describe the bug

This is an "opinionated" take on the recent changes to routes and `load` function behavior. It's a big change, that I am not a fan of but can see the merit. Among other things it now requires more boilerplate code, which we all don't like to deal with. 

Here's the problem:  +page.svelte doesn't receive `data` unless there's +page.ts file with `load` function even though we might have `data` set by parent layouts. This forces one to create a bunch of +page.ts files with a the following boilerplate. Wouldn't be nicer to do that as a default for all pages, so we don't have to create +page.ts files unless we're actually doing something specific there? 

```
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ parent }) => {
  return await parent();
};
```
 

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-f8ky2l?file=src/routes/+page.js

The +page.js file seems to be completely unnecessary but you can't remove it or +page receives no `data`.

### Logs

_No response_

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.416 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

serious, but I can work around it

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rich-Harris**
Closes #5994.

Today, if you have a page with a `load`...

```js
// src/routes/foo/+page.js
export function load() {
  return {
    pagedata: 'hello from page load'
  };
}
```

...then the corresponding `data` prop will contain `pagedata` and nothing else. If you have some data from a layout `load` function that you need in the page, you need to call `await parent()` in the page's `load`:

```diff
// src/routes/foo/+page.js
-export function load() {
+export async function load({ parent }) {
+  const { layoutdata } = await parent();
  return {
+    layoutdata,
    pagedata: 'hello from page load'
  };
}
```

As of this PR, that's no longer the case — layout data will automatically be inherited (with correct types!) so that you can reference `data.layoutdata` (or, more realistically, `data.user.name`) throughout your app without boilerplate.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/runtime/client/client.js [hunk 1]
```diff
@@ -403,10 +403,10 @@ export function create_client({ target, base, trailing_slash }) {
 		let data = {};
 		let data_changed = false;
 		for (let i = 0; i < filtered.length; i += 1) {
-			Object.assign(data, filtered[i].data);
+			data = { ...data, ...filtered[i].data };
 			// Only set props if the node actually updated. This prevents needless rerenders.
 			if (!current.branch.some((node) => node === filtered[i])) {
-				result.props[`data_${i}`] = filtered[i].data;
+				result.props[`data_${i}`] = data;
```
Comment (dummdidumm) [inline packages/kit/src/runtime/client/client.js:409]: Is this logic still correct? If any parent updates, so does the data so we likely can no longer rely on "this node didn't change", but rather "everything up to and including this node didn't change"

File: packages/kit/src/core/sync/write_types.js [hunk 2]
```diff
@@ -449,36 +449,43 @@ function process_node(ts, node, outdir, params, groups) {
...
+			node.shared,
+			`${parent_type} & ${server_data}`,
+			proxy
+		)}`;
+		load = `Kit.Load<${params}, ${server_data}, ${parent_type}, OutputData>`;
+	} else if (server_data === 'null') {
+		data = parent_type;
 	} else {
-		data = server_data;
+		data = `${parent_type} & ${server_data}`;
```
Comment (dummdidumm) [inline packages/kit/src/core/sync/write_types.js:470]: This could give a type conflict if they set the same prop but to different types. It probably needs the same omit logic as the parent type function.

File: packages/kit/src/core/sync/write_types.js [hunk 3]
```diff
@@ -449,36 +449,43 @@ function process_node(ts, node, outdir, params, groups) {
...
 	if (node.shared) {
 		const content = fs.readFileSync(node.shared, 'utf8');
 		const proxy = tweak_types(ts, content, shared_names);
 		if (proxy?.modified) {
 			written_proxies.push(write(`${outdir}/proxy${path.basename(node.shared)}`, proxy.code));
 		}
 
-		data = get_data_type(node.shared, 'load', server_data, proxy);
-		load = `Kit.Load<${params}, ${server_data}, ${get_parent_type('LayoutData')}, OutputData>`;
+		data = `${parent_type} & ${get_data_type(
```
Comment (dummdidumm) [inline packages/kit/src/core/sync/write_types.js:461]: Same omit gotcha here

**Review by dummdidumm — COMMENTED** [review]
Looks good! I left three things that probably need a change, also the docs should probably mention this

File: packages/kit/src/core/sync/write_types.js (hunk 2 above)
Comment (Rich-Harris) [reply packages/kit/src/core/sync/write_types.js]: good catch, added

File: packages/kit/src/runtime/client/client.js (hunk 1 above)
Comment (Rich-Harris) [reply packages/kit/src/runtime/client/client.js:409]: oops, yep — nice save

Comment (Rich-Harris) [reply packages/kit/src/runtime/client/client.js:409]: https://github.com/sveltejs/kit/pull/6050/commits/f0823cb459f22d4c22549bb490680f0c6a165ade

**Review by dummdidumm — APPROVED** [review]

**Comment by tsukhu** [comment]
Thank you for this update. I have deleted 3 page.ts files now :-)

**Comment by rohanrajpal** [comment]
Love this!
