### PR TITLE
fix: precompress filter

### LINKED ISSUE #10184: precompress option not working since 1.20.3
### Describe the bug

After npm upgrade took me from sveltekit 1.20.2 to 1.20.4, I noticed that the output of svelte-package no longer included .gz and .br files. Reverting to 1.20.2 solves the problem. Since 1.20.3 and 1.20.4 were related to tiny-glob, and builder uses `glob` to locate files for precompression, I'm sure the two are related.

### Reproduction

I believe any build with `precompress: true` is going to fail, but here is my repo: https://github.com/txstate-etc/dosgato-admin. 
- git clone
- Change package.json to un-pin the sveltekit version 
- `npm upgrade`
- `npm run build`
- inspect the `build` directory
- observe that there are no .br or .gz files.

### Logs

```Shell
The broken and non-broken build logs are identical. Neither mentions doing any compression.
```

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 192.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.4
```

### Severity

blocking an upgrade

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gtm-nayan**
closes #10184 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [ ] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/kit/src/core/adapt/builder.js [hunk 1]
```diff
@@ -12,7 +12,9 @@ import { write } from '../sync/utils.js';
 import { list_files } from '../utils.js';
 
 const pipe = promisify(pipeline);
-const extensions = ['html', 'js', 'mjs', 'json', 'css', 'svg', 'xml', 'wasm'];
+const extensions = ['html', 'js', 'mjs', 'json', 'css', 'svg', 'xml', 'wasm'].map(
+	(ext) => `.${ext}`
+);
```
Comment (ghostdevv) [inline packages/kit/src/core/adapt/builder.js:17]: We could instead change the filter in compress to `extname(file).slice(1)`

Comment (ghostdevv) [inline packages/kit/src/core/adapt/builder.js:17]:
```suggestion
const extensions = ['.html', '.js', '.mjs', '.json', '.css', '.svg', '.xml', '.wasm']
```

**Review by ghostdevv — COMMENTED** [review]
You beat me to the punch! Only other issue is that the tiny glob function returned absolute paths which `list_files` does not, breaking `compress_file`

File: packages/kit/src/core/adapt/fixtures/.gitignore [hunk 2]
```diff
@@ -0,0 +1,2 @@
+compress/*.br
+compress/*.gz
```
Comment (gtm-nayan) [inline packages/kit/src/core/adapt/fixtures/.gitignore:2]:
```suggestion
compress/*.gz

```

File: packages/kit/src/core/adapt/builder.spec.js [hunk 3]
```diff
@@ -66,3 +66,17 @@ test('copy files', () => {
 
 	rmSync(dest, { force: true, recursive: true });
 });
+
+test('compress files', async () => {
+	// @ts-ignore
```
Comment (benmccann) [inline packages/kit/src/core/adapt/builder.spec.js:71]: can you either remove this or add an explanation as to why it's necessary?

if it's unfixable then we generally use `@ts-expect-error`. we only use `@ts-ignore` temporarily for ones we intend to fix later

File: packages/kit/src/core/adapt/builder.spec.js [hunk 4]
```diff
@@ -1,7 +1,7 @@
-import { rmSync } from 'node:fs';
-import { join } from 'node:path';
+import { existsSync, rmSync } from 'node:fs';
+import { join, dirname } from 'node:path';
 import { fileURLToPath } from 'node:url';
-import { expect, test } from 'vitest';
+import { assert, expect, test } from 'vitest';
 import glob from 'tiny-glob/sync.js';
```
Comment (benmccann) [inline packages/kit/src/core/adapt/builder.spec.js:5]: how does this work still? is this test actually being run or is it being pulled in as a transitive dependency from some other package?

Comment (gtm-nayan) [reply packages/kit/src/core/adapt/builder.spec.js:5]: This had me spinning around for a good 15 minutes. Turns out it's a workspace dependency so it's available in all packages in the repository.

Comment (benmccann) [reply packages/kit/src/core/adapt/builder.spec.js:5]: ah, I wonder if that caused us not to notice some of these issues because it was available there, but not in end user projects

would you mind removing it as a workspace dependency? you can make it a `devDependency` of this project. we've tried to avoid workspace dependencies in favor of per-project dependencies except for stuff like eslint and prettier

Comment (dummdidumm) [reply packages/kit/src/core/adapt/builder.spec.js:5]: What package should become a `devDependency`? Lost on context

Comment (gtm-nayan) [reply packages/kit/src/core/adapt/builder.spec.js:5]: Oop, forgot about this one, tiny-glob should be moved to the kit devDependencies instead of workspace but I think we can just get rid of it altogether.

Comment (dummdidumm) [reply packages/kit/src/core/adapt/builder.spec.js:5]: Would you do that so we can finish and merge the PR?

File: packages/kit/src/core/adapt/builder.spec.js [hunk 5]
```diff
@@ -46,23 +46,27 @@ test('copy files', () => {
...
 
-	expect(builder.writeClient(dest)).toEqual(
-		glob('**', { cwd: dest, dot: true, filesOnly: true }).map(posixify)
-	);
-
-	expect(glob('**', { cwd: `${outDir}/output/client`, dot: true })).toEqual(
-		glob('**', { cwd: dest, dot: true })
-	);
+	expect(builder.writeClient(dest)).toEqual(list_files(dest).map(posixify));
+	expect(list_files(dest)).toEqual(list_files(dest));
```
Comment (gtm-nayan) [inline packages/kit/src/core/adapt/builder.spec.js:50]:
```suggestion
	expect(list_files(`${outDir}/output/client`)).toEqual(list_files(dest));
```

**Review by dummdidumm — APPROVED** [review]
