### PR TITLE
fix: construct correct pathname for isr from route with nested params

### LINKED ISSUE #9459: 404 Page not found is thrown if using ISR in route with slug
### Describe the bug

I have the following page structure: `/Transfers/From-[from]/To-[to]/By-[by]`

Under the page folder `By-[by]` I added a `+page.server.js` with ISR enabled:

```
export const config = {
  isr: {
    expiration: false,
    bypassToken: BYPASS_TOKEN,
    allowQuery: []
  }
};
```
When I run the application locally with `npm run dev` or `npm run preview` the page is found and rendered correctly. But when deploying to Vercel a 404 error is thrown.

### Reproduction

Visit https://sveltekit-isr-demo.vercel.app/Transfers/From-Krabi-sss/To-Samui/By-Train
Github: https://github.com/tonprince/sveltekit-isr-demo

### Logs

_No response_

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 144.55 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-vercel: ^2.4.0 => 2.4.0 
    @sveltejs/kit: ^1.12.0 => 1.12.0 
    svelte: ^3.57.0 => 3.57.0 
    vite: ^4.2.1 => 4.2.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dummdidumm**
fixes #9459

During testing I noticed that this also fails for optional routes like `[[maybe]]/yes`. The resulting URL to redirect to could contain two `/` in a row, which breaks routing. I'm not sure how this is solvable statically without a bunch of extra logic which potentially breaks other things, so I added a runtime adjustment for that.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### CODE REVIEW

File: packages/adapter-vercel/files/serverless.js [hunk 1]
```diff
@@ -22,10 +22,12 @@ export default async (req, res) => {
...
 
 		const params = new URLSearchParams(search);
-		const pathname = params.get('__pathname');
+		let pathname = params.get('__pathname');
 
 		if (pathname) {
 			params.delete('__pathname');
+			// Optional routes' pathname replacements look like `/foo/$1/bar` which means we could end up with an url like /foo//bar
+			pathname = pathname.replace(/\/+/g, '/');
 			req.url = `${pathname}${path.endsWith(DATA_SUFFIX) ? DATA_SUFFIX : ''}?${params}`;
```
Comment (dummdidumm) [inline packages/adapter-vercel/files/serverless.js:31]: Is this safe to do like this? `pathname` sounds like it should not contain the host/origin etc so not the protocol (`https://`) part which we should leave alone, but `req.url` sounds like it _is_ part if it

**Review by Rich-Harris — APPROVED** [review]
