### PR TITLE
fix: add support for trusted types CSP

### LINKED ISSUE #7975: Support CSP `require-trusted-types-for`
### Describe the problem

Even though `require-trusted-types-for` seems to be present in the list of CSP directives in the configuration, setting it (to `script`, which is its only value) will actually cause SvelteKit to fail to function properly:

image

### Describe the proposed solution

I don't know much about this directive but it seems like what is assigned to `innerHTML` properties and whatnot, must be a special "trusted" type — see [this article](https://web.dev/trusted-types/).

SvelteKit (or probably Svelte, more specifically) does do a lot of these things (e.g. changing `innerHTML` properties and so on), so SvelteKit should probably account for this when this directive is enabled.

### Alternatives considered

_No response_

### Importance

nice to have

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by teemingc**
closes #7975

This PR:
- adds a validation error that guides the user to update their Svelte version when using the CSP directive `require-trusted-types-for` or `trusted-types`.
- uses a trusted policy to register the service worker when possible
- errors if the svelte policy name is not included when trusted-types is configured
- errors if the sveltekit policy name is not included when trusted-types is configured and a service worker exists and is automatically registered by us. We don't care if the user is registering the service worker on their own because then they can create their own trusted policy while doing so

### Open questions

1. Should we automatically add `svelte-trusted-html` to `trusted-types` if `require-trusted-types-for` is in use?
	- This will cause any other trusted type policies to throw an error.
2. Or should we only add `svelte-trusted-html` when the user has `trusted-types` configured?
	- This means any trusted type policy is permitted on the page, which kind of defeats the purpose.
3. Or should we do nothing?
	- This means any trusted type policy is permitted on the page, which kind of defeats the purpose.
	- If the user has `trusted-types` configured but omitted `svelte-trusted-html`, they will have to discover the error message in the browser console logs, and figure out that they have to add the svelte trusted type to the config themselves.
5. Or should we error when the `trusted-types` config option isn't configured alongside the `require-trusted-types-for` option?
	- This will help teach users to add `svelte-trusted-html` themselves.
	- Could be kind of annoying and/or limiting.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. Changesets that add features should be `minor` and those that fix bugs should be `patch`. Please prefix changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

**Comment by willfarrell** [comment]
Love this.

Thoughts;
- should the TrustedType id be automatically included in the the `trusted-types` array similar to how `csp` auto adds nonce/hash?
- should the TrustedType id be a hash or build number or something? `sveltekit-9md83k` to prevent name collision from other libraries in the future. Not sure if there is a real attack vector here.

File: packages/kit/src/core/sync/utils.js [hunk 1]
```diff
@@ -74,5 +76,9 @@ export function dedent(strings, ...values) {
 }
 
 export function isSvelte5Plus() {
-	return Number(VERSION[0]) >= 5;
+	return MAJOR >= 5;
+}
+
+export function supportsTrustedTypes() {
```
Comment (Rich-Harris) [inline packages/kit/src/core/sync/utils.js:83]:
```suggestion
// TODO 3.0 remove this once we can bump the peerDep range
export function supportsTrustedTypes() {
```

**Review by Rich-Harris — APPROVED** [review]
nice!
