### PR TITLE
fix: Externalize app initialization to adapters

### LINKED ISSUE #1784: ReferenceError: fetch is not defined
This [change](https://github.com/sveltejs/kit/commit/d729b0848f2f45586c5e19c7b689e6eb2eaee96e#diff-ed48923f0655f935bee505cdcbf40212129ff49a89c2c9d752bd63aa1e6282c4R191
) cause fetch is not defined error with sveltekit + node-adapter.

**Describe the bug**

Build svelte-kit project with node-adapter, 
execute with node v14.16.0, it fails with error "ReferenceError: fetch is not defined"

**Logs**
```
file:///root/realadvisor/netimmo.web/.build/index.js:1836
  serverFetch: hooks.serverFetch || fetch
                                    ^

ReferenceError: fetch is not defined
    at get_hooks (file:///root/realadvisor/netimmo.web/.build/index.js:1836:37)
    at init (file:///root/realadvisor/netimmo.web/.build/index.js:1681:12)
    at file:///root/realadvisor/netimmo.web/.build/index.js:1900:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**To Reproduce**

```bash
npm init svelte@next my-app # use defaults
cd my-app
npm install @sveltejs/adapter-node@1.0.0-next.29
npm install
```

change svelte.config.js on

```javascript
import node from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    adapter: node({
      out: '.build',
    }),
  },
};

export default config;
```

```bash
npm run build
node build
```

### PR DESCRIPTION
**Pull request by GrygrFlzr**
Fixes #1784. Closes #1786 as its alternative.

This PR contains a **breaking change** to the adapter API.

## Current Behavior

https://github.com/sveltejs/kit/blob/559aad5f9dae6037a2d5fc4a63de0440634f41f2/packages/kit/src/core/build/index.js#L383

The built `app.js` file contains a side effect of calling the `init` function, which ends up running before polyfills like `@sveltejs/kit/install-fetch`. Although ESM (supposedly) guarantees a top-down order for import side effects, this is currently not necessarily true with esbuild nor rollup (see https://github.com/evanw/esbuild/issues/399#issuecomment-695967781).

## Proposed Behavior

https://github.com/sveltejs/kit/blob/e2f1b3f98124bb99606dcc0016e0072ed5e0e192/packages/kit/src/core/build/index.js#L288-L292

The `init` call is removed from the built `app.js`, and instead it becomes the responsibility of the adapters to call it at least once. This lets it control when the initialization happens, allowing us to guarantee that it happens after any polyfills:

https://github.com/sveltejs/kit/blob/e2f1b3f98124bb99606dcc0016e0072ed5e0e192/packages/adapter-node/src/index.js#L4-L8

This may also be useful in the future should the `init` function need to perform other side effects.

## Non-breaking alternate solutions

1. Use `require()` and the require shim to import the app to force it to run last:
    ```js
    const { render } = require('../output/server/app.js');
    ```
    This is not a great long-term solution considering we're forging ahead with ESM anyway.
2. Call `init` from `render` the first time it's called:
    ```js
    let initialized = false;
    export function render(/* ... */) {
      if (!initialized) {
        initialized = true;
        init(/* ... */);
      }
      // ...
    }
    ```
    In environments such as `adapter-node` it won't be evaluated until the server handles the quest, which may delay the initial response. May also affect serverless environments where lambdas may live longer than a single request.

### CODE REVIEW

File: packages/kit/src/install-fetch.js [hunk 1]
```diff
@@ -1,7 +1,20 @@
-// @ts-nocheck
 import fetch, { Response, Request, Headers } from 'node-fetch';
 
-globalThis.fetch = fetch;
-globalThis.Response = Response;
-globalThis.Request = Request;
-globalThis.Headers = Headers;
+Object.defineProperties(globalThis, {
```
Comment (GrygrFlzr) [inline packages/kit/src/install-fetch.js:3]: `defineProperties` seems like a more robust solution, and also avoids having to slap `ts-nocheck` directives.

File: packages/adapter-node/src/require_shim.js [hunk 2]
```diff
@@ -1,2 +1,2 @@
 import { createRequire } from 'module';
-global.require = createRequire(import.meta.url);
+globalThis.require = createRequire(import.meta.url);
```
Comment (GrygrFlzr) [inline packages/adapter-node/src/require_shim.js:2]: Consistency with the rest of the codebase.

File: packages/adapter-netlify/files/entry.js [hunk 3]
```diff
@@ -1,8 +1,9 @@
 import '@sveltejs/kit/install-fetch'; // eslint-disable-line import/no-unresolved
 
 // TODO hardcoding the relative location makes this brittle
-import { render } from '../output/server/app.js'; // eslint-disable-line import/no-unresolved
+import { init, render } from '../output/server/app.js'; // eslint-disable-line import/no-unresolved
 
+init();
```
Comment (benmccann) [inline packages/adapter-netlify/files/entry.js:6]: style nit: I might put a blank line after the call to `init();` in each adapter

**Review by benmccann — APPROVED** [review]
Thank you!
