### PR TITLE
respect `--mode`

### LINKED ISSUE #5573: Non-production builds still builds production SSR bundles
### Describe the bug

I'm trying to set up a dev/staging build step in my deploy pipeline, but can't convince Svelte Kit to produce a correct build. Not being able to do so means I can't add `noindex` tags to my pages, and dev sites could leak into search engines.

### Reproduction

Run `npm run build` on https://stackblitz.com/edit/sveltejs-kit-template-default-m2k71o?file=package.json&terminal=dev

### Logs

```shell
❯ npm run build
$ vite build --mode testing
vite v3.0.0 building for testing...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/_app/manifest.json                                                       5.18 KiB
.svelte-kit/output/client/_app/immutable/start-737da6ab.js                                         28.85 KiB / gzip: 9.79 KiB
.svelte-kit/output/client/_app/immutable/pages/__layout.svelte-147ef2ce.js                         6.19 KiB / gzip: 2.45 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-74c83d2a.js                                  3.57 KiB / gzip: 1.38 KiB
.svelte-kit/output/client/_app/immutable/pages/about.svelte-6a933808.js                            3.52 KiB / gzip: 1.58 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-03b28467.js                            7.35 KiB / gzip: 3.15 KiB
.svelte-kit/output/client/_app/immutable/pages/todos/index.svelte-57505142.js                      8.74 KiB / gzip: 3.68 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-a91a3869.js                                  13.80 KiB / gzip: 5.85 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-92dd14f8.js                                  0.43 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-cdeec3fd.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/immutable/assets/__layout-c39c904e.css                              5.11 KiB / gzip: 1.57 KiB
.svelte-kit/output/client/_app/immutable/assets/about-34f9bec4.css                                 0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/assets/index-15f21104.css                                 1.47 KiB / gzip: 0.53 KiB
.svelte-kit/output/client/_app/immutable/assets/index-da7b4a06.css                                 3.75 KiB / gzip: 1.04 KiB
vite v3.0.0 building SSR bundle for production...
✓ 35 modules transformed.
.svelte-kit/output/server/manifest.json                         2.37 KiB
.svelte-kit/output/server/index.js                              76.18 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.js      1.35 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js      4.63 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js     0.74 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js         1.40 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js         8.23 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js   5.94 KiB
.svelte-kit/output/server/immutable/chunks/index-59c70007.js    4.15 KiB
.svelte-kit/output/server/immutable/chunks/hooks-5a10edf9.js    0.46 KiB
(node:17) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
```

### System Info

```shell
System:
    OS: Linux 5.15 KDE neon 5.25
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 3.17 GB / 7.53 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Firefox: 101.0.1
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.69 => 1.0.0-next.69 
    @sveltejs/adapter-static: next => 1.0.0-next.37 
    @sveltejs/kit: next => 1.0.0-next.377 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I can't run my usual workflow without this as I can't tell build which environment they're in.

### PR DESCRIPTION
**Pull request by Rich-Harris**
~~This mostly fixes #5573, but not quite. It fixes `mode` but `dev`/`prod` is broken — for some reason, with `--mode custom`, `import.meta.env.DEV` is `true` even for the built app. I haven't been able to replicate this in a plain Vite app, so it seems we're doing something iffy.~~

Closes #5573

The conflation of mode and command is unfortunate: `import.meta.env.DEV` should be true if `command === 'serve'` and vice versa. It should have nothing to do with `mode`. I'm not sure if that's part of what's happening here.

Slightly unrelated, but: looking at this stuff more closely, I'm inclined to remove `mode` from `$app/env` — it's a Vite concept, not a SvelteKit one, and should probably be expressed as `import.meta.env.MODE`.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC: https://github.com/sveltejs/rfcs
- [x] This message body should clearly illustrate what problems it solves.
- [x] Ideally, include a test that fails without this PR but passes with it.

### Tests
- [x] Run the tests with `pnpm test` and lint the project with `pnpm lint` and `pnpm check`

### Changesets
- [x] If your PR makes a change that should be noted in one or more packages' changelogs, generate a changeset by running `pnpm changeset` and following the prompts. All changesets should be `patch` until SvelteKit 1.0

### CODE REVIEW

File: packages/kit/src/vite/build/build_server.js [hunk 1]
```diff
@@ -111,7 +111,7 @@ export class Server {
 /**
  * @param {{
  *   cwd: string;
- *   config: import('types').ValidatedConfig
+ *   config: import('types').ValidatedConfig;
```
Comment (benmccann) [inline packages/kit/src/vite/build/build_server.js:114]: should add to the next two lines as well

**Comment by Rich-Harris** [comment]
I think I found a bug in Vite: https://github.com/vitejs/vite/issues/9203. Might be easiest to just use `define` for the values inside `$app/env`, pending a fix

**Comment by bluwy** [comment]
> I think I found a bug in Vite: [vitejs/vite#9203](https://github.com/vitejs/vite/issues/9203). Might be easiest to just use `define` for the values inside `$app/env`, pending a fix

Given this is intentional in Vite, perhaps we want to revert the patch in this PR to stay consistent.

**Comment by Rich-Harris** [comment]
Opened a PR to this branch that removes those redundant values: https://github.com/sveltejs/kit/pull/5614

**Review by benmccann — APPROVED** [review]

**Comment by bluwy** [comment]
> I'm surprised it's intentional to be honest — to my mind, `DEV = command === 'serve'` and `PROD = command === 'build'`. Any other distinction just isn't particularly useful, so I would prefer to use `define` as in this PR.

Late to the party, but this is because some cases you might want to have dev behavior builds. For example, a staging site where you get helpful dev errors locally before deploying to prod where you want to have errors captured via Sentry instead.

With this change, we're blocking this usecase unless we use `import.meta.env.MODE` to compare, but now we have to compare on the custom mode names instead, which isn't great if you have multiple modes lying around, e.g. multiple stagings.

I think we should still align with Vite here even if it may sound confusing. Having SK and Vite contradicting would be more confusing for users, espeically that we're a Vite plugin, users are reading both SK and Vite docs.

**Comment by Mlocik97** [comment]
I never used `server`, I had `!browser` (negation of browser is server, as per implementation that Mathias did), So it was just why to have both browser and server values when they are just negation of each other? I found it redundant too.

**Comment by benmccann** [comment]
I think there are three cases here:
- running dev server
- running in prod
- running elsewhere like QA / staging

The question is whether QA / staging should be categorized as dev or prod. Vite says dev and this PR says prod. It's quite ambiguous. It's really neither and the problem is we're trying to jam three values into two. I wonder if the solution isn't instead to define `DEV` and `PROD` as checking their respective modes don't compute the value of one based off the other but only check if that's the mode that's set.
